Update patch set 4
Patch Set 4:

> Build Failed
 > 
 > http://ci.libreoffice.org/job/lo_gerrit_master/11531/ : FAILURE

<http://ci.libreoffice.org/job/lo_gerrit_master/11531/Gerrit=Gerrit,Platform=Windows/console>:

C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/connectivity/source/drivers/mork/MPreparedStatement.cxx(366) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

(i.e., "ORowSetValue" mentioned in the parameter list of the out-of-class definition of member function [connectivity::mork::]OPreparedStatement::setParameter in global scope, after a using directive for connectivity::mork, not finding connectivity::ORowSetValue):  Apparently a bug in MSVC.  [basic.lookup.unqual]/6: "A name used in the definition of a function following the function’s declarator-id[footnote: This refers to unqualified names that occur, for instance, in a type or default argument in the parameter-declaration-clause
or used in the function body.] that is a member of
namespace N (where, only for the purpose of exposition, N could represent the global scope) shall be declared
before its use in the block in which it is used or in one of its enclosing blocks (6.3) or, shall be declared
before its use in namespace N or, if N is a nested namespace, shall be declared before its use in one of N’s
enclosing namespaces."

Patch-set: 4
Reviewer: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0