Bump MSVC baseline to Visual Studio 2019 version 16.5
After b4b7e92cbf5a212cc1c648af86df2dee364d48c8 "Use MSVC's /permissive- to make
it more standards conforming", vmiklos reported that his 16.4.6 build started to
fail with

> C:/lo/master/connectivity/source/drivers/odbc/OStatement.cxx(411): error C2760: syntax error: unexpected token 'identifier', expected 'type specifier'
> C:/lo/master/connectivity/source/drivers/odbc/OStatement.cxx(411): note: This diagnostic occurred in the compiler generated function 'T connectivity::odbc::OStatement_Base::getStmtOption(SQLINTEGER) const'
> C:/lo/master/connectivity/source/drivers/odbc/OStatement.cxx(418): error C2760: syntax error: unexpected token 'identifier', expected 'type specifier'
> C:/lo/master/connectivity/source/drivers/odbc/OStatement.cxx(418): note: This diagnostic occurred in the compiler generated function 'SQLRETURN connectivity::odbc::OStatement_Base::setStmtOption(SQLINTEGER,T) const'
> [build CXX] connectivity/source/drivers/odbc/ODatabaseMetaData.cxx
> make[1]: *** [C:/lo/master/solenv/gbuild/LinkTarget.mk:301: C:/lo/master/workdir/CxxObject/connectivity/source/drivers/odbc/OStatement.o] Error 2
> make[1]: *** Waiting for unfinished jobs....
> C:/lo/master/connectivity/source/drivers/odbc/ODatabaseMetaDataResultSet.cxx(161): error C3861: 'checkDisposed': identifier not found
> C:/lo/master/connectivity/source/drivers/odbc/ODatabaseMetaDataResultSet.cxx(161): note: 'checkDisposed': function declaration must be available as none of the arguments depend on a template parameter
> C:/lo/master/connectivity/source/drivers/odbc/ODatabaseMetaDataResultSet.cxx(161): note: This diagnostic occurred in the compiler generated function 'T connectivity::odbc::ODatabaseMetaDataResultSet::getInteger(sal_Int32)'
> make[1]: *** [C:/lo/master/solenv/gbuild/LinkTarget.mk:298: C:/lo/master/workdir/CxxObject/connectivity/source/drivers/odbc/ODatabaseMetaDataResultSet.o] Error 2

while it succeeded after upgrading to 16.8.4.  That change had been seen working
with 16.5.4 (on tb73, see
<https://lists.freedesktop.org/archives/libreoffice/2021-January/086635.html>
"Heads up: Use MSVC's /permissive- to make it more standards conforming"), so
lets hope that bumping the baseline from 16.4 to 16.5 is all that is needed.

Change-Id: I7446f778a94e15e7ea5c8ef0780bf10831a2d4b7