linux_aarch64: loplugin:cstylecast in bridges
/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/bridges/source/cpp_uno/gcc3_linux_aarch64/cpp2uno.cxx:588:10: error: C-style cast from incomplete 'void *' to 'void (*)(const unsigned char *, const unsigned char *)' (BitCast) [loplugin:cstylecast]
       = (void (*)(unsigned char const *, unsigned char const *)) dlsym(
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

fix that by using reinterpret_cast instead (and also fix the indent of
the lines)

Change-Id: I06ee2b2ca350790e2f97435cd70e58acd7c2cf84
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/186334
Reviewed-by: Christian Lohmaier <lohmaier+LibreOffice@googlemail.com>
Tested-by: Jenkins
(cherry picked from commit ef4948bde237459a407a7deede6ab4e4e5b4551b)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/186363
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>