fix skia build on loongarch64
Add missing _lasx files, because otherwise we get

/usr/bin/ld: /<<PKGBUILDDIR>>/workdir/GenCxxObject/UnpackedTarball/skia/src/core/SkBitmapProcState_opts.o: in function `SkOpts::Init_BitmapProcState()':
./././workdir/UnpackedTarball/skia/src/core/SkBitmapProcState_opts.cpp:36:(.text+0x58): undefined reference to `SkOpts::Init_BitmapProcState_lasx()'
/usr/bin/ld: /<<PKGBUILDDIR>>/workdir/GenCxxObject/UnpackedTarball/skia/src/core/SkBlitRow_opts.o: in function `SkOpts::Init_BlitRow()':
./././workdir/UnpackedTarball/skia/src/core/SkBlitRow_opts.cpp:36:(.text+0x58): undefined reference to `SkOpts::Init_BlitRow_lasx()'
/usr/bin/ld: /<<PKGBUILDDIR>>/workdir/GenCxxObject/UnpackedTarball/skia/src/core/SkOpts.o: in function `SkOpts::Init()':
./././workdir/UnpackedTarball/skia/src/core/SkOpts.cpp:65:(.text+0x237d8): undefined reference to `SkOpts::Init_lasx()'
/usr/bin/ld: /<<PKGBUILDDIR>>/workdir/GenCxxObject/UnpackedTarball/skia/src/core/SkSwizzler_opts.o: in function `SkOpts::Init_Swizzler()':
./././workdir/UnpackedTarball/skia/src/core/SkSwizzler_opts.cpp:51:(.text+0x58): undefined reference to `SkOpts::Init_Swizzler_lasx()'

cf. https://buildd.debian.org/status/fetch.php?pkg=libreoffice&arch=loong64&ver=4%3A25.2.0~beta1-1&stamp=1733592509&raw=1

Change-Id: I232b4656a87a4c3d87d669769c6483e01425c0e6
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/178051
Tested-by: Jenkins
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>
Reviewed-by: wu jiahuan <wujiahuan@loongson.cn>
Tested-by: René Engelhard <rene@debian.org>
(cherry picked from commit a0d5bc55d5c0cd47d8357ddbba952a179fae9207)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/179485
Reviewed-by: René Engelhard <rene@debian.org>