Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/74408/ : FAILURE

error: redundant functional cast from "bool" to "bool" [loplugin:redundantcast] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/qa/cppunit/BinaryDataContainerTest.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/76557/ )

clang plugin redundantcast did trigger. redundant functional cast from "bool" to "bool" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/76557/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/76557/ )

the cppunit test CppunitTest_sd_export_ooxml2 failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/76557/ )

the test UITest_hide_cols failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/76557/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1