Update patch set 11
Patch Set 11: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/102199/ : FAILURE

Visual studio complained about error C2859: C:\cygwin\home\tdf\lode\jenkins\workspace\gerrit_windows@2\workdir\LinkTarget\Library\sblo.dll.objects.pdb is not the pdb file that was used when this precompiled header was created, recreate the precompiled header. in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/basic/source/sbx/sbxscan.cxx ( https://ci.libreoffice.org/job/gerrit_windows/113306/ )

Patch-set: 11
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1