cui: fix warning C6013: Dereferencing NULL pointer 'Current()'
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/cui/source/dialogs/toolbartabpage.cxx(110): error C2220: the following warning is treated as an error
C:\cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win_analyze\cui\source\dialogs\toolbartabpage.cxx(45) : warning C6011: Dereferencing NULL pointer 'Current()'. : Lines: 45, 41, 43, 45
make[1]: *** [C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/solenv/gbuild/LinkTarget.mk:338: C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/workdir/CxxObject/cui/source/dialogs/toolbartabpage.o] Error 2
make[1]: *** Waiting for unfinished jobs....

after
commit 4ab26f4ea0c627844531144a6a903c357a604a5e
Author: Heiko Tietze <tietze.heiko@gmail.com>
Date:   Mon May 26 12:03:40 2025 +0200

    Resolves tdf#158880 - Let users select multiple toolbars at once

Change-Id: I54375b705e332d49b7635dc257ff20e9f61d3f39
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/185859
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>