Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/107949/ : FAILURE

clang plugin stringview did trigger. instead of an "rtl::OString" constructed from a "OStringNumber<int>", pass a "std::string_view" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/107685/ )

error: rather use O[U]String::Concat than constructing "rtl::OString" from "const char [15]" on RHS of + (where LHS is of type "const typename std::enable_if_t<ToStringHelper<OString>::allowOStringConcat && ToStringHelper<OString>::allowOStringConcat, OStringConcat<OString, OString> >" (aka "const rtl::OStringConcat<rtl::OString, rtl::OString>")) [loplugin:stringadd] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/extras/uiwriter/uiwriter3.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/107685/ )

Patch-set: 7
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1