Fix bogus OUString constructor fixes.
aeb41c9b9b7559c6d87bf92807acdc0df9e104cc
(remove redundant calls to OUString constructor)
introduced:
error: variable 'sComposedName' is uninitialized when used within its own initialization

Change-Id: I846337da43625d1cdbd33f0705499daa0c419894