Directly initialize vectors in sfx2/ObjectInspectorTreeHandler
since we've got all the information from the beginning.

The static_cast is to fix this error:
/home/julien/lo/libreoffice/sfx2/source/devtools/ObjectInspectorTreeHandler.cxx:976:39: error: type 'float' cannot be narrowed to 'int' in initializer list [-Wc++11-narrowing]
    std::vector<int> aMethodsWidths { nMethodsDigitWidth * 30, nMethodsDigitWidth * 15,
                                      ^~~~~~~~~~~~~~~~~~~~~~~
/home/julien/lo/libreoffice/sfx2/source/devtools/ObjectInspectorTreeHandler.cxx:976:39: note: insert an explicit cast to silence this issue
    std::vector<int> aMethodsWidths { nMethodsDigitWidth * 30, nMethodsDigitWidth * 15,
                                      ^~~~~~~~~~~~~~~~~~~~~~~
                                      static_cast<int>(      )

Change-Id: I7d59d947bd54bf97dd559b6813cabd3ea4216efe