sd: fix missing include
sd/source/filter/grf/sdgrffilter.cxx:134:40: error: ‘comphelper::LibreOfficeKit’ has not been declared

Change-Id: I2ad09cc32ac9be506ab615b4eb7536796d454bc3
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/195218
Tested-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>