workaround a weird gcc optimization werror bug
gcc (GCC) 4.9.2 20141101 (Red Hat 4.9.2-1)

framework/source/fwe/classes/addonsoptions.cxx: In member function ‘void framework::AddonsOptions_Impl::ReadAndAssociateImages(const rtl::OUString&, const rtl::OUString&)’:
framework/source/fwe/classes/addonsoptions.cxx:267:16: error: array subscript is above array bounds [-Werror=array-bounds]
         struct ImageEntry
                ^

The combination of aScaled[2]; aImage[2]; aURL[2] in sequence apparently lead
to some overoptimization and/or alignment problem, already declaring aImage[3]
helped (but not aScaled[3]), but that's not what we want.

Change-Id: I82e28d4887ab8072a17d0a9341d322c1cf61aedc
(cherry picked from commit 549b7fad48bb9ddcba7dfa92daea6ce917853a03)