coplugin:socketPoll
> wsd/FileServer.cpp:2327:42: error: Only SocketPoll can have std::shared_ptr<Socket> as a member. Everything else should have std::weak_ptr<Socket> [coplugin:socketPoll]
>  2327 |     auto fetchWithKey = [uri, uriAnonym, socket, requestPath = getRequestPath(request),
>       |                                          ^~~~~~

since 998b1b8168f80586e33a7ee83477afb75da076b0 "Reuse the saved AI provider key
when listing models"

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I771b989c6112c5454ee1638e57232a357e0b409e
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/8055
Reviewed-by: Rashesh Padia <rashesh.padia@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>