Update patch set 3
Patch Set 3:

Could this be the cause for <https://ci.libreoffice.org/job/lo_callgrind_linux/8338/> and following failing with

  [...]
  [build UIA] modules/swriter
  Could not find platform independent libraries <prefix>
  Could not find platform dependent libraries <exec_prefix>
  Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
  Fatal Python error: initfsencoding: Unable to get the locale encoding
  ModuleNotFoundError: No module named 'encodings'
  
  Current thread 0x00001527c5c45740 (most recent call first):
  [build PRL] CustomTarget/postprocess/images/commandimagelist.ilst
  [build CXX] sc/source/ui/app/inputwin.cxx
  /home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/solenv/gbuild/UIConfig.mk:157: recipe for target '/home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/workdir/UIConfig/modules/swriter.a11yerrors' failed
  make[1]: *** [/home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/workdir/UIConfig/modules/swriter.a11yerrors] Aborted (core dumped)
  [...]

(if its <https://git.libreoffice.org/core/+/15ff451d4a1de46da8f949ee0e1e402bda845568%5E!> "Resolves: tdf#132038 missing adjustment for rotation" happens to be the first change to a .ui file after this change got submitted, in what appears to be incremental builds)?

Patch-set: 3
CC: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>