Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/87200/ : FAILURE

Visual studio complained about error C2398: Element "1": conversion from "initializer list" to "E" requires a narrowing conversion in file C:/cygwin/home/tdf/jenkins/workspace/gerrit_windows/canvas/workben/canvasdemo.cxx(161) ( https://ci.libreoffice.org/job/gerrit_windows/97761/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1