Avoid -Werror=nonnull with glibc-headers-x86-2.32-1.fc33.noarch
...on Fedora 33:

> ~/lo/core/vcl/unx/generic/app/i18n_cb.cxx: In function ‘void Preedit_InsertText(preedit_text_t*, XIMText*, int)’:
> ~/lo/core/vcl/unx/generic/app/i18n_cb.cxx:149:34: error: argument 1 is null but the corresponding size argument 3 value is 1024 [-Werror=nonnull]
>   149 |         size_t nBytes = wcstombs ( nullptr, pWCString, 1024 /* don't care */);
>       |                         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from ~/gcc/trunk/inst/include/c++/11.0.0/cstdlib:75,
>                  from ~/lo/core/include/sal/log.hxx:15,
>                  from ~/lo/core/vcl/unx/generic/app/i18n_cb.cxx:25:
> /usr/include/stdlib.h:937:15: note: in a call to function ‘size_t wcstombs(char*, const wchar_t*, size_t)’ declared with attribute ‘access (write_only, 1, 3)’
>   937 | extern size_t wcstombs (char *__restrict __s,
>       |               ^~~~~~~~

(Allowing the first argument to wcstombs to be null, and in which case the third
argument is ignored, is a POSIX extension.)

Change-Id: Ic078623643010b7539bc5bc1b498f18977ae77ca
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/103473
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit 782d160458d319c6c77fffa4c003c519afffaa17)