Update patch set 3
Patch Set 3:

> Yes I looked, but I don't get the same error. so there was a little
 > confusion...
 > 
 > FAIL: test_checkBookmarks (check_bookmarks.CheckBookmarks)
 > ----------------------------------------------------------------------
 > Traceback (most recent call last):
 > File "/ev/kadertarlan/tmpfs/libreoffice/sw/qa/python/check_bookmarks.py",
 > line 90, in test_checkBookmarks
 > self.m_actualHashes.assertExpectation(self.get20111110Expectations())
 > File "/ev/kadertarlan/tmpfs/libreoffice/sw/qa/python/check_bookmarks.py",
 > line 41, in assertExpectation
 > self.assertEqual(aExpectation.m_nSetupHash, self.m_nSetupHash)
 > AssertionError: '-4b0706744e8452fe1ae9d5e1c28cf70fb6194795' !=
 > '3a8bb8a26c6b8d4cb972b73f9746ca26cdb75708'
 > - -4b0706744e8452fe1ae9d5e1c28cf70fb6194795
 > + 3a8bb8a26c6b8d4cb972b73f9746ca26cdb75708
 > 
 > 
 > ----------------------------------------------------------------------
 > Ran 17 tests in 6.181s
 > 
 > FAILED (failures=1, expected failures=1)
 > 3a8bb8a26c6b8d4cb972b73f9746ca26cdb75708
 > 3e15ed4b083cdca3e07432c2965ed5cf2b6674c3
 > b7069f1b2e7d5c96bde0a093363e0a8974fa37c6
 > b7069f1b2e7d5c96bde0a093363e0a8974fa37c6

 > Yes I looked, but I don't get the same error. so there was a little
 > confusion...
 > 
 > FAIL: test_checkBookmarks (check_bookmarks.CheckBookmarks)
 > ----------------------------------------------------------------------

Probably because you only run the python test and not all tests, please look at the console output in jenkins the last lines says exactly what the problem is. Hint it is not in your python files.


 > Traceback (most recent call last):
 > File "/ev/kadertarlan/tmpfs/libreoffice/sw/qa/python/check_bookmarks.py",
 > line 90, in test_checkBookmarks
 > self.m_actualHashes.assertExpectation(self.get20111110Expectations())
 > File "/ev/kadertarlan/tmpfs/libreoffice/sw/qa/python/check_bookmarks.py",
 > line 41, in assertExpectation
 > self.assertEqual(aExpectation.m_nSetupHash, self.m_nSetupHash)
 > AssertionError: '-4b0706744e8452fe1ae9d5e1c28cf70fb6194795' !=
 > '3a8bb8a26c6b8d4cb972b73f9746ca26cdb75708'
 > - -4b0706744e8452fe1ae9d5e1c28cf70fb6194795
 > + 3a8bb8a26c6b8d4cb972b73f9746ca26cdb75708
 > 
 > 
 > ----------------------------------------------------------------------
 > Ran 17 tests in 6.181s
 > 
 > FAILED (failures=1, expected failures=1)
 > 3a8bb8a26c6b8d4cb972b73f9746ca26cdb75708
 > 3e15ed4b083cdca3e07432c2965ed5cf2b6674c3
 > b7069f1b2e7d5c96bde0a093363e0a8974fa37c6
 > b7069f1b2e7d5c96bde0a093363e0a8974fa37c6

 > Yes I looked, but I don't get the same error. so there was a little
 > confusion...
 > 
 > FAIL: test_checkBookmarks (check_bookmarks.CheckBookmarks)
 > ----------------------------------------------------------------------
 > Traceback (most recent call last):
 > File "/ev/kadertarlan/tmpfs/libreoffice/sw/qa/python/check_bookmarks.py",
 > line 90, in test_checkBookmarks
 > self.m_actualHashes.assertExpectation(self.get20111110Expectations())
 > File "/ev/kadertarlan/tmpfs/libreoffice/sw/qa/python/check_bookmarks.py",
 > line 41, in assertExpectation
 > self.assertEqual(aExpectation.m_nSetupHash, self.m_nSetupHash)
 > AssertionError: '-4b0706744e8452fe1ae9d5e1c28cf70fb6194795' !=
 > '3a8bb8a26c6b8d4cb972b73f9746ca26cdb75708'
 > - -4b0706744e8452fe1ae9d5e1c28cf70fb6194795
 > + 3a8bb8a26c6b8d4cb972b73f9746ca26cdb75708
 > 
 > 
 > ----------------------------------------------------------------------
 > Ran 17 tests in 6.181s
 > 
 > FAILED (failures=1, expected failures=1)
 > 3a8bb8a26c6b8d4cb972b73f9746ca26cdb75708
 > 3e15ed4b083cdca3e07432c2965ed5cf2b6674c3
 > b7069f1b2e7d5c96bde0a093363e0a8974fa37c6
 > b7069f1b2e7d5c96bde0a093363e0a8974fa37c6

Patch-set: 3