vcl: avoid unused variable warning
vcl/source/gdi/pdfobjectcopier.cxx: In member function ‘rtl::OString vcl::PDFObjectCopier::copyExternalResources(vcl::filter::PDFObjectElement&, const rtl::OString&, std::__debug::map<int, int>&)’:
vcl/source/gdi/pdfobjectcopier.cxx:240:27: error: unused variable ‘pDict’ [-Werror=unused-variable]
  240 |                 if (auto* pDict = dynamic_cast<filter::PDFDictionaryElement*>(rItem.second))
      |                           ^~~~~

Change-Id: I864210144e6154eb79a42e6cd5ceb3d5dbd39a76
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/144449
Reviewed-by: Dennis Francis <dennis.francis@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>