Remove useless check
...that was introduced with b14107dd0eaf9bfc276544e1900873d36075425e "tdf#133858
reduce the double-ref range to data content", but which can only ever be either
true or invoke undefined behavior (as gets reported as

> sc/source/core/tool/compiler.cxx:6412:27: error: comparing the result of pointer addition ‘(((ScCompiler*)this)->ScCompiler::<anonymous>.formula::FormulaCompiler::pCode + -8)’ and NULL [-Werror=address]
>  6412 |     if (!pCode || !(pCode -1) || !(*(pCode - 1)))
>       |                    ~~~~~~~^~~

with recent GCC 12 trunk)

Change-Id: I72395f1874343a047afceaa5e342e9e67a51c44f
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/123531
Reviewed-by: Dennis Francis <dennis.francis@collabora.com>
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
Tested-by: Jenkins
(cherry picked from commit a60296694b3af2c18e7aa81eba8782e0ad03f7b8)