Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/3261/ : FAILURE

clang plugin badstatics did trigger. bad static variable causes crash on shutdown ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/3240/ )

error: bad static variable causes crash on shutdown [loplugin:badstatics] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/graphic/Manager.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/3240/ )

Patch-set: 7
Label: Verified=-1