Update patch set 18
Patch Set 18:

> Patch Set 17:
> 
> Excuse Noel,
> I was wondering if you could help me.
> I saw on your patch 104629: long->tools::Long in slideshow..starmath
> a similar error to mine: error: ‘Long’ is not a member of ‘tools’
> You solved it by rebasing your patch. So I was wondering if you could help me with that.
> Thanks you for your time.

There are typically one of two possible reason

(1) is that the code does not include the tools/long.hxx header
(2) is that there is more than one "tools" namespace that the compiler can see, in which case
the answer is to change the code to use
   ::tools::Long
instead of
   tools::Long
to help the compiler out

Patch-set: 18
Reviewer: Gerrit User 1000083 <1000083@6622c302-437a-49ad-a91d-55ba7dcf1615>