Update patch set 2
Patch Set 2:

Unfortunately, the Android (non-pdfium) build with master as of 65c2ba2daa61e1a7e9faca680abefb13544f04fc currently fails, which looks related to this commit (s. the '#if HAVE_FEATURE_PDFIUM'... in vcl/source/filter/ipdf/pdfread.cxx).

Could you possibly take a look?

/home/michael.weghorn/development/git/libreoffice-WORKTREE_android-x86/vcl/source/filter/ipdf/pdfread.cxx:133:10: error: no matching function for call to 'getCompatibleStream'
    if (!getCompatibleStream(rStream, aMemoryStream))
         ^~~~~~~~~~~~~~~~~~~
/home/michael.weghorn/development/git/libreoffice-WORKTREE_android-x86/vcl/source/filter/ipdf/pdfread.cxx:120:6: note: candidate function not viable: requires 4 arguments, but 2 were provided
bool getCompatibleStream(SvStream& rInStream, SvStream& rOutStream, sal_uInt64 nPos,
     ^
1 error generated.

Patch-set: 2
CC: Gerrit User 1000789 <1000789@6622c302-437a-49ad-a91d-55ba7dcf1615>