Update patch set 10
Patch Set 10:

> Doubt it's my fault, compiled it with 5.2.6 without errors. Jenkins
 > is not helping me figure out what's wrong.

Of course it is. Go to the job's logs, pick one of the platforms and from there the console output. At the end of such log you see

Error: Reserved formatindex="50" in FormatElement.
Error: Reserved formatindex="51" in FormatElement.
Error: Reserved formatindex="52" in FormatElement.
Error: Reserved formatindex="53" in FormatElement.
Hint: Next free formatindex is 60.

That doesn't happen in 5.2 because the reserved index range was changed later.

Patch-set: 10
Reviewer: Gerrit User 1000023 <1000023@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0