Update patch set 2
Patch Set 2:

removed unoany.cxx from the path, the plugin expects the whitelisting comment on same line
 error: 'error' diagnostics expected but not seen: 
   File /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/compilerplugins/clang/test/unoany.cxx Line 23: unnecessary copy, rather use <<= operator directly with the 'makeAny' argument [loplugin:unoany]
   File /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/compilerplugins/clang/test/unoany.cxx Line 25: unnecessary copy, rather use <<= operator directly with the 'Any' constructor argument [loplugin:unoany]
 error: 'error' diagnostics seen but not expected: 
   File /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/compilerplugins/clang/test/unoany.cxx Line 22: unnecessary copy, rather use <<= operator directly with the 'makeAny' argument [loplugin:unoany]
   File /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/compilerplugins/clang/test/unoany.cxx Line 24: unnecessary copy, rather use <<= operator directly with the 'Any' constructor argument [loplugin:unoany]
 4 errors generated.

Patch-set: 2
CC: Gerrit User 1000027 <1000027@6622c302-437a-49ad-a91d-55ba7dcf1615>