Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/23185/ : FAILURE

clang plugin casttovoid did trigger. unused virtual function parameter name ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/24543/ )

error: unused virtual function parameter name [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/ui/vba/vbaapplication.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/24543/ )

Patch-set: 2
Label: Verified=-1