werror: declaration hides previous declaration
Change-Id: I0f8422a4f8c27ec253d917985d2593d8d87bb5f0
Reviewed-on: https://gerrit.libreoffice.org/22685
Reviewed-by: Michael Stahl <mstahl@redhat.com>
Tested-by: Michael Stahl <mstahl@redhat.com>
(cherry picked from commit d375cafef68e8be9d0d35cbb535b8481a3913ace)
Signed-off-by: Michael Stahl <mstahl@redhat.com>