Adapt to Clang 12 trunk cosmetic diagnostics changes
<https://github.com/llvm/llvm-project/commit/
e7f3e2103cdb567dda4fd52f81bf4bc07179f5a8> "Suppress printing template arguments
that match default template arguments of types by default" caused

> error: 'error' diagnostics seen but not expected:
>   File /home/sbergman/lo/core/compilerplugins/clang/test/makeshared.cxx Line 58: rather use make_shared than constructing from 'typename std::remove_reference<unique_ptr<int> &>::type' (aka 'std::unique_ptr<int>') [loplugin:makeshared]
>   File /home/sbergman/lo/core/compilerplugins/clang/test/makeshared.cxx Line 60: rather use make_shared than constructing from 'typename std::remove_reference<unique_ptr<int> &>::type' (aka 'std::unique_ptr<int>') [loplugin:makeshared]

in compilerplugins/clang/test/makeshared.cxx, and <https://github.com/llvm/
llvm-project/commit/5f12f4ff9078455cad9d4806da01f570553a5bf9> "Suppress printing
of inline namespace names in diagnostics by default, except where they are
necessary to disambiguate the target" caused

> error: 'note' diagnostics seen but not expected:
>   File /home/sbergman/lo/core/compilerplugins/clang/test/external.cxx Line 133: a function associating 'N::E' is declared here [loplugin:external]
>   File /home/sbergman/lo/core/compilerplugins/clang/test/external.cxx Line 140: a function associating 'N::E' is declared here [loplugin:external]
>   File /home/sbergman/lo/core/compilerplugins/clang/test/external.cxx Line 144: a function associating 'N::E' is declared here [loplugin:external]
>   File /home/sbergman/lo/core/compilerplugins/clang/test/external.cxx Line 167: a function associating 'N::E' is declared here [loplugin:external]
>   File /home/sbergman/lo/core/compilerplugins/clang/test/external.cxx Line 172: a function associating 'N::E' is declared here [loplugin:external]

Change-Id: If1ec798fd9876b5be058c63bcaca3e2a36c0dbb6