sw: fix crash in InitBookmarks() with forum-mso-en-8410.docx
Error: attempt to dereference a past-the-end iterator.

Probably this only crashes in the assert(iter->pNode...) as the rest of
the function already checks that "iter == end".

(regression from commit 46e04a712e97f9095ef4da7f0e52f50cf2bfbb32)

Change-Id: If652a15d1cdebb21fbce028fceeaee8dce8f7f6d