xmloff: fix stack-use-after-return in SvXMLExport::exportDoc()
PropertySetInfo(PropertyMapEntry const * pMap) stores the pointers,
and its lifetime is controlled by refcounting, so the lifetime
of aInfoMap can't be automatic.

ERROR: AddressSanitizer: stack-use-after-return on address ...
... is located in stack of thread T46
at offset 224 in frame SvXMLExport::exportDoc(xmloff::token::XMLTokenEnum)

This frame has 39 object(s):
  ...
  [224, 288) 'aInfoMap' <== Memory access at offset 224 is inside this variable

Change-Id: I4eaa9d38bab708b222d999b0982100d7ef97e95c
(cherry picked from commit ee599ea46365adc37f4d495d9ff9778c25c04c92)
Reviewed-on: https://gerrit.libreoffice.org/42504
Reviewed-by: Caolán McNamara <caolanm@redhat.com>
Tested-by: Caolán McNamara <caolanm@redhat.com>
(cherry picked from commit 89a5b2c31b4c9d5e068e9d1aef2eac50d70df80e)