Update patch set 12
Patch Set 12: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/38469/ : FAILURE

error ""dispose" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/dbaccess/source/ui/inc/WTypeSelect.hxx:55:22 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/41475/ )

clang plugin unreffun did trigger. Unreferenced externally invisible function template definition ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/41475/ )

error: "dispose" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/dbaccess/source/ui/inc/WTypeSelect.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/41475/ )

Patch-set: 12
Label: Verified=-1