Update patch set 2
Patch Set 2:

> Have you had time to check the failing problem on win ?

I tried at that time, and failed. But now I start to believe that this has something in common with what I experience in https://lists.freedesktop.org/archives/libreoffice/2020-July/085526.html. There adding a boost header into the unit test module fixed the issue experienced with disabled precompiled headers. Currently I experience the same problem -coincidentally - in uiwriter3.cxx, with

> tdf133982.docx:
> testTdf133982::TestBody finished in: 1025ms
> C:/lo/src/core/sw/qa/extras/uiwriter/uiwriter3.cxx(267) : error : Assertion
> Test name: testTdf126504::TestBody
> equality assertion failed
> - Expected: 4
> - Actual  : 3
> 
> Failures !!!
>Run: 315   Failure total: 1   Failures: 1   Errors: 0

... which is also only visible with disabled PCH. Now I look into this patch again, and see the removal of the boost header ... :-( it's somehow really broken.

Patch-set: 2
Reviewer: Gerrit User 1000994 <1000994@6622c302-437a-49ad-a91d-55ba7dcf1615>