add missing juh dependencies to JunitTests
no idea why it suddently fails for me this way but without it I get
java.lang.NoClassDefFoundError: com/sun/star/comp/helper/Bootstrap

Change-Id: I514cf83a439437a7cfaf6b35149818915b7a03ff