Avoid -Werror,-Wunused-parameter
> /Volumes/lode/lode/jenkins/workspace/lo_tb_master_mac/vcl/quartz/salvd.cxx:120:22: error: unused parameter 'pGraphic' [-Werror,-Wunused-parameter]
>     AquaSalGraphics* pGraphic, tools::Long &nDX, tools::Long &nDY,
>                      ^

(<https://ci.libreoffice.org/job/lo_tb_master_mac/52565/>) since
a46c265051af9b383c928914087d1e91025c2d2f "split CreateVirtualDevice into two
methods".  (The argument to

>     mpGraphics = new AquaSalGraphics( /*pGraphic*/ );

had been commented out ever since the code got introduced in
f0faedb959edd27d6b5b96ec77fd54f7172d52dd "INTEGRATION: CWS aquabmpfix01
(1.22.12); FILE MERGED".)

Change-Id: I476bba0fe65005bbd8f95e7185639e0a6629affd
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/181101
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>