Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/26823/ : FAILURE

error ""get_id" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sw/source/uibase/inc/numfmtlb.hxx:130:22 ( https://ci.libreoffice.org/job/gerrit_mac/28718/ )

error: "get_id" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sw/source/uibase/inc/numfmtlb.hxx ( https://ci.libreoffice.org/job/gerrit_mac/28718/ )

Patch-set: 4
Label: Verified=-1