Update patch set 3
Patch Set 3:

I have Linux master builds failing since last night during RPM packaging, this commit looks suspiciously related. Error message:

Processing files: libreoffice7.1-freedesktop-menus-7.1.0-0.noarch
error: File not found by glob: /workdir/workdir/CustomTarget/sysui/rpm/libreoffice/freedesktop/usr/share/icons/hicolor/*/mimetypes/*svg


RPM build errors:
    File not found by glob: /workdir/workdir/CustomTarget/sysui/rpm/libreoffice/freedesktop/usr/share/icons/hicolor/*/mimetypes/*svg
make[1]: *** [/workdir/workdir/CustomTarget/sysui/rpm/libreoffice/libreoffice7.1-freedesktop-menus-7.1.0-0.noarch.rpm] Error 1
make: *** [build] Error 2

Patch-set: 3
CC: Gerrit User 1000006 <1000006@6622c302-437a-49ad-a91d-55ba7dcf1615>