Fix HAVE_CPP_CONSTEVAL check for MSVC
For one, it always trivially failed with

> LINK : fatal error LNK1104: cannot open file 'LIBCMT.lib'

because of a missing LIB env var expected by cl.  (Rather using LDFLAGS with
something like

> LDFLAGS="$LDFLAGS -LIBPATH:$COMPATH/lib/$WIN_HOST_ARCH"

instead of prepending LIB to $CXX via env wouldn't work, as AC_RUN_IFELSE puts
LDFLAGS too early on the compiler command line, causing "cl : Command line
warning D9002 : ignoring unknown option '-LIBPATH:...'".  And just using
something like

> CXX="env LIB=$COMPATH/lib/$WIN_HOST_ARCH $CXX"

instead of the full $ILIB would cause "LINK : fatal error LNK1104: cannot open
file 'kernel32.lib'".)  This means that the HAVE_CPP_CONSEVAL check had to be
moved past setting up ILIB.

But for another, detection of HAVE_CPP_CONSTEVAL under --with-latest-c++ would
trigger MSVC bug <https://developercommunity.visualstudio.com/t/1581879> "Bogus
error C7595 with consteval constructor in ternary expression (/std:c++latest)"
at

> sd/source/ui/unoidl/unoobj.cxx(742): error C7595: 'Color::Color': call to immediate function is not a constant expression

(and see also f8a30a87a9d0c68dc16d5fa2ca63f687b1d90da1 "Fix (mis-)uses of
temporary O[U]StringLiteral") so add a test for that bug to the checking code.

Change-Id: Iedf793f388fc190555a71ed3ab63e87a77ad4828
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/125093
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>