Update patch set 2
Patch Set 2:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/73304/ : FAILURE

error "this member function can be declared static [loplugin:staticmethods]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/basic/qa/cppunit/basictest.hxx:34:10 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75483/ )

use default type instead of indirection ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75483/ )

clang plugin salunicodeliteral did trigger. in LIBO_INTERNAL_ONLY code, replace literal cast to "sal_Unicode" (aka "char16_t") with a u"..." char16_t character literal ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75483/ )

error: in LIBO_INTERNAL_ONLY code, replace literal cast to "sal_Unicode" (aka "char16_t") with a u"..." char16_t character literal [loplugin:salunicodeliteral] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/basic/qa/cppunit/basictest.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75483/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>