Update patch set 10
Patch Set 10: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/57116/ : FAILURE

clang plugin unusedvariablecheck did trigger. unused variable "aStreamsList" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/60201/ )

error: unused variable "aStreamsList" [loplugin:unusedvariablecheck] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sd/source/filter/sdpptwrp.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/60201/ )

Patch-set: 10
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1