Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/46975/ : FAILURE

error ""DrivesHighdpiScaling" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/inc/qt5/Qt5Graphics.hxx:84:18 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/50386/ )

clang plugin redundantcast did trigger. static_cast from "qreal" (aka "double") prvalue to "qreal" prvalue is redundant ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/50386/ )

error: "DrivesHighdpiScaling" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/inc/qt5/Qt5Graphics.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/50386/ )

Patch-set: 5
Label: Verified=-1