zxing: use new CreateBarcode API with zxing >= 3.0
cassert.patch fixes
workdir/UnpackedTarball/zxing/core/src/Content.cpp: In member function ‘std::string ZXing::Content::render(bool) const’:
workdir/UnpackedTarball/zxing/core/src/Content.cpp:145:9: error: ‘assert’ was not declared in this scope
  145 |         assert(!utf8Cache.empty());

0001-Silence-deprecated-declarations-warnings-on-Windows-.patch fixes
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\zxing\core\src\ReaderOptions.h(173): error C2220: the following warning is treated as an error
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\zxing\core\src\ReaderOptions.h(173): warning C4996: 'ZXing::ReaderOptions::tryCode39ExtendedMode': was declared deprecated
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\zxing\core\src\ReaderOptions.h(176): warning C4996: 'ZXing::ReaderOptions::validateCode39CheckSum': was declared deprecated
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\zxing\core\src\ReaderOptions.h(180): warning C4996: 'ZXing::ReaderOptions::validateITFCheckSum': was declared deprecated

Notes from Axxel:

QrCodeGenDialog.cxx:
The patch technically breaks the "margin" functionality.
The new API simply does not allow to specify an arbitrary number of margin pixels.
By default, the generated symbols are rendered with a quiet zone according
to the specifications of the respective barcode symbology.

Version.h:
The updated patch is supposed to
 * enable the new libzint backend (which is embedded inside the zxing-cpp tar ball)
 * completely disable the reader functionality, as it is apparently not used by LibreOffice
 * remove some unused symbologies (like PDF417, etc.) from the build

Co-authored-by: axxel <awagger@gmail.com>
Change-Id: Ica02e6e1a9f3b6ebf9cfa0f5d4421a7065f2cc9e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/200607
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>