Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://cpci.cbg.collabora.co.uk:8080/job/Gerrit%20for%20cp-6.4/1733/ : FAILURE

Visual studio complained about error C2440: "<function-style-cast>": cannot convert from "const char *" to "rtl::OUString" in file C:/lo/jenkins/workspace/gerrit_windows_cp-6.4_32bit/filter/source/svg/svgwriter.cxx(1179) ( https://cpci.cbg.collabora.co.uk:8080/job/gerrit_windows_cp-6.4_32bit/1740/ )

Patch-set: 2
Tag: autogenerated:jenkins-gerrit-trigger
Reviewer: Gerrit User 1002181 <1002181@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1