Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/24830/ : FAILURE

error "class "FontInfo" was previously declared as a struct [-Werror,-Wmismatched-tags]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/canvas/base/canvasbase.hxx:31:39 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/26436/ )

error: class "FontInfo" was previously declared as a struct [-Werror,-Wmismatched-tags] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/canvas/base/canvasbase.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/26436/ )

Patch-set: 1
Label: Verified=-1