Fix call through empty std::function
...after d5e894dec11f5fbc8c1e42625c01d3d3c2c250c2 "vcl: add VclCustomWidget for
client-rendered widgets" introduced a latent null-factory bug, and then
4a64c7e12c34b9840624e3c1e30746022c06b1bf "cui: client-render the spelling dialog
error sentence" started to actually trigger it, as seen during
UITest_writer_tests4,

> ======================================================================
> ERROR: test_tdf157992 (spellDialog.SpellingAndGrammarDialog.test_tdf157992)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File ".../engine/sw/qa/uitest/writer_tests4/spellDialog.py", line 192, in test_tdf157992
>     sentence = xDialog.getChild('errorsentence')
> uno.com.sun.star.uno.RuntimeException: C++ code threw St17bad_function_call: bad_function_call at bridges/source/cpp_uno/gcc3_linux_x86-64/uno2cpp.cxx:238

(which has meanwhile been removed with 617bfe64deea59c702734ae0c1cb89578349d2da
"engine UITest_writer_tests4: remove broken test_tdf157992")

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I4820b28359b9f9d530f6b2552e0ca86d92a38a03
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/5367
Tested-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>