Let test_tdf170386 work on Windows
After commit 54b76f7ca0ba07b3a8630ebcd30ea091050f0812
(Avoid parameter introduced in Python 3.12, 2026-02-13), it failed
on Windows with

Traceback (most recent call last):
  File "C:\lo\build\instdir\program\python-core-3.13.12\lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\lo\core\uitest\uitest\test.py", line 220, in create_doc_in_start_center
    yield component
  File "C:/lo/core/sd/qa/uitest/impress_tests2/tdf170386.py", line 55, in test_tdf170386
    xModel.storeAsURL(url, [])
    ~~~~~~~~~~~~~~~~~^^^^^^^^^
tdf170386.com.sun.star.task.ErrorCodeIOException: SfxBaseModel::impl_store <file:///C:/lo/build/tmp/tmp8d1tnp7g.odg> failed: 0x507(Error Area:Io Class:Access Code:7) at C:/lo/core/sfx2/source/doc/sfxbasemodel.cxx:3304

That was because tempfile.NamedTemporaryFile locks the created file
on Windows, unless some specific conditions are true (documented at
https://docs.python.org/3/library/tempfile.html).

Fix it by creating a custom context manager, which checks platform,
and calls tempfile.NamedTemporaryFile with delete_on_close=False on
Windows.

Change-Id: I122fabc89e469a02802c1e5237052d71cdf8bcdf
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/200994
Tested-by: Jenkins
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>