Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/108283/ : FAILURE

error "‘void {anonymous}::detail::insert(rtl_String**, sal_Int32*, sal_Int32, const char*, sal_Int32)’ defined but not used [-Werror=unused-function]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sal/rtl/strimp.hxx:138:6 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/111777/ )

error: ‘void {anonymous}::detail::insert(rtl_String**, sal_Int32*, sal_Int32, const char*, sal_Int32)’ defined but not used [-Werror=unused-function] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sal/rtl/strimp.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/111777/ )

compiler warning unused-function treated as error: ‘void {anonymous}::detail::insert(rtl_String**, sal_Int32*, sal_Int32, const char*, sal_Int32)’ defined but not used in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sal/rtl/strimp.hxx:138:6 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/111777/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1