Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/25800/ : FAILURE

Visual studio complained about error C2440: "reinterpret_cast": cannot convert from "const int *" to "std::atomic<int> *" in file c:\cygwin\home\tdf\lode\jenkins\workspace\gerrit_windows\workdir\unpackedtarball\harfbuzz\src\hb-atomic.hh(272) ( https://ci.libreoffice.org/job/gerrit_windows/29916/ )

Patch-set: 1
Label: Verified=-1