Update patch set 1
Patch Set 1: Code-Review-1 Verified-1

Hi guys, I'm trying to figure out what's causing this problem:

[marcos@xfiles core]$ make starmath
cd /mnt/data/gitroot/core/starmath && make  -j 4 -rs
[build CXX] starmath/source/dialog.cxx
[build LOC] top level modules: starmath
[build LOC] loaded modules: starmath
In file included from /mnt/data/gitroot/core/workdir/UnpackedTarball/boost/boost/bind.hpp:22:0,
                 from /mnt/data/gitroot/core/workdir/UnpackedTarball/boost/boost/signals2/slot.hpp:15,
                 from /mnt/data/gitroot/core/workdir/UnpackedTarball/boost/boost/signals2/connection.hpp:23,
                 from /mnt/data/gitroot/core/workdir/UnpackedTarball/boost/boost/signals2/signal.hpp:21,
                 from /mnt/data/gitroot/core/include/vcl/edit.hxx:23,
                 from /mnt/data/gitroot/core/include/vcl/fixed.hxx:27,
                 from /mnt/data/gitroot/core/include/sfx2/tbxctrl.hxx:27,
                 from /mnt/data/gitroot/core/include/sfx2/app.hxx:42,
                 from /mnt/data/gitroot/core/starmath/source/dialog.cxx:25:
/mnt/data/gitroot/core/workdir/UnpackedTarball/boost/boost/bind/bind.hpp: In instantiation of ‘struct boost::_bi::result_traits<boost::_bi::unspecified, void (SmSymbolDialog::*)()>’:
/mnt/data/gitroot/core/workdir/UnpackedTarball/boost/boost/bind/bind_template.hpp:15:48:   required from ‘class boost::_bi::bind_t<boost::_bi::unspecified, void (SmSymbolDialog::*)(), boost::_bi::list2<boost::_bi::value<SmSymbolDialog*>, boost::arg<1> > >’
/mnt/data/gitroot/core/starmath/source/dialog.cxx:1474:122:   required from here
/mnt/data/gitroot/core/workdir/UnpackedTarball/boost/boost/bind/bind.hpp:69:37: error: ‘void (SmSymbolDialog::*)()’ is not a class, struct, or union type
     typedef typename F::result_type type;
                                     ^

Can someone give a direct here? Thanks!

Patch-set: 1
Reviewer: Gerrit User 1000186 <1000186@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Label: Code-Review=-1