fix compile: missing semi-colon in < gtk 3.22 block
compile error message:
vcl/unx/gtk3/gtk3gtkframe.cxx:2930:1: error: new types
may not be defined in a return type
 enum GdkAnchorHints
 ^~~~
vcl/unx/gtk3/gtk3gtkframe.cxx:2930:1: note: (perhaps a
semicolon is missing after the definition of ‘GdkAnchorHints’)

It passes Jenkins tests since they ignore this block.

Change-Id: I3da71d114ac4cd82ac4644f3b6cc1f7142810f44