Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/93686/ : FAILURE

clang plugin stringview did trigger. instead of an "rtl::OUString" constructed from a "sal_Unicode" (aka "char16_t"), pass a "std::u16string_view" (or an "rtl::OUStringChar") ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/94574/ )

error: instead of an "rtl::OUString" constructed from a "sal_Unicode" (aka "char16_t"), pass a "std::u16string_view" (or an "rtl::OUStringChar") [loplugin:stringview] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/ui/docshell/impex.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/94574/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1