sc: fix windows build
C:\cygwin64\home\tdf\jenkins\workspace\lo_daily_src\sc\inc\cellsuno.hxx(404): error C2487: 'ScCellRangesObj::{ctor}': member of dll interface class may not be declared with dll interface

after
commit 79322a7025bb6fd61928204f90230560b09b4ba9
Author: Noel Grandin <noel.grandin@collabora.co.uk>
Date:   Wed May 21 15:28:41 2025 +0200

    tdf#166684 strip out some unnecessary UNO work

Change-Id: I0d90f5ba07d309d3fc1d4a5518596ed1667e547d
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/185931
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>