Update patch set 9
Patch Set 9: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/55447/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "xmlDocPtr" to "std::unique_ptr<xmlDoc,xmlDocDeleter>" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/chart2/qa/extras/xshape/chart2xshape.cxx(176) ( https://ci.libreoffice.org/job/gerrit_windows/63543/ )

Patch-set: 9
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1