Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/19534/ : FAILURE

error: ParmVarDecl, use "bool" instead of "sal_Bool" [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/qa/extras/chart2import.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/20152/ )

clang plugin salbool did trigger. ParmVarDecl, use "bool" instead of "sal_Bool" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/20152/ )

Patch-set: 1
Label: Verified=-1