Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/37235/ : FAILURE

error: externally available entity "SetToolBarProperty" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/window/NotebookBarAddonsMerger.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/40119/ )

clang plugin external did trigger. externally available entity "SetToolBarProperty" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/40119/ )

Patch-set: 2
Label: Verified=-1