Remove some OSL_DEBUG_LEVEL > 1 code
...that would no longer compile since 2f5f45921b05904a4be1ff633be09c62cb44ff08
"support O(U)String::number() for fast string concatenation", anyway:

> vcl/unx/generic/app/i18n_cb.cxx:508:56: error: incompatible operand types ('const char [14]' and 'OStringNumber<int>')
>                 << ((call_data->type == XIMBitmapType) ?
>                                                        ^

Change-Id: Id7818ed6228ff317e1bee4efd53f15a2786689d4