Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/21591/ : FAILURE

error "use "bool" instead of "sal_Bool" as return type [loplugin:salbool]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/filter/source/svg/svgfilter.hxx:284:5 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/22624/ )

clang plugin salbool did trigger. use "bool" instead of "sal_Bool" as return type ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/22624/ )

error: use "bool" instead of "sal_Bool" as return type [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/filter/source/svg/svgfilter.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/22624/ )

Patch-set: 1
Label: Verified=-1