pyuno: hook into import *after* the _whole_ uno module is successfully loaded
This avoids breaking the whole python process module importing
when an uno.py import failure happens after the hooking point.
In that case, _uno_import is still the python module loader,
but _g_delegatee is not anymore bound to the previously installed
importer, and thus any module import fails with:
  File "/home/master/src/libreoffice/core/install/basis3.5/program/uno.py", line 260, in _uno_import
    return _g_delegatee( name, *optargs, **kwargs )
TypeError: 'NoneType' object is not callable