Update patch set 1
Patch Set 1:

I do not know if the difference to your system is, that you have multiple SDK installed, I do not I only have 10.12. 

The 2 exact errors I get are:
/Users/jani/libreoffice/repos/core/core/pyuno/source/module/pyuno_util.cxx:43:18: error: no matching function for call to 'PyUnicodeUCS2_FromUnicode'
    ret = PyRef( PyUnicode_FromUnicode( str.getStr(), str.getLength() ), SAL_NO_ACQUIRE );
                 ^~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/unicodeobject.h:196:32: note: expanded from macro 'PyUnicode_FromUnicode'
# define PyUnicode_FromUnicode PyUnicodeUCS2_FromUnicode
                               ^~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/unicodeobject.h:464:23: note: candidate function not viable: no known conversion from 'const sal_Unicode *' (aka 'const char16_t *') to 'const Py_UNICODE *' (aka 'const unsigned short *') for 1st argument
---> + a lot of trying

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/unicodeobject.h:196:32: note: expanded from macro 'PyUnicode_FromUnicode'
# define PyUnicode_FromUnicode PyUnicodeUCS2_FromUnicode
                               ^
/Users/jani/libreoffice/repos/core/core/pyuno/source/module/pyuno_util.cxx:63:11: error: no matching conversion for functional-style cast from 'Py_UNICODE *' (aka 'unsigned short *') to 'rtl::OUString'
    ret = OUString( PyUnicode_AS_UNICODE( pystr ) );
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jani/libreoffice/repos/core/core/include/rtl/ustring.hxx:177:14: note: candidate constructor not viable: no known conversion from 'Py_UNICODE *' (aka 'unsigned short *') to 'sal_Unicode' (aka 'char16_t') for 1st argument; dereference the argument with *
    explicit OUString( sal_Unicode value )
             ^
---> + a lot of trying.


As you can see from the path the compiler uses include files from 10.12, so I think in order to test on your machine, you need to force it to use 10.12

Patch-set: 1
Reviewer: Gerrit User 1001121 <1001121@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0