pyuno: fix build against system-python-3.6
pyuno/source/module/pyuno_runtime.cxx:984:57: error: use of undeclared identifier 'PyThread_get_thread_ident'

It's only an assert, so simply do it only for >=3.7.

Change-Id: Ia3fffc7a9af30780adff9bc7dbabe1727c1f8f54
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/86410
Reviewed-by: Michael Stahl <michael.stahl@cib.de>
Tested-by: Jenkins
(cherry picked from commit fb4e15a89d8d8f081c0c152e5047bc0e76870b39)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/86421
Tested-by: Michael Stahl <michael.stahl@cib.de>