Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master_android/509/ : FAILURE

the build failed because of an issue with the bot itself, not with the code.
The Bot failed to checkout the source ( https://ci.libreoffice.org/job/gerrit_android_x86_64/97/ )

https://ci.libreoffice.org/job/gerrit_master/68000/ : FAILURE

clang plugin salcall did trigger. SAL_CALL inconsistency ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70418/ )

error: SAL_CALL inconsistency [loplugin:salcall] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/xmloff/source/core/xmlimp.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70418/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1