Update patch set 1
Patch Set 1:

Note: while this patch seems to be ok, on master it makes Android builds fail with

/home/android/lo/master-android-arm/drawinglayer/source/primitive2d/borderlineprimitive2d.cxx:210:60: error: 'round' is not a member of 'std'
                         dNote: while this patch seem to be ok, on master it makes Android builds fail with
ouble fWidth = bPixelCorrection ? std::round(fLeftWidth) : fLeftWidth;

Same for line 222 with fRightWidth, line numbers as of http://tinderbox.libreoffice.org/cgi-bin/gunzip.cgi?tree=MASTER&brief-log=1461072005.29714

This change should be amended with the corresponding fix.

Patch-set: 1
Label: Verified=0