Avoid -Werror=deprecated-declarations
...with qt5-qtbase-devel-5.15.1-1.fc33.x86_64 on Fedora 33:

> ~/lo/core/vcl/qt5/Qt5AccessibleWidget.cxx: In function ‘QAccessible::Relation {anonymous}::lcl_matchUnoRelation(short int)’:
> ~/lo/core/vcl/qt5/Qt5AccessibleWidget.cxx:138:20: error: ‘constexpr QFlags<T>::QFlags(QFlags<T>::Zero) [with Enum = QAccessible::RelationFlag; QFlags<T>::Zero = int QFlags<QAccessible::RelationFlag>::Private::*]’ is deprecated: Use default constructor instead [-Werror=deprecated-declarations]
>   138 |             return nullptr;
>       |                    ^~~~~~~
> In file included from /usr/include/qt5/QtCore/qglobal.h:1304,
>                  from /usr/include/qt5/QtCore/qnamespace.h:43,
>                  from /usr/include/qt5/QtCore/qobjectdefs.h:48,
>                  from /usr/include/qt5/QtCore/qobject.h:46,
>                  from /usr/include/qt5/QtCore/QObject:1,
>                  from ~/lo/core/vcl/inc/qt5/Qt5AccessibleWidget.hxx:14,
>                  from ~/lo/core/vcl/qt5/Qt5AccessibleWidget.cxx:20:
> /usr/include/qt5/QtCore/qflags.h:123:80: note: declared here
>   123 |     QT_DEPRECATED_X("Use default constructor instead") Q_DECL_CONSTEXPR inline QFlags(Zero) noexcept : i(0) {}
>       |                                                                                ^~~~~~

Change-Id: Ic0c113fe208764e8bc0b9c3fbf7358d6af4000ce
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/103474
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit ed424cf629b2ab33089b1be0dccfce60be85d726)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/183434
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
Tested-by: allotropia jenkins <jenkins@allotropia.de>