browsebox: Convert dispatch ID defines to enum class
Convert the `BROWSER_*` defines in include/svtools/brwbox.hxx
to a new enum class BrowserDispatchId.

The specific integer values that were used
don't seem to have any particular meaning, so
just drop them.

Add default case that does nothing in BrowseBox::Dispatch
to address

    /home/michi/development/git/libreoffice/svtools/source/brwbox/brwbox2.cxx:1779:13: error: 5 enumeration values not handled in switch: 'NONE', 'CURSORENDOFSCREEN', 'CURSORTOPOFSCREEN'... [-Werror,-Wswitch]
     1779 |     switch (eId)
          |             ^~~
    1 error generated.

Change-Id: Ibb023ec13ee2c10a0fc0ef7abe1371dbd856e735
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/181167
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins