Update patch set 1
Patch Set 1:

Windows build failed because of internal problem, not relevant to patch:
java.io.IOException: Failed to mkdirs: C:\cygwin/home/tdf/lode/jenkins\workspace\lo_gerrit_master\Gerrit\Gerrit\Platform\Windows

Patch-set: 1
Label: Verified=0