Update patch set 1
Patch Set 1:

> error: Server does not allow request for unadvertised object 3b2fd61e82d2ab68c941cfdd848ace5f91b05652

Sounds like a problem not caused by this change.

Patch-set: 1