Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/42378/ : FAILURE

clang plugin salbool did trigger. VarDecl, use "bool" instead of "sal_Bool" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/45580/ )

error: VarDecl, use "bool" instead of "sal_Bool" [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/ui/misc/bookmark.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/45580/ )

Patch-set: 4
Label: Verified=-1