Fix build
After commit 07b9a47b8f26ebb9a62180b52522ded5bf53617b (Fix SIGABRT
in SortOrderReverser::addOrderIndices with mismatched key states,
2026-03-21).

A very strange error:

SortOrderReverserTest.o : error LNK2019: unresolved external symbol
"__declspec(dllimport) public: __cdecl Color::Color(void)"
(__imp_??0Color@@QEAA@XZ) referenced in function "public: __cdecl
ScSortKeyState::ScSortKeyState(void)" (??0ScSortKeyState@@QEAA@XZ)

which mentions an inline ctor as unresolved in my VS2026 build.

Change-Id: Id3c52675a8d93371f67a64cd3fe8de4013f54b23
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/202353
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>