Update to latest external/quickjs 0.16.2
...thereby switching to the simpler amalgam zip
(<https://github.com/quickjs-ng/quickjs/releases/download/v0.16.2/quickjs-amalgam.zip>).

No idea why the Windows build would only now start to fail with

> quickjs-amalgam.c
> C:/PROGRA~1/MIB055~1/18/COMMUN~1/VC/Tools/MSVC/14.51.36231/Include\vcruntime_c11_stdatomic.h(12): fatal error C1189: #error:  "C atomic support is not enabled"
> make[1]: *** [C:/lo/jenkins/workspace/gerrit_windows_app_main/engine/solenv/gbuild/LinkTarget.mk:342: C:/lo/jenkins/workspace/gerrit_windows_app_main/engine/workdir/GenCObject/UnpackedTarball/quickjs/quickjs-amalgam.o] Error 1

(<https://cpci.cbg.collabora.co.uk:8080/job/gerrit_windows_app_main/11892/>),
but it apparently needs an additional /experimental:c11atomics, same as what
<https://github.com/quickjs-ng/quickjs/commit/569b238ec415da087a4a19f45bbd10a1137151c5>
"Add cross-platform Atomics support" does.

(And error source location reporting apparently changed slightly, presumably at
<https://github.com/quickjs-ng/quickjs/commit/d90ab51d2614735a03c70e4f131f6142abb70cb3>
"Report the correct column for an undefined global reference", so adapt
CppunitTest_jsuno_execute accordingly.)

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I0e6f16e591fb3da6af16d5eb1c7c61c7b158d39b
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/11957
Reviewed-by: Andras Timar <andras.timar@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>