Avoid test_tdf139301 hanging upon failure
At least in my local Linux build, UITest_writer_tests7
UITEST_TEST_NAME=tdf139301.tdf139301.test_tdf139301, as introduced with
183c06fc02a50fb117bb6162e4d6e56cdd34fad1 "tdf#139301 fix OOXML-compatible preset
dash styles", consistently fails (for whatever reason) with

> FAIL: test_tdf139301 (tdf139301.tdf139301)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "~/lo/core/sw/qa/uitest/writer_tests7/tdf139301.py", line 40, in test_tdf139301
>     self.assertEqual(style, styles[i])
> AssertionError: 'Dash Dot Dot' != 'Dot'
> - Dash Dot Dot
> + Dot

and then would hang in tearDown (presumably because the

  self.ui_test.close_dialog_through_button(xOKBtn)

line would be skipped due to the AssertionError being thrown).

While this commit does not fix the failing test, it at least makes it no longer
hang.

Change-Id: I80fd88d1668b162166a971f1a7bef1b5f965c421