Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/85162/ : FAILURE

error: no need to explicitly init an instance of "std::unique_ptr<MSWordSections>" with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/filter/ww8/rtfexport.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/86567/ )

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "std::unique_ptr<MSWordSections>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/86567/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1