Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/69829/ : FAILURE

clang plugin external did trigger. externally available entity "DrawBevel" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72166/ )

error: externally available entity "DrawBevel" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/svx/source/dialog/fntctrl.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72166/ )

Patch-set: 6
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1