Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/82400/ : FAILURE

clang plugin stringviewparam did trigger. replace function parameter of type "const rtl::OUString &" with "std::u16string_view" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/83931/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/83931/ )

error: replace function parameter of type "const rtl::OUString &" with "std::u16string_view" [loplugin:stringviewparam] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/xmlscript/qa/cppunit/test.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/83931/ )

Patch-set: 7
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1