Rename sorted_vector::erase(size_t) to erase_at
emscripten clang fails with:

sc/source/core/data/attarray.cxx:378:44: \
    error: call to member function 'erase' is ambiguous
                        aNewCondFormatData.erase(nIndex);
                        ~~~~~~~~~~~~~~~~~~~^~~~~
include/o3tl/sorted_vector.hxx:86:15: note: candidate function
    size_type erase( const Value& x )
              ^
include/o3tl/sorted_vector.hxx:97:10: note: candidate function
    void erase( size_t index )

This looks like a compiler error, but if the vector contained
size_t values, this would also be ambiguous to begin with. So
this just renames erase(size_t) to erase_at.

And instead of a 2nd find in the failing code, after copying
the vector, it mow uses std::distance to remove the item.

Change-Id: I7d03ff32352a1890cc01ca241452c0f00d6a9302