Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/111622/ : FAILURE

error ""SparklineData" defined as a struct here but previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Werror,-Wmismatched-tags]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/inc/SparklineData.hxx:18:1 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/111110/ )

clang plugin unusedmember did trigger. unused class member ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/111110/ )

error: unused class member [loplugin:unusedmember] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/core/data/column2.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/111110/ )

"file" vs <file> clang plugin ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/111110/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1