-Wimplicit-function-declaration
> workdir/UnpackedTarball/zlib/gzlib.c:242:9: error: call to undeclared function 'lseek'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
>   242 |         LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
>       |         ^

etc., as causing an error now by default with Clang 18 trunk

Change-Id: Ic19c5710357a1f65046b5a225c6a181c3046938c
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/160554
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>