Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/70992/ : FAILURE

clang plugin toolslong did trigger. VarDecl, use "tools::Long" instead of "long" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/73293/ )

error: VarDecl, use "tools::Long" instead of "long" [loplugin:toolslong] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/ui/view/tabvwsh3.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/73293/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1