Fix compilerplugins/clang/test/useuniqueptr.cxx for clang-cl
...where it failed with

> error: 'error' diagnostics expected but not seen:
>   File C:/lo-clang/core/compilerplugins/clang/test/useuniqueptr.cxx Line 266: rather manage this var with std::some_container<std::unique_ptr<T>> [loplugin:useuniqueptr]
>   File C:/lo-clang/core/compilerplugins/clang/test/useuniqueptr.cxx Line 275: rather manage this member with std::some_container<std::unique_ptr<T>> [loplugin:useuniqueptr]

apparently due to differences in how some std types are implemented.

Change-Id: Ib81ed1a1da867359e7f22bb6fb6ceb3e610e2b41