sw: fix assert due to inconsistent ordering of MarkManager::m_vAllMarks
In function:
    std::pair<_FIter, _FIter> std::equal_range(_FIter, _FIter, const _Tp&,
    _Compare) [with _FIter = gnu_debug::_Safe_iterator<gnu_cxx::
    normal_iterator<sw::mark::MarkBase**, vector<sw::mark::MarkBase*,
    allocator<sw::mark::MarkBase*> > >, debug::vector<sw::mark::MarkBase*>,
    random_access_iterator_tag>; _Tp = SwPosition; _Compare =
    {anonymous}::CompareIMarkStartsBefore]

Error: elements in iterator range [first, last) are not partitioned by the
predicate __comp and value __val.

Change-Id: I2c78d64dc6e87ba1aae0dd08a0ece01b0c43e9fd
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/149553
Tested-by: Jenkins
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>