Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/93314/ : FAILURE

Visual studio complained about error C2440: "return": cannot convert from "const ScopedHBITMAP" to "HBITMAP" in file C:/cygwin/home/tdf/jenkins/workspace/gerrit_windows/vcl/inc\win/salbmp.h(51) ( https://ci.libreoffice.org/job/gerrit_windows/104203/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1