add --disable-pedantic to avoid warnings as error for xmlsec
like...

 symkeys.c:621:30: error: no newline at end of file [-Werror,-Wnewline-eof]
 #endif /* XMLSEC_NO_PBKDF2 */
                             ^
 1 error generated.
 make[5]: *** [Makefile:765: libxmlsec1_openssl_la-symkeys.lo] Error 1

Change-Id: I1dcd0cb6b350f412c30fb5a8d3aa4976cd0afde5
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/150980
Tested-by: Jenkins
Reviewed-by: Caolán McNamara <caolanm@redhat.com>
(cherry picked from commit aa87fe2562e7a55a18a1c757a49babfe74377bcd)