Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/22294/ : FAILURE

error "‘SwFEShell’ has not been declared" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sw/source/core/inc/flyfrm.hxx:271:30 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/23129/ )

error: ‘SwFEShell’ has not been declared in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sw/source/core/inc/flyfrm.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/23129/ )

Patch-set: 1
Label: Verified=-1