skia: upgrade to m144
Add external/skia/C4100warning.patch.1 to fix
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(92): error C2220: the following warning is treated as an error
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(92): warning C4100: 'window': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(93): warning C4100: 'c': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(95): warning C4100: 'y': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(95): warning C4100: 'x': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(96): warning C4100: 'y': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(96): warning C4100: 'x': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(96): warning C4100: 'delta': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(97): warning C4100: 'y': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(97): warning C4100: 'x': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(97): warning C4100: 'owner': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(99): warning C4100: 'state': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(100): warning C4100: 'y': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(100): warning C4100: 'x': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(100): warning C4100: 'scale': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(100): warning C4100: 'state': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(101): warning C4100: 'stateValue': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(101): warning C4100: 'stateName': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(104): warning C4100: 'height': unreferenced parameter
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\skia\tools/sk_app/Window.h(104): warning C4100: 'width': unreferenced parameter

Done following the steps in external/skia/README

Change-Id: If6d60484b36f8f90cf899078426586cf0c382daa
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/195856
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>