Fix GlobalNamespace check
...so that e.g. building on F36 with -stdlib=libc++ doesn't fail with

> i18nutil/source/utility/paper.cxx:311:75: error: NullToPointer ValueDependentIsNotNull ZeroLiteral -> nullptr [loplugin:nullptr]
>         locale_t loc = newlocale(LC_PAPER_MASK, "", static_cast<locale_t>(0));
>                                                                           ^

when the locale_t typedef declaration is nested in extern "C" (from
/usr/include/stdlib.h) which in turn is nested in extern "C++" (from LLVM's
include/c++/v1/math.h)

Change-Id: Ie81d7425cda231954bdbab47c3a0431dc7c27f5f