Remove broken --enable-gtk4
...which was off by default and started to fail to build after
7e6fda4318221051bf7ee9caaf51f86066350104 "loplugin:unusedmethods",

> engine/vcl/unx/gtk4/gtkcairo.cxx:10:10: fatal error: ../gtk3/gtkcairo.cxx: No such file or directory
>    10 | #include "../gtk3/gtkcairo.cxx"
>       |          ^~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I87338def75fc8ac3708ba63178be24208742d31f
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/7380
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>