Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/44931/ : FAILURE

error "class "ImplSVHelpData" was previously declared as a struct [-Werror,-Wmismatched-tags]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/inc/helpwin.hxx:27:1 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/48390/ )

error: class "ImplSVHelpData" was previously declared as a struct [-Werror,-Wmismatched-tags] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/inc/helpwin.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/48390/ )

Patch-set: 2
Label: Verified=-1