Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > The gerrit clang compiler usually gives me warnings about that those constructors are unnecessary.
> 
> No, it does not (or else ~everybody would get compilation failures with the current version)?

This is the warning I got:
/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/starmath/source/mathml/export.cxx:412:16: error: elide constructor call [loplugin:stringconstant]
        return OUString(u"");

What did I misunderstand?

> > So I guess it's performance related.
> 
> No, it is not; it merely makes syntactically implicit what was explicit.
> 
> 
> What is your motivation for changing from plain "..." string literals to UTF-16 u"..." ones?  None of these changes are wrong, but I don't see much motivation for any of them, either.  (Especially not if done only in one random location.  If there were a compelling reason to always use u"..." literals in OUString construction, we should do that change globally.)

Since OUString uses utf16 beneath it just made sense.

Patch-set: 2