sw: Use constexpr instead of #define for SwFrameType combinations
... and address loplugin:redundantfcast warning

    /home/michi/development/git/libreoffice/sw/source/core/layout/wsfrm.cxx:3380:39: error: redundant functional cast from 'const SwFrameType' to 'SwFrameType' [loplugin:redundantfcast]
     3380 |                                    : ~SwFrameType(FRM_NEIGHBOUR);
          |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Change-Id: Ie497b15a4e94ebd8aa59156446785ee00fba8a9f
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/184600
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>