Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/21070/ : FAILURE

clang plugin redundantinline did trigger. function has no external linkage but is explicitly declared "inline" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/22002/ )

error: function has no external linkage but is explicitly declared "inline" [loplugin:redundantinline] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/svx/source/sidebar/possize/PosSizePropertyPanel.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/22002/ )

Patch-set: 2
Label: Verified=-1