#i127139# undefined reference to `__stack_chk_fail' breaks build on some Linux 32-bit systems
Work around this issue for the time being, by always explicitly linking to libc (-lc)
for all gbuild modules, which I've verified doesn't break anything. (Using the Gold linker
instead of BFD also works, also for unknown reasons, but the Gold linker may not always be
available.)

Also revert the previous workaround in main/svl/Library_passwordcontainer.mk

Patch by: me