Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/73120/ : FAILURE

Visual studio complained about error C2664: "void connectivity::ado::OTools::putValue(const connectivity::ado::WpADOProperties &,const connectivity::ado::OLEVariant &,const connectivity::ado::OLEVariant &)": cannot convert argument 2 from "rtl::OUString" to "const connectivity::ado::OLEVariant &" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/connectivity/source/drivers/ado/AColumns.cxx(106) ( https://ci.libreoffice.org/job/gerrit_windows/83005/ )

likely caused by leftovers that linger around from an aborted build ( https://ci.libreoffice.org/job/gerrit_windows/83005/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1