Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/70603/ : FAILURE

clang plugin subtlezeroinit did trigger. if zero-initialization of "(anonymous namespace)::MyDocumentHandler" is intentional here, better make that more explicit (e.g., assigning to members, default constructor, default member initializers, std::memset) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72923/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72923/ )

error: if zero-initialization of "(anonymous namespace)::MyDocumentHandler" is intentional here, better make that more explicit (e.g., assigning to members, default constructor, default member initializers, std::memset) [loplugin:subtlezeroinit] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sax/qa/cppunit/parser.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72923/ )

the cppunit test CppunitTest_sd_import_tests failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72923/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1