Update patch set 8
Patch Set 8: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/110830/ : FAILURE

Visual studio complained about error C2440: "<function-style-cast>": cannot convert from "LPWSTR" to "rtl::OUString" in file C:/cygwin/home/tdf/jenkins/workspace/gerrit_windows/shell/source/win32/jumplist/JumpList.cxx(201) ( https://ci.libreoffice.org/job/gerrit_windows/122892/ )

Patch-set: 8
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1