work around rounding difference on i386 in descriptiveStatistics test
No idea why this only appears now, but:

======================================================================
FAIL: test_descriptive_statistics (descriptiveStatistics.descriptiveStatistics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rene/tmp/autopkgtest-lxc.4j23khs6/downtmp/build.zIT/src/sc/qa/uitest/statistics/descriptiveStatistics.py", line 108, in te
st_descriptive_statistics
    self.assertEqual(round(get_cell_by_position(document, 0, 6, 10).getValue(),14) , 0.01524095329036)
AssertionError: 0.01524095329035 != 0.01524095329036

Change-Id: I496daf61a9542ea0da78e6092dd7070a2665ab0a
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/127363
Tested-by: René Engelhard <rene@debian.org>
Tested-by: Jenkins
Reviewed-by: Eike Rathke <erack@redhat.com>
(cherry picked from commit c6f7d7d5b3f11ea054532608c542bad3da28f398)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/137522