Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_63/1319/ : FAILURE

error: unused parameter name [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64_branch/sw/source/core/doc/DocumentContentOperationsManager.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil_branch/654/ )

clang plugin casttovoid did trigger. unused parameter name ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil_branch/654/ )

Patch-set: 2