Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/97564/ : FAILURE

error: unused capture-default [loplugin:unusedcapturedefault] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/core/data/formulacell.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/98228/ )

clang plugin unusedcapturedefault did trigger. unused capture-default ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/98228/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000023 \u003c1000023@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}