Fix --enable-gtk3 build
...by partially reverting 7a0f5d70dd544caf869823d535073907f78f8957 "use
std::string in COKit::getTextSelection", which caused

> In file included from engine/kit/source/gtk/kitdocview.cxx:26:
> engine/include/COKit/COKitGtk.h:308:38: error: 'kit_doc_view_copy_selection' has C-linkage specified, but returns user-defined type 'std::string' (aka 'basic_string<char>') which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
>   308 | KIT_DOC_VIEW_DLLPUBLIC std::string   kit_doc_view_copy_selection  (KitDocumentView* pDocView,
>       |                                      ^
> engine/kit/source/gtk/kitdocview.cxx:3989:16: error: conversion function from 'std::nullptr_t' to 'std::string' (aka 'basic_string<char>') invokes a deleted function
>  3989 |         return nullptr;
>       |                ^~~~~~~
> ~/gcc/inst/lib/gcc/x86_64-pc-linux-gnu/17.0.0/../../../../include/c++/17.0.0/bits/basic_string.h:889:7: note: 'basic_string' has been explicitly marked deleted here
>   889 |       basic_string(nullptr_t) = delete;
>       |       ^
> engine/kit/source/gtk/kitdocview.cxx:3994:51: error: use of undeclared identifier 'aUsedMimeType'; did you mean 'pUsedMimeType'?
>  3994 |     return pDocument->getTextSelection(pMimeType, aUsedMimeType);
>       |                                                   ^~~~~~~~~~~~~
>       |                                                   pUsedMimeType
> engine/kit/source/gtk/kitdocview.cxx:3985:43: note: 'pUsedMimeType' declared here
>  3985 |                              std::string* pUsedMimeType)
>       |                                           ^

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I805f842f32869d94dd8828b6e07e7ef06da70f89
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/9384
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>