Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/76558/ : FAILURE

error "static_cast from "const SfxPoolItem *" to "const ScLineBreakCell *", which are not related by inheritance, is not allowed" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sc/inc/document.hxx:1719:16 ( https://ci.libreoffice.org/job/gerrit_mac/82142/ )

error: member access into incomplete type "const ScLineBreakCell" in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sc/source/ui/view/cliputil.cxx ( https://ci.libreoffice.org/job/gerrit_mac/82142/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1