fix build: chart2 -Werror=maybe-uninitialized
Not sure why only I'm picking this up on Ubuntu 24.04
gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0

chart2/source/controller/main/ControllerCommandDispatch.cxx:786:49:
error: ‘nFontWeight’ may be used uninitialized
[-Werror=maybe-uninitialized]
  786 |                 bool bFontWeight = (nFontWeight > 100.0);
      |                                    ~~~~~~~~~~~~~^~~~~~~~
libreoffice/chart2/source/controller/main/
ControllerCommandDispatch.cxx:784:23:
note: ‘nFontWeight’ was declared here
  784 |                 float nFontWeight;

Added with commit 1160d5b29a9cdae5ec6126663e888b8e5c76aba4
Author: Attila Szűcs on Thu Apr 24 11:13:08 2025 +0200
    Chart Font sidebar panel
and commited on May 8.

I'm sure I sucessfully compiled on this machine since May 8,
but just now I did a make clean and hit this warning.
I added to autogen.input: --with-distro=LibreOfficeFlatpak

Anyway, now it compiles for me.

Change-Id: I32cd286cdaa607bc4062e9238e9983fd8713f67c
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/187125
Tested-by: Jenkins
Reviewed-by: Justin Luth <jluth@mail.com>
Signed-off-by: Xisco Fauli <xiscofauli@libreoffice.org>
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/189858