external/nss: Missing include
> In file included from ../../nss-tool/common/util.cc:5:
> ../../nss-tool/common/util.h:30:64: error: no type named 'ifstream' in namespace 'std'
>    30 | std::istream &GetStreamFromFileOrStdin(std::string &path, std::ifstream &ifs);
>       |                                                           ~~~~~^

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: Ib31f9b2efaf38fb4d9aa0b5f78509b54f946496f
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/9809
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>