Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/69791/ : FAILURE

clang plugin fakebool did trigger. VarDecl, use "bool" instead of "sal_Bool" (aka "unsigned char") ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72129/ )

error: VarDecl, use "bool" instead of "sal_Bool" (aka "unsigned char") [loplugin:fakebool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/svx/source/dialog/fntctrl.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72129/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1