[25-2 only] Use o3tl::cmp_less instead of std::cmp_less
While o3tl::cmp_less was dropped for master in

    commit 8e0ffffe60f1e9c97d7937ffe7d206fb62900357
    AuthorDate: Thu Oct 26 22:40:24 2023 +0200
    CommitDate: Thu Apr 24 10:07:03 2025 +0200

        Directly use std::cmp_*, drop o3tl::cmp_*

, Android NDK 25 - the maximum NDK version supported on
the libreoffice-25-2 branch - doesn't support std::cmp_less,
so switch this use of std::cmp_less to o3tl::cmp_less on
that branch only.

Fixes this Android build error:

    .../editeng/source/editeng/impedit3.cxx:2427:44: error: no member named 'cmp_less' in namespace 'std'; did you mean 'o3tl::cmp_less'?
            while (aKashidaArray.size() > i && std::cmp_less(nGapSize, nEmRequiredSize))
                                               ^~~~~~~~~~~~~
                                               o3tl::cmp_less
    .../include/o3tl/intcmp.hxx:57:52: note: 'o3tl::cmp_less' declared here
    template <typename T1, typename T2> constexpr bool cmp_less(T1 value1, T2 value2) noexcept

Change-Id: I02ca2e75c321ad981b78e2473a035915187877cb
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/186135
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Tested-by: Jenkins
(cherry picked from commit a7d05a18cec16db25065ff713a6c115ddde552e3)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/186177
Tested-by: Christian Lohmaier <lohmaier+LibreOffice@googlemail.com>
Reviewed-by: Christian Lohmaier <lohmaier+LibreOffice@googlemail.com>