sw: UITest_writer_tests8 test_tdf150443 more tolerant
This fails on Fedora 39, also in the libreoffice-24-2 branch, with:
    self.assertEqual(get_state_as_dict(xWriterEdit)["CurrentPage"], "4")
AssertionError: '5' != '4'

Presumably a font substitution changing metrics problem, as "NexusSansOT"
is not found.

It looks like the exact page doesn't matter for the test.

Change-Id: I62eadb8321352ea47a0f8f83ab91fd50ff01f7e4
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/164353
Tested-by: Jenkins
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>
(cherry picked from commit 0b21e2a404c114529376dc50764dc0286dafc745)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/164364
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>