kit: fix the Linux gtk3 build after enum scoping
Building kit on Linux with gtk3 and gcc 14.2.0 failed with nine errors,
seven of them case labels

 /home/mk/online/1/engine/kit/source/gtk/kitdocview.cxx: In function 'gboolean globalCallback(gpointer)':
 /home/mk/online/1/engine/kit/source/gtk/kitdocview.cxx:933:29: error: could not convert 'COKitCallbackType::STATUS_INDICATOR_START' from 'COKitCallbackType' to 'int'
   933 |     case COKitCallbackType::STATUS_INDICATOR_START:
       |          ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
       |                             |
       |                             COKitCallbackType

and two the calls that fill the struct

 /home/mk/online/1/engine/kit/source/gtk/kitdocview.cxx: In function 'void globalCallbackWorker(COKitCallbackType, const char*, void*)':
 /home/mk/online/1/engine/kit/source/gtk/kitdocview.cxx:984:94: error: no matching function for call to '{anonymous}::CallbackData::CallbackData(COKitCallbackType&, const char*, KitDocumentView*&)'
   984 |     CallbackData* pCallback = new CallbackData(eType, pPayload ? pPayload : "(nil)", pDocView);
       |                                                                                              ^
 /home/mk/online/1/engine/kit/source/gtk/kitdocview.cxx:370:22: note:   no known conversion for argument 1 from 'COKitCallbackType' to 'int'
   370 |     CallbackData(int nType, std::string aPayload, KitDocumentView* pDocView)
       |                  ~~~~^~~~~

e54c4388aa8049f0caffafd902c8750168dc46f0 (Make COKitCallbackType a scoped
enumeration, 2026-07-28) left CallbackData::m_nType an int, which the
scoped type no longer converts to. Only a gtk3 build compiles this file,
kit/Module_kit.mk making Library_kitgtk and Executable_gtktiledviewer
conditional on ENABLE_GTK3: CI disables gtk3 in CPLinuxCommon.conf.

Signed-off-by: Mike Kaganski <mike.kaganski@collabora.com>
Change-Id: I6608532a9d6d5bf73b885e480c7aaf76b17caf65
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/8490
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>