Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/119091/ : FAILURE

Visual studio complained about error C2440: "static_cast": cannot convert from "ViewShellDocId" to "sal_Int32" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sfx2/source/view/lokhelper.cxx(857) ( https://ci.libreoffice.org/job/gerrit_windows/131829/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1, 2a3d0183ca376b7dd87048b4f6105bd3187f804b