Update patch set 24
Patch Set 24: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/70164/ : FAILURE

error "class "SmToken" was previously declared as a struct [-Werror,-Wmismatched-tags]" triggered in included file /home/tdf/lode/jenkins/workspace/android_x86/starmath/inc/starmathdatabase.hxx:23:1 ( https://ci.libreoffice.org/job/gerrit_android_x86/609/ )

error: class "SmToken" was previously declared as a struct [-Werror,-Wmismatched-tags] in file /home/tdf/lode/jenkins/workspace/android_x86/starmath/inc/starmathdatabase.hxx ( https://ci.libreoffice.org/job/gerrit_android_x86/609/ )

Patch-set: 24
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1