Revert brittle UITest for now
UITest_writer_tests2
UITEST_TEST_NAME=ComplexGroupShapeTest.ComplexGroupShapeTest.test_ComplexGroupShape,
introduced with e5650de86072b9db586a4532b5239acda77598c4 "tdf#143574 sw:
textboxes in group shapes - part 3 take 2", is apparently brittle and often
fails with

> ERROR: test_ComplexGroupShape (ComplexGroupShapeTest.ComplexGroupShapeTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/tdf/lode/jenkins/workspace/lo_ubsan/sw/qa/uitest/writer_tests2/ComplexGroupShapeTest.py", line 96, in test_ComplexGroupShape
>     self.assertEqual(True,document.getCurrentSelection().getByIndex(0).TextBox)
> AttributeError: TextBox

in (slow) ASan+UBSan builds like <https://ci.libreoffice.org//job/lo_ubsan/2232>
as well as in (fast) Flatpak `make check` test builds like
<https://flathub.org/builds/#/builders/32/builds/71183>.

There is work going on at <https://gerrit.libreoffice.org/c/core/+/126861>
"[WIP]Sw: Replace PyUITests with CPPUnit ones" to fix that, so remove the test
for now until that fix is ready, to get the various failing builds unstuck.

Change-Id: I3579cedce35e1373c04f976a1a57ac98f1f33448