fix windows build
34a7b51ea482d4487d4fb8e61cde18aa1ff9b8ff (for 5-1) auto → size_t made
32bit happy, but win64bit still failed with:
error C2784: ´_Ty std::min(std::initializer_list<_Elem>,_Pr)´ : could
not deduce template argument for ´std::initializer_list<_Elem>´ from
´__int64´

(cherry picked from commit 53f645a9c959d93bde9230862c415c4ab2e3817b)

Change-Id: Ib44840f692f1bcdea90decfe443c6eb72806002a