a11y: give the calc functions sidebar labels
Put labels above the search entry and category combobox, move the
accessible-name to the label text. Fixes the ScFunctionsDeck cypress
a11y check:

  A11yValidatorException: In sidebar at '... > ScFunctionsDeck > ...
  > FunctionPanel > ... > search > search-input': input element
  'search-input' is missing a visible label. Sidebar form controls
  should have a <label> or aria-labelledby association, not just
  aria-label.

Signed-off-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Change-Id: Icc999274a4bccf18f8419cdedb352156165603b2
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/2513
Reviewed-by: Mohit Marathe <mohit.marathe@collabora.com>