Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/100204/ : FAILURE

clang plugin unusedcapturedefault did trigger. unused capture-default ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/100646/ )

error: unused capture-default [loplugin:unusedcapturedefault] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/source/model/main/Diagram.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/100646/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000083 \u003c1000083@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}