Update patch set 2
Patch Set 2:

> /home/julien/lo/libo_perf/l10ntools/source/helper.cxx:19:69: error: replace function parameter of type 'const rtl::OString &' with 'std::string_view' [loplugin:stringviewparam]
>     const OString& rText, const OString& rUnEscaped, const OString& rEscaped )
>                                                      ~~~~~~~~~~~~~~~^~~~~~~~
> /home/julien/lo/libo_perf/l10ntools/inc/helper.hxx:31:69: note: previous declaration is here [loplugin:stringviewparam]
>     const OString& rText, const OString& rUnEscaped, const OString& rEscaped );
>                                                      ~~~~~~~~~~~~~~~^~~~~~~~
> 1 error generated.
[...]
> #--enable-dbgutil

Ah, so the call to rEscaped.getLength() (which would otherwise suppress the warning) in the assert at l10ntools/source/helper.cxx:20 is hidden by the (implicit) --disable-assert-always-abort.  Hm, maybe we should also conservatively suppress the warning when we see an NDEBUG-disabled assert (or something even more conservative).

Patch-set: 2