vcl: GTK: fix libstdc++ "irreflexive" assert
/usr/include/c++/6.1.1/bits/stl_algo.h:4737:
Error: comparison doesn't meet irreflexive requirements, assert(!(a < a)).

GdkRectangleCoincident is clearly not a less-than operator as required
for std::sort.

(cherry picked from commit e2b267b1906817cc45f0e4896bed58cff5b6b0f9)
Reviewed-on: https://gerrit.libreoffice.org/26762
Tested-by: Jenkins <ci@libreoffice.org>
Reviewed-by: Caolán McNamara <caolanm@redhat.com>
Tested-by: Caolán McNamara <caolanm@redhat.com>
(cherry picked from commit 8851333f8aafe84ca9479faf24d9164035aff520)

squashed dependency:
fdo#78799 - ignore overlayed monitors with co-incident origin.
This happens with certain fglrx drivers etc. where 'cloned' is not
set but instead both monitors are placed over the top of each other
(by XFCE) -> work around that.
(cherry picked from commit 5eeea7c91d87ee8f0b8bc8c0144c04fb84310bbf)

Change-Id: If2e65d420dc8cdf0707081361a40d4eaea28424e