Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/10035/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "std::unique_ptr<SvStream,std::default_delete<_Ty>>" to "SvStream *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sfx2/source/doc/graphhelp.cxx(90) ( https://ci.libreoffice.org/job/gerrit_windows/10706/ )

Patch-set: 2
Label: Verified=-1