Avoid loplugin:salcall
> In file included from jurt/source/pipe/staticsalhack.cxx:39:
> sal/osl/unx/module.cxx:212:6: error: SAL_CALL unnecessary here [loplugin:salcall]
> void SAL_CALL osl_unloadModule(oslModule hModule)
> ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

in an ASan+UBSan build with --enable-compiler-plugins, after
b5b1eae538a902fed165d5dd93ad6ddda3c5cb70 "Add HAVE_(UNIX_)DLAPI config header
define".  DISABLE_DYNLOADING was defined there ever since
ddc7bb629ade15b3341f2e3c347652c7b8925037 "Poor hack for libjpipe.so under Clang
-fsanitize=*" but doesn't appear to be necessary.  (Alternatively,
loplugin:salcall could be taught not to warn if the function definition involves
any #if'ery.)

Change-Id: I5786979eb944d59f969c9875d77b03f9b2432161
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/128797
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>