Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/96284/ : FAILURE

error: unused variable "aWW8ListStyleCounts" [loplugin:unusedvariablecheck] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/filter/ww8/ww8par.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/97026/ )

clang plugin unusedvariablecheck did trigger. unused variable "aWW8ListStyleCounts" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/97026/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000804 \u003c1000804@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}