Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/12985/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "void *(__cdecl *)(size_t)" to "rtl_allocateStringFn" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sal/rtl/strimp.cxx(68) ( https://ci.libreoffice.org/job/gerrit_windows/14298/ )

Patch-set: 2
Label: Verified=-1