Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/51959/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "SwFormatField *" to "SwFormatField" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sw/source/core/fields/docufld.cxx(2178) ( https://ci.libreoffice.org/job/gerrit_windows/59836/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1