Revert "Compute (un-)premultiply_table at compile time"
This reverts commit 644188bf7f3a07222f2b58a3794348197fb8ad24.  It has been found
to cause compilation failure ("vcl/source/bitmap/BitmapTools.cxx(1078): error
C2131: expression did not evaluate to a constant") with Visual Studio 2017
version 15.9, as discussed in the mail thread starting at
<https://lists.freedesktop.org/archives/libreoffice/2018-December/081500.html>
"Windows build failure - C2131: expression did not evaluate to a constant" (and
Mike thankfully filed a bug upstream,
<https://developercommunity.visualstudio.com/content/problem/398218/
c2131-error-with-stdarray-and-stdmake-integer-sequ.html>).  Also, Jenkins node
tb39 which runs the "Gerrit Windows" sub-job of Jenkins' "Gerrit for master"
job apparently has such a Visual Studio 2017 version 15.9 installed, so keeps
failing that job.

Change-Id: I87d25863f2e07474fbb2df3c8f72cd2bcc89582e