Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/33132/ : FAILURE

error ""INCLUDED_CUI_INC_QRleCODEGENDIALOGBASE_HXX" is used as a header guard here, followed by #define of a different macro [-Werror,-Wheader-guard]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/cui/source/inc/QrCodeGenDialogBase.hxx:9:9 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/35641/ )

"file" vs <file> clang plugin ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/35641/ )

clang plugin includeform did trigger. replace <...> include form with "..." for inclusion of a source file next to the current source file, /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/cui/source/inc/cuitabarea.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/35641/ )

error: "INCLUDED_CUI_INC_QRleCODEGENDIALOGBASE_HXX" is used as a header guard here, followed by #define of a different macro [-Werror,-Wheader-guard] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/cui/source/inc/QrCodeGenDialogBase.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/35641/ )

Patch-set: 6
Label: Verified=-1