Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/88145/ : FAILURE

Visual studio complained about error C3246: "dxcanvas::LinePolyPolygon": cannot inherit from "basegfx::unotools::UnoPolyPolygon" as it has been declared as "final" in file C:\cygwin\home\tdf\lode\jenkins\workspace\gerrit_windows\canvas\source\directx\dx_linepolypolygon.hxx(32) ( https://ci.libreoffice.org/job/gerrit_windows/98746/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1