external/zxing: Avoid MSVC 2022 error C2326
> workdir/UnpackedTarball/zxing/core/src/qrcode/QRDetector.cpp(431): error C2326: 'auto ZXing::QRCode::SampleMQR::<lambda_1>::operator ()(int,bool) const': function cannot access 'FORMAT_INFO_COORDS'

seen at least with VS 2022 17.4.2 and VS 2022 17.5.0 Preview 1.0, but not with
VS 2019 16.11.21.  It looks to me like a bug in MSVC, but then again it doesn't
hurt to make that variable static, anyway.

Change-Id: I48fa22f9495791e60953f9f717ffc8333314de1c
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/143826
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit 3f564769446032825b20ca6414caa1c196076ddc)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/143854
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>