Update patch set 2
Patch Set 2: Code-Review-1

(1 comment)

to fix this error you need to adapt the declaration in the hxx file and the definition in the cxx file to be consistent:

Visual studio complained about error C2556: "size_t SwCompatibilityOptPage::GetDocumentOptions(void) const": overloaded function differs only by return type from "sal_uLong SwCompatibilityOptPage::GetDocumentOptions(void) const" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sw/source/ui/config/optcomp.cxx(306)

Patch-set: 2
Reviewer: Gerrit User 1000022 <1000022@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Code-Review=-1