Update patch set 3
Patch Set 3:

> > * the CompilerTest in solenv doesn't work at all
 > 
 > Icecream doesn't force local build of -fsyntax-only builds.
 > https://github.com/icecc/icecream/commit/a20258cd60597a5a12aa2c573efbc7fc13e6277a

ah! that should make the test run, at the cost of making the test useless in predicting whether it works in the actual build.

 > > * the already mentioned problem that this doesn't work:
 > > compiler.getSourceManager().getFileEntryForID(
 > > compiler.getSourceManager().getMainFileID())
 > 
 > I don't understand, what is the problem?

i forgot to paste the "->getName()" at the end...

the whitelisting based on the return value of that call doesn't work, e.g.:

opencl/source/openclwrapper.cxx:524:11: error: expression always evaluates to zero, lhs=0 rhs=unknown [loplugin:expressionalwayszero]

presumably the return value is <stdin> though i havent checked it.

Patch-set: 3