Update patch set 16
Patch Set 16: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/39169/ : FAILURE

error: no need to explicitly init an instance of "std::unique_ptr<RangeChooserTabPage>" with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/source/controller/dialogs/dlg_DataSource.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/42206/ )

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "std::unique_ptr<RangeChooserTabPage>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/42206/ )

Patch-set: 16
Label: Verified=-1