Fix UBSan SwBodyFrame RTTI usage
...since 27c46ecf34b32bae1806d3fc0e1684179301feb8 "sw comments on frames:
improve doc coordinates -> doc model pos conversion":

> DynamicLibraryManagerException: "Failed to load dynamic library: /home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/LinkTarget/CppunitTest/libtest_sw_layoutwriter.so
> /home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/LinkTarget/CppunitTest/libtest_sw_layoutwriter.so: undefined symbol: _ZTI11SwBodyFrame"
> Path is '/home/tdf/lode/opt/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/bin'
> warn:unotools.config:18752:18752:unotools/source/config/configmgr.cxx:140: ConfigManager not empty
>
> Error: a unit test failed, please do one of:
>
> make CppunitTest_sw_layoutwriter CPPUNITTRACE="gdb --args"
>     # for interactive debugging on Linux
> make CppunitTest_sw_layoutwriter VALGRIND=memcheck
>     # for memory checking
> make CppunitTest_sw_layoutwriter DEBUGCPPUNIT=TRUE
>     # for exception catching

(<https://ci.libreoffice.org//job/lo_ubsan/1348/>)

Change-Id: Icdbbe98f55918dc70a57c01a67da73792e3726a8