Fix -Werror,-Wshadow
clang failed with:
/usr/include/qt6/QtDBus/qdbuserror.h:26:9: error: declaration shadows a variable in the global namespace [-Werror,-Wshadow]
   26 |         Other = 1,
      |         ^
net/Socket.hpp:1265:38: note: previous declaration is here
 1265 | enum HostType : uint8_t { LocalHost, Other };
      |                                      ^

HostType is an unscoped enum at namespace scope, so LocalHost and Other
are names in the global namespace, and the Qt headers have enumerators
with the same names: QHostAddress::LocalHost, QDBusError::Other and the
Other of the Reason enum in qevent.h. Only the qt/ code includes both
net/Socket.hpp and those headers.

Fix the problem by turning HostType into a scoped enum, so its
enumerators stay inside it and no longer clash with anything.

Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: I0b70d35bfe70f05050b3437332542b2065ef07c5
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/12671
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>