Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/112188/ : FAILURE

clang plugin unnecessaryoverride did trigger. public virtual function just calls public parent ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/111629/ )

error: public virtual function just calls public parent [loplugin:unnecessaryoverride] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/unx/generic/gdi/salgdi.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/111629/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/111629/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000154 \u003c1000154@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}