Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/56167/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "xmlDocUniquePtr" to "xmlDocPtr" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sw/qa/extras/ooxmlexport/ooxmlexport14.cxx(944) ( https://ci.libreoffice.org/job/gerrit_windows/64294/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1