external/skia: Fix a std::sort comparison function's assertion assumptions
At least with a LLVM 19 libc++ in hardening debug mode (where it uses additional
invocations of the comparison function passed to std::sort, to verify that the
function actually implements a strict weak ordering), chart2_dialogs_test failed
with

> LO_TEST_LOCALE=en-US
> [_RUN_____] Chart2DialogsTest::openAnyDialog
> workdir/UnpackedTarball/skia/src/sksl/transform/SkSLFindAndDeclareBuiltinVariables.cpp:112: fatal error: "assert(InterfaceBlockName(*a) != InterfaceBlockName(*b))"

apparently because the implementation of std::sort made additional
same-arguments calls of operator ()(x, x) that the Skia implementation of the
comparison function was not expecting to happen.  But the only relevant
guarantee that C++20 appears to make for std::sort is that its complexity is
O(N log N) comparisons, so any implementation could legitimately do such a
"useless" additional same-arguments call of operator ()(x, x) for each of the N
elements of the to-be-sorted range.

Change-Id: I3a14eb05b5ae9101f37f92e10ecc91a90585de87
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/164577
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>