Update patch set 12
Patch Set 12: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/55853/ : FAILURE

error: use "true" instead of "sal_True" [loplugin:fakebool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/connectivity/source/drivers/mysqlc/mysqlc_statement.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/58983/ )

clang plugin fakebool did trigger. use "true" instead of "sal_True" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/58983/ )

Patch-set: 12
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1