NotebookBarAddonsItem appears to be required to be a complete type here
...contrary to what 96cb87ca0194be82f8831c701a09b1c1ca623845 "tdf#146619 Use
more forward declarations in include/vcl/[a-o]" apparently assumed, as seen at
least with recent Clang 23 trunk against recent libstdc++ 16 trunk,

> In file included from vcl/source/window/builder.cxx:14:
> In file included from ~/gcc/inst/lib/gcc/x86_64-pc-linux-gnu/16.0.1/../../../../include/c++/16.0.1/memory:80:
> ~/gcc/inst/lib/gcc/x86_64-pc-linux-gnu/16.0.1/../../../../include/c++/16.0.1/bits/unique_ptr.h:90:16: error: invalid application of 'sizeof' to an incomplete type 'NotebookBarAddonsItem'
>    90 |         static_assert(sizeof(_Tp)>0,
>       |                       ^~~~~~~~~~~
> ~/gcc/inst/lib/gcc/x86_64-pc-linux-gnu/16.0.1/../../../../include/c++/16.0.1/bits/unique_ptr.h:398:4: note: in instantiation of member function 'std::default_delete<NotebookBarAddonsItem>::operator()' requested here
>   398 |           get_deleter()(std::move(__ptr));
>       |           ^
> include/vcl/builder.hxx:59:80: note: in instantiation of member function 'std::unique_ptr<NotebookBarAddonsItem>::~unique_ptr' requested here
>    59 |                std::unique_ptr<NotebookBarAddonsItem> pNotebookBarAddonsItem = nullptr);
>       |                                                                                ^
> include/vcl/builder.hxx:44:8: note: forward declaration of 'NotebookBarAddonsItem'
>    44 | struct NotebookBarAddonsItem;
>       |        ^

Change-Id: I81537c4c7f774bb1f9e7e3bdbf85af9786c9e016
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/198131
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>