Fix MSVC2019 build after 629dfff3c7289f185268c7088e67931f6bbd9ce0
... failing like this:

  [CXX] desktop/source/app/sofficemain.cxx
  C:\PROGRA~2\WI3CF2~1\10\Include\10.0.18362.0\um\winnt.h(656): error C4005: 'DECLARE_HANDLE': macro redefinition
  C:\lo\src\core\include\sal/main.h(91): note: see previous definition of 'DECLARE_HANDLE'
  C:\PROGRA~2\WI3CF2~1\10\Include\10.0.18362.0\shared\minwindef.h(250): error C2371: 'HINSTANCE': redefinition; different basic types
  C:\lo\src\core\include\sal/main.h(93): note: see declaration of 'HINSTANCE'
  make[1]: *** [C:/lo/src/core/solenv/gbuild/LinkTarget.mk:293: C:/lo/src/core/workdir/CxxObject/desktop/source/app/sofficemain.o] Error 2

Apparently MSVC2017 isn't affected, since the problematic commit passed
CI happliy (didn't test myself if MSVC version is actually the problem,
or maybe specific Windows SDK version).

Change-Id: Ibcaa3a8d09bae54e436366623fe103e8c5f58f40