Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/94567/ : FAILURE

error "type "const std::hash<SwTextGlyphsKey>" does not provide a call operator" triggered in included file /home/tdf/lode/opt_private/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/hashtable_policy.h:87:11 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/95417/ )

error: no viable conversion from "_Safe_iterator<std::__debug::unordered_map<SwTextGlyphsKey, SwTextGlyphsData, SwTextGlyphsKeyHash, std::equal_to<SwTextGlyphsKey>, std::allocator<std::pair<const SwTextGlyphsKey, SwTextGlyphsData> > >::_Base_iterator, unordered_map<[2 * ...], SwTextGlyphsKeyHash, [2 * ...]>>" to "_Safe_iterator<std::__debug::unordered_map<SwTextGlyphsKey, SwTextGlyphsData, std::hash<SwTextGlyphsKey>, std::equal_to<SwTextGlyphsKey>, std::allocator<std::pair<const SwTextGlyphsKey, SwTextGlyphsData> > >::_Base_iterator, unordered_map<[2 * ...], std::hash<SwTextGlyphsKey>, [2 * ...]>>" in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/core/txtnode/fntcache.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/95417/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1