tdf#78174: toolkit: work around GCC 4.9 -Os link failure
A build with gcc (GCC) 4.9.2 20141101 (Red Hat 4.9.2-1) for 32-bit x86
fails because of these undefined symbols:

> nm --demangle workdir/CxxObject/svx/source/fmcomp/fmgridif.o | grep
 \\bWindowListenerMultiplexer::acquire
         U non-virtual thunk to WindowListenerMultiplexer::acquire()

They should probably be generated inline.  Work around by out-lining the
definition of the methods.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64812

(cherry picked from commit 6b3aa0fe4094e87290bd33a30bd6cd99ee78ce38)

toolkit: export some ListenerMultiplexer types

These are used from svx and apparently some (buggy?) toolchains fail with
fmgridif.cxx:: undefined reference to `non-virtual thunk
 to WindowListenerMultiplexer::acquire()'

(cherry picked from commit bb182b47ca7362b05c03d583d3547643d9a99562)

Change-Id: I318f7c39bdf1243be385bc6dc0a47862b22e92c5
Reviewed-on: https://gerrit.libreoffice.org/14510
Reviewed-by: Caolán McNamara <caolanm@redhat.com>
Tested-by: Caolán McNamara <caolanm@redhat.com>
(cherry picked from commit 5e6cd9b7a15e7e6a994e8f3e4fafed2928dbf42d)