Silence new GCC 14 trunk -Werror=alloc-size
> sal/rtl/byteseq.cxx: In function ‘void rtl_byte_sequence_reference2One(sal_Sequence**)’:
> sal/rtl/byteseq.cxx:63:20: error: allocation of insufficient size ‘8’ for type ‘sal_Sequence’ {aka ‘_sal_Sequence’} with size ‘12’ [-Werror=alloc-size]
>    63 |             pNew = static_cast<sal_Sequence *>(malloc( SAL_SEQUENCE_HEADER_SIZE ));
>       |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(cherry-picked from 5e3af4aec40531b490950da5ed49342a01c1477b)

Change-Id: I9d4081ed2938fffdf282c852250a3eed5f0d9e25
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/161269
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
(cherry picked from commit 86211693569151d0f9d824425927b35d76bd1737)