Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_64/1300/ : FAILURE

Visual studio complained about error C2664: "void std::unique_ptr<SwFormatVertOrient,std::default_delete<_Ty>>::reset(SwFormatVertOrient *) noexcept": cannot convert argument 1 from "SfxPoolItem *" to "SwFormatVertOrient *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sw/source/core/unocore/unosett.cxx(1874) ( https://ci.libreoffice.org/job/gerrit_windows/64197/ )

likely caused by leftovers that linger around from an aborted build ( https://ci.libreoffice.org/job/gerrit_windows/64197/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1