Workaround internal compiler error on tb77
As reported in https://ci.libreoffice.org/job/gerrit_windows/98360/console :

  C:/cygwin/home/tdf/jenkins/workspace/gerrit_windows/svx/source/svdraw/svdedxv.cxx(2639): fatal error C1001: Internal compiler error.
  (compiler file 'msc1.cpp', line 1591)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  If possible please provide a repro here: https://developercommunity.visualstudio.com
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information
  C:/cygwin/home/tdf/jenkins/workspace/gerrit_windows/svx/source/svdraw/svdedxv.cxx(2631): note: while evaluating constexpr function 'svl::ItemsArray'
  INTERNAL COMPILER ERROR in 'C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x86\cl.exe'
      Please choose the Technical Support command on the Visual C++
      Help menu, or open the Technical Support help file for more information

tb77 uses VS 16.7.7 (cl.exe is under Tools/MSVC/14.27.29110); tb68 with
cl.exe under Tools/MSVC/14.28.29910 has no problems compiling this.

Let's make the code simple for now, until we upgrade the tooling on CI.

Change-Id: I10aaf289454c89b2f49b4be947627a9a3be30fde
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/117137
Tested-by: Mike Kaganski <mike.kaganski@collabora.com>
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>
(cherry picked from commit 90cb57eb53e28ecb983001bf8f018577abb6d145)