Update patch set 1
Patch Set 1:

Thanks! :)
It get's further now, but still fails (s. below).

BTW, is there any way to somehow blacklist such things so the next loplugin run doesn't break it again?

/home/michael.weghorn/development/git/libreoffice-WORKTREE_android-x86/vcl/android/androidinst.cxx:112:32: error: base 'SvpSalFrame' is marked 'final'
class AndroidSalFrame : public SvpSalFrame
                               ^
/home/michael.weghorn/development/git/libreoffice-WORKTREE_android-x86/vcl/inc/headless/svpframe.hxx:38:7: note: 'SvpSalFrame' declared here
class SvpSalFrame final : public SalFrame
      ^           ~~~~~
/home/michael.weghorn/development/git/libreoffice-WORKTREE_android-x86/vcl/android/androidinst.cxx:112:7: warning: 'AndroidSalFrame' has virtual functions but non-virtual destructor [-Wnon-virtual-dtor]
class AndroidSalFrame : public SvpSalFrame
      ^
/home/michael.weghorn/development/git/libreoffice-WORKTREE_android-x86/vcl/android/androidinst.cxx:118:11: error: type 'SvpSalFrame' is not a direct or virtual base of 'AndroidSalFrame'
        : SvpSalFrame(pInstance, pParent, nSalFrameStyle)
          ^~~~~~~~~~~
/home/michael.weghorn/development/git/libreoffice-WORKTREE_android-x86/vcl/android/androidinst.cxx:121:13: error: use of undeclared identifier 'SetPosSize'
            SetPosSize(0, 0, viewWidth, viewHeight, SAL_FRAME_POSSIZE_WIDTH | SAL_FRAME_POSSIZE_HEIGHT);
            ^
/home/michael.weghorn/development/git/libreoffice-WORKTREE_android-x86/vcl/android/androidinst.cxx:163:12: error: cannot initialize return object of type 'SalFrame *' with an rvalue of type 'AndroidSalFrame *'
    return new AndroidSalFrame( this, NULL, nStyle );
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/michael.weghorn/development/git/libreoffice-WORKTREE_android-x86/vcl/android/androidinst.cxx:168:12: error: cannot initialize return object of type 'SalFrame *' with an rvalue of type 'AndroidSalFrame *'
    return new AndroidSalFrame( this, pParent, nStyle );
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 5 errors generated.
[CXX] sc/source/filter/xml/importcontext.cxx

Patch-set: 1
CC: Gerrit User 1000789 <1000789@6622c302-437a-49ad-a91d-55ba7dcf1615>