Update patch set 16
Patch Set 16: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/83680/ : FAILURE

likely caused by leftovers that linger around from an aborted build ( https://ci.libreoffice.org/job/gerrit_windows/94219/ )

Visual studio complained about error C2668: "rtl::OUStringBuffer::append": ambiguous call to overloaded function in file C:/cygwin/home/tdf/jenkins/workspace/gerrit_windows/sc/source/core/tool/compiler.cxx(1619) ( https://ci.libreoffice.org/job/gerrit_windows/94219/ )

Patch-set: 16
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1