Update patch set 2
Patch Set 2:

> Patch Set 1:
> 
> > Visual studio complained about error C2065: "nNewLen": undeclared identifier in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sal/osl/w32/file_dirvol.cxx(1684) ( https://ci.libreoffice.org/job/gerrit_windows/56153/ )
> 
> And actually I don't understand what happened here... need to look into the related parent change maybe.


Hello sir, I'm using a ubuntu machine, that is the reason these issues are going undetected. I'll make sure this doesn't happen next time. Sorry for the trouble.

Patch-set: 2
Reviewer: Gerrit User 1002325 <1002325@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0