Update patch set 1
Patch Set 1: Verified-1

(1 comment)

Fails to build here:

 /git/libreoffice/libreoffice-4-2/sd/qa/unit/import-tests.cxx: In member function ‘void SdFiltersTest::testFdo71961()’:
 git/libreoffice/libreoffice-4-2/sd/qa/unit/import-tests.cxx:349:5: error: ‘SdrObjCustomShape’ was not declared in this scope

some missing include? See also inline comment for avoiding an explicit dynamic_cast.

Patch-set: 1
Label: Verified=-1