Fix --with-java builds
...after 524932a2c99e1a2594e2da190fd570a6c765c7d8 "gbuild: use response-file
names derived from the target and not mktemp" started to cause

> [JCS] Jar/libreoffice
> engine/ridljar/source/libreoffice/module-info.java:9: error: modules are not supported in -source 8
> module org.libreoffice.uno
> ^
>   (use -source 9 or higher to enable modules)
> 1 error
> make[1]: *** [engine/solenv/gbuild/JavaClassSet.mk:68: engine/workdir/JavaClassSet/Jar/libreoffice/done] Error 1

as the gb_JavaClassSet__command recipe contains multiple independent
RESPONSEFILEs

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I4a3853d35649225d2ff17ba86c165288e861b44b
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/6176
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>