Update patch set 3
Patch Set 3:

> seems that redundantcast is wrong here...

...at

> /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/window/abstdlg.cxx:43:16: error: redundant functional cast from 'FuncPtrCreateDialogFactory' (aka 'VclAbstractDialogFactory *(*)()') to 'FuncPtrCreateDialogFactory' [loplugin:redundantcast]
>         return FuncPtrCreateDialogFactory(nullptr);
>                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Why do you think that it is wrong?  There is clearly no need for an explicit cast there.  (And the reason that the loplugin warns here is of a technical nature:  Clang models this as an implicit cast from std::nullptr_t to FuncPtrCreateDialogFactory, followed by an explicit functional cast from FuncPtrCreateDialogFactory to FuncPtrCreateDialogFactory, and loplugin:redundantcast warns about that outer cast.)

Patch-set: 3