Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/104102/ : FAILURE

clang plugin unusedvariablecheck did trigger. unused variable "xShape" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/104254/ )

error: unused variable "xShape" [loplugin:unusedvariablecheck] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/extras/globalfilter/globalfilter.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/104254/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1003492 \u003c1003492@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}