Update patch set 2
Patch Set 2:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/99133/ : FAILURE

error: externally available typedef"ed entity "WMFRecords" is not previously declared in an included file (if it is only used in this translation unit, put it in an unnamed namespace; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/emfio/source/reader/wmfreader.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/99663/ )

clang plugin external did trigger. externally available typedef"ed entity "WMFRecords" is not previously declared in an included file (if it is only used in this translation unit, put it in an unnamed namespace; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/99663/ )

Patch-set: 2