Extend '-Werror=attributes' workaround for all GCC versions
Drop the GCC version check from the workaround introduced
in

    commit 2c6cea672a852b85cfb6d2e313d806f257481417
    Author: Stephan Bergmann <sbergman@redhat.com>
    Date:   Wed May 18 10:46:55 2022 +0200

        Work around bogus -Werror=attributes with old GCC

        ...after 9c3c6a6b661ea8f84c1285b07a502de5c98a1495 "Replace OFFSET_OF macro with
        a function template", as seen at
        <https://ci.libreoffice.org//job/lo_tb_master_linux_dbg/38076/>,

        > /home/tdf/lode/jenkins/workspace/lo_tb_master_linux_dbg/cppu/source/uno/check.cxx:263:28: error: ‘maybe_unused’ attribute ignored [-Werror=attributes]
        >      [[maybe_unused]] Char3 chars;
        >                             ^~~~~

        (Not sure which versions of GCC are affected exactly; lets restrict this to
        GCC 7 for now.)

        Change-Id: I28ec8914b60c98dce769ad40ef4141aec4960aa3
        Reviewed-on: https://gerrit.libreoffice.org/c/core/+/134509
        Tested-by: Jenkins
        Reviewed-by: Stephan Bergmann <sbergman@redhat.com>

At least my GCC 11.3.0 build on Debian testing fails just the
same way otherwise.

Change-Id: I815e4a24da13e0ae66b1dff2941e636c7ebdfd9c