solenv concat-deps: Use bool instead of int variable
`internal_boost` is semantically a boolean. Use a
bool variable accordingly.

Addresses this loplugin:implicitboolconversion
error otherwise seen with an upcoming commit converting
concat-deps.c from a C to a C++ program:

    /home/user/development/git/libreoffice/solenv/bin/concat-deps.cxx:1128:22: error: implicit conversion (IntegralCast) from 'bool' to 'int' [loplugin:implicitboolconversion]
     1128 |     internal_boost = !env_str || strcmp(env_str,"TRUE");
          |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I037c89250fc87071b1d7ce29b348cd175293f554
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/209868
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins