Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/20139/ : FAILURE

error: unused parameter name [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/core/doc/DocumentTimerManager.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/20902/ )

clang plugin casttovoid did trigger. unused parameter name ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/20902/ )

Patch-set: 3
Label: Verified=-1