Update patch set 13
Patch Set 13: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/98453/ : FAILURE

error: externally available entity "createPolyPolygon" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/qa/cppunit/outdev.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/99038/ )

clang plugin external did trigger. externally available entity "createPolyPolygon" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/99038/ )

Patch-set: 13
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000295 \u003c1000295@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}