external/epoxy: Fix -Wint-conversion
...with recent Clang 16 trunk since
<https://github.com/llvm/llvm-project/commit/7068aa98412ade19a34b7ed126f4669f581b2311>
"Strengthen -Wint-conversion to default to an error", causing

> workdir/UnpackedTarball/epoxy/src/gl_generated_dispatch.c:114547:77: error: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned long') to parameter of type 'GLhandleARB' (aka 'void *') [-Wint-conversion]
> GEN_THUNKS(glAttachObjectARB, (GLhandleARB containerObj, GLhandleARB obj), ((uintptr_t)containerObj, (uintptr_t)obj))
>                                                                             ^~~~~~~~~~~~~~~~~~~~~~~
> workdir/UnpackedTarball/epoxy/src/dispatch_common.h:150:40: note: expanded from macro 'GEN_THUNKS'
>     GEN_GLOBAL_REWRITE_PTR(name, args, passthrough)                  \
>                                        ^~~~~~~~~~~
> workdir/UnpackedTarball/epoxy/src/dispatch_common.h:95:14: note: expanded from macro 'GEN_GLOBAL_REWRITE_PTR'
>         name passthrough;                                        \
>              ^~~~~~~~~~~

etc.  (Curiously, this only hit on macOS, not on Linux even with
--without-system-epoxy.)

Change-Id: I2c87bca2cc5510d17098028d4532989f48e349a9