Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/55130/ : FAILURE

error ""GetNumLines" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/ui/inc/inputwin.hxx:202:29 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/58288/ )

error: conditional expression of the form "A ? B : false" (with A of type "const SfxViewShell *" and B of type "bool") can logically be simplified as "A && B" [loplugin:simplifybool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/source/controller/main/ChartController_Window.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/58288/ )

clang plugin simplifybool did trigger. conditional expression of the form "A ? B : false" (with A of type "const SfxViewShell *" and B of type "bool") can logically be simplified as "A && B" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/58288/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1