Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/85538/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "initializer list" to "std::map<rtl::OUString,sal_Int32,std::less<rtl::OUString>,std::allocator<std::pair<const rtl::OUString,sal_Int32>>>" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/connectivity/source/drivers/ado/ADatabaseMetaDataResultSet.cxx(1118) ( https://ci.libreoffice.org/job/gerrit_windows/96092/ )

Patch-set: 5
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1