tdf137314 Add margin to CppunitTest assertions
The test had multiple failures on Windows with:

oox/qa/unit/vml.cxx(79) : error : Assertion
Test name: tdf137314_vml_rotation_unit_fd::TestBody
equality assertion failed
- Expected: 1490
- Actual  : 1491

So add a 1px margin to all value checks.

Change-Id: I70298db253299a57cc37eed482c0816d902fbeab
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/116192
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
(cherry picked from commit 60b98189281524c85b559ee3b6adc1381b793b9d)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/116154