Drop duplicated SbiRuntime::isVBAEnabled definition
9ad446b4020e1829a64ed228df5574f41d510be5 "more effort for --disable-scripting
and windows --enable-mergelibs=more" had added this definition in the #else
branch (without giving a rationale), but there's no configuration where this
could actually work, as it conflicts with the pre-existing, unconditional
SbiRuntime::isVBAEnabled definition that directly follows it.  (And at least
Emscripten builds started to fail with

> basic/source/runtime/runtime.cxx:376:18: error: redefinition of 'isVBAEnabled'
>   376 | bool SbiRuntime::isVBAEnabled()
>       |                  ^
> basic/source/runtime/runtime.cxx:369:18: note: previous definition is here
>   369 | bool SbiRuntime::isVBAEnabled()
>       |                  ^

now.)

Change-Id: I9d7730abe95eaf6a72f52a272b95c8a1e06f36e3
Reviewed-on: https://gerrit.collaboraoffice.com/c/core/+/953
Tested-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>