external/coinmp: Avoid -Werror,-Wc++2b-extensions
> ClpSimplex.cpp:6038:2: error: use of a '#elifdef' directive is a C++2b extension [-Werror,-Wc++2b-extensions]
> #elifdef COIN_HAS_MUMPS
>  ^

seen with Clang 15 trunk since
<https://github.com/llvm/llvm-project/commit/a1545f51a9ef299ca6c6716bd80b862f360453ab>
"Warn if using `elifdef` & `elifndef` in not C2x & C++2b mode" (and which is
turned into an error because External_coinmp builds with --pedantic-errors)

Change-Id: I1db213aec91bc17c720fd58270eab452b2e4e0f5
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/134478
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>