oox: fix -Werror=dangling-reference
engine/oox/source/drawingml/lineproperties.cxx: In member function ‘void oox::drawingml::LineProperties::pushToPropMap(oox::drawingml::ShapePropertyMap&, const oox::GraphicHelper&, Color, sal_Int16, const model::ComplexColor*) const’:
engine/oox/source/drawingml/lineproperties.cxx:518:100: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  518 |                      aLineColor.createComplexColor(rGraphicHelper, nPhClrTheme).getTransformations())
      |                                                                                                    ^
engine/oox/source/drawingml/lineproperties.cxx:518:51: note: ‘model::ComplexColor’ temporary created here
  518 |                      aLineColor.createComplexColor(rGraphicHelper, nPhClrTheme).getTransformations())
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Probably a fallout from commit 8d092bfb81ada176e2538d437d722dab7a070431
(oox: keep the shade the style reference of a shape puts on its line,
2026-09-29), seen with gcc-15

Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: I143523c2263d22facc32eb9bbe9a875bcfa210dc
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/13996
Reviewed-by: Samuel Mehrbrodt <samuel.mehrbrodt@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>