Always set java bytecode / source target to 1.6 / 6
which is our minimum requirement anyway.

Got these errors:
error: Source option 5 is no longer supported. Use 6 or later.
error: Target option 1.5 is no longer supported. Use 1.6 or later.

Change-Id: I8a22fab6a1f9a713cb55b4c5d8173c3bbcd28587