external/skia: Missing include
...at least when building with Visual Studio 2022 Preview 17.4.0,

> In file included from workdir/UnpackedTarball/skia/src/core/SkKeyHelpers.cpp:14:
> workdir/UnpackedTarball/skia\src/core/SkShaderCodeDictionary.h(45,43): error: no type named 'string' in namespace 'std'
>     using GenerateGlueCodeForEntry = std::string (*)(const std::string& resultName,
>                                      ~~~~~^

etc.

Reviewed-on: https://gerrit.libreoffice.org/c/core/+/141833
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit 3e009159cd1801507f6e965444a7dade5497f89a)
Conflicts:
	external/skia/UnpackedTarball_skia.mk

Change-Id: Idd8dafb4e57e04088ee60954ecfa601cc7588e55
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/146382
Tested-by: Jenkins
Reviewed-by: Caolán McNamara <caolanm@redhat.com>