Revert "Add more more dependencies to VCL makefiles"
This reverts commit ab03a09745fe52209747fb901eca91ef14cda5a5.  It is
unfortunately not clear what issues exactly that commit was supposed to fix.
And buovjaga now reported on IRC that his built (implicitly
--without-system-harfbuzz --without-system-icu) failed to link e.g.
Library_vclplug_gtk3 due to harfbuzz missing symbols from ICU, like

> /usr/bin/ld: /home/user/libreoffice/workdir/UnpackedTarball/harfbuzz/src/.libs/libharfbuzz.a(libharfbuzz_la-hb-icu.o): in function `hb_icu_unicode_decompose_compatibility(hb_unicode_funcs_t*, unsigned int, unsigned int*, void*)':
> /home/user/libreoffice/workdir/UnpackedTarball/harfbuzz/src/hb-icu.cc:334: undefined reference to `unorm2_getNFKDInstance_62'
[...]

that went away by removing the dependency on harfbuzz from
vcl/Library_vclplug_gtk3.mk.  However, it is not clear to me why buovjaga's
setup would cause (parts of)
workdir/UnpackedTarball/harfbuzz/src/.libs/libharfbuzz.a to actually be linked
into Library_vclplug_gtk3 (and then cause undefined references to ICU symbols),
when those harfbuzz parts are not actually needed by Library_vclplug_gtk3 in the
first place (as demonstrated by removing the dependency from
vcl/Library_vclplug_gtk3.mk).

So lets revert the commit for now and see what (if anything) breaks.

Change-Id: I265fb8c610c1912fbe688e51b5da4928a4652720