Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/60022/ : FAILURE

error "VarDecl, use "bool" instead of "sal_Bool" (aka "unsigned char") [loplugin:fakebool]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/xmlsecurity/source/xmlsec/nss/nssinitializer.hxx:41:12 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/62952/ )

error: VarDecl, use "bool" instead of "sal_Bool" (aka "unsigned char") [loplugin:fakebool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/xmlsecurity/source/xmlsec/nss/nssinitializer.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/62952/ )

clang plugin fakebool did trigger. VarDecl, use "bool" instead of "sal_Bool" (aka "unsigned char") ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/62952/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1