Fix non-pch Windows build
... after commit c880d2bec8907db17ef92220a16f09a7c55c0e6a
(Fix some non self contained headers in module sw, 2026-01-25).

The change in sw/inc/ndtxt.hxx created circular dependency:

- sw/source/core/access/parachangetrackinginfo.cxx
  - #include <wrong.hxx> (executes #pragma once, will not be included again)
    - #include <ndtxt.hxx> (at the beginning of wrong.hxx, only on Windows;
      before its classes are read)
      - #include "../source/core/inc/wrong.hxx" (ignored because of #pragma once)
      - #include "../source/core/inc/SwGrammarMarkUp.hxx" (needs access to
        definitions in wrong.hxx, yet unavailable)

Resulting in

C:\lo\core\sw\inc\../source/core/inc/SwGrammarMarkUp.hxx(36): error C2504: 'SwWrongList': base class undefined
C:\lo\core\sw\inc\../source/core/inc/SwGrammarMarkUp.hxx(46): error C3668: 'SwGrammarMarkUp::~SwGrammarMarkUp': method with override specifier 'override' did not override any base class methods
C:\lo\core\sw\inc\../source/core/inc/SwGrammarMarkUp.hxx(47): error C3668: 'SwGrammarMarkUp::Clone': method with override specifier 'override' did not override any base class methods
C:\lo\core\sw\inc\../source/core/inc/SwGrammarMarkUp.hxx(48): error C3668: 'SwGrammarMarkUp::CopyFrom': method with override specifier 'override' did not override any base class methods
C:\lo\core\sw\inc\../source/core/inc/SwGrammarMarkUp.hxx(42): error C2065: 'WRONGLIST_GRAMMAR': undeclared identifier
C:\lo\core\sw\inc\../source/core/inc/SwGrammarMarkUp.hxx(42): error C2614: 'SwGrammarMarkUp': illegal member initialization: 'SwWrongList' is not a base or member
Change-Id: I868902d6d0552832c4db3aefdba8ee76fa19bce1
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/198124
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>
Tested-by: Jenkins