Don't enable the requires clause for Clang 15
similar to 5831d5f03a5ea5b89984574ffe436f38500726da
    Don't enable the requires clause for some Xcode Clang

Step #3 - "compile-honggfuzz-address-x86_64": checking whether Clang is new enough... yes (15.0.0)

In file included from libreoffice/core-clang/animations/source/animcore/animcore.cxx:20:
In file included from libreoffice/core-clang/workdir/UnoApiHeadersTarget/offapi/normal/com/sun/star/util/XCloneable.hpp:8:
libreoffice/core-clang/workdir/UnoApiHeadersTarget/udkapi/normal/com/sun/star/uno/XInterface.hpp:32:65: error: invalid application of 'sizeof' to an incomplete type 'animcore::(anonymous namespace)::AnimationNode'
template<typename T> inline constexpr auto isUnoInterfaceType = sizeof (T) && IsUnoInterfaceType<T>::value;
                                                                ^~~~~~~~~~
libreoffice/core-clang/include/unotools/weakref.hxx:119:33: note: in instantiation of variable template specialization 'cppu::detail::isUnoInterfaceType' requested here
        requires(!cppu::detail::isUnoInterfaceType<interface_type>)
                                ^
libreoffice/core-clang/animations/source/animcore/animcore.cxx:309:44: note: in instantiation of template class 'unotools::WeakReference<animcore::(anonymous namespace)::AnimationNode>' requested here
    unotools::WeakReference<AnimationNode> mxParent;
                                           ^
libreoffice/core-clang/animations/source/animcore/animcore.cxx:121:7: note: definition of 'animcore::(anonymous namespace)::AnimationNode' is not complete until the closing '}'
class AnimationNode final:  public AnimationNodeBase
      ^

Change-Id: I4feb54d5739464d356e2769eeb368c368cc29104
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/157250
Tested-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>