win: Fix --disable-skia Windows build
... which after

    commit 4a4d388e17ae7490ed36f4bb0dd21fbefcdda124
    Date:   Wed May 7 01:58:16 2025 +0200

        simplify CompatibleDC

        This class is only really used by the skia case. The non-skia
        (i.e. GDI) case completely bypasses it.
        So we can remove the hierarchy and just make it into a skia focused
        class, simplifying the code structure in the process

was seen failing like this:

    C:\Users\mwegh\development\git\libreoffice\vcl\inc\skia/utils.hxx(34): fatal error C1083: Cannot open include file: 'SkRegion.h': No such file or directory
    make[1]: *** [C:/Users/mwegh/development/git/libreoffice/solenv/gbuild/LinkTarget.mk:338: C:/Users/mwegh/development/git/libreoffice/workdir/CxxObject/vcl/win/gdi/salnativewidgets-luna.o] Error 2
    make: *** [Makefile:301: build] Error 2

Change-Id: Iaa0f6d3da85467bae07d55b5dba9a4bd68cc784d
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/185473
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Reviewed-by: Regina Henschel <rb.henschel@t-online.de>
Tested-by: Jenkins