remove hsqldb from mergedlibs
regression from
    commit ae17922b7d0f797129dd5fbd5514d691ac9ebeaa
    Author: Noel Grandin <noel.grandin@collabora.co.uk>
    Date:   Wed Feb 14 09:33:05 2024 +0200
    add more libs into --enable-mergelibs=more build

sberg is seeing
    This breaks e.g.  dbaccess_hsqldb_test  with
    java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError:

likely because the jar file is trying to load libhsqldb.so instead of
libmerged.so

Change-Id: I9f42aea6471dbe35b27a584465b333a1d30caf5b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/164022
Tested-by: Jenkins
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>