Update patch set 3
Patch Set 3:

...presumably because the test's code is cut early at

> ======================================================================
> FAIL: test_tdf131291 (chartDataLabels.chartDataLabels)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/sbergman/lo/core/sc/qa/uitest/chart/chartDataLabels.py", line 302, in test_tdf131291
>     self.assertEqual(xDataSeries[0].NumberFormat, xFormat)
> AssertionError: None != 104

Patch-set: 3