Enable JS UNO in the engine for extension support in COOL
(which showed at least
<https://cpci.cbg.collabora.co.uk:8080/job/gerrit_linux_gcc_main/1574/> failing
with

> /opt/rh/devtoolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld[build CXX] registry/tools/regview.cxx: /home/collabora/jenkins/workspace/gerrit_linux_gcc_main/engine/workdir/GenCObject/UnpackedTarball/quickjs/quickjs.o: in function `js_atomics_wait':
> quickjs.c:(.text+0x9a572): undefined reference to `pthread_condattr_setclock'
> /opt/rh/devtoolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: /home/collabora/jenkins/workspace/gerrit_linux_gcc_main/engine/workdir/GenCObject/UnpackedTarball/quickjs/quickjs.o: in function `JS_AddIntrinsicTypedArrays':
> quickjs.c:(.text+0xa173b): undefined reference to `pthread_once'

due to a missing -pthread; and
<https://cpci.cbg.collabora.co.uk:8080/job/gerrit_linux_gcc_main/1720/> failing
with

> /opt/rh/devtoolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: cannot find -lmergedlo
> collect2: error: ld returned 1 exit status
> make[1]: *** [/home/collabora/jenkins/workspace/gerrit_linux_gcc_main/engine/jsuno/Library_jsuno.mk:10: /home/collabora/jenkins/workspace/gerrit_linux_gcc_main/engine/instdir/program/libjsunolo.so] Error 1

due to --enable-mergelibs, so add Library_jsuno into Library_merged)

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I9b892f8b18cc6c25d4c3fb6e31d9c9890087e610
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/2726
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>