Update patch set 2
Patch Set 2: Verified-1

this looks like a real problem:


Traceback (most recent call last):
  File "/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/python/text_portion_enumeration_test.py", line 2826, in test_meta_xtextcursor
    self.assertEqual("Two", string, "gotoEndOfWord(): wrong string")
AssertionError: 'Two' != ''
- Two
+ 
 : gotoEndOfWord(): wrong string


the mac and gcc-release builds do not run the "subsequentcheck" target so they didn't run this test.


i suspect that the ANYWORD thing spuriously causes IsEndWordWT to return true for an empty cursor that's between a CH_TXTATR_WHATEVER and "T"?
for this kind of field there's a magic character at the start of it and at the end ... it's CH_TXTATR_BREAKWORD

Patch-set: 2
Label: Verified=-1