Make engine/jsuno/source/json.cxx compile with Android and Apple baselines
...so a later commit can move it out of --enable-quickjs--only Library_jsuno
into Library_comphelper.  The relevant Gerrit Jenkins failures would have been

> 21:34:01 /home/collabora/jenkins/workspace/gerrit_android_app_main_arm64-v8a/engine/comphelper/source/misc/json.cxx:100:25: error: call to deleted function 'from_chars'
> 21:34:01   100 |     auto const[p, ec] = std::from_chars(utf8.getStr(), utf8.getStr() + utf8.getLength(), value);
> 21:34:01       |                         ^~~~~~~~~~~~~~~
> 21:34:01 /home/collabora/jenkins/workspace/gerrit_android_app_main_arm64-v8a/engine/comphelper/source/misc/json.cxx:687:28: note: in instantiation of function template specialization '(anonymous namespace)::parseJsonNumberAs<float>' requested here
> 21:34:01   687 |             auto const v = parseJsonNumberAs<float>(json);
> 21:34:01       |                            ^
> 21:34:01 /opt/android-sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/__charconv/from_chars_integral.h:38:19: note: candidate function has been explicitly deleted
> 21:34:01    38 | from_chars_result from_chars(const char*, const char*, bool, int = 10) = delete;
> 21:34:01       |                   ^
> 21:34:01 /opt/android-sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/__charconv/from_chars_integral.h:224:1: note: candidate template ignored: requirement 'is_integral<float>::value' was not satisfied [with _Tp = float]
> 21:34:01   224 | from_chars(const char* __first, const char* __last, _Tp& __value) {
> 21:34:01       | ^
> 21:34:01 /opt/android-sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/__charconv/from_chars_integral.h:230:1: note: candidate function template not viable: requires 4 arguments, but 3 were provided
> 21:34:01   230 | from_chars(const char* __first, const char* __last, _Tp& __value, int __base) {
> 21:34:01       | ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 21:34:01 /home/collabora/jenkins/workspace/gerrit_android_app_main_arm64-v8a/engine/comphelper/source/misc/json.cxx:100:25: error: call to deleted function 'from_chars'
> 21:34:01   100 |     auto const[p, ec] = std::from_chars(utf8.getStr(), utf8.getStr() + utf8.getLength(), value);
> 21:34:01       |                         ^~~~~~~~~~~~~~~
> 21:34:01 /home/collabora/jenkins/workspace/gerrit_android_app_main_arm64-v8a/engine/comphelper/source/misc/json.cxx:698:28: note: in instantiation of function template specialization '(anonymous namespace)::parseJsonNumberAs<double>' requested here
> 21:34:01   698 |             auto const v = parseJsonNumberAs<double>(json);
> 21:34:01       |                            ^
> 21:34:01 /opt/android-sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/__charconv/from_chars_integral.h:38:19: note: candidate function has been explicitly deleted
> 21:34:01    38 | from_chars_result from_chars(const char*, const char*, bool, int = 10) = delete;
> 21:34:01       |                   ^
> 21:34:01 /opt/android-sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/__charconv/from_chars_integral.h:224:1: note: candidate template ignored: requirement 'is_integral<double>::value' was not satisfied [with _Tp = double]
> 21:34:01   224 | from_chars(const char* __first, const char* __last, _Tp& __value) {
> 21:34:01       | ^
> 21:34:01 /opt/android-sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/__charconv/from_chars_integral.h:230:1: note: candidate function template not viable: requires 4 arguments, but 3 were provided
> 21:34:01   230 | from_chars(const char* __first, const char* __last, _Tp& __value, int __base) {
> 21:34:01       | ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(<https://cpci.cbg.collabora.co.uk:8080/job/gerrit_android_app_main_arm64-v8a/8103/console>
for Android, where there is no known-good NDK version yet to use in the #if
condition (LLVM 20 libc++ would bring the necessary support, but latest NDK 28
still uses LLVM 19; also cf. <https://github.com/android/ndk/issues/1574> "[BUG]
C++17 STL <charconv> implementation missing floating point functions") so I left
a TODO there to eventually get rid of the #if condition once there is a
sufficiently new NDK we use as our baseline, and

> 21:43:47 /Users/ci/jenkins/workspace/gerrit_macos_app_main/engine/comphelper/source/misc/json.cxx:100:30: error: 'from_chars' is unavailable: introduced in macOS 26.0
> 21:43:47   100 |     auto const[p, ec] = std::from_chars(utf8.getStr(), utf8.getStr() + utf8.getLength(), value);
> 21:43:47       |                              ^
> 21:43:47 /Users/ci/jenkins/workspace/gerrit_macos_app_main/engine/comphelper/source/misc/json.cxx:687:28: note: in instantiation of function template specialization '(anonymous namespace)::parseJsonNumberAs<float>' requested here
> 21:43:47   687 |             auto const v = parseJsonNumberAs<float>(json);
> 21:43:47       |                            ^
> 21:43:47 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.4.sdk/usr/include/c++/v1/__charconv/from_chars_floating_point.h:58:1: note: 'from_chars' has been explicitly marked unavailable here
> 21:43:47    58 | from_chars(const char* __first, const char* __last, float& __value, chars_format __fmt = chars_format::general) {
> 21:43:47       | ^
> 21:43:47 /Users/ci/jenkins/workspace/gerrit_macos_app_main/engine/comphelper/source/misc/json.cxx:100:30: error: 'from_chars' is unavailable: introduced in macOS 26.0
> 21:43:47   100 |     auto const[p, ec] = std::from_chars(utf8.getStr(), utf8.getStr() + utf8.getLength(), value);
> 21:43:47       |                              ^
> 21:43:47 /Users/ci/jenkins/workspace/gerrit_macos_app_main/engine/comphelper/source/misc/json.cxx:698:28: note: in instantiation of function template specialization '(anonymous namespace)::parseJsonNumberAs<double>' requested here
> 21:43:47   698 |             auto const v = parseJsonNumberAs<double>(json);
> 21:43:47       |                            ^
> 21:43:47 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.4.sdk/usr/include/c++/v1/__charconv/from_chars_floating_point.h:63:1: note: 'from_chars' has been explicitly marked unavailable here
> 21:43:47    63 | from_chars(const char* __first, const char* __last, double& __value, chars_format __fmt = chars_format::general) {
> 21:43:47       | ^

(<https://cpci.cbg.collabora.co.uk:8080/job/gerrit_macos_app_main/10644/console>)
for macOS (and similarly for iOS), where we'll eventually get rid of the #if
conditions when we bump the version-min baselines to at least 26.0.

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I14c1a855fc274cfd3104a7cd0e87a9581889222c
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/9607
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>