Update patch set 11
Patch Set 11: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/68601/ : FAILURE

error: VarDecl, use "tools::Long" instead of "long" [loplugin:toolslong] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/unx/generic/gdi/salbmp.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70993/ )

clang plugin toolslong did trigger. VarDecl, use "tools::Long" instead of "long" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70993/ )

Patch-set: 11
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1