Fix some OUString construction error with VS2013
A bit unclear to me whether the code really did what was intended with
earlier VS versions either.

VS2013 said: error C2664: 'rtl::OUString::OUString(const sal_uInt32
*,sal_Int32)' : cannot convert argument 1 from 'const char *' to
'const rtl::OUString &'

Reason: cannot convert from 'const char *' to 'const rtl::OUString'

No constructor could take the source type, or constructor overload
resolution was ambiguous

Change-Id: Ie23d8382515064062a3ed46418d9d4a977b35d28
(cherry picked from commit eee44c951c104da342d55fd4de634efd51ae59ae)