sw: fix warning C6011: Dereferencing NULL pointer 'pShell'
E:/jenkins/workspace/lo_tb_master_win_analyze/sw/source/core/layout/paintfrm.cxx(4506): error C2220: the following warning is treated as an error
E:\jenkins\workspace\lo_tb_master_win_analyze\sw\source\core\layout\paintfrm.cxx(4489) : warning C6011: Dereferencing NULL pointer 'pShell'. : Lines: 4235, 4236, 4250, 4251, 4253, 4254, 4256, 4257, 4258, 4260, 4263, 4265, 4277, 4278, 4279, 4290, 4293, 4294, 4322, 4329, 4333, 4353, 4359, 4360, 4362, 4364, 4365, 4369, 4373, 4381, 4403, 4369, 4408, 4411, 4364, 4359, 4412, 4278, 4413, 4419, 4472, 4474, 4477, 4480, 4481, 4483, 4477, 4484, 4486, 4489

After
commit 58d677055d9f6da976bf4fe34c1d89dd6871050d
Author: Miklos Vajna <vmiklos@collabora.com>
Date:   Mon Jan 19 13:34:32 2026 +0100

    cool#13988 sw redline render mode: handle anchored images

Change-Id: I68cc27e1d2b9ef1fd9851f6079c7b52a488070a3
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/197853
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
(cherry picked from commit d32d9234466c296b8df5542ba10a5d92d75372b6)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/197912