Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> I have Linux master builds failing since last night during RPM packaging, this commit looks suspiciously related. Error message:
> 
> Processing files: libreoffice7.1-freedesktop-menus-7.1.0-0.noarch
> error: File not found by glob: /workdir/workdir/CustomTarget/sysui/rpm/libreoffice/freedesktop/usr/share/icons/hicolor/*/mimetypes/*svg
> 

Looks like one more line in root/sysui/desktop/freedesktop/freedesktop-menus.spec needs to go:

/usr/share/icons/hicolor/*/mimetypes/*svg


What is best? Another Gerrit ticket with a commit deleting that line?

Patch-set: 3