Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/100758/ : FAILURE

error "‘RID_BMP_LOCKED’ defined but not used [-Werror=unused-variable]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/basctl/inc/bitmaps.hlst:16:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/104376/ )

compiler warning unused-variable treated as error: ‘RID_BMP_LOCKED’ defined but not used in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/basctl/inc/bitmaps.hlst:16:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/104376/ )

error: ‘basctl::DLGED_PROP_DECORATION’ defined but not used [-Werror=unused-variable] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/basctl/source/inc/dlgeddef.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/104376/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000083 \u003c1000083@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}