Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/100947/ : FAILURE

error "‘CHART2_COOSYSTEM_POLAR_VIEW_SERVICE_NAME’ defined but not used [-Werror=unused-variable]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/chart2/source/inc/servicenames_coosystems.hxx:22:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/104564/ )

compiler warning unused-variable treated as error: ‘CHART2_COOSYSTEM_POLAR_VIEW_SERVICE_NAME’ defined but not used in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/chart2/source/inc/servicenames_coosystems.hxx:22:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/104564/ )

error: ‘CHART2_COOSYSTEM_POLAR_VIEW_SERVICE_NAME’ defined but not used [-Werror=unused-variable] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/chart2/source/inc/servicenames_coosystems.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/104564/ )

Patch-set: 6
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1