Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/45890/ : FAILURE

error "redundant function redeclaration [loplugin:unreffun]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/drawinglayer/source/tools/emfphelperdata.hxx:43:17 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/49325/ )

error: externally available entity "ImageDataTypeToString" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/drawinglayer/source/tools/emfpenums.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/49325/ )

clang plugin external did trigger. externally available entity "ImageDataTypeToString" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/49325/ )

Patch-set: 6
Label: Verified=-1