out-of-bounds tab access when deleting second last sheet
Which in a debug build lead to STL assert
Error: attempt to subscript container with out-of-bounds index

Change-Id: I09fddbc9e4b214b0313c193f85830ed458d20c0e
(cherry picked from commit 0c55972d747511dbc711f3c9cbb4db5d8c5dc2ff)