Bump curl version check to 7.19.4 in configure.ac
Constants CURLPROTO_HTTP, CURLPROTO_HTTPS, ... have been introduced in curl 7.19.4.
With current requirement (>= 7.13.1), we would get build errors like
  "cmis/src/libcmis/base-session.cxx:841: error: CURLOPT_PROTOCOLS was not declared in this scope"
in cases of using curl < 7.19.4.

Change-Id: Ifa6c56fc71715cceb19d30bb2d6f48f0b1dbd7da