Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/70382/ : FAILURE

error "use "tools::Long" instead of "long" as return type [loplugin:toolslong]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/cui/source/inc/splitcelldlg.hxx:42:13 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72702/ )

clang plugin toolslong did trigger. use "tools::Long" instead of "long" as return type ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72702/ )

error: use "tools::Long" instead of "long" as return type [loplugin:toolslong] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/cui/source/inc/splitcelldlg.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72702/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1