Update patch set 1
Patch Set 1:

Hi Julien. In my test neither of Python 3.3 or Python 2 work with the patch, because of the removed terminating blackslashes:

$ ~/libo/install/program/python pythonscript_new-abcad82d451c27e959c666771bd7d8198fbd6f54.py 
  File "pythonscript_new-abcad82d451c27e959c666771bd7d8198fbd6f54.py", line 178
    self.s_UriMap =
                  ^
SyntaxError: invalid syntax

Also it would be fine to restrict the patch only for the deprecated Python syntax (simplier to review and handle the changes). Thanks, László

Patch-set: 1
Reviewer: Gerrit User 1001002 <1001002@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0
Label: Code-Review=0