Update patch set 2
Patch Set 2:

Ah, I see. I just assumed that Android in general has a single problem. So my local armv7 build fails like this: https://pastebin.com/raw/2MwKCKCR

Does that ring a bell for you? I guess the root problem there is the

 mpi/mpcpucache.c:91:15: error: invalid output constraint '=a' in asm

line.

Patch-set: 2