Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/111776/ : FAILURE

build likely got stuck and was aborted due to not producing any output to the log ( https://ci.libreoffice.org/job/gerrit_windows/123932/ )

Visual studio complained about error C2065: "mnDestTab": undeclared identifier in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/sc/source/core/data/column2.cxx(2102) ( https://ci.libreoffice.org/job/gerrit_windows/123932/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1