Update git submodules
* Update dictionaries from branch 'libreoffice-26-2'
  to 69233aed16953a6b65eddf1c9c351f21b36eb7a2
  - da_DK: fix build
    
    l10ntools/source/xrmmerge.cxx is not prepared to work with
    subdirectories.
    Besides, en-US has to be the first on the list.
    This fix comes with another fix in l10ntools/source/xrmmerge.cxx
    
    --- a/l10ntools/source/xrmmerge.cxx
    +++ b/l10ntools/source/xrmmerge.cxx
    @@ -397,7 +397,8 @@ void XRMResMerge::WorkOnDesc(
                         sSearch = "xlink:href=\""_ostr;
                         sReplace = sSearch;
    
    -                    const OString sLocDescFilename = sDescFilename.replaceFirst( "en-US"_ostr, sCur);
    +                    // for cases like desc_en_US.txt or desc_en-US.txt
    +                    const OString sLocDescFilename = sDescFilename.replaceFirst( "en-US"_ostr, sCur).replaceFirst( "en_US"_ostr, sCur);
    
                         sSearch += sDescFilename;
                         sReplace += sLocDescFilename;
    
    Error: cannot write /home/tdf/lode/jenkins/workspace/lo_gerrit/tb/build_master/workdir/DescriptionTranslateTarget/dictionaries/da_DK/description/desc_da_DK.txt
    make[1]: *** [/home/tdf/lode/jenkins/workspace/lo_gerrit/tb/src_master/solenv/gbuild/Dictionary.mk:147: /home/tdf/lode/jenkins/workspace/lo_gerrit/tb/build_master/workdir/DescriptionTranslateTarget/dictionaries/da_DK/description.xml] Error 134
    make[1]: *** Deleting file '/home/tdf/lode/jenkins/workspace/lo_gerrit/tb/build_master/workdir/DescriptionTranslateTarget/dictionaries/da_DK/description.xml'
    make[1]: *** Waiting for unfinished jobs....
    
    Change-Id: Ibbb5f5d9529cd02143d81fe3fda72924658ae130
    Reviewed-on: https://gerrit.libreoffice.org/c/dictionaries/+/206351
    Tested-by: Xisco Fauli <xiscofauli@libreoffice.org>
    Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
    (cherry picked from commit 8a76169e8be8c04b3abb802db38c170bc97b65bc)
    Reviewed-on: https://gerrit.libreoffice.org/c/dictionaries/+/206370