Update patch set 2
Patch Set 2:

> I tried to add a number to nullptr and had this:
 > test.cpp: In function ‘int main()’:
 > test.cpp:6:44: error: invalid operands of types ‘std::nullptr_t’
 > and ‘int’ to binary ‘operator+’
 > const std::vector<int> rHhea(0, nullptr + 3);
 > ~~~~~~~~^~~

get() will return a char* with a value of NULLPTR (which is normally zero)
since adding zero to get() still gets you zero, we are calling std::vector with two identical pointers, so the vector is of zero length, so it doesn't access any memory, so nothing bad happens

Patch-set: 2
Reviewer: Gerrit User 1000083 <1000083@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0