Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_feature/273/ : FAILURE

error ""getName" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/chart2/source/inc/ChartStyle.hxx:77:31 ( https://ci.libreoffice.org/job/gerrit_mac/40534/ )

error: "getName" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/chart2/source/inc/ChartStyle.hxx ( https://ci.libreoffice.org/job/gerrit_mac/40534/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1