Update patch set 2
Patch Set 2:

> /usr/include/c++/4.8/debug/safe_iterator.h:264:
 > Error: attempt to dereference a past-the-end iterator.
 > 
 > Objects involved in the operation:
 > iterator "this" @ 0x0x2b45ebd29ec0 {
 > type =
 > 
 > while running this test:
 > 
 > make CppunitTest_xmlsecurity_signing CPPUNIT_TEST_NAME=testOOXMLDescription

Indeed. I forgot to backport one of my fixes. Sorry about that, this should do the trick:
https://gerrit.libreoffice.org/#/c/46723/

Patch-set: 2
Reviewer: Gerrit User 1001240 <1001240@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0