external: update pdfium to 5187
build.patch.1 is extended to avoid:

> C:/lo/master/workdir/UnpackedTarball/pdfium/third_party/libopenjpeg/openjpeg.c(438): error C2491: 'opj_decoder_set_strict_mode': definition of dllimport function not allowed

and also is extended to avoid:

> /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/stl_tree.h:2028:5: note:   no known conversion for argument 1 from ‘std::pair<fxcrt::RetainPtr<CPDF_Object>, std::unique_ptr<CPDF_PageObjectAvail> >::first_type {aka fxcrt::RetainPtr<CPDF_Object>}’ to ‘const CPDF_Object* const&’

(cherry picked from commit 92914312cfb36a86ceb6308a2966f033152fd927)

[ backport note: core/fxcrt/cfx_datetime.cpp doesn't seems to do any
platform-specific includes anymore, so bsd-time.patch.1 looks no longer
needed. ]

Change-Id: Icacc05627a8612b33d6445685d26470e7c757b8e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/140046
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>