Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/23081/ : FAILURE

error "no need to explicitly init an instance of "std::unique_ptr<Sw2LinesPos>" with nullptr, just use default constructor [loplugin:simplifyconstruct]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/inc/crstate.hxx:166:9 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/24435/ )

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "std::unique_ptr<Sw2LinesPos>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/24435/ )

error: no need to explicitly init an instance of "std::unique_ptr<Sw2LinesPos>" with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/inc/crstate.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/24435/ )

Patch-set: 1
Label: Verified=-1