Revert "add sal*Int64 conversions to BigInt"
This reverts commit 5dae4238ea6e21df42f4437a43d152954fc494fd, which appears to
have ambiguitiy problems not only on Windows, but generally with 32-bit builds
like <https://ci.libreoffice.org/job/gerrit_android_x86/1518/>:

> /home/tdf/lode/jenkins/workspace/android_x86/tools/source/generic/bigint.cxx:501:18: error: conversion from 'int' to 'const BigInt' is ambiguous
>         *this *= 10;
>                  ^~
> /home/tdf/lode/jenkins/workspace/android_x86/include/tools/bigint.hxx:58:5: note: candidate constructor
>     BigInt(sal_Int32 nValue)
>     ^
> /home/tdf/lode/jenkins/workspace/android_x86/include/tools/bigint.hxx:66:5: note: candidate constructor
>     BigInt( double nVal );
>     ^
> /home/tdf/lode/jenkins/workspace/android_x86/include/tools/bigint.hxx:67:5: note: candidate constructor
>     BigInt( sal_uInt32 nVal );
>     ^
> /home/tdf/lode/jenkins/workspace/android_x86/include/tools/bigint.hxx:68:5: note: candidate constructor
>     BigInt( sal_Int64 nVal );
>     ^
> /home/tdf/lode/jenkins/workspace/android_x86/include/tools/bigint.hxx:69:5: note: candidate constructor
>     BigInt( sal_uInt64 nVal );
>     ^

Change-Id: I674b14c342ece3e170185b7ce2f34ccb8ff91c7a