openssl_headers depends on generated opensslconf.h
...at workdir/UnpackedTarball/openssl/include/openssl/opensslconf.h, as can be
seen with failed builds like
<https://ci.libreoffice.org//job/lo_tb_master_mac/35209>:

[...]
> [build PAT] openssl
> [build C  ] UnpackedTarball/mariadb-connector-c/plugins/auth/caching_sha2_pw.c
> [build C  ] UnpackedTarball/mariadb-connector-c/libmariadb/secure/openssl_crypt.c
> [build DEP] LNK:Library/libclucene.dylib
> [build LNK] Library/libclucene.dylib
> In file included from /Users/tdf/lode/jenkins/workspace/lo_tb_master_mac/workdir/UnpackedTarball/mariadb-connector-c/libmariadb/secure/openssl_crypt.c:21:
> /Users/tdf/lode/jenkins/workspace/lo_tb_master_mac/workdir/UnpackedTarball/openssl/include/openssl/evp.h:13:11: fatal error: 'openssl/opensslconf.h' file not found
> # include <openssl/opensslconf.h>
>           ^~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.

Change-Id: Ied1dcdd0afb6099e9218671c6a06c0edaafc931e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/108928
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit 0f7008e91f45cf8e3cee6f372ce012b38a795e26)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/108911
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>
(cherry picked from commit 74b6e9d45a7f97c8723f638a784017be99f3a8c2)