Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/86639/ : FAILURE

Visual studio complained about error C2819: type "SvxNumRule" does not have an overloaded member "operator ->" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sd/qa/unit/export-tests-ooxml1.cxx(408) ( https://ci.libreoffice.org/job/gerrit_windows/97223/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1