Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/100858/ : FAILURE

error "‘CHART2_SERVICE_NAME_CHARTTYPE_BUBBLE’ defined but not used [-Werror=unused-variable]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/chart2/source/inc/servicenames_charttypes.hxx:34:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/104479/ )

compiler warning unused-variable treated as error: ‘CHART2_SERVICE_NAME_CHARTTYPE_BUBBLE’ defined but not used in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/chart2/source/inc/servicenames_charttypes.hxx:34:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/104479/ )

error: ‘CHART2_SERVICE_NAME_CHARTTYPE_BUBBLE’ defined but not used [-Werror=unused-variable] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/chart2/source/inc/servicenames_charttypes.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/104479/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1