Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/28441/ : FAILURE

likely caused by leftovers that linger around from an aborted build ( https://ci.libreoffice.org/job/gerrit_windows/33020/ )

Visual studio complained about error C2143: syntax error: missing ")" before "]" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/vcl/win/window/salframe.cxx(4970) ( https://ci.libreoffice.org/job/gerrit_windows/33020/ )

Patch-set: 1
Label: Verified=-1