(related: tdf#149595) sw: also re-sort SwSortedObjs on SwPageFrame
... if SwTextNode content changes; for the unit test here we get:

  Error: elements in iterator range [first, last) are not partitioned by
  the predicate __comp and value __val.

Also, the SwTextNode may have multiple text frames on multiple pages.

Change-Id: I05d4276e4b4b94fe3cd2cdfda3418ad51fa08f5f
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/144108
Tested-by: Jenkins
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>
(cherry picked from commit c684301352bcca709bc8d1c99e0f08e7096e9716)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/144131
Reviewed-by: Christian Lohmaier <lohmaier+LibreOffice@googlemail.com>