Drop PocoFoundation's bundled zlib to avoid a duplicate zlib
StaticLibrary_PocoFoundation compiled its own bundled zlib, but various of
online's gbuild/Executable_*s also link the engine's zlib, as pulled in via
libpng.  While that was normally harmless, it caused ASan builds to fail linking
with

> [LNK] Executable/coolforkit-caps
> /usr/bin/ld.bfd: .../engine/workdir/LinkTarget/StaticLibrary/libPocoFoundation.a(adler32.o): in function `adler32_z':
> .../engine/workdir/UnpackedTarball/poco/dependencies/zlib/src/adler32.c:61: multiple definition of `adler32_z'; .../engine/workdir/LinkTarget/StaticLibrary/libzlib.a(adler32.o):.../engine/workdir/UnpackedTarball/zlib/adler32.c:61: first defined here

etc. (due to the __odr_asan_gen_* indicators being compiled in).

Now, anything that links zlib on online's Automake side will link against the
system zlib (via ZLIB_LIBS), while anything that links zlib on online's gbuild
side will link against whatever engine's --with/--without-system-zlib provides.

(For CODA-Q, at least a flatpak build started to fail with

>   CXXLD    coda-qt
> /usr/lib/gcc/x86_64-unknown-linux-gnu/15.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /app/lib/x86_64-linux-gnu/libQt6WebEngineCore.so: undefined reference to symbol 'deflate'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/15.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/15.2.0/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status

now, and the easiest fix is to make sure in qt/Makefile.am that POCO_LIBS
appears before ZLIB_LIBS on the linker command line.)

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I3e449e46a833366bf96c12eac24d77124d7c1aba
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/8578
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>