Update patch set 6
Patch Set 6:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/94734/ : FAILURE

clang plugin unusedmember did trigger. unused class member ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/95558/ )

error: unused class member [loplugin:unusedmember] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/filter/eps/eps.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/95558/ )

Patch-set: 6