Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/18867/ : FAILURE

error: externally available entity "getPageSize" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/qa/extras/chart2import.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/19476/ )

clang plugin external did trigger. externally available entity "getPageSize" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/19476/ )

Patch-set: 5
Label: Verified=-1