Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/32612/ : FAILURE

error "checking whether a config macro ENABLE_GSTREAMER_1_0 is defined [loplugin:checkconfigmacros]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/inc/unx/gstsink.hxx:15:2 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/34957/ )

clang plugin checkconfigmacros did trigger. checking whether a config macro ENABLE_GSTREAMER_1_0 is defined ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/34957/ )

error: checking whether a config macro ENABLE_GSTREAMER_1_0 is defined [loplugin:checkconfigmacros] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/inc/unx/gstsink.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/34957/ )

Patch-set: 1
Label: Verified=-1