Update patch set 2
Patch Set 2:

I tried to reduce the amount of noise in your patch: http://pastebin.com/raw.php?i=cN70JW3F is what I got.

When trying to build this, I get: master/sw/qa/extras/uiwriter/uiwriter.cxx:436: undefined reference to `SwHHCWrapper::Convert()'

And so on. If the class is prefixed with "Sw", then you can make it public, see how e.g. the SwDoc class is public.

An other note: if you want to load a .odt document, then put your test in uiwriter, "uwriter" is more a unit test for SwDoc itself, you can't really invoke a whole filter from that. uiwriter is more an integration test, there you can do this, you can find already working examples in that suite.

Alternatively, you can go the uwriter way, but then you need to build your test document "from code", it may be a bit painful to do so. pDoc->getIDocumentContentOperations().InsertString() is the key method to insert test into the document.

Patch-set: 2
Label: Verified=0