freetype: Build '--without-brotli'
After

    commit c99b73c16b725ec2bf2f5417f28d1688c3322d7d
    Date:   Wed Oct 20 12:08:02 2021 +0100

        upgrade freetype to 2.11.0

my local Android x86 build (using NDK 20.0.5594570) started
failing with

    In file included from .../workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:25:
    .../workdir/UnpackedTarball/freetype/src/sfnt/sfwoff2.c:27:10: fatal error: 'brotli/decode.h' file not found
    #include <brotli/decode.h>
             ^~~~~~~~~~~~~~~~~
    1 error generated.

Disable the optional Brotli dependency added upstream with

    commit 9443a1bc3e6cfa315db976ff80f6c5e91b12b387
    Author: Nikhil Ramakrishnan (निखिल रामकृष्णन) <ramakrishnan.nikhil@gmail.com>
    Date:   Fri Jun 28 01:01:17 2019 +0530

        Add Brotli dependency and required checks.

        Brotli is required for decompressing WOFF2 font directory streams.
        The library is thus being added as an optional dependency for
        FreeType.

        * builds/unix/configure.raw: Add checks for `libbrotlidec'.
        (REQUIRES_PRIVATE, LIBS_PRIVATE, LIBSSTATIC_CONFIG): Updated.

        * devel/ftoption.h, include/freetype/config/ftoption.h
        (FT_CONFIG_OPTION_USE_BROTLI): New macro.

Change-Id: Iea8d3e333cb60182026fb9fde5a0171ae197ee57