Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/57054/ : FAILURE

error "unnecessary user-declared destructor [loplugin:unnecessaryoverride]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/filter/ww8/ww8par.hxx:141:5 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/60140/ )

clang plugin unusedvariablecheck did trigger. unused variable "aStreamsList" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/60140/ )

error: unused variable "aStreamsList" [loplugin:unusedvariablecheck] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sd/source/filter/sdpptwrp.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/60140/ )

Patch-set: 7
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1