Update patch set 4
Patch Set 4:

Why these changes? VclPtr<Foo> needs definition of Foo, so wherever we use VclPtr<Foo>, we need to include the header with Foo. These changes do the opposite, making the respective headers not self-contained.

This one fails again in disable-pch, like this:

C:\lo\src\core\include\rtl/ref.hxx(129): error C2027: use of undefined type 'vcl::Window'
C:\lo\src\core\include\vcl/svapp.hxx(61): note: see declaration of 'vcl::Window'
C:\lo\src\core\include\rtl/ref.hxx(127): note: while compiling class template member function 'rtl::Reference<reference_type>::~Reference(void)'
with
[
reference_type=vcl::Window
]
C:\lo\src\core\include\vcl/uitest/uiobject.hxx(149): note: see reference to function template instantiation 'rtl::Reference<reference_type>::~Reference(void)' b
eing compiled
withC:\lo\src\core\include\rtl/ref.hxx(129): error C2027: use of undefined type 'vcl::Window'

[C:\lo\src\core\include\vcl/uitest/uiobject.hxx(42): note: see declaration of 'vcl::Window'

reference_type=vcl::WindowC:\lo\src\core\include\rtl/ref.hxx(127): note: while compiling class template member function 'rtl::Reference<reference_type>::~Refere
nce(void)'

]with

C:\lo\src\core\include\vcl/vclptr.hxx(64): note: see reference to class template instantiation 'rtl::Reference<reference_type>' being compiled[

withreference_type=vcl::Window

[]

reference_type=vcl::WindowC:\lo\src\core\include\vcl/uitest/uiobject.hxx(149): note: see reference to function template instantiation 'rtl::Reference<reference_
type>::~Reference(void)' being compiled

]with

C:\lo\src\core\include\vcl/vclevent.hxx(190): note: see reference to class template instantiation 'VclPtr<vcl::Window>' being compiled[

reference_type=vcl::Window
]
C:\lo\src\core\include\vcl/vclptr.hxx(64): note: see reference to class template instantiation 'rtl::Reference<reference_type>' being compiled
with
[
reference_type=vcl::Window
]
C:\lo\src\core\include\vcl/vclevent.hxx(190): note: see reference to class template instantiation 'VclPtr<vcl::Window>' being compiled
make[1]: *** [C:/lo/src/core/solenv/gbuild/LinkTarget.mk:301: C:/lo/src/build/workdir/CxxObject/vcl/source/uitest/uno/uiobject_uno.o] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [C:/lo/src/core/solenv/gbuild/LinkTarget.mk:301: C:/lo/src/build/workdir/CxxObject/vcl/source/uitest/uno/uitest_uno.o] Error 2
make: *** [Makefile:286: build] Error 2

Patch-set: 4
CC: Gerrit User 1000994 <1000994@6622c302-437a-49ad-a91d-55ba7dcf1615>