fix linker error
/builddir/build/BUILD/libreoffice-4.4.1.1/workdir/CxxObject/svtools/source/misc/imageresourceaccess.o: In function `com::sun::star::uno::Reference<com::sun::star::io::XOutputStream>::Reference(com::sun::star::io::XOutputStream*)':
/builddir/build/BUILD/libreoffice-4.4.1.1/include/com/sun/star/uno/Reference.hxx:137: undefined reference to `non-virtual thunk to utl::OSeekableOutputStreamWrapper::acquire()'

(cherry picked from commit 8bb0446974282b32d06cdbd35af83f91e033b4af)

see also: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64812

Change-Id: Ic644a8299cf2f79f02c1e3ca0de9687520f402a9
Signed-off-by: Michael Stahl <mstahl@redhat.com>