Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/37307/ : FAILURE

error: simplify [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/control/field.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/40217/ )

clang plugin simplifyconstruct did trigger. simplify ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/40217/ )

use default type instead of indirection ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/40217/ )

Patch-set: 1
Label: Verified=-1