Update patch set 2
Patch Set 2: Code-Review-1

testing with 64 bits vs2015 with --enable-sgdb-firebird on top of current master

w_tab_t': '4' bytes padding added after data member 'in_sw_tab_t::in_sw_optype'
c:\cygwin\home\tdf\lode\dev\core\workdir\unpackedtarball\firebird\src\include\fb_exception.h(122): warning C4820: 'Fireb
ird::system_error': '4' bytes padding added after data member 'Firebird::system_error::errorCode'
C:/PROGRA~2/WINDOW~4/10/Include/10.0.10586.0/ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition
c:\cygwin\home\tdf\lode\dev\core\workdir\unpackedtarball\firebird\src\include\gen/autoconfig.h(705): note: see previous
definition of 'snprintf'
C:/PROGRA~2/WINDOW~4/10/Include/10.0.10586.0/ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprint
f conflicts with Standard Library function declaration
../gen/make.rules:112: recipe for target '../temp/boot/jrd/gds.o' failed

Patch-set: 2
Reviewer: Gerrit User 1000003 <1000003@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Code-Review=-1