Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_64/1694/ : FAILURE

error: use of undeclared identifier "getShapes"; did you mean "getPages"? in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sw/qa/extras/rtfexport/rtfexport5.cxx ( https://ci.libreoffice.org/job/gerrit_mac/69053/ )

the build failed because of an issue with the bot itself, not with the code.
The Bot failed to checkout the source ( https://ci.libreoffice.org/job/gerrit_mac/69053/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1