Upgrade external/boost to latest Boost 1.80.0
<https://dev-www.libreoffice.org/src/boost_1_80_0.tar.xz> has been generated (on
Fedora 36) with

> $ wget https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.bz2
> $ printf '1e19565d82e43bc59209a168f5ac899d3ba471d55c7610c677d4ccf2c9c500c0 boost_1_80_0.tar.bz2' | sha256sum -c # cf. <https://www.boost.org/users/history/version_1_80_0.html>
> boost_1_80_0.tar.bz2: OK
> $ external/boost/repack_tarball.sh boost_1_80_0.tar.bz2
> Unpacking boost_1_80_0.tar.bz2 ...
> Removing unnecessary files ...
> Creating boost_1_80_0.tar.xz ...
> Cleaning up ...
> 322e567e98c466c0aa0e380ed8c647552fe4af48998648428f1b5f0c8eff4666  boost_1_80_0.tar.xz
> Done.

* For one, in StaticLibrary_boost_filesystem,
<https://github.com/boostorg/filesystem/commit/36cf9aaf816a39dce3d32e2bfe09e214d7f3ab64>
"Updated protection of remove_all against CVE-2022-21658 on POSIX" had
introduced uses of certain POSIX *at functions (like utimensat) conditionally on
some new BOOST_FILESYSTEM_HAS_POSIX_AT_APIS, to be discovered by
workdir/UnpackedTarball/boost/libs/filesystem/CMakeLists.txt which we don't run.
Assume that those POSIX functions are available on all our non-Windows baselines
and hardcode that in external/boost/StaticLibrary_boost_filesystem.mk.  (If it
turns out that we need to exclude some more platforms there, we /might/ need to
backport
<https://github.com/boostorg/filesystem/commit/5864f397ccad30f6e73221b90bdac57a303b9752>
"Fixed a missing include on POSIX systems that don't support *at APIs" from the
develop branch towards Boost 1.81.)

* For another, in StaticLibrary_boost_locale,
<https://github.com/boostorg/locale/commit/41868c62a0519799696b544518f1efd831ff71c2>
"Support systems without implicit include path" had moved source files around
(and then would have failed with

> workdir/UnpackedTarball/boost/libs/locale/src/boost/locale/shared/mo_lambda.cpp:7:10: fatal error: 'boost/locale/shared/mo_lambda.hpp' file not found
> #include "boost/locale/shared/mo_lambda.hpp"
>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

etc. without the additional -I option).

Change-Id: I5e53f7ddab07eadba9bdf653acad571f50517b46