Update patch set 17
Patch Set 17:

> Uploaded patch set 15.

> $ git checkout efc1d001821747dc72140aeb3e0f0b48b1eed005 && git submodule update && git fetch https://git.libreoffice.org/core refs/changes/05/77405/14 && git cherry-pick FETCH_HEAD
[...]
> error: could not apply 8d91ea7891fc... drop gtk2 support
> hint: after resolving the conflicts, mark the corrected paths
> hint: with 'git add <paths>' or 'git rm <paths>'
> hint: and commit the result with 'git commit'
> $ git status
[...]
> Unmerged paths:
>   (use "git add/rm <file>..." as appropriate to mark resolution)
> 
> 	deleted by them: vcl/unx/gtk/a11y/atkaction.cxx
> 	deleted by them: vcl/unx/gtk/a11y/atkimage.cxx
> 	deleted by them: vcl/unx/gtk/a11y/atktable.cxx
> 	deleted by them: vcl/unx/gtk/a11y/atkutil.cxx
> 	deleted by them: vcl/unx/gtk/a11y/atkwrapper.cxx
> 	deleted by them: vcl/unx/gtk/gloactiongroup.cxx

I identified as gone missing <https://gerrit.libreoffice.org/plugins/gitiles/core/+/f5bbb2db98fe420174328e6c8e2f3d160a9b7758%5E!/> "Clean up uses of deprecated G_CONST_RETURN" (addressed now by <https://gerrit.libreoffice.org/#/c/80026/> "Reinstate 'Clean up uses of deprecated G_CONST_RETURN'") and <https://gerrit.libreoffice.org/plugins/gitiles/core/+/efc1d001821747dc72140aeb3e0f0b48b1eed005%5E!/> "Use G_ADD_PRIVATE and *_get_instance_private" (addressed now by <https://gerrit.libreoffice.org/#/c/80027/> "Reinstate 'Use G_ADD_PRIVATE and *_get_instance_private'").  Hopefully nothing else has gone missing due to this change?

Patch-set: 17