Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/114983/ : FAILURE

error: rather use O[U]String::Concat than constructing "rtl::OString" from "const char *" on RHS of + (where LHS is of type "const typename std::enable_if_t<ToStringHelper<OStringConcat<OStringConcat<OStringConcat<OStringConcat<OStringConcat<OStringConcat<char const[3], OStringNumber<int>>, char const[3]>, OStringNumber<int>>, char const[3]>, OStringNumber<int>>, char const[3]>>::allowOStringConcat && ToStringHelper<OStringNumber<int>>::allowOStringConcat, OStringConcat<OStringConcat<OStringConcat<OStringConcat<OStringConcat<OStringConcat<OStringConcat<char const[3], OStringNumber<int>>, char const[3]>, OStringNumber<int>>, char const[3]>, OStringNumber<int>>, char const[3]>, OStringNumber<int>>>" (aka "const rtl::OStringConcat<rtl::OStringConcat<rtl::OStringConcat<rtl::OStringConcat<rtl::OStringConcat<rtl::OStringConcat<rtl::OStringConcat<char const[3], rtl::OStringNumber<int>>, char const[3]>, rtl::OStringNumber<int>>, char const[3]>, rtl::OStringNumber<int>>, char const[3]>, rtl::OStringNumber<int>>")) [loplugin:stringadd] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/core/tool/prnsave.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/114110/ )

clang plugin stringview did trigger. instead of an "rtl::OString" constructed from a "const char *", pass a "std::string_view" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/114110/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000947 \u003c1000947@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}