Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/95684/ : FAILURE

clang plugin stringview did trigger. instead of an "rtl::OUString" constructed from a "char16_t", pass a "std::u16string_view" (or an "rtl::OUStringChar") ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/96443/ )

error: rather use O[U]String::Concat than constructing "rtl::OUString" from "char16_t" on LHS of + (where RHS is of type "const rtl::OUString") [loplugin:stringadd] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/uibase/wrtsh/delete.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/96443/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1001002 \u003c1001002@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}