Use --with-sytem-cairo for the ASan+UBSan tinderbox again
After 1ae450504cf57457f9702684b1517fda1dd3c481 "drop gtk2 support" removed the
implicit --enable-gtk which removed the implicit --with-system-cairo,
<https://ci.libreoffice.org/job/lo_ubsan/1402/> started to fail with

> [build LNK] Executable/canvasdemo
[...]
> /home/tdf/lode/jenkins/workspace/lo_ubsan/instdir/program/libcairo.so.2: undefined reference to `__muloti4'
[...]
> clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
> /home/tdf/lode/jenkins/workspace/lo_ubsan/solenv/gbuild/LinkTarget.mk:635: recipe for target '/home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/LinkTarget/Executable/canvasdemo' failed

etc.  Instead of trying to fix that, just explicitly build --with-system-cairo
again.  (Another approach could be to --enable-gtk3, which implicitly sets
--with-system-cairo, too.)

Change-Id: I335b2a694b85a15efae6002d890ce0d67811b2bb
Reviewed-on: https://gerrit.libreoffice.org/79962
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>