Update patch set 21
Patch Set 21:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/70161/ : FAILURE

error "class "SmToken" was previously declared as a struct [-Werror,-Wmismatched-tags]" triggered in included file /home/tdf/lode/jenkins/workspace/android_x86_64/starmath/inc/starmathdatabase.hxx:23:1 ( https://ci.libreoffice.org/job/gerrit_android_x86_64/612/ )

error: class "SmToken" was previously declared as a struct [-Werror,-Wmismatched-tags] in file /home/tdf/lode/jenkins/workspace/android_x86_64/starmath/inc/starmathdatabase.hxx ( https://ci.libreoffice.org/job/gerrit_android_x86_64/612/ )

Patch-set: 21
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>