Update patch set 16
Patch Set 16: Code-Review+1

is this still a problem?

 > but that still runs into the AC_CHECK_HEADER failure I outlined a
 > few days ago:
 > 
 > onfigure:33031: checking qrcodegen/QrCode.hpp usability
 > configure:33031: g++ -c    conftest.cpp >&5
 > In file included from conftest.cpp:147:
 > /usr/include/qrcodegen/QrCode.hpp:378:48: error: expected
 > class-name before '{' token
 > class data_too_long : public std::length_error {
 > ^
 > configure:33031: $? = 1

guess it would be fixed by including <stdexcept> which the library does not include itself which is clearly a bug... but i wonder how that can be missing when vector has functions that throw std::exceptions too...

does it work if you change it to

+    AC_CHECK_HEADER(qrcodegen/QrCode.hpp, [],
+        [AC_MSG_ERROR(qrcodegen C++ headers not found.)], [#include <stdexcept>])

otherwise i dont see any problem now

Patch-set: 16
Label: Code-Review=+1