replace o3tl::make_unsigned with a local NumUtil::makeUnsigned
o3tl is an engine-internal library, not part of the LOKit SDK, and it is
not on the include path of everything Online compiles.  Everything gbuild
builds gets -I$(SRCDIR)/include for free, solenv/gbuild/LinkTarget.mk sets
the default INCLUDE to it, which is why the uses in .cpp files went
unnoticed.  wsd/KitWSDGlobals.cpp is the only C++ file automake compiles
in a packaging build, and its include path is -I${LOKIT_PATH}, which
coolwsd.spec.in sets to bundled/include: the two COKit headers that the
dist-hook copies into the tarball, nothing else.  Once the include moved
into common/FileUtil.hpp, KitWSDGlobals.cpp reached it through
WSDGlobals.hpp and Clipboard.hpp and the rpm build broke with

  ./common/FileUtil.hpp:26:10: fatal error: o3tl/safeint.hxx: No such file or directory

Bundling the header is no help, it pulls in sal/config.h and
o3tl/intcmp.hxx.  make_unsigned is four lines, so keep a copy of it in
NumUtil.hpp and drop the dependency on the engine headers.

Signed-off-by: Andras Timar <andras.timar@collabora.com>
Change-Id: I56e3a09a1e8a3cd1a4c4a52ba9103fc468189985
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/12394
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>