Use System::Boolean instead of the non-existent System::Bool
cli_uno failed to compile:

> cli_ure/source/uno_bridge/cli_data.cxx(1242): error C2039: 'Bool': is not a member of 'System'
> cli_ure/source/uno_bridge/cli_data.cxx(1242): error C2065: 'Bool': undeclared identifier

The .NET type is System::Boolean; System::Bool does not exist. The wrong name
came in with the static_assert added by 67e8da990fbdba7719ea107c29f4e57b62d5b6db
("replace sal_Bool with bool", 2026-06-20); sizeof(System::Boolean) is 1, so the
assertion still holds.

Signed-off-by: Mike Kaganski <mike.kaganski@collabora.com>
Change-Id: I71ddede927c5e0ad2d3f972e25b9bf338c1d4d4c
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/5139
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>