Fix Windows build
 C:/lo/core2/editeng/qa/unit/core-test.cxx(2381): error C2668: 'EditDoc::GetParaAsString': ambiguous call to overloaded function
 C:\lo\core2\editeng\inc\editdoc.hxx(183): note: could be 'rtl::OUString EditDoc::GetParaAsString(const ContentNode *,sal_Int32,sal_Int32)'
 C:\lo\core2\editeng\inc\editdoc.hxx(182): note: or       'rtl::OUString EditDoc::GetParaAsString(sal_Int32) const'
 C:/lo/core2/editeng/qa/unit/core-test.cxx(2381): note: while trying to match the argument list '(int)'
 C:/lo/core2/editeng/qa/unit/core-test.cxx(2381): error C2672: 'CppUnit::assertEquals': no matching overloaded function found
 C:/lo/core2/editeng/qa/unit/core-test.cxx(2381): error C2780: 'void CppUnit::assertEquals(const T &,const T &,CppUnit::SourceLine,const std::string &)': expects 4 arguments - 3 provided
 C:\lo\build2\workdir\UnpackedTarball\cppunit\include\cppunit/TestAssert.h(161): note: see declaration of 'CppUnit::assertEquals'
 C:/lo/core2/editeng/qa/unit/core-test.cxx(2404): error C2668: 'EditDoc::GetParaAsString': ambiguous call to overloaded function
 C:\lo\core2\editeng\inc\editdoc.hxx(183): note: could be 'rtl::OUString EditDoc::GetParaAsString(const ContentNode *,sal_Int32,sal_Int32)'
 C:\lo\core2\editeng\inc\editdoc.hxx(182): note: or       'rtl::OUString EditDoc::GetParaAsString(sal_Int32) const'
 C:/lo/core2/editeng/qa/unit/core-test.cxx(2404): note: while trying to match the argument list '(int)'
 C:/lo/core2/editeng/qa/unit/core-test.cxx(2404): error C2672: 'CppUnit::assertEquals': no matching overloaded function found
 C:/lo/core2/editeng/qa/unit/core-test.cxx(2404): error C2780: 'void CppUnit::assertEquals(const T &,const T &,CppUnit::SourceLine,const std::string &)': expects 4 arguments - 3 provided
 C:\lo\build2\workdir\UnpackedTarball\cppunit\include\cppunit/TestAssert.h(161): note: see declaration of 'CppUnit::assertEquals'

Change-Id: I8f9b6fc32669d7b0626c07f2fb4c7dbd254dfc1c
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/199902
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>