Update patch set 2
Patch Set 2:

Looks like this change broke the build:

/home/master/src/libreoffice/workdirs/libreoffice-4-3/svx/source/sidebar/possize/PosSizePropertyPanel.cxx: In member function ‘long int svx::sidebar::PosSizePropertyPanel::AngleModifiedHdl(void*)’:
/home/master/src/libreoffice/workdirs/libreoffice-4-3/svx/source/sidebar/possize/PosSizePropertyPanel.cxx:506:72: error: invalid use of incomplete type ‘const class AllSettings’
     const LocaleDataWrapper& rLocaleWrapper( Application::GetSettings().GetLocaleDataWrapper() );
                                                                        ^
In file included from /home/master/src/libreoffice/workdirs/libreoffice-4-3/include/vcl/window.hxx:25:0,
                 from /home/master/src/libreoffice/workdirs/libreoffice-4-3/include/vcl/syswin.hxx:25,
                 from /home/master/src/libreoffice/workdirs/libreoffice-4-3/include/vcl/floatwin.hxx:25,
                 from /home/master/src/libreoffice/workdirs/libreoffice-4-3/include/vcl/dockwin.hxx:25,
                 from /home/master/src/libreoffice/workdirs/libreoffice-4-3/include/vcl/toolbox.hxx:26,
                 from /home/master/src/libreoffice/workdirs/libreoffice-4-3/include/sfx2/sidebar/SidebarToolBox.hxx:23,
                 from /home/master/src/libreoffice/workdirs/libreoffice-4-3/include/sfx2/sidebar/ControlFactory.hxx:23,
                 from /home/master/src/libreoffice/workdirs/libreoffice-4-3/svx/source/sidebar/possize/PosSizePropertyPanel.cxx:21:
/home/master/src/libreoffice/workdirs/libreoffice-4-3/include/vcl/outdev.hxx:80:7: error: forward declaration of ‘const class AllSettings’
 class AllSettings;
       ^
/home/master/src/libreoffice/workdirs/libreoffice-4-3/solenv/gbuild/LinkTarget.mk:183: recipe for target '/home/master/src/libreoffice/workdirs/libreoffice-4-3/workdir/CxxObject/svx/source/sidebar/possize/PosSizePropertyPanel.o' failed
make[1]: *** [/home/master/src/libreoffice/workdirs/libreoffice-4-3/workdir/CxxObject/svx/source/sidebar/possize/PosSizePropertyPanel.o] Error 1
make[1]: *** Waiting for unfinished jobs....

Patch-set: 2
Reviewer: Gerrit User 1000084 <1000084@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0