Revert "vcl: test getting glyph boundary rect from LogicalFontInstance"
This reverts commit 0cef06f0a2c0963e8c1579b78975710e6af4471c.

Reason for revert: 

https://gerrit.libreoffice.org/c/core/+/141234/comments/89325e55_2271cfe8

> Stephan Bergmann:
>
> I saw the unrelated <https://gerrit.libreoffice.org/c/core/+/143026/1> fail its Jenkins <https://ci.libreoffice.org/job/gerrit_windows/140750/> build on tb88-win with
>
>   C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/vcl/qa/cppunit/logicalfontinstance.cxx(53) : error : Assertion
>   Test name: VclLogicalFontInstanceTest::testglyphboundrect
>   equality assertion failed
>   - Expected: 51x82@(7,-80)
>   - Actual  : 50x82@(7,-80)

Change-Id: Idc4132adbaf0b051dcf955f3f1e7c44841c60117
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/142928
Tested-by: Jenkins
Reviewed-by: خالد حسني <khaled@aliftype.com>