UBSan apparently needs ScDataPilotFieldsObj RTTI now
...seeing CppunitTest_sc_filters_test failing with

> DynamicLibraryManagerException: "Failed to load dynamic library: /home/sberg/lo/core/workdir/LinkTarget/CppunitTest/libtest_sc_filters_test.so
> /home/sberg/lo/core/instdir/program/libscfiltlo.so: undefined symbol: _ZTI20ScDataPilotFieldsObj"

Change-Id: I787e116dc3ae1249ac8377767e49d0cbcd9ec2db
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/196266
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>
(cherry picked from commit 09cfff610b52d8c6888f8911e25a761c53ea0eb7)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/201610
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>