Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/24217/ : FAILURE

likely caused by leftovers that linger around from an aborted build ( https://ci.libreoffice.org/job/gerrit_windows/28054/ )

Visual studio complained about error C2110: "+": cannot add two pointers in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/bridges/source/cpp_uno/msvc_win32_intel/except.cxx(557) ( https://ci.libreoffice.org/job/gerrit_windows/28054/ )

Patch-set: 1
Label: Verified=-1