Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/53899/ : FAILURE

error "unknown type name "SCTAB"" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/filter/inc/xestream.hxx:341:20 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/57103/ )

error: externally available entity "switchOnJVMPreloading" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/stoc/source/javaloader/javaloader.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/57103/ )

clang plugin external did trigger. externally available entity "switchOnJVMPreloading" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/57103/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1