Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/17127/ : FAILURE

Visual studio complained about error C2440: "=": cannot convert from "const sal_uInt8 *" to "void *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/canvas/source/directx/dx_impltools.cxx(507) ( https://ci.libreoffice.org/job/gerrit_windows/18944/ )

Patch-set: 2
Label: Verified=-1