Allow building against JDK 18
...where ExternalProject_hsqldb failed with

>      [java] java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
>      [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:194)
>      [java] 	at org.apache.tools.ant.taskdefs.Java.run(Java.java:891)
>      [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:231)
>      [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
>      [java] 	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
>      [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
>      [java] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
>      [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
>      [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
>      [java] 	at org.apache.tools.ant.Task.perform(Task.java:350)
>      [java] 	at org.apache.tools.ant.Target.execute(Target.java:449)
>      [java] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
>      [java] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
>      [java] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
>      [java] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
>      [java] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
>      [java] 	at org.apache.tools.ant.Main.runBuild(Main.java:818)
>      [java] 	at org.apache.tools.ant.Main.startAnt(Main.java:223)
>      [java] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
>      [java] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
>      [java] Caused by: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
>      [java] 	at java.base/java.lang.System.setSecurityManager(System.java:416)
>      [java] 	at org.apache.tools.ant.types.Permissions.setSecurityManager(Permissions.java:103)
>      [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:216)
>      [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:155)
>      [java] 	... 19 more

while building target switchtojdk17 (but then unfortunately carried on, without
the source modifications that should have been done by that target, leading to
confusing errors like

>     [javac] workdir/UnpackedTarball/hsqldb/src/org/hsqldb/jdbc/jdbcConnection.java:426: error: jdbcConnection is not abstract and does not override abstract method createStruct(String,Object[]) in Connection

that should have been under control at least ever since
7dbfc0012cc75e7dac9a416b53149ad8ec33f071 "make hsqldb build with java 1.7".)

Unconditionally passing ANT_OPTS -Djava.security.manager=allow should be
harmless when building against older JDK versions.

Change-Id: I9d143d8bcfff67870017bb1c874eec53e0ff9672