Adapt loplugin:unnecessaryparen to CXXRewrittenBinaryOperator
...as debuted in Clang with
<https://github.com/llvm/llvm-project/commit/778dc0f1d49230f53401ae0c190fe460bda4ffd1>
"[c++20] Add CXXRewrittenBinaryOperator to represent a comparison operator that
is rewritten as a call to multiple other operators" towards Clang 10, and would
have caused a false

> xmloff/source/style/XMLRtlGutterPropertyHandler.cxx:40:16: error: parentheses immediately inside assignment [loplugin:unnecessaryparen]
>     rValue <<= (it != aRtlModes.end());
>                ^~~~~~~~~~~~~~~~~~~~~~~

with --with-latest-c++ and an appropriate libstdc++.

Change-Id: Iede63144dff1e1c833a1da7090b599e792351926
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/113744
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>