fix(android/boost): correct long-double width #elif
Unlike other x86_64 platforms, Android x86_64 uses the same number of bits in
its long-double as AArch64. Unfortunately, in boost this long-double width is
gated only by architecture, so x86_64 Android is mistakenly placed here causing:

    fp_traits.hpp:314: error: static assertion failed due to requirement
    '113 == 64': Oops, assumption that long double is an 80-bit quantity is
    incorrect!!

We should write the correct assumption into the #elif here, which will cause
Android x86_64 to fall through to the generic case below...

Signed-off-by: Skyler Grey <skyler.grey@collabora.com>
Change-Id: Ic3819408a69de5e79e45d7d5500c5b616a6a6964
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/9335
Reviewed-by: Karthik Godha <karthik.godha@collabora.com>