sd: BestFittingCacheComparer must be irreflexive
/usr/include/c++/7/bits/stl_algo.h:4866:
Error: comparison doesn't meet irreflexive requirements, assert(!(a < a)).

... when using "Window->New Window" in Impress.

Change-Id: I885a59cf378b7020d549580c2fc1cf121c6a59bd
(cherry picked from commit d4269c5373cf8ccc0a5631b9d0900227e11e13f1)