Update patch set 15
Patch Set 15:

Build Failed 

https://ci.libreoffice.org/job/gerrit_feature/24/ : FAILURE

clang plugin sallogareas did trigger. missing log area ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/2959/ )

error: missing log area [loplugin:sallogareas] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/svx/source/svdraw/svdobj.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/2959/ )

Patch-set: 15