sw_ww8export3: missing dependency
This unit test fails when called after 'make clean':

  > make clean
  > make CppunitTest_sw_ww8export3
  ...
  testdf79553_lineNumbers::Load_Verify_Reload_Verify finished in: 9591ms
  C:/lo/src/core/sw/qa/extras/ww8export/ww8export3.cxx(149) : error : Assertion
  Test name: testTdf128501::Load_Verify_Reload_Verify
  equality assertion failed
  - Expected: FrameShape
  - Actual  : com.sun.star.drawing.RectangleShape

  Failures !!!
  Run: 47   Failure total: 1   Failures: 1   Errors: 0

See https://gerrit.libreoffice.org/c/core/+/107003

Change-Id: I4970529f23ad38cb8cc9f403000ac19b0f79008f