Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/102236/ : FAILURE

error "‘xmloff::EVENT_APPLICATION’ defined but not used [-Werror=unused-variable]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/xmloff/source/forms/strings.hxx:203:31 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/105825/ )

error: ‘xmloff::EVENT_APPLICATION’ defined but not used [-Werror=unused-variable] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/xmloff/source/forms/strings.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/105825/ )

compiler warning unused-variable treated as error: ‘xmloff::EVENT_APPLICATION’ defined but not used in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/xmloff/source/forms/strings.hxx:203:31 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/105825/ )

Patch-set: 7
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1