perf: lcl_FindCellStyle scanned every cell style of every table style
since:

commit 637c0d37b5e6c581e352d5bf9e1c2260d47bcc32
Date:   Thu Sep 3 07:40:18 2026 +0000

    cool#16081 Bring Word's built-in table styles to Writer

Every document now has 247 table styles, and a cell style lookup that
missed the cell style pool built and compared a name for each cell
style of each of them, so saving to ODF became quadratic. hello.odt
took 3s to save in CI and 22s in a debug build.

That showed up as unit-httpws reloadWhileDisconnecting failing in
https://cpci.cbg.collabora.co.uk:8080/job/gerrit_linux_gcc_main/15652/
and in five more builds of that job with:

    coolwsd: ./helpers.hpp:850: std::shared_ptr<http::WebSocketSession> helpers::loadDocAndGetSession(...): Assertion `!"isLoaded"' failed.
    ERROR: Assertion failure: Failed to load the document .../reloadWhileDisconnecting_5bd6514e_hello.odt/ws. Condition: isLoaded

SwXTextCellStyle::GetBoxAutoFormat already parses the table style
name out of the cell style name and looks that up directly, so use
it here too.

Signed-off-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Change-Id: I9e923d971a2b1a2cab67dc067554e1ffc1174fbe
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/13068
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>