Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/27126/ : FAILURE

error: no need to explicitly init an instance of "std::unique_ptr<svt::MSODocumentLockFile>" with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sfx2/source/doc/docfile.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/28946/ )

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "std::unique_ptr<svt::MSODocumentLockFile>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/28946/ )

Patch-set: 2
Label: Verified=-1