Fix build on big-endian platforms with clang
Reportedly, this builds OK with gcc, but not with clang (rightfully).

/tmp/usr/ports/editors/libreoffice/work/libreoffice-6.3.0.4/connectivity/source/drivers/odbc/OTools.cxx:148:21:
error: arithmetic on a pointer to void
_pValue += _nSize - properSize;
~~~~~~~ ^
1 error generated.

The pointer arithmetics on void* was introduced in 2012 in commit
9ee96273a2090b63e0f579a1e9c9cef780756e6d.

Change-Id: I78beddeda8bc516e45dd2a99dba8c7b8b1cf9255