Update patch set 4
Patch Set 4:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/89691/ : FAILURE

error: externally available entity "ImplHandleMouseEvent2" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/window/winproc.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/90883/ )

clang plugin external did trigger. externally available entity "ImplHandleMouseEvent2" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/90883/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>