Simplify nXWidth initialization
...which happens to avoid an unhelpful -Werror=strict-overflow with GCC 7 and
--enable-optimized:

> vcl/source/edit/texteng.cxx: In member function ‘bool TextEngine::CreateLines(sal_uInt32)’:
> vcl/source/edit/texteng.cxx:2197:9: error: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]
>          if ( nTmpWidth > nXWidth )
>          ^~

Change-Id: Ia87933da6e38b8b462d2ea34c3db6a84c5840f92
Reviewed-on: https://gerrit.libreoffice.org/66690
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit 41fded57629ce1c14d806c0f37c18540ad2cf613)