Update patch set 2
Patch Set 2:

This has a logical merge conflict with <https://git.libreoffice.org/core/+/35e471bb4d1388cf5afcdcee214cf5111edf44e3%5E!/> "Adapt the remaining OUString functions to std string_view", see <https://tinderbox.libreoffice.org/cgi-bin/gunzip.cgi?tree=libreoffice-7-1&brief-log=1611357001.13723#err746>:

  36224         /tinderbox/buildslave/source/libo-71/desktop/source/app/crashreport.cxx: In static member function âstatic void CrashReporter::writeSystemInfo()â:
  36225 NEXT    /tinderbox/buildslave/source/libo-71/desktop/source/app/crashreport.cxx:269:81: error: no matching function for call to ârtl::OUString::fromUtf8(std::sub_match<__gnu_cxx::__normal_iterator<const char*, std::basic_string<char> > >::string_type)â
  36226                          addKeyValue("CPUModelName", OUString::fromUtf8( match[ 1 ].str()), AddItem);
  36227                                                                                          ^
  36228         In file included from /tinderbox/buildslave/source/libo-71/include/desktop/crashreport.hxx:15:0,
  36229                          from /tinderbox/buildslave/source/libo-71/desktop/source/app/crashreport.cxx:10:
  36230         /tinderbox/buildslave/source/libo-71/include/rtl/ustring.hxx:3104:21: note: candidate: static rtl::OUString rtl::OUString::fromUtf8(const rtl::OString&)
  36231              static OUString fromUtf8(const OString& rSource)
  36232                              ^~~~~~~~
  36233         /tinderbox/buildslave/source/libo-71/include/rtl/ustring.hxx:3104:21: note:   no known conversion for argument 1 from âstd::sub_match<__gnu_cxx::__normal_iterator<const char*, std::basic_string<char> > >::string_type {aka std::basic_string<char>}â to âconst rtl::OString&â

Patch-set: 2
CC: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>