gpgme: Upgrade to 1.24.0
* external/gpgmepp/gettid.patch fixes
/opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: ./.libs/libgpgme.so: undefined reference to `gettid'

* external/gpgmepp/strcasecmp.patch fixes
libgpgme.lib(key.obj) : error LNK2019: unresolved external symbol _strcasecmp referenced in function __gpgme_key_append_name

Downloaded from https://www.gnupg.org/ftp/gcrypt/gpgme/gpgme-1.24.0.tar.bz2

Change-Id: I2f2587f5157db7610d6ffaa84b49f9677ba1cc4c
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/176160
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
(cherry picked from commit 96fb0457f49975a7e9a90eb92442e678b5d279ba)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/176237
Reviewed-by: Thorsten Behrens <thorsten.behrens@allotropia.de>