Create destination directory also for non-empty sourcepath directory
Do not attempt to copy anything. This can happen with
instdir/share/extensions being populated from some build (e.g. by
dictionaries) but no extension to be installed.

The result was
ERROR: Can't copy file: /build/core/instdir/share/extensions -> /build/usr/opt/core/lib/libreoffice/share/extensions
Is a directory at /build/core/solenv/bin/modules/installer/worker.pm line 350.

and the copy() created the destination as 0-length file instead.

The recent changes not copying extensions/packages.txt anymore and
related may have triggered this:

6c487d2d7e8aa5cdef55cbd7bc78058184671d82 Fix and simplify "any bundled extensions installed" check
626050e86b7d5ca0c3bfc265cc33ce8e9d1bf195 gb_Package_Package must specify a directory
f267340d300da6318435ed1b2ae48b9f4275e2c4 Remove unused $(LIBO_SHARE_FOLDER)/extensions/package.txt

Change-Id: I93c1b0867bf234255fdef9d31c447b9b20011e17