Update patch set 4
Patch Set 4:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/93553/ : FAILURE

error ""bad_optional_access" is unavailable: introduced in macOS 10.13" triggered in included file /Volumes/Jenkins/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/editeng/outlobj.hxx:198:28 ( https://ci.libreoffice.org/job/gerrit_mac/98955/ )

error: "bad_optional_access" is unavailable: introduced in macOS 10.13 in file /Volumes/Jenkins/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/editeng/outlobj.hxx ( https://ci.libreoffice.org/job/gerrit_mac/98955/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>