Update patch set 2
Patch Set 2:

So the new UITest_writer_tests7 UITEST_TEST_NAME=tdf139301.tdf139301.test_tdf139301 keeps failing for my slow-executing ASan+UBSan build, always with something like "'Dash' != 'Dash Dot'" or "'Dash Dot' != 'Dash Dot Dot'" (i.e., from the end of the `i` loop).  But with a sleep added at

  import time

  [...]

              for i in range(i+1):
                  self.xUITest.executeCommand(".uno:JumpToNextFrame")
                  time.sleep(1)

even another fast-executing (which would otherwise not fail) consistently fails with

  ======================================================================
  FAIL: test_tdf139301 (tdf139301.tdf139301)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/sbergman/lo2/core/sw/qa/uitest/writer_tests7/tdf139301.py", line 42, in test_tdf139301
      self.assertEqual(style, styles[i])
  AssertionError: 'Long Dash' != 'Long Dash Dot'
  - Long Dash
  + Long Dash Dot
  ?          ++++

(i.e., always on the second iteration of the `i` loop).  It smells like the first .uno:JumpToNextFrame triggers some asynchronous switch (which thus happens at an unpredictable later time, too late to be noticeable during a normal, fast-executing build) into a state where later .uno:JumpToNextFrame are ignored.

Can you try to make this test deterministic?

Patch-set: 2