Fix Android build after commit ac419786b3244d909901db053841862abf5e7a2f
... giving this error:

   In file included from
   /home/android/lo/master-android-arm/filter/source/xmlfilteradaptor/XmlFilterAdaptor.cxx:50:
   /home/android/lo/master-android-arm/include/comphelper/scopeguard.hxx:36:14:
   error: function 'comphelper::<deduction guide for ScopeGuard><(lambda at
   /home/android/lo/master-android-arm/filter/source/xmlfilteradaptor/XmlFilterAdaptor.cxx:146:34)>'
   has internal linkage but is not defined [-Werror,-Wundefined-internal]
       explicit ScopeGuard( Func && func ) : m_func( std::move(func) ) {}
                ^
   /home/android/lo/master-android-arm/filter/source/xmlfilteradaptor/XmlFilterAdaptor.cxx:146:28:
   note: used here
       comphelper::ScopeGuard guard([&]() {
                              ^

See https://lists.freedesktop.org/archives/libreoffice/2019-April/082599.html

Change-Id: If719d183d2ce15fa4877cd8bbf457d79097765be
Reviewed-on: https://gerrit.libreoffice.org/71510
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>
Tested-by: Mike Kaganski <mike.kaganski@collabora.com>