partially revert "loplugin:unusedmethods"
partially revert
    commit 74cd0d0b281f8df75612bfb600df2eae62c4d21d
    Author: Noel Grandin <noel.grandin@collabora.co.uk>
    Date:   Thu Jun 29 13:53:30 2023 +0200
    loplugin:unusedmethods

It generates
/home/tdf/lode/jenkins/workspace/lo_gerrit/tb/src_master/extensions/source/update/ui/updatecheckui.cxx:35:10:
fatal error: vcl/menubarupdateicon.hxx: No such file or directory
10054          #include <vcl/menubarupdateicon.hxx>
10055                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I42cd6f5fecf7c0154f5d733119d5cdac0830182d
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/153782
Tested-by: Jenkins
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>