vcl: missing stdint
include/vcl/filter/PngImageWriter.hxx:25:16: error: ‘uint8_t’ was not declared in this scope
vcl/source/filter/GraphicFormatDetector.cxx:846:5: error: ‘uint64_t’ was not declared in this scope

Change-Id: Ia98a4665536fbd79866b5972ea44e8813da28735