Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/110291/ : FAILURE

clang plugin salunicodeliteral did trigger. in LIBO_INTERNAL_ONLY code, replace literal cast to "sal_Unicode" (aka "char16_t") with a u"..." char16_t character literal ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/109864/ )

error: in LIBO_INTERNAL_ONLY code, replace literal cast to "sal_Unicode" (aka "char16_t") with a u"..." char16_t character literal [loplugin:salunicodeliteral] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/filter/ww8/ww8par5.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/109864/ )

use default type instead of indirection ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/109864/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000804 \u003c1000804@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}