Avoid -Werror,-Wcast-function-type-mismatch, remove unused int return
> vcl/unx/generic/app/i18n_ic.cxx:225:51: error: cast from 'int (*)(XIC, XPointer, XPointer)' (aka 'int (*)(_XIC *, char *, char *)') to 'XIMProc' (aka 'void (*)(_XIM *, char *, char *)') converts to incompatible function type [-Werror,-Wcast-function-type-mismatch]
>   225 |                 maPreeditStartCallback.callback = reinterpret_cast<XIMProc>(PreeditStartCallback);
>       |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I94d1d0042516a01f8597bc65895042ddae76c98b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/165291
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>