Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/39011/ : FAILURE

error ""Activate" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/vcl/wizardmachine.hxx:94:29 ( https://ci.libreoffice.org/job/gerrit_mac/42253/ )

error: "Activate" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/vcl/wizardmachine.hxx ( https://ci.libreoffice.org/job/gerrit_mac/42253/ )

Patch-set: 4
Label: Verified=-1