Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/59410/ : FAILURE

clang plugin unusedvariablecheck did trigger. unused variable "aEventNamesCache" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/62371/ )

error: unused variable "aEventNamesCache" [loplugin:unusedvariablecheck] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/cui/source/customize/macropg.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/62371/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1