Missing construction of SfxCmisVersionsDialog::m_xVersionBox
...ever since b1baf73dc671069bedec18d170f8199b0766ea60 "weld
SfxCmisVersionsDialog".  (Found by GCC 11 trunk with --enable-optimized,

> sfx2/source/dialog/versdlg.cxx: In constructor ‘SfxCmisVersionsDialog::SfxCmisVersionsDialog(weld::Window*, SfxViewFrame*)’:
> sfx2/source/dialog/versdlg.cxx:435:36: error: ‘this’ pointer null [-Werror=nonnull]
>   435 |     m_xVersionBox->set_size_request(m_xVersionBox->get_approximate_digit_width() * 90,
>       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   436 |                                     m_xVersionBox->get_height_rows(15));
>       |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

)

Change-Id: I2720d6bc49af717951a0af6a262fb013a27e09df
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/108886
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>