external/cairo: Silence some -Wincompatible-pointer-types
...as seen at least when doing an Emscripten build against emsdk 4.0.15 (which
uses a Clang with
<https://github.com/llvm/llvm-project/commit/b24769855d97697de08e2296a548c033f193caf4>
"[Clang] [Sema] Make `-Wincompatible-pointer-types` an error by default
(#157364)"),

> cairo-image-source.c:89:33: error: incompatible pointer types passing 'pixman_image_t **' (aka 'union pixman_image **') to parameter of type 'void **' [-Wincompatible-pointer-types]
>    89 |         if (_cairo_atomic_ptr_cmpxchg (&__pixman_transparent_image,
>       |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./cairo-atomic-private.h:143:34: note: expanded from macro '_cairo_atomic_ptr_cmpxchg'
>   143 |   _cairo_atomic_ptr_cmpxchg_impl(x, oldv, newv)
>       |                                  ^
> ./cairo-atomic-private.h:136:39: note: passing argument to parameter 'x' here
>   136 | _cairo_atomic_ptr_cmpxchg_impl(void **x, void *oldv, void *newv)
>       |                                       ^
> cairo-image-source.c:121:33: error: incompatible pointer types passing 'pixman_image_t **' (aka 'union pixman_image **') to parameter of type 'void **' [-Wincompatible-pointer-types]
>   121 |         if (_cairo_atomic_ptr_cmpxchg (&__pixman_black_image,
>       |                                        ^~~~~~~~~~~~~~~~~~~~~
> ./cairo-atomic-private.h:143:34: note: expanded from macro '_cairo_atomic_ptr_cmpxchg'
>   143 |   _cairo_atomic_ptr_cmpxchg_impl(x, oldv, newv)
>       |                                  ^
> ./cairo-atomic-private.h:136:39: note: passing argument to parameter 'x' here
>   136 | _cairo_atomic_ptr_cmpxchg_impl(void **x, void *oldv, void *newv)
>       |                                       ^
> cairo-image-source.c:153:33: error: incompatible pointer types passing 'pixman_image_t **' (aka 'union pixman_image **') to parameter of type 'void **' [-Wincompatible-pointer-types]
>   153 |         if (_cairo_atomic_ptr_cmpxchg (&__pixman_white_image,
>       |                                        ^~~~~~~~~~~~~~~~~~~~~
> ./cairo-atomic-private.h:143:34: note: expanded from macro '_cairo_atomic_ptr_cmpxchg'
>   143 |   _cairo_atomic_ptr_cmpxchg_impl(x, oldv, newv)
>       |                                  ^
> ./cairo-atomic-private.h:136:39: note: passing argument to parameter 'x' here
>   136 | _cairo_atomic_ptr_cmpxchg_impl(void **x, void *oldv, void *newv)
>       |                                       ^

Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191368
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Tested-by: Jenkins
(cherry picked from commit 4ad6309f5b7460a8e1c558d68a94c4515ec1b73f)
Conflicts:
	external/cairo/UnpackedTarball_cairo.mk

Change-Id: Ie7e6424350b60e61db2cc13c17fa14b1cc0e9944
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191369
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>