Fix bashism in configure tests for curl and libcmis
When /bin/sh is dash:

./configure: 35165: test: yes: unexpected operator
checking whether to enable breakpad... no
./configure: 35218: test: yes: unexpected operator

Causing HAVE_FEATURE_CURL not to be set to 1 and build to fail:

sw/source/ui/misc/translatelangselect.cxx:160:24: error: no member named 'TranslateDocumentCancellable' in namespace 'SwTranslateHelper'
  160 |     SwTranslateHelper::TranslateDocumentCancellable(m_rWrtSh, aConfig, m_bCancelTranslation);
      |     ~~~~~~~~~~~~~~~~~~~^

Introduced in:

5bf7c2fa5794 ("Fix --disable-curl build", 2023-09-14)

Change-Id: Ifbc4bc1a7cde86101ff13b05ec7cee6836798605
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/167831
Tested-by: Ilmari Lauhakangas <ilmari.lauhakangas@libreoffice.org>
Reviewed-by: Ilmari Lauhakangas <ilmari.lauhakangas@libreoffice.org>
Tested-by: Jenkins