Update patch set 14
Patch Set 14: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/58561/ : FAILURE

error: unused variable "option_suppressLicense" [-Werror,-Wunused-variable] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/cui/source/dialogs/AdditionsDialog.cxx ( https://ci.libreoffice.org/job/gerrit_mac/63292/ )

the build failed because of an issue with the bot itself, not with the code.
The Bot failed to checkout the source ( https://ci.libreoffice.org/job/gerrit_mac/63292/ )

Patch-set: 14
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1