Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/5694/ : FAILURE

error: FieldDecl, use "bool" instead of "sal_Bool" [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/reportdesign/source/filter/xml/xmlTable.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/5643/ )

clang plugin salbool did trigger. FieldDecl, use "bool" instead of "sal_Bool" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/5643/ )

Patch-set: 6
Label: Verified=-1