Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://cpci.cbg.collabora.co.uk:8080/job/Gerrit%20for%20cp-6.0/272/ : FAILURE

Visual studio complained about error C2429: language feature "nested-namespace-definition" requires compiler flag "/std:c++latest" in file C:\lo\jenkins\workspace\gerrit_windows_cp-6.0_32bit\include\vcl/filter/PDFiumLibrary.hxx(22) ( https://cpci.cbg.collabora.co.uk:8080/job/gerrit_windows_cp-6.0_32bit/116/ )

Patch-set: 1
Tag: autogenerated:jenkins-gerrit-trigger
Reviewer: Gerrit User 1002181 <1002181@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1