Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/41096/ : FAILURE

Visual studio complained about error C2440: "<function-style-cast>": cannot convert from "o3tl::is_typed_flags<SfxSlotMode,20891436>::Wrap" to "sal_Int32" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/framework/source/dispatch/dispatchinformationprovider.cxx(78) ( https://ci.libreoffice.org/job/gerrit_windows/47616/ )

Patch-set: 7
Label: Verified=-1