gtk3: alpha rects using cairo
(cherry picked from commit 65d31de78dd3f5055102122e60b7261f8b170df5)

Change-Id: I7fdcd6336fdc7ea8149c385a177db91ffaa61c94

stinking ancient cairo impls

Change-Id: I35e826bc78556a912358dfad2fac7c45ca35bfd1
(cherry picked from commit a7a95af74badcb745bb1c86c7f9a21444ca12c77)

WaE: -Werror=unused-parameter on Android

Change-Id: Ie5a4015794350a513c39a60ae650f4626d92e1b8
(cherry picked from commit b28a63728ac081b3cc94c76d0bac4a573087ca5e)

error: missing binary operator before token '('

Change-Id: Ieafb13245a11347cbda8a33e49ad618bf85d8a89
(cherry picked from commit 3928a1514c9202a52d698570022c197ecc8703eb)

WaE: error: 'CAIRO_VERSION' is not defined

Change-Id: I9e4f0d0af541226089a6295962a91ca09debb418
(cherry picked from commit b51fe01f7c8853c353401001bdd417b9ed27fb87)

try harder to hide this from android tinderbox

Change-Id: I586fea9f1570b68ed789da8b10a3b46216c42969
(cherry picked from commit f1761903cdafd12d4b33d4e8733971a3d9ad8a10)