gtk3: error: 'GTK_STATE_FLAG_CHECKED' was not declared in this scope
Seen with gtk3-3.10.9.

Change-Id: I0fc3f6187e270bb13d110bee7c817b5f48d4ce50
(cherry picked from commit a38f8c2228f15611136ad6a4b69d77e167a2b781)