Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/60381/ : FAILURE

likely caused by leftovers that linger around from an aborted build ( https://ci.libreoffice.org/job/gerrit_windows/69050/ )

Visual studio complained about error C2065: "PACKAGE_VERSION": undeclared identifier in file assuan.c(286) ( https://ci.libreoffice.org/job/gerrit_windows/69050/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1