Fix external/gpgmepp Linux RPATH
In other external projects using libtool, we fix that by patching configure,
resetting hardcode_libdir_flag_spec[_CXX] at the end of the linux*) case block
that sets the Linux-specific value.  But here we run autoreconf in
ExternalProject_libassuan, so that patch in configure would be overwritten.  The
relevant code in configure comes from autoconf boilerplate, so we cannot just do
the same patch in configure.ac.  But we can reset hardcode_libdir_flag_spec
sufficiently late in configure.ac so that things still work as intended.

At least on Linux, during the build of gpgmepp, some internal executables like
t-encrypt are built linking against libgpgme.so, which in turn links against the
libassuan and libgpg-error libs, but libtool does not extend LD_RUN_PATH for the
linker to find those.  So a previous version of this change failed with
<https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/462/console>:

[...]
> libtool: link: LD_RUN_PATH="/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/workdir/UnpackedTarball/gpgmepp/src/.libs:/usr/local/lib:" /home/tdf/lode/opt/bin/ccache /home/tdf/lode/opt_private/clang-3.8.0/bin/clang -O0 -fstrict-aliasing -fstrict-overflow -fno-inline -ggdb2 -Wall -Wcast-align -Wshadow -Wstrict-prototypes -Wl,-z -Wl,origin -Wl,-rpath -Wl,\$ORIGIN -o t-encrypt t-encrypt.o  ../../src/.libs/libgpgme.so
[...]
> ../../src/.libs/libgpgme.so: undefined reference to `gpg_err_code_from_syserror@GPG_ERROR_1.0'
> ../../src/.libs/libgpgme.so: undefined reference to `gpgrt_vasprintf@GPG_ERROR_1.0'
> ../../src/.libs/libgpgme.so: undefined reference to `gpg_err_code_to_errno@GPG_ERROR_1.0'
> ../../src/.libs/libgpgme.so: undefined reference to `gpg_err_code_from_errno@GPG_ERROR_1.0'
> ../../src/.libs/libgpgme.so: undefined reference to `gpgrt_free@GPG_ERROR_1.0'
> ../../src/.libs/libgpgme.so: undefined reference to `gpgrt_lock_unlock@GPG_ERROR_1.0'
> ../../src/.libs/libgpgme.so: undefined reference to `gpgrt_snprintf@GPG_ERROR_1.0'
> ../../src/.libs/libgpgme.so: undefined reference to `gpgrt_lock_lock@GPG_ERROR_1.0'
> ../../src/.libs/libgpgme.so: undefined reference to `gpg_err_set_errno@GPG_ERROR_1.0'
> ../../src/.libs/libgpgme.so: undefined reference to `gpg_strsource@GPG_ERROR_1.0'
> ../../src/.libs/libgpgme.so: undefined reference to `gpgrt_asprintf@GPG_ERROR_1.0'
> ../../src/.libs/libgpgme.so: undefined reference to `gpg_strerror_r@GPG_ERROR_1.0'
> ../../src/.libs/libgpgme.so: undefined reference to `gpg_strerror@GPG_ERROR_1.0'
> ../../src/.libs/libgpgme.so: undefined reference to `gpgrt_lock_destroy@GPG_ERROR_1.0'
> clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
> Makefile:640: recipe for target 't-encrypt' failed
[...]

so pass in an LD_RUN_PATH pointing at those libs.  (I think another solution
would be to make ExternalProject_gpgmepp depend on ExternalPackage_libassuan and
ExternalPackage_libgpg-error and pass in LD_RUN_PATH pointing at
instdir/program/.  The pros would be that ExternalProject_gpgmepp would not need
to know the relative paths inside those other projects where the libs are
located (src/.libs/); the cons would be that instdir/program/ contains a variety
of other libs that could thus be accidentally be picked up here.  Yet another
solution could be to build ExternalPackage_gpgmepp with --allow-shlib-undefined
linker option, but then it might miss real undefined-symbol errors.)

Change-Id: I7e37abf802d213347bd80383b7980d85cf0762d4