Drop -I$(dir $(2)) also from gb_*Object__tool_command
...after ecbaf980625a9e7b06abe91c7c70e78f6ad469a7 "-I$(dir $(3)) in
gb_CObject__command_pattern is no longer needed" and
f218f8f6c8c587d2d78679f935093329f145fede "-I$(dir $(3)) in
gb_CObject__command_pattern is no longer needed" had already dropped it from
plain gb_CObject__command_pattern.  (0349c738da5970d9f0fc10d7cf4d7b766ce10e13
"support for compiler rewriters" had created gb_*Object__tool_command at a time
when plain gb_*Object__command still contained those -I arguments, so had
presumably just copied them over without a specific additional need to have them
in the tool_command variants; and ecbaf980625a9e7b06abe91c7c70e78f6ad469a7 and
f218f8f6c8c587d2d78679f935093329f145fede then just failed to also remove them
from the tool_command variants.)

Presence of the -I arguments in the tool_command variants caused e.g. `make
COMPILER_PLUGIN_TOOL=fakebool` to fail with

> sw/source/filter/ww8/ww8par.cxx:97:10: error: replace <...> include form with "..." for inclusion of a source file next to the current source file, sw/source/filter/ww8/../../core/inc/DocumentRedlineManager.hxx [loplugin:includeform]
> #include <../../core/inc/DocumentRedlineManager.hxx>
>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I7ef513507375dcee5d88db53cef58433f7f68e36
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/94867
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>