Update patch set 6
Patch Set 6:

Hi Advait! Thank you for the patch! Please see the comments below. :)

> Patch Set 6: Verified-1
> 
> Build Failed 
> 
> https://ci.libreoffice.org/job/gerrit_master/49643/ : FAILURE
> 
> Visual studio complained about error C2220: warning treated as error - no "object" file generated in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sal/osl/w32/file_url.cxx(533) ( https://ci.libreoffice.org/job/gerrit_windows/57286/ )

To see the details of the build and the warnings & errors: click the build link (https://ci.libreoffice.org/job/gerrit_master/49643/), then click on the "console" icon of the "gerrit_windows" line on the list.

Near the end of the full log, you will see this message:
C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sal/osl/w32/file_url.cxx(533): warning C4100: 'pustrPath': unreferenced formal parameter

Seems like you no longer use the value of "pustrPath" inside the method, so if that's my mistake, use it properly, or if that is no longer needed, you should also remove it from the method signature.

More details about the visual studio warning: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4100?view=vs-2019

Patch-set: 6
Reviewer: Gerrit User 1001264 <1001264@6622c302-437a-49ad-a91d-55ba7dcf1615>