Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_feature/217/ : FAILURE

error ""setChartStyle" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/chart2/source/inc/OPropertySet.hxx:206:27 ( https://ci.libreoffice.org/job/gerrit_mac/37112/ )

error: "setChartStyle" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/chart2/source/inc/OPropertySet.hxx ( https://ci.libreoffice.org/job/gerrit_mac/37112/ )

Patch-set: 1
Label: Verified=-1