Update patch set 11
Patch Set 11: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/6125/ : FAILURE

error: FieldDecl, use "bool" instead of "sal_Bool" [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/inc/fmtfsize.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/6057/ )

clang plugin salbool did trigger. FieldDecl, use "bool" instead of "sal_Bool" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/6057/ )

Patch-set: 11
Label: Verified=-1