Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/59402/ : FAILURE

error "‘com::sun::star::chart2::LegendPosition’ has not been declared" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/chart2/source/view/inc/LegendEntryProvider.hxx:74:13 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/62981/ )

error: ‘com::sun::star::chart2::LegendPosition’ has not been declared in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/chart2/source/view/inc/LegendEntryProvider.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/62981/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1