external/libodfgen: Missing include (uint8_t)
> OdfGenerator.cxx: In function ‘void {anonymous}::appendUnicodeTo(long unsigned int, librevenge::RVNGString&)’:
> OdfGenerator.cxx:58:9: error: ‘uint8_t’ was not declared in this scope
>    58 |         uint8_t first;
>       |         ^~~~~~~

Change-Id: Ibdb34f4e22ad5095dd1062098d441ab5f7ba7c59
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/202712
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>