Update patch set 1
Patch Set 1:

This fails to build on my machine with:

In file included from /usr/include/c++/8/memory:80,
                 from /libreoffice/core/include/sfx2/basedlgs.hxx:22,
                 from /libreoffice/core/cui/source/factory/cuiexp.cxx:20:
/usr/include/c++/8/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = QrCodeGenDialog]’:
/usr/include/c++/8/bits/unique_ptr.h:274:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = QrCodeGenDialog; _Dp = std::default_delete<QrCodeGenDialog>]’
/libreoffice/core/cui/source/factory/dlgfact.hxx:672:30:   required from here
/usr/include/c++/8/bits/unique_ptr.h:79:16: error: invalid application of ‘sizeof’ to incomplete type ‘QrCodeGenDialog’
  static_assert(sizeof(_Tp)>0,
                ^~~~~~~~~~~

Patch-set: 1
Label: Code-Style=0