Update patch set 7
Patch Set 7:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/86254/ : FAILURE

error: instead of an "rtl::OString" constructed from a "const char *", pass a "std::string_view" [loplugin:stringview] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/extras/txtencexport/txtencexport.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/87616/ )

clang plugin stringview did trigger. instead of an "rtl::OString" constructed from a "const char *", pass a "std::string_view" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/87616/ )

Patch-set: 7
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>