Fix the build
...after abc8ea2da28b17a4a4784830fe74fd2743f8a131 "tdf#165742 Step 2: Create a
ChartType derived class for chartex funnel chart." got merged after
1aa34c45b6622942983c872d9d307d5768b68246 "fold DataSeriesHelper functions into
DataSeries" and thus started to cause

> /Volumes/lode/lode/jenkins/workspace/lo_tb_master_mac_dbg/chart2/source/model/template/FunnelChartTypeTemplate.cxx:151:23: error: no member named 'setPropertyAlsoToAllAttributedDataPoints' in namespace 'chart::DataSeriesHelper'
>     DataSeriesHelper::setPropertyAlsoToAllAttributedDataPoints(xSeries, "BorderStyle",
>     ~~~~~~~~~~~~~~~~~~^
> /Volumes/lode/lode/jenkins/workspace/lo_tb_master_mac_dbg/chart2/source/model/template/FunnelChartTypeTemplate.cxx:161:27: error: no member named 'setPropertyAlsoToAllAttributedDataPoints' in namespace 'chart::DataSeriesHelper'
>         DataSeriesHelper::setPropertyAlsoToAllAttributedDataPoints(xSeries, "Geometry3D",
>         ~~~~~~~~~~~~~~~~~~^

(<https://ci.libreoffice.org//job/lo_tb_master_mac_dbg/50335/>) etc.

Change-Id: If9ebdc92b00511144ec9ed556aa80b1f49a0399e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/184323
Reviewed-by: Patrick Luby <guibomacdev@gmail.com>
Tested-by: Jenkins
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>