Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/117963/ : FAILURE

error: externally available entity "lcl_TestEmbeddedTextInDecimal" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/qa/unit/subsequent_export_test2.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/116787/ )

clang plugin external did trigger. externally available entity "lcl_TestEmbeddedTextInDecimal" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/116787/ )

Patch-set: 7
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1, 319af780ce74d933aa99e88eca24ca8424bca8a3