Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/45077/ : FAILURE

Visual studio complained about error C3246: "dxcanvas::LinePolyPolygon": cannot inherit from "basegfx::unotools::UnoPolyPolygon" as it has been declared as "final" in file c:\cygwin\home\tdf\lode\jenkins\workspace\gerrit_windows\canvas\source\directx\dx_linepolypolygon.hxx(33) ( https://ci.libreoffice.org/job/gerrit_windows/52227/ )

Patch-set: 1
Label: Verified=-1