Update patch set 1
Patch Set 1:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/70671/ : FAILURE

clang plugin toolslong did trigger. VarDecl, use "tools::Long" instead of "long" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72986/ )

compiler couldn"t find the file »twips.hxx« referenced from /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/inc/swtypes.hxx:27:10 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72986/ )

error: VarDecl, use "tools::Long" instead of "long" [loplugin:toolslong] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/writerperfect/qa/unit/WPXSvStreamTest.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72986/ )

Patch-set: 1