Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/113384/ : FAILURE

Visual studio complained about error C2440: "return": cannot convert from "std::u16string_view" to "rtl::OUString" in file C:/cygwin/home/tdf/jenkins/workspace/gerrit_windows/framework/source/uielement/generictoolbarcontroller.cxx(65) ( https://ci.libreoffice.org/job/gerrit_windows/125616/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1