Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://cpci.cbg.collabora.co.uk:8080/job/Gerrit%20for%20co-22.05/215/ : FAILURE

Visual studio complained about error C2440: "<function-style-cast>": cannot convert from "initializer list" to "oox::xls::Color" in file C:/lo/jenkins/workspace/gerrit_windows_co-22.05_32bit/sc/source/filter/oox/SparklineFragment.cxx(29) ( https://cpci.cbg.collabora.co.uk:8080/job/gerrit_windows_co-22.05_32bit/198/ )

Patch-set: 1
Tag: autogenerated:jenkins-gerrit-trigger
Reviewer: Gerrit User 1002181 <1002181@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000154 \u003c1000154@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}