Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/111723/ : FAILURE

error "‘invert50_bits’ defined but not used [-Werror=unused-variable]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/vcl/inc/unx/x11_cursors/invert50.h:21:22 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/115285/ )

error: expected identifier before numeric constant in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/vcl/inc/fontinstance.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/115285/ )

compiler warning unused-variable treated as error: ‘invert50_bits’ defined but not used in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/vcl/inc/unx/x11_cursors/invert50.h:21:22 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/115285/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000821 \u003c1000821@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}