Update patch set 2
Patch Set 2:

Do you remember the reason for this change?  Seems that it was this change of com.sun.star.script.framework.provider.ClassLoaderFactory.getURLClassLoader(ScriptMetaData)'s return type that broke binary compatibility (presumably causing a NoSuchMethodError at load time) for <http://mail-archives.apache.org/mod_mbox/openoffice-dev/201806.mbox/%3c651c8fee-b467-421c-eae1-a8710f41692c@apache.org%3e> "Just a little side note on the scripting framework ..."

Patch-set: 2
Reviewer: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0