changes to "Replaced deprecated tools/String with OUString in ScMatrix"
Errors during compile:

* sc/source/core/tool/interpr1.cxx: In member function ‘const String& {anonymous}::VectorMatrixAccessor::GetString(SCSIZE) const’:
  sc/source/core/tool/interpr1.cxx:4629:71: error: returning reference to temporary [-Werror]
  * with --enable-werror

* sc/source/core/tool/interpr1.cxx: In function ‘void {anonymous}::lcl_GetLastMatch(SCSIZE&, const {anonymous}::VectorMatrixAccessor&, SCSIZE, bool)’:
  sc/source/core/tool/interpr1.cxx:4724:52: error: ambiguous overload for ‘operator==’ in ‘aStr == (& rMat)->{anonymous}::VectorMatrixAccessor::GetString((rIndex + -1u))’
  sc/source/core/tool/interpr1.cxx:4728:52: error: ambiguous overload for ‘operator==’ in ‘aStr == (& rMat)->{anonymous}::VectorMatrixAccessor::GetString((rIndex + 1u))’

Change-Id: I28eb3d23f4d5c08a30534abdf940597923cbb68c