Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/109208/ : FAILURE

error "instead of an "rtl::OUString" constructed from a "typename std::enable_if_t<ToStringHelper<OUStringConcat<char const[49], OUString>>::allowOUStringConcat && ToStringHelper<char const[30]>::allowOUStringConcat && libreoffice_internal::ConstCharArrayDetector<char const[30], void>::ok, OUStringConcat<OUStringConcat<char const[49], OUString>, char const[30]>>" (aka "rtl::OUStringConcat<rtl::OUStringConcat<char const[49], rtl::OUString>, char const[30]>"), pass a "std::u16string_view" via "rtl::OUStringConcatenation" [loplugin:stringview]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/unotools/VersionConfig.hxx:46:39 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/108866/ )

error: instead of an "rtl::OUString" constructed from a "typename std::enable_if_t<ToStringHelper<OUStringConcat<char const[49], OUString>>::allowOUStringConcat && ToStringHelper<char const[30]>::allowOUStringConcat && libreoffice_internal::ConstCharArrayDetector<char const[30], void>::ok, OUStringConcat<OUStringConcat<char const[49], OUString>, char const[30]>>" (aka "rtl::OUStringConcat<rtl::OUStringConcat<char const[49], rtl::OUString>, char const[30]>"), pass a "std::u16string_view" via "rtl::OUStringConcatenation" [loplugin:stringview] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/unotools/VersionConfig.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/108866/ )

clang plugin getstr did trigger. directly use object of type "rtl::OString" in a call of "operator <<", instead of calling "getStr" first ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/108866/ )

Patch-set: 7
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1