Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/38844/ : FAILURE

error: no need to explicitly init an instance of "std::unique_ptr<ExtensionsTabPage>" with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/cui/source/options/treeopt.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/41873/ )

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "std::unique_ptr<ExtensionsTabPage>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/41873/ )

Patch-set: 6
Label: Verified=-1