Fix gpgmepp build with glibc
posix-io.c: In function '_gpgme_io_spawn':
posix-io.c:492:23: error: void value not ignored as it ought to be
  492 |             while ((i = closefrom (fd)) && errno == EINTR)
      |                       ^
make[1]: *** [Makefile:964: posix-io.lo] Error 1

Change-Id: I0e7abc33200ca7436c72e925447e681fd241c6a7
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/123259
Tested-by: Jenkins
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>
(cherry picked from commit f60214a1ad45f947d063e4cfdbeb86bd819ab87c)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/124470
Reviewed-by: Caolán McNamara <caolanm@redhat.com>