Update patch set 3
Patch Set 3:

I guess that it is this change that causes the below failure in CppunitTest_sc_bugfix_test, at least when building against GCC trunk libstdc++ in debug mode:

> /home/sbergman/gcc/trunk/inst/lib/gcc/x86_64-pc-linux-gnu/10.0.0/../../../../include/c++/10.0.0/debug/safe_iterator.h:174:
> In function:
>     __gnu_debug::_Safe_iterator<std::__detail::_Node_iterator<std::pair<const 
>     rtl::OUString, std::unique_ptr<ScMyStyleRanges, 
>     std::default_delete<ScMyStyleRanges> > >, false, true>, 
>     std::__debug::unordered_map<rtl::OUString, 
>     std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> >, 
>     std::hash< ::rtl::OUString>, std::equal_to<rtl::OUString>, 
>     std::allocator<std::pair<const rtl::OUString, 
>     std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> > 
>     > > >, std::forward_iterator_tag>::_Safe_iterator(const 
>     _Safe_iterator<_Iterator, _Sequence, _Category> &) [_Iterator = 
>     std::__detail::_Node_iterator<std::pair<const rtl::OUString, 
>     std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> > 
>     >, false, true>, _Sequence = std::__debug::unordered_map<rtl::OUString, 
>     std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> >, 
>     std::hash< ::rtl::OUString>, std::equal_to<rtl::OUString>, 
>     std::allocator<std::pair<const rtl::OUString, 
>     std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> > 
>     > > >, _Category = std::forward_iterator_tag]
> 
> Error: attempt to copy-construct an iterator from a singular iterator.
> 
> Objects involved in the operation:
>     iterator "this" @ 0x0x7ffc5a3aea98 {
>       type = std::__detail::_Node_iterator<std::pair<rtl::OUString const, std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> > >, false, true> (mutable iterator);
>       state = singular;
>     }
>     iterator "other" @ 0x0x1885a18 {
>       type = std::__detail::_Node_iterator<std::pair<rtl::OUString const, std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> > >, false, true> (mutable iterator);
>       state = singular;
>       references sequence with type 'std::__debug::unordered_map<rtl::OUString, std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> >, std::hash<rtl::OUString>, std::equal_to<rtl::OUString>, std::allocator<std::pair<rtl::OUString const, std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> > > > >' @ 0x0x1663cc0
>     }
[...]
> Thread 1 (Thread 0x7ff14217e740 (LWP 2620)):
> #0  0x00007ff1421caeb5 in raise () at /lib64/libc.so.6
> #1  0x00007ff1421b5895 in abort () at /lib64/libc.so.6
> #2  0x00007ff1427ae78d in (anonymous namespace)::callSystemHandler(int, siginfo_t*, void*) (signal=6, info=0x7ffc5a3ae0b0, context=0x7ffc5a3adf80) at /home/sbergman/lo2/core/sal/osl/unx/signal.cxx:393
>         act = {
>           __sigaction_handler = {
>             sa_handler = 0x0, 
>             sa_sigaction = 0x0
>           }, 
>           sa_mask = {
>             __val = {0 <repeats 16 times>}
>           }, 
>           sa_flags = 0, 
>           sa_restorer = 0x95793885a026be00
>         }
>         i = 5
> #3  0x00007ff1427ae104 in (anonymous namespace)::signalHandlerFunction(int, siginfo_t*, void*) (signal=6, info=0x7ffc5a3ae0b0, context=0x7ffc5a3adf80) at /home/sbergman/lo2/core/sal/osl/unx/signal.cxx:483
>         Info = {
>           Signal = osl_Signal_AccessViolation, 
>           UserSignal = 6, 
>           UserData = 0x0
>         }
> #4  0x00007ff14236de70 in <signal handler called> () at /lib64/libpthread.so.0
> #5  0x00007ff1421caeb5 in raise () at /lib64/libc.so.6
> #6  0x00007ff1421b5895 in abort () at /lib64/libc.so.6
> #7  0x00007ff1425adc7f in __gnu_debug::_Error_formatter::_M_error() const (this=0x7ff12afda2e8 <__gnu_debug::_Error_formatter::_S_at(char const*, unsigned int, char const*)::__formatter>) at /home/sbergman/gcc/trunk/src/libstdc++-v3/src/c++11/debug.cc:1119
>         go_to_next_line = <optimized out>
>         ctx = {
>           _M_max_length = 78, 
>           _M_column = 1, 
>           _M_first_line = false, 
>           _M_wordwrap = false
>         }
>         __PRETTY_FUNCTION__ = "void __gnu_debug::_Error_formatter::_M_error() const"
>         has_header = <optimized out>
> #8  0x00007ff12a19250e in __gnu_debug::_Safe_iterator<std::__detail::_Node_iterator<std::pair<rtl::OUString const, std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> > >, false, true>, std::__debug::unordered_map<rtl::OUString, std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> >, std::hash<rtl::OUString>, std::equal_to<rtl::OUString>, std::allocator<std::pair<rtl::OUString const, std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> > > > >, std::forward_iterator_tag>::_Safe_iterator(__gnu_debug::_Safe_iterator<std::__detail::_Node_iterator<std::pair<rtl::OUString const, std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> > >, false, true>, std::__debug::unordered_map<rtl::OUString, std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> >, std::hash<rtl::OUString>, std::equal_to<rtl::OUString>, std::allocator<std::pair<rtl::OUString const, std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> > > > >, std::forward_iterator_tag> const&) (this=0x7ffc5a3aea98, __x=invalid iterator) at /home/sbergman/gcc/trunk/inst/include/c++/10.0.0/debug/safe_iterator.h:170
> #9  0x00007ff12a18f0b0 in ScMyStylesImportHelper::AddDefaultRange(ScRange const&) (this=0x1663cc0, rRange=...) at /home/sbergman/lo2/core/sc/source/filter/xml/XMLStylesImportHelper.cxx:258
>         aPrevItr = {
>   <std::__detail::_Node_iterator_base<std::pair<rtl::OUString const, std::unique_ptr<ScMyStyleRanges, std::default_delete<ScMyStyleRanges> > >, true>> = {
>     _M_cur = 0x18f37e0
>   }, <No data fields>}
>         nStartCol = 11
>         nEndCol = 16

Patch-set: 3