Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/39010/ : FAILURE

error ""Activate" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/vcl/wizardmachine.hxx:94:29 ( https://ci.libreoffice.org/job/gerrit_mac/42252/ )

error: "Activate" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/vcl/wizardmachine.hxx ( https://ci.libreoffice.org/job/gerrit_mac/42252/ )

Patch-set: 3
Label: Verified=-1