Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/30250/ : FAILURE

error: unused variable declaration [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sd/source/ui/func/fuolbull.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/32290/ )

clang plugin casttovoid did trigger. unused variable declaration ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/32290/ )

Patch-set: 2
Label: Verified=-1