Fix no-pch Windows build
 C:/lo/core/sw/source/uibase/misc/glosdoc.cxx(452): error C3083: 'FileBase': the symbol to the left of a '::' must be a type
 C:/lo/core/sw/source/uibase/misc/glosdoc.cxx(452): error C2039: 'getSystemPathFromFileURL': is not a member of 'osl'
 C:\lo\core\include\osl/getglobalmutex.hxx(29): note: see declaration of 'osl'
 C:/lo/core/sw/source/uibase/misc/glosdoc.cxx(452): error C3861: 'getSystemPathFromFileURL': identifier not found
 C:/lo/core/sw/source/uibase/misc/glosdoc.cxx(452): error C3083: 'FileBase': the symbol to the left of a '::' must be a type
 C:/lo/core/sw/source/uibase/misc/glosdoc.cxx(452): error C2039: 'E_None': is not a member of 'osl'
 C:\lo\core\include\osl/getglobalmutex.hxx(29): note: see declaration of 'osl'
 C:/lo/core/sw/source/uibase/misc/glosdoc.cxx(452): error C2065: 'E_None': undeclared identifier

Change-Id: I96d48b961522c508a71c99d3046046842b2ad865
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/201535
Tested-by: Jenkins
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>
(cherry picked from commit 251d494c6e7a52e125eb05f3981c778c5c67a6f5)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/201611
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>