Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/102278/ : FAILURE

error ""createViewIndependentPrimitive2DSequence" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /home/tdf/lode/jenkins/workspace/android_x86_64/include/svx/sdr/contact/viewcontactofsdrobj.hxx:50:61 ( https://ci.libreoffice.org/job/gerrit_android_x86_64/12054/ )

error: "createViewIndependentPrimitive2DSequence" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /home/tdf/lode/jenkins/workspace/android_x86_64/include/svx/sdr/contact/viewcontactofsdrobj.hxx ( https://ci.libreoffice.org/job/gerrit_android_x86_64/12054/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000083 \u003c1000083@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}