Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/78358/ : FAILURE

error "replace <...> include form with "..." for inclusion of a source file next to the current source file, /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/source/inc/RegressionCalculationHelper.hxx [loplugin:includeform]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/source/inc/MovingAverageRegressionCurveCalculator.hxx:22:10 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/80269/ )

error: replace <...> include form with "..." for inclusion of a source file next to the current source file, /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/source/inc/RegressionCalculationHelper.hxx [loplugin:includeform] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/source/inc/MovingAverageRegressionCurveCalculator.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/80269/ )

"file" vs <file> clang plugin ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/80269/ )

clang plugin includeform did trigger. replace <...> include form with "..." for inclusion of a source file next to the current source file, /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/source/inc/RegressionCalculationHelper.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/80269/ )

Patch-set: 5
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1