Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/43781/ : FAILURE

error: externally available entity "TmplInsertEntryIntoUI" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/cui/source/customize/cfg.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/47270/ )

clang plugin external did trigger. externally available entity "TmplInsertEntryIntoUI" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/47270/ )

Patch-set: 4
Label: Verified=-1