fix cypress ci failure
failure of

 1) Chart Data Table dialog
        Delete series column:
      AssertionError: Timed out retrying after 10000ms: Too many elements found. Found '5', expected '4'.

since:

commit e71ee2bad6b82c07a075e35e4dbf6dd25c143a51
Date:   2026-05-14 12:10:24 +0200

    jsdialog: don't apply rowheader styling outside ChartDataDialog

which adjusted the change of:

commit 39069feed7a779bedc26f163785d44a268c6caae
Date:   2026-03-14 09:27:37 +0100

    jsdialog: render Chart Data Table dialog with TreeView grid

The intent seems to be to restrict the styling to just #ChartDataDialog,
so make that explicit in the css.

Signed-off-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Change-Id: I9f2b02d4c0cc3f31f9e400efba33c7be8527f679
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/2633
Tested-by: Andras Timar <andras.timar@collabora.com>
Reviewed-by: Andras Timar <andras.timar@collabora.com>