Fix 'make translations' run
Recent commits introduced strings in .ui files without context
which makes 'make translations' fail with:

[build POT] pot.done
Traceback (most recent call last):
  File "/home/gabor/src/core/solenv/bin/uiex", line 30, in <module>
    keyid = entry.msgctxt + '|' + entry.msgid
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Affected commits are:
e74be9ad773c7769c5d8765bb2ac234967e420ec
213a83ce46edf1b81f2285fd59f1d04935760caa

Change-Id: If7afc4bb157a6406cabba141d375e9b0dab5f3de
Reviewed-on: https://gerrit.libreoffice.org/41322
Tested-by: Jenkins <ci@libreoffice.org>
Reviewed-by: Katarina Behrens <Katarina.Behrens@cib.de>