Update patch set 2
Patch Set 2:

Sorry for noticing late, but this breaks a unit test under dbgutil:

/usr/include/c++/4.8/debug/safe_iterator.h:264:
Error: attempt to dereference a past-the-end iterator.

Objects involved in the operation:
    iterator "this" @ 0x0x2b45ebd29ec0 {
      type = 

while running this test:

make CppunitTest_xmlsecurity_signing CPPUNIT_TEST_NAME=testOOXMLDescription

Patch-set: 2