fix "incomplete type" type in skia build
seen by ohallot on a Kubuntu system
(gcc version 12.2.0 kubuntu 23.4)

/usr/include/c++/12/bits/unique_ptr.h:396:17:   required from
‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = SkImageGenerator;
_Dp = std::default_delete<SkImageGenerator>]’
/mnt/bigfast/git/lom/workdir/UnpackedTarball/skia/src/ports/SkImageGenerator_none.cpp:14:12:
required from here
/usr/include/c++/12/bits/unique_ptr.h:93:23: error: invalid application
of ‘sizeof’ to incomplete type ‘SkImageGenerator’
   93 |         static_assert(sizeof(_Tp)>0,
      |                       ^~~~~~~~~~~

Change-Id: I172bfd1aa063de2c283c7205637de58c47dc73fb
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/154386
Tested-by: Jenkins
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>