Update patch set 3
Patch Set 3:

> Patch Set 3: Verified-1
> 
> Build Failed 
> 
> https://ci.libreoffice.org/job/gerrit_master/52498/ : FAILURE
> 
> error: no member named "get_ptr" in "std::optional<int>" in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/oox/source/drawingml/diagram/diagramlayoutatoms.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/55745/ )

so this change is apparently no longer relevant for master after <https://gerrit.libreoffice.org/plugins/gitiles/core/+/9ad252b2e79576119c2d733a1a45fdd9e9f83140%5E!/> "Drop o3tl::optional wrapper"

Patch-set: 3