Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/111620/ : FAILURE

error "class "SparklineData" was previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Werror,-Wmismatched-tags]" triggered in included file /Users/brettcornwall/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sc/source/ui/inc/undo/UndoInsertSparkline.hxx:20:1 ( https://ci.libreoffice.org/job/gerrit_mac/116822/ )

error: class "SparklineData" was previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Werror,-Wmismatched-tags] in file /Users/brettcornwall/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sc/source/ui/inc/undo/UndoInsertSparkline.hxx ( https://ci.libreoffice.org/job/gerrit_mac/116822/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1