Fix --enable-mergelibs=more --enable-sal-log build
...after 621e16205363c1eea0be57017997396dee63df4b "add UNLESS_MERGELIBS_MORE and
use to reduce symbol visibility" caused

> vcl/source/opengl/x11/context.cxx:118: error: undefined reference to 'OpenGLHelper::debugMsgStream(std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> > const&)'
> vcl/source/opengl/x11/context.cxx:270: error: undefined reference to 'OpenGLHelper::debugMsgStream(std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> > const&)'
> vcl/source/opengl/x11/context.cxx:370: error: undefined reference to 'OpenGLHelper::debugMsgStream(std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> > const&)'
> vcl/source/opengl/x11/context.cxx:251: error: undefined reference to 'OpenGLHelper::debugMsgStream(std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> > const&)'
> collect2: error: ld returned 1 exit status
> make[1]: *** [vcl/Library_vclplug_gen.mk:20: instdir/program/libvclplug_genlo.so] Error 1

Change-Id: If27b1ffaad7b40dd3baffa8b3a33b1cc3a8e7153
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/164314
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>