Avoid unhelpful -Werror=stringop-truncation
...emitted at least by recent GCC 11 trunk (even with --disable-optimized, where
optimization level traditionally has some impact on what warnings of this kind
are emitted exactly):

> tools/source/misc/json_writer.cxx: In member function ‘tools::ScopedJsonWriterNode tools::JsonWriter::startNode(const char*)’:
> tools/source/misc/json_writer.cxx:42:12: error: ‘char* strncpy(char*, const char*, size_t)’ output truncated before terminating nul copying 5 bytes from a string of the same length [-Werror=stringop-truncation]
>    42 |     strncpy(mPos, "\": { ", 5);
>       |     ~~~~~~~^~~~~~~~~~~~~~~~~~~

etc.

Change-Id: Id96964b178b61879cf2373c5b418f5c9df4a226f
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/96593
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>
Reviewed-by: Justin Luth <justin_luth@sil.org>
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
Tested-by: Jenkins
(cherry picked from commit de32eb539bbcf291f9968ae12696e1317fdb855d)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/96749
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Aron Budea <aron.budea@collabora.com>