Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/17894/ : FAILURE

error: in call of "rtl::OUString::operator+=", replace "OUString" constructed from a "sal_Unicode" with an "OUStringLiteral1" [loplugin:stringconstant] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/cui/source/options/optjava.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/18543/ )

use default type instead of indirection ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/18543/ )

clang plugin stringconstant did trigger. in call of "rtl::OUString::operator+=", replace "OUString" constructed from a "sal_Unicode" with an "OUStringLiteral1" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/18543/ )

Patch-set: 1
Label: Verified=-1