boost: suppress GCC6 -Wplacement-new=
function_base.hpp line 308
error: placement new constructing an object of type "boost::..." and
size ‘16’ in a region of type ‘char’ and size ‘1’

Change-Id: If905d56bd21dd30a957b50fa3d5eed3a63899d62
Reviewed-on: https://gerrit.libreoffice.org/26769
Tested-by: Jenkins <ci@libreoffice.org>
Reviewed-by: Caolán McNamara <caolanm@redhat.com>
Tested-by: Caolán McNamara <caolanm@redhat.com>
(cherry picked from commit 0a15048b075a9a610ce7b660dabd3b723d489a6a)