Fix staticsalhack
...after b6feccc9a2154336ff4a83fcc62def322cfcbe84 "Replace dtoa with fast_float
for faster string-to-float parsing",

> In file included from jurt/source/pipe/staticsalhack.cxx:67:
> sal/rtl/math.cxx:38:10: fatal error: 'fast_float/fast_float.h' file not found
>    38 | #include <fast_float/fast_float.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I473f19180dfa8eb42b86a724af09718000dadb14
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191305
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Tested-by: Jenkins
(cherry picked from commit acc85023fd2c296b096567d0b9e73a486efe4d4d)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/194703
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>