Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/77309/ : FAILURE

Visual studio complained about error C2440: "static_cast": cannot convert from "SdrObjectUniquePtr" to "SdrPathObj *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/svx/qa/unit/customshapes.cxx(352) ( https://ci.libreoffice.org/job/gerrit_windows/87501/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1