gla11y: only set the ld path when lxml is bundled
In a non-debug build a system python with its own lxml found the
bundled libpython3.14.so.1.0 in instdir and failed with:

    Fatal Python error: Failed to import encodings module
    ModuleNotFoundError: No module named 'encodings'
    make[1]: *** [solenv/gbuild/UIConfig.mk:157: workdir/UIConfig/cui.a11yerrors] Error 1

same problem as:

commit 190f81e34d918da289310a90416f9b6b7be7295f
Date:   Mon Mar 23 11:32:36 2020 +0100

    configure,gbuild: gla11y fails on Fedora 31

Signed-off-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Change-Id: I645fdf175e0839a2e8c5c7da914c0af17e859973
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/13771
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>