Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/118879/ : FAILURE

build likely got stuck and was aborted due to not producing any output to the log ( https://ci.libreoffice.org/job/gerrit_windows/131596/ )

Visual studio complained about error C2220: the following warning is treated as an error in file C:/cygwin/home/tdf/jenkins/workspace/gerrit_windows/desktop/source/deployment/manager/dp_extensionmanager.cxx(299) ( https://ci.libreoffice.org/job/gerrit_windows/131596/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1, 393375a2905201cb97feb5c7ad535082d4175f21