checklistmenu needs dockwin.hxx instead of floatwin.hxx
following https://cgit.freedesktop.org/libreoffice/core/commit/?id=a16e6122dc62f545df90b9ea4d1f4723c46336b6
author	Caolán McNamara <caolanm@redhat.com>	2020-05-28 15:24:29 +0100
committer	Caolán McNamara <caolanm@redhat.com>	2020-06-12 20:03:54 +0200
commit	a16e6122dc62f545df90b9ea4d1f4723c46336b6 (patch)
tree	b6dfbe06f36d715292fe88821f33f141645b1ad2
parent	a5b181df04e4688256bda19e1bece7bf9fd3fa02 (diff)
weld checklistmenu
rework the "menu" to be a treeview using hover selection instead of
a custom set of widgetry, and drop the newly unused custom a11y code

See TB Linux-rpm_deb-x86_64_86-TDF
44146         /tinderbox/buildslave/build/workdir/CxxObject/sc/source/ui/cctrl/checklistmenu.o: In function `ScCheckListMenuControl::EndPopupMode()´:
44147         /tinderbox/buildslave/source/libo-master/sc/source/ui/cctrl/checklistmenu.cxx:400: undefined reference to `DockingManager::EndPopupMode(vcl::Window const*)´
44148         /tinderbox/buildslave/build/workdir/CxxObject/sc/source/ui/cctrl/checklistmenu.o: In function `ScCheckListMenuControl::StartPopupMode(tools::Rectangle const&, FloatWinPopupFlags)´:
44149         /tinderbox/buildslave/source/libo-master/sc/source/ui/cctrl/checklistmenu.cxx:408: undefined reference to `DockingManager::SetPopupModeEndHdl(vcl::Window const*, Link<FloatingWindow*, void> const&)´
44150         /tinderbox/buildslave/source/libo-master/sc/source/ui/cctrl/checklistmenu.cxx:409: undefined reference to `DockingManager::StartPopupMode(vcl::Window const*, tools::Rectangle const&, FloatWinPopupFlags)´
44151         /tinderbox/buildslave/build/workdir/CxxObject/sc/source/ui/cctrl/checklistmenu.o: In function `ScCheckListMenuControl::handleMenuTimeout(ScCheckListMenuControl::SubMenuItemData const*)´:
44152         /tinderbox/buildslave/source/libo-master/sc/source/ui/cctrl/checklistmenu.cxx:239: undefined reference to `DockingManager::EndPopupMode(vcl::Window const*)´
44153         /tinderbox/buildslave/source/libo-master/sc/source/ui/cctrl/checklistmenu.cxx:225: undefined reference to `DockingManager::EndPopupMode(vcl::Window const*)´
44154 NEXT    collect2: error: ld returned 1 exit status
44155 NEXT    make[1]: *** [/tinderbox/buildslave/source/libo-master/sc/Library_sc.mk:10: /tinderbox/buildslave/build/instdir/program/libsclo.so] Error 1
44156 NEXT    make: *** [Makefile:282: build] Error 2

Change-Id: Ie4690c4ab5023a1ae43fe9fd1d8e37aad2b9a33b