Fix Windows build after commit 2a97d38fbf89ef6f17452fa9d93c2d6fb062f233
> C:/lo/core/sfx2/source/doc/objserv.cxx(561): error C2429: attribute
  'fallthrough' requires compiler flag '/std:c++17'

Change-Id: Id5924138ab75b87b82c205340d1e699426e04773