Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/109130/ : FAILURE

likely caused by leftovers that linger around from an aborted build ( https://ci.libreoffice.org/job/gerrit_windows/120971/ )

Visual studio complained about error C2679: binary "<<": no operator found which takes a right-hand operand of type "const T" (or there is no acceptable conversion) in file C:\cygwin\home\tdf\lode\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\cppunit\include\cppunit/tools/StringHelper.h(25) ( https://ci.libreoffice.org/job/gerrit_windows/120971/ )

Patch-set: 6
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1