UBSan needs some more RTTI during CppunitTest_sw_core_unocore now
> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_sw_core_unocore.so
> LinkTarget/CppunitTest/libtest_sw_core_unocore.so: undefined symbol: _ZTI22SwFormatContentControl"

and

> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_sw_core_unocore.so
> workdir/LinkTarget/CppunitTest/libtest_sw_core_unocore.so: undefined symbol: _ZTI16SwContentControl"

presumably since 5da08b21cd23f2e70f5003733b03a7aee7915225 "sw content controls:
add UNO API to insert this with custom props"

Change-Id: I77370f11766456081827257d688490ff6e138cce
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/132447
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>