Update patch set 3
Patch Set 3:

Thank you for committing, and I'm sorry for the late reply. 

#if 0 block around the comment causes an another build error(fatal error C1004: Unexpected End Of File Found).

Build Error message is here.


/opt/lo/bin/make -j 8 -rs -f F:/lo4mas/core/Makefile.gbuild \
	 \
	 \
	 \
	all
/cygdrive/f/lo4mas/core//dictionaries/Module_dictionaries.mk:12: target Dictionary_af should be a l10n target
/cygdrive/f/lo4mas/core//dictionaries/Module_dictionaries.mk:12: target Dictionary_an should be a l10n target
/cygdrive/f/lo4mas/core//dictionaries/Module_dictionaries.mk:12: target Dictionary_ar should be a l10n target
(SNIP)
[build CUT] sal_rtl_oustring
[build CUT] sal_rtl_textenc
[build CUT] sal_rtl_strings
F:/lo4mas/core/i18npool/qa/cppunit/test_breakiterator.cxx(725) : warning C4819: ファイルは、現在のコード ページ (932) で表示できない文字を含んでいます。データの損失を防ぐために、ファイルを Unicode 形式で保存してください。
F:/lo4mas/core/i18npool/qa/cppunit/test_breakiterator.cxx(961) : fatal error C1004: 予期せぬ EOF が検出されました。
[build CUT] sal_rtl_uri
F:/lo4mas/core/solenv/gbuild/LinkTarget.mk:177: recipe for target 'F:/lo4mas/core/workdir/CxxObject/i18npool/qa/cppunit/test_breakiterator.o' failed
make[1]: *** [F:/lo4mas/core/workdir/CxxObject/i18npool/qa/cppunit/test_breakiterator.o] Error 2
make[1]: *** Waiting for unfinished jobs....
Makefile:219: recipe for target 'build' failed
make: *** [build] Error 2

Patch-set: 3