gpgme: upgrade to release 1.18.0
Remove gpgme.git-4b64774b6d13ffa4f59dddf947a97d61bcfa2f2e.patch.1 as it has applied in 1.18.0.

* 0001-cpp-Fix-building-with-C-11.patch.1: fixed error "no matching function for call to object of type "(lambda at importresult.cpp:154:71)"".
* w32-include.patch: add missing #include <string> (for std::string).
* macos-include.patch: add missing #include <algorithm> (for std::any_of).

Change-Id: I45f2ef415d80e6ee848699803e971f154812c9c6
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/143039
Tested-by: Jenkins
Tested-by: Caolán McNamara <caolanm@redhat.com>
Reviewed-by: Caolán McNamara <caolanm@redhat.com>