Only run meson from python when it apparently needs to be
...where "apparently needs to be" is approximated by the meson executable being
named *.py (which, in turn is approximated by some GNU Make $(filter) check).
This follows up on ae24fc8c639b230284f94e837497cd7919f79d21 "harfbuzz: migrate
to meson" and should avoid e.g. issues with --enable-python=fully-internal on
Linux like

> Traceback (most recent call last):
>   File "/home/sberg/lo/core/instdir/program/python-core-3.11.12/lib/importlib/metadata/__init__.py", line 563, in from_name
>     return next(cls.discover(name=name))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> StopIteration
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>   File "/usr/bin/meson", line 33, in <module>
>     sys.exit(load_entry_point('meson==1.7.0', 'console_scripts', 'meson')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/bin/meson", line 22, in importlib_load_entry_point
>     for entry_point in distribution(dist_name).entry_points
>                        ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sberg/lo/core/instdir/program/python-core-3.11.12/lib/importlib/metadata/__init__.py", line 982, in distribution
>     return Distribution.from_name(distribution_name)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sberg/lo/core/instdir/program/python-core-3.11.12/lib/importlib/metadata/__init__.py", line 565, in from_name
>     raise PackageNotFoundError(name)
> importlib.metadata.PackageNotFoundError: No package metadata was found for meson
> make[1]: *** [/home/sberg/lo/core/external/harfbuzz/ExternalProject_harfbuzz.mk:47: /home/sberg/lo/core/workdir/ExternalProject/harfbuzz/build] Error 1

(<https://gerrit.libreoffice.org/c/core/+/183345/22#message-66c17b20610944c79d6d7206a62869ad430c3a60>
"harfbuzz: migrate to meson")

Change-Id: I44da7aebdc35a4be838046f0b065f1b646487156
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/184254
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>