Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/55064/ : FAILURE

Visual studio complained about error C3246: "MetricFieldUIObject": cannot inherit from "SpinFieldUIObject" as it has been declared as "final" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/include\vcl/uitest/uiobject.hxx(391) ( https://ci.libreoffice.org/job/gerrit_windows/63139/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1