Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/70589/ : FAILURE

clang plugin toolslong did trigger. VarDecl, use "tools::Long" instead of "long" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72909/ )

error: VarDecl, use "tools::Long" instead of "long" [loplugin:toolslong] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/writerperfect/qa/unit/WPXSvStreamTest.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72909/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1