Emscripten: Module.uno_scripts are relative to document.baseURI
...so explicitly make them absolute, in case the WorkerGlboalScope used in
runUnoScriptUrl would make them absolute relative to a different base URL.

(See <https://github.com/mdn/content/issues/35568>
"WorkerGlobalScope.importScripts URLs relative to what base URL?" for my
confusion of what base URL should actually be used there.  But at least with an
emsdk that uses recent Emscripten trunk towards 3.1.65, and where meanwhile
worker threads no longer load an soffice.worker.js but instead use some blob:
URL, a

> Module.uno_scripts = ['example.js'];

now failed with

> Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The URL 'example.js' is invalid.

on Chrome 127.)

(cherry-picked from 7d37241dcb7aa20adfa7510323cfd7984ff5e911)

Change-Id: I9f9b43d501a7b5d933c8506debdebe67ff1b5795
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/172325
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
Tested-by: Jenkins