Update patch set 4
Patch Set 4:

The build failed with the following errors:

C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sal/qa/systools/test_comtools.cxx(188): error C2220: warning treated as error - no 'object' file generated
C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sal/qa/systools/test_comtools.cxx(188): warning C4101: 'ex': unreferenced local variable
C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sal/qa/systools/test_comtools.cxx(201): warning C4101: 'ex': unreferenced local variable

I removed the unused "ex" variables, the build should be successful this time.

Patch-set: 4
Reviewer: Gerrit User 1002061 <1002061@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0