Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/14247/ : FAILURE

error: unused parameter name [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/svtools/source/control/ctrlbox.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/14874/ )

clang plugin casttovoid did trigger. unused parameter name ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/14874/ )

Patch-set: 3
Label: Verified=-1