Update patch set 3
Patch Set 3: Code-Review-1

and this one fails with an assertion, again preserving it here before CI log cleansing:

Assertion failed: !pImpl->mpStaticDefaults || typeid(rItem) == typeid(GetDefaultItem(nWhich)), file C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/windows_msc_dbgutil_32/svl/source/items/itempool.cxx, line 617
abort() has been calledAssertion failed: nullptr == mpSchedulerData, file C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/windows_msc_dbgutil_32/vcl/source/app/scheduler.cxx, line 578
abort() has been called
Error: a unit test failed, please do one of:
make CppunitTest_sw_ww8export CPPUNITTRACE=TRUE # which is a shortcut for the following line

Patch-set: 3
Reviewer: Gerrit User 1000006 <1000006@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Code-Review=-1