Confine findAnnotations to HAVE_FEATURE_PDFIUM
Otherwise e.g. Android builds would fail with

> vcl/source/filter/ipdf/pdfread.cxx:231:77: error: no member named 'PDFiumPage' in namespace 'vcl::pdf'
> std::vector<PDFGraphicAnnotation> findAnnotations(std::unique_ptr<vcl::pdf::PDFiumPage>& pPage,
>                                                                   ~~~~~~~~~~^

etc.

Regression apparently introduced with 6d275917944c274a22620c2c19880eb8e94f2558
"extract PDF import for annotations to a separate function".

Change-Id: I364d8d3f30c7eeaa933bfe6aebaf4cad35c20d2b