CppunitTest_sc_shapetest needs some more RTTI in UBSan builds now
...since 02e4f6c44295004f5c7201a7aa2744fd0518ba9d "tdf#134355 custom shapes are
never on layer 'controls' in Calc" and ae2e7a2a7f9fc56f0388b823a6e35111c4005619
"tdf#140252 unit test Controls in Calc are always on layer 'controls'":

> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_sc_shapetest.so
> workdir/LinkTarget/CppunitTest/libtest_sc_shapetest.so: undefined symbol: _ZTI11FuConstruct"

(due to e.g. the derived call to FuConstruct::MouseMove at
sc/qa/unit/scshapetest.cxx:239:17);

> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_sc_shapetest.so
> workdir/LinkTarget/CppunitTest/libtest_sc_shapetest.so: undefined symbol: _ZTI17FuConstUnoControl"

(due to e.g. the static_cast at sc/qa/unit/scshapetest.cxx:232:37);

> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_sc_shapetest.so
> workdir/LinkTarget/CppunitTest/libtest_sc_shapetest.so: undefined symbol: _ZTI18FuConstCustomShape"

(due to e.g. the static_cast at sc/qa/unit/scshapetest.cxx:279:38).

Change-Id: I79a8f5d31647c7b04a3519923cd7fcae58cd8f45
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/111053
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>