Update patch set 1
Patch Set 1:

Thanks a lot Noel for your review.

Since yesterday I keep getting errors like this, so it's impossible to update the patch right now:

gelma@glen:~/dev/prg/libreoffice/libreoffice$ git push origin gr_typos_send:refs/for/master
Counting objects: 228, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (137/137), done.
Writing objects: 100% (228/228), 20.07 KiB | 0 bytes/s, done.
Total 228 (delta 200), reused 102 (delta 87)
remote: Resolving deltas: 100% (200/200)
remote: Counting objects: 228, done
remote: Processing changes: updated: 1, refs: 6, done    
remote: error: internal error while processing changes
To ssh://logerrit/core
 ! [remote rejected] gr_typos_send -> refs/for/master (internal error)
error: failed to push some refs to 'ssh://logerrit/core'

As soon as it works, I let you know.

Thanks a lot,
Andrea

Patch-set: 1
Reviewer: Gerrit User 1000638 <1000638@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0