Remove the HSQLDB and JDBC connectivity drivers
...and all the stuff that thus becomes unused, now that
e31394b005e715a0a2556ee1fa82f4a0a07df874 "loplugin:unusedmethods" started to
make them fail to build with

> engine/connectivity/source/drivers/hsqldb/HConnection.cxx:89:37: error: too many arguments to function call, expected single argument '_rxProxyConnection', have 2 arguments
>    89 |         setDelegation(_xConnection, _rxContext);
>       |         ~~~~~~~~~~~~~               ^~~~~~~~~~
> engine/include/connectivity/ConnectionWrapper.hxx:57:14: note: 'setDelegation' declared here
>    57 |         void setDelegation(css::uno::Reference< css::uno::XAggregation >& _rxProxyConnection);
>       |              ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

and

> engine/connectivity/source/drivers/hsqldb/HTables.cxx:107:53: error: call to non-static member function without an object argument
>   107 |     bool bIsNew = connectivity::sdbcx::ODescriptor::isNew( xObject );
>       |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~

and

> engine/connectivity/source/drivers/jdbc/Timestamp.cxx:107:54: error: no member named 'toTimeStringS' in namespace 'dbtools::DBTypeConversion'; did you mean 'toTimeString'?
>   107 |     OUString sDateStr = ::dbtools::DBTypeConversion::toTimeStringS(_rOut);
>       |                                                      ^~~~~~~~~~~~~
>       |                                                      toTimeString
> engine/include/connectivity/dbconversion.hxx:121:40: note: 'toTimeString' declared here
>   121 |         OOO_DLLPUBLIC_DBTOOLS OUString toTimeString(const css::util::Time& rTime);
>       |                                        ^

etc.

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: Ib6559ec0a464755ac424310424f145a6404ce902
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/5020
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>