libgpg-error: upgrade to 1.51
* external/libgpg-error/w32-build-fixes-6.patch fixes
libgpg-error.lib(libgpg_error_la-spawn-w32.obj) : error LNK2019: unresolved external symbol __imp__AllowSetForegroundWindow@4 referenced in function __gpgrt_process_spawn

Downloaded from https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.51.tar.bz2

Change-Id: I6001d1932d1226c0daa037408523f98a9e719f2d
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/176446
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
(cherry picked from commit 908b85de630fd0d474491c4f2f7402cb39553150)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/176490
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>