Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/77668/ : FAILURE

error "unused parameter "aViewRange" [-Werror,-Wunused-parameter]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/vcl/outdev.hxx:2020:50 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/79618/ )

error: unused parameter "aViewRange" [-Werror,-Wunused-parameter] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/vcl/outdev.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/79618/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1