Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/5816/ : FAILURE

error: FieldDecl, use "bool" instead of "sal_Bool" [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/reportdesign/source/filter/xml/xmlTable.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/5755/ )

clang plugin salbool did trigger. FieldDecl, use "bool" instead of "sal_Bool" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/5755/ )

Patch-set: 7
Label: Verified=-1