Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/53178/ : FAILURE

Visual studio complained about error C2220: the following warning is treated as an error in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/chart2/source/tools/RegressionCurveHelper.cxx(480) ( https://ci.libreoffice.org/job/gerrit_windows/61176/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1