fix unused function: SwapForRTL(widget) only if GTK3.22
Compiling on Ubuntu 16.04 produced this error:
vcl/unx/gtk3/gtk3gtkinst.cxx:1683:10: error:
‘bool {anonymous}::SwapForRTL(GtkWidget*)’
defined but not used [-Werror=unused-function]
     bool SwapForRTL(GtkWidget* pWidget)

Change-Id: I5f6c52a263d560208898d8fa136643d1bc037717