workaround for a strange mingw problem caused by fast string operator+
error: no matching function for call to ‘transform(const com::sun::star::beans::NamedValue*,
const com::sun::star::beans::NamedValue*, com::sun::star::uno::Any*,
<unresolved overloaded function type>)’

Change-Id: I7d38a7ee13497fd11b2cea340e2f800dd78f485f