Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/117216/ : FAILURE

clang plugin external did trigger. externally available entity "pngWrite" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/116090/ )

error: externally available entity "pngWrite" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/filter/png/PngImageWriter.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/116090/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1, 39be87ed8f61c6d4663d2ab3375a158a2a7c80d7
Attention: {"person_ident":"Gerrit User 1003564 \u003c1003564@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}