Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/109950/ : FAILURE

Visual studio complained about error C2440: "static_cast": cannot convert from "SalGraphicsImpl *" to "WinSalGraphicsImplBase *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/vcl/win/gdi/salnativewidgets-luna.cxx(1022) ( https://ci.libreoffice.org/job/gerrit_windows/121975/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1