Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/93134/ : FAILURE

error: in LIBO_INTERNAL_ONLY code, replace literal cast to "sal_Unicode" (aka "char16_t") with a u"..." char16_t character literal [loplugin:salunicodeliteral] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/extras/uiwriter/uiwriter2.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/94053/ )

use default type instead of indirection ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/94053/ )

clang plugin salunicodeliteral did trigger. in LIBO_INTERNAL_ONLY code, replace literal cast to "sal_Unicode" (aka "char16_t") with a u"..." char16_t character literal ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/94053/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1