Work around MSVC bug with "..."_ostr vs. u"..."_ostr
Since 27d1f3ac016d77d3c907cebedca558308f366855 "O[U]String literals (unusable
for now, C++20 only)",
<https://developercommunity.visualstudio.com/t/Using-same-string-literal-suffix-for-cha/10416970>
"Using same string literal suffix for char and char16_t string overloads causes
'no matching overloaded function found'" caused --with-latest-c++ builds to fail
with

> sal/qa/rtl/strings/test_oustring_stringliterals.cxx(432): error C2672: '""_ostr': no matching overloaded function found
> include\rtl/ustring.hxx(3604): note: could be 'rtlunittest::OUString operator ""_ostr(void)'
> include\rtl/string.hxx(2402): note: or       'rtlunittest::OString operator ""_ostr(void)'
> sal/qa/rtl/strings/test_oustring_stringliterals.cxx(432): error C2672: 'CppUnit::assertEquals': no matching overloaded function found
> workdir\UnpackedTarball\cppunit\include\cppunit/TestAssert.h(161): note: could be 'void CppUnit::assertEquals(const T &,const T &,CppUnit::SourceLine,const std::string &)'
> sal/qa/rtl/strings/test_oustring_stringliterals.cxx(432): note: 'void CppUnit::assertEquals(const T &,const T &,CppUnit::SourceLine,const std::string &)': expects 4 arguments - 3 provided

etc.  So help MSVC along by renaming from u"..."_ostr to u"..."_ustr for now.

Change-Id: Iad401f0681ac9326b7c57259c5483263ddfbfd4e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/154634
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>