Update patch set 10
Patch Set 10: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/58129/ : FAILURE

Visual studio complained about error C2440: "default argument": cannot convert from "int" to "int &" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/include\o3tl/safeCoInitUninit.hxx(49) ( https://ci.libreoffice.org/job/gerrit_windows/66315/ )

Patch-set: 10
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1