Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/26742/ : FAILURE

error: externally available entity "GetFlyFromMarked" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/core/frmedt/feshview.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/28520/ )

clang plugin external did trigger. externally available entity "GetFlyFromMarked" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/28520/ )

Patch-set: 3
Label: Verified=-1