Qt5 actually return the selection
This broke my Windows build with interesting error messages:

Qt5AccessibleWidget.cxx(772): error C2440: "=": "sal_Int32 *"
kann nicht in "int *" konvertiert werden

Qt5AccessibleWidget.cxx(772): note: Die Typen, auf die verwiesen
wird, sind nicht verknuepft; die Konvertierung erfordert einen
reinterpret_cast-Operator oder eine Typumwandlung im C- oder
Funktionsformat.

Same for line 774.

So actually return the selection parts depending on the provided
int pointers.

Change-Id: Iffbe4481883450b9dacefa867ba7035861d62cdf