Revert "drawinglayer: improve logging for fonts"
This reverts commit 7732444c5d4e79ae0218932afe85bcc4b56a00a4.

Breaks the build, ("error: use of undeclared identifier "UnitTypeToString" in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/drawinglayer/source/tools/emfpfont.cxx ( https://ci.libreoffice.org/job/gerrit_mac/49472/ )")

Change-Id: I2a67d945413a12736699b15a9fdaa0328503977a