Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/63301/ : FAILURE

likely caused by leftovers that linger around from an aborted build ( https://ci.libreoffice.org/job/gerrit_windows/72290/ )

Visual studio complained about error C4430: missing type specifier - int assumed. Note: C++ does not support default-int in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/sal/osl/all/log.cxx(347) ( https://ci.libreoffice.org/job/gerrit_windows/72290/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1