Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/21423/ : FAILURE

error ""SetDrawingArea" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sw/source/uibase/inc/optload.hxx:129:18 ( https://ci.libreoffice.org/job/gerrit_mac/22479/ )

error: "SetDrawingArea" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sw/source/uibase/inc/optload.hxx ( https://ci.libreoffice.org/job/gerrit_mac/22479/ )

Patch-set: 1
Label: Verified=-1