Missing include
...as reported at
<https://lists.freedesktop.org/archives/libreoffice/2023-January/089788.html>
"boost 1.81 breaks libetonyek and gtv-calc-header-bar.cxx",

> /home/etna/Tmpbuild/libreoffice/libreofficekit/qa/gtktiledviewer/gtv-calc-header-bar.cxx:36:25: error: implicit instantiation of undefined template 'std::vector<(anonymous namespace)::GtvCalcHeaderBarPrivateImpl::Header>'
>     std::vector<Header> m_aHeaders;
>                         ^
> /home/etna/Runtime/BuildSystem/LLVM13WithWASM/bin/../include/c++/v1/iosfwd:251:28: note: template is declared here
> class _LIBCPP_TEMPLATE_VIS vector;
>                            ^

Change-Id: I6cc93195147979a5bf2785faf4bb0e71a9fd4a94
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/145185
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>