Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/119076/ : FAILURE

clang plugin external did trigger. externally available entity "ImplStarSymbolToStarBats" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/117828/ )

error: externally available entity "ImplStarSymbolToStarBats" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/unotools/source/misc/fontcvt.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/117828/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1, c8453db61ca30b41a3c3bdbe95a3df81acfc81bf
Attention: {"person_ident":"Gerrit User 1001339 \u003c1001339@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}