Update patch set 14
Patch Set 14:

> Patch Set 13:
> 
> Hiii
> 
> I am not facing any code related build failures, but my build is failing because of this error :
> 
> templdlg.o : error LNK2019: unresolved external symbol
> mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "C:/build/instdir/program/sfxlo.dll". The system cannot find the file specified.
> 
> However, in the master branch this error does not appear.. Could you please once check if you are getting the same error on your system?

Hii

It is resolved now.. VCL_DLL in StyleList.hxx was causing the linkage break :)

Patch-set: 14