Update patch set 11
Patch Set 11: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/109025/ : FAILURE

clang plugin unnecessaryoverride did trigger. public virtual function just calls public parent ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/108690/ )

error: public virtual function just calls public parent [loplugin:unnecessaryoverride] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/i18npool/qa/cppunit/test_calendar.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/108690/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/108690/ )

the test UITest_search_replace failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/108690/ )

Patch-set: 11
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1