external/nss: sign_libs=0 also on Linux
With 21def6d703ff19190a8d3f10063cca0f195d96af "build nss through its own gyp and
ninja build instead of coreconf", at least my local Clang trunk ASan/UBSan build
(which relies on an LD_LIBRARY_PATH in the environment) started to fail with

> [1082/1083] ACTION nss_sign_shared_libs: shlibsign_8fd0737676bd3e8f49d31783f050fac9a255bd366a7015e6a241ae43bdce09c4
> FAILED: [code=1] /home/sberg/co1/online/engine/workdir/UnpackedTarball/nss/dist/Debug/lib/libfreebl3.chk /home/sberg/co1/online/engine/workdir/UnpackedTarball/nss/dist/Debug/lib/libfreeblpriv3.chk /home/sberg/co1/online/engine/workdir/UnpackedTarball/nss/dist/Debug/lib/libnssdbm3.chk /home/sberg/co1/online/engine/workdir/UnpackedTarball/nss/dist/Debug/lib/libsoftokn3.chk
> cd ../../; /home/sberg/co1/online/engine/instdir/program/python ./coreconf/shlibsign.py /home/sberg/co1/online/engine/workdir/UnpackedTarball/nss/dist/Debug/lib/libfreebl3.so /home/sberg/co1/online/engine/workdir/UnpackedTarball/nss/dist/Debug/lib/libfreeblpriv3.so /home/sberg/co1/online/engine/workdir/UnpackedTarball/nss/dist/Debug/lib/libnssdbm3.so /home/sberg/co1/online/engine/workdir/UnpackedTarball/nss/dist/Debug/lib/libsoftokn3.so
> Traceback (most recent call last):
>   File "/home/sberg/co1/online/engine/workdir/UnpackedTarball/nss/nss/./coreconf/shlibsign.py", line 30, in <module>
>     main()
>     ~~~~^^
>   File "/home/sberg/co1/online/engine/workdir/UnpackedTarball/nss/nss/./coreconf/shlibsign.py", line 14, in main
>     sign(lib_file)
>     ~~~~^^^^^^^^^^
>   File "/home/sberg/co1/online/engine/workdir/UnpackedTarball/nss/nss/./coreconf/shlibsign.py", line 27, in sign
>     subprocess.check_call([os.path.join(bin_path, 'shlibsign'), '-C', '-v', '-i', lib_file], env=env, stdout=dev_null, stderr=dev_null)
>     ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sberg/co1/online/engine/instdir/program/python-core-3.14.5/lib/subprocess.py", line 420, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['/home/sberg/co1/online/engine/workdir/UnpackedTarball/nss/dist/Debug/bin/shlibsign', '-C', '-v', '-i', '/home/sberg/co1/online/engine/workdir/UnpackedTarball/nss/dist/Debug/lib/libfreebl3.so']' returned non-zero exit status 127.
> Exception ignored while finalizing file <_io.FileIO name='/dev/null' mode='wb' closefd=True>:
> ResourceWarning: unclosed file <_io.BufferedWriter name='/dev/null'>
> ninja: build stopped: subcommand failed.
> make[1]: *** [/home/sberg/co1/online/engine/external/nss/ExternalProject_nss.mk:91: /home/sberg/co1/online/engine/workdir/ExternalProject/nss/build] Error 1

because that shlibsign.py does

>         env['LD_LIBRARY_PATH'] = env['DYLD_LIBRARY_PATH'] = ld_lib_path

fully replacing LD_LIBRARY_PATH with its own, so that its execution of
`./dist/Debug/bin/shlibsign -C -v -i ./dist/Debug/lib/libfreebl3.so` would have
failed with "error while loading shared libraries: libclang_rt.asan.so: cannot
open shared object file".

Just like is done for Windows (and was done for Linux before the "build nss
through its own gyp and ninja build instead of coreconf" change), don't sign the
libraries to avoid all of these issues.

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: Ib2f3acbbabc8cd84b8a0ed03e5f603dee2fcf109
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/9810
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>