Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/78666/ : FAILURE

error "virtual function "imp_CreatePeer" has a different return type ("FmXGridPeer *") than the function it overrides (which has return type "rtl::Reference<FmXGridPeer>")" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/dbaccess/source/ui/inc/sbagrid.hxx:86:33 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/80560/ )

error: virtual function "imp_CreatePeer" has a different return type ("FmXGridPeer *") than the function it overrides (which has return type "rtl::Reference<FmXGridPeer>") in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/dbaccess/source/ui/inc/sbagrid.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/80560/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1