Fix build in sd
2597          /home/tdf/lode/jenkins/workspace/lo_tb_master_linux/sd/source/ui/sidebar/SlideBackground.cxx: In member function ‘virtual boost::property_tree::ptree sd::sidebar::SlideBackground::DumpAsPropertyTree()’:
2598  NEXT    /home/tdf/lode/jenkins/workspace/lo_tb_master_linux/sd/source/ui/sidebar/SlideBackground.cxx:234:65: error: return type ‘boost::property_tree::ptree {aka class boost::property_tree::basic_ptree<std::basic_string<char>, std::basic_string<char> >}’ is incomplete
2599           boost::property_tree::ptree SlideBackground::DumpAsPropertyTree()
2600                                                                           ^
2601  NEXT    /home/tdf/lode/jenkins/workspace/lo_tb_master_linux/sd/source/ui/sidebar/SlideBackground.cxx:241:48: error: variable ‘boost::property_tree::ptree aTree’ has initializer but incomplete type
2602               boost::property_tree::ptree aTree(Control::DumpAsPropertyTree());
2603                                                          ^~~~~~~~~~~~~~~~~~
2604  NEXT    /home/tdf/lode/jenkins/workspace/lo_tb_master_linux/sd/source/ui/sidebar/SlideBackground.cxx:241:67: error: invalid use of incomplete type ‘boost::property_tree::ptree {aka class boost::property_tree::basic_ptree<std::basic_string<char>, std::basic_string<char> >}’
2605               boost::property_tree::ptree aTree(Control::DumpAsPropertyTree());
2606                                                                             ^

due to 2d748207d343bf97fac34261cafeaefd9d5fc74f

Change-Id: Ic8cc00fa94e77359c1a51948f6a5dabf55ab9f07