fix cypress: condfmt_spec, drop the ellipsis from various format menu entries
the conditional format menu labels no longer carry it, so the spec times out in ci
looking for text that is not there:

  1) Conditional Format Dialog Tests
       JSDialog conditional formatting:
     AssertionError: Timed out retrying after 60000ms: Expected to find content: 'Highlight cells with...' within the selector: '.ui-combobox-entry.jsdialog.ui-grid-cell > span' but never did.
      at Context.eval (integration_tests/desktop/calc1/condfmt_spec.js:18:24)

since:

commit 4650e5489600864644d271fc9df3aa5da7cf47a4
Date:   Mon Aug 10 15:20:56 2026 +0200

    cool#11179 Remove ellipsis from cond. formatting dropdown menu

the assertions it broke came from:

commit 3ddccdc8ff95cb66bd304b6156dde594f1bf5aac
Date:   Mon Aug 10 14:58:14 2026 +0200

    cool#11181 Fix layout for Data Bar and Color Scale dropdowns

commit d7a00017a5c9059a9680484b81f77a08af7ee544
Date:   Thu Aug 6 14:39:12 2026 +0530

    jsdialog: menubutton: first entry is always pre-selected

each of those passed ci on a base without the others, the problem
only arises when they were all in

Signed-off-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Change-Id: I77d1ea159bb9cd1fb718dfa4e4fa58f78daf0678
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/9162
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>