Add experimental support for Emscripten JSPI
...which I've seen fundamentally working when building with recent emsdk against
recent Qt6 trunk (and including <https://github.com/qt/qtbase/pull/108> "Update
the check for WebAssembly JSPI support") and running on recent Chrome (with JSPI
enabled under <chrome://flags/>)

Reviewed-on: https://gerrit.libreoffice.org/c/core/+/176031
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
(cherry picked from commit f510ce620fba08e6aa8bc40af2e47f0b51caa66d, to avoid

> sc/source/filter/oox/workbookfragment.cxx:333:28: error: 'HAVE_EMSCRIPTEN_JSPI' is not defined, evaluates to 0 [-Werror,-Wundef]
>   333 | #if defined EMSCRIPTEN && !HAVE_EMSCRIPTEN_JSPI
>       |                            ^

after c806d990d88bd6095cffb54ebbd95ea9cf146f33 "Emscripten: Hack to not call
Application::Yield when loading xslt")

Change-Id: I98c11c5ee7e95b135ddc33c95c95752055ecd4c5
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/184137
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
Tested-by: allotropia jenkins <jenkins@allotropia.de>