Replace some uses of OUStringChar with string literals
(At least MSVC++ 14.14, aka Visual Studio 2017 version 15.7, apparently requires
`"\xDFFF"` to be written with a `u` prefix in the concatenated string literal

  u"\xD800" "\U000103FF" "\xDFFF" "A"

to avoid "error C2022: '57343': too big for character", so prefix all the
individual string literals in such concatenations, even if that should be
redundant.)

Change-Id: Ief69e6c7ae71fe2c4c9c56c38fab0bc782ceb82c