Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/116569/ : FAILURE

Visual studio complained about error C2398: Element "1": conversion from "unsigned long" to "tools::Long" requires a narrowing conversion in file C:\cygwin\home\tdf\lode\jenkins\workspace\gerrit_windows\vcl\inc\salgeom.hxx(60) ( https://ci.libreoffice.org/job/gerrit_windows/128846/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1