Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/28890/ : FAILURE

clang plugin selfinit did trigger. referencing a variable during its own initialization is error-prone and thus suspicious ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/30824/ )

error: referencing a variable during its own initialization is error-prone and thus suspicious [loplugin:selfinit] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sd/source/ui/view/sdwindow.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/30824/ )

Patch-set: 5
Label: Verified=-1