Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/40607/ : FAILURE

error "unused function "FieldUnitToString" [-Werror,-Wunused-function]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/tools/fldunit.hxx:50:20 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/43705/ )

error: unused function "FieldUnitToString" [-Werror,-Wunused-function] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/tools/fldunit.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/43705/ )

Patch-set: 1
Label: Verified=-1