Update patch set 1
Patch Set 1:

error: could not apply 678aa52... Change 'Add' to 'Add to Dictionary' in the Dialog also
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

I'll try to rebase the change in a bit.

Patch-set: 1
Reviewer: Gerrit User 1000013 <1000013@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0
Label: Code-Review=0