Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/78135/ : FAILURE

error: no need to explicitly init an instance of "writerfilter::Reference<Stream>::Pointer_t" (aka "SvRef<Reference<writerfilter::Stream> >") with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/writerfilter/source/ooxml/OOXMLDocumentImpl.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/80061/ )

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "writerfilter::Reference<Stream>::Pointer_t" (aka "SvRef<Reference<writerfilter::Stream> >") with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/80061/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1