Update patch set 2
Patch Set 2:

It was for Windows TB:
795           [build CXX] cui/source/tabpages/tppattern.cxx
796   NEXT    C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win64_dbg/cui/source/dialogs/FontFeaturesDialog.cxx(79): error C2672: ´std::min´: no matching overloaded function found
797   NEXT    C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win64_dbg/cui/source/dialogs/FontFeaturesDialog.cxx(81): error C2780: ´_Ty std::min(std::initializer_list<_Elem>)´: expects 1 arguments - 2 provided
798           C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\Include\algorithm(4551): note: see declaration of ´std::min´
799   NEXT    C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win64_dbg/cui/source/dialogs/FontFeaturesDialog.cxx(81): error C2782: ´const _Ty &std::min(const _Ty &,const _Ty &) noexcept(<expr>)´: template parameter ´_Ty´ is ambiguous
800           C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\Include\algorithm(4538): note: see declaration of ´std::min´
801           C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win64_dbg/cui/source/dialogs/FontFeaturesDialog.cxx(81): note: could be ´long´
802           C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win64_dbg/cui/source/dialogs/FontFeaturesDialog.cxx(81): note: or       ´_Ty´
803           with
804           [
805           _Ty=tools::Long
806           ]

Good idea for std::clamp !

Patch-set: 2