Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/56446/ : FAILURE

error: VarDecl, use "bool" instead of "sal_Bool" (aka "unsigned char") [loplugin:fakebool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/toolkit/source/controls/controlmodelcontainerbase.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/59552/ )

clang plugin fakebool did trigger. VarDecl, use "bool" instead of "sal_Bool" (aka "unsigned char") ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/59552/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1