Update patch set 4
Patch Set 4:

bisecting shows that this broke <https://ci.libreoffice.org/job/lo_ubsan/1345/>

> /desktop/source/lib/init.cxx:978:15: runtime error: member call on address 0x613000234800 which does not point to an object of type 'desktop::CallbackFlushHandler'
> 0x613000234800: note: object has a possibly invalid vptr: abs(offset to top) too big
>  f3 13 00 62  17 14 80 46 69 2b 00 00  00 00 00 00 00 00 00 00  00 34 33 4a 69 2b 00 00  05 00 00 00
>               ^~~~~~~~~~~~~~~~~~~~~~~
>               possibly invalid vptr
>     #0 0x2b694a00543e in desktop::CallbackFlushHandler::callback(int, char const*, void*) /desktop/source/lib/init.cxx:978:15
>     #1 0x2b69470a3c85 in SfxViewShell::libreOfficeKitViewCallback(int, char const*) const /sfx2/source/view/viewsh.cxx:1493:9
>     #2 0x2b6946f36fe9 in SfxLokHelper::notifyWindow(SfxViewShell const*, unsigned int, rtl::OUString const&, std::__debug::vector<std::pair<rtl::OString const, rtl::OString const>, std::allocator<std::pair<rtl::OString const, rtl::OString const> > > const&) /sfx2/source/view/lokhelper.cxx:195:16
>     #3 0x2b69470af642 in SfxViewShell::notifyWindow(unsigned int, rtl::OUString const&, std::__debug::vector<std::pair<rtl::OString const, rtl::OString const>, std::allocator<std::pair<rtl::OString const, rtl::OString const> > > const&) const /sfx2/source/view/viewsh.cxx:1988:5
>     #4 0x2b6903ab27ec in vcl::Window::PixelInvalidate(tools::Rectangle const*) /vcl/source/window/paint.cxx:1227:20
>     #5 0x2b6903ab1a9b in vcl::Window::LogicInvalidate(tools::Rectangle const*) /vcl/source/window/paint.cxx:1207:9
>     #6 0x2b69048c0ca4 in vcl::Window::queue_resize(StateChangedType) /vcl/source/window/window2.cxx:1348:13
>     #7 0x2b690413504f in DockingWindow::queue_resize(StateChangedType) /vcl/source/window/dockwin.cxx:1046:18
>     #8 0x2b690496f10f in vcl::Window::StateChanged(StateChangedType) /vcl/source/window/window.cxx:1923:13
>     #9 0x2b690412c52f in DockingWindow::StateChanged(StateChangedType) /vcl/source/window/dockwin.cxx:676:13
>     #10 0x2b6945b936e6 in SfxDockingWindow::StateChanged(StateChangedType) /sfx2/source/dialog/dockwin.cxx:1525:20
>     #11 0x2b690496fd6d in vcl::Window::CompatStateChanged(StateChangedType) /vcl/source/window/window.cxx:3713:5
>     #12 0x2b690495ded6 in vcl::Window::Show(bool, ShowFlags) /vcl/source/window/window.cxx:2183:9
>     #13 0x2b6944fd9f44 in vcl::Window::Hide() /include/vcl/window.hxx:927:50
>     #14 0x2b6944fcaf40 in SfxChildWindow::Hide() /sfx2/source/appl/childwin.cxx:633:18
>     #15 0x2b694532c4a9 in SfxWorkWindow::DeleteControllers_Impl() /sfx2/source/appl/workwin.cxx:583:21
>     #16 0x2b6946e8c3f7 in SfxFrame::DoClose_Impl() /sfx2/source/view/frame.cxx:156:26
>     #17 0x2b6946f809fd in SfxBaseController::dispose() /sfx2/source/view/sfxbasecontroller.cxx:983:28
>     #18 0x2b699766863b in (anonymous namespace)::XFrameImpl::setComponent(com::sun::star::uno::Reference<com::sun::star::awt::XWindow> const&, com::sun::star::uno::Reference<com::sun::star::frame::XController> const&) /framework/source/services/frame.cxx:1492:33
>     #19 0x2b6997673860 in (anonymous namespace)::XFrameImpl::close(unsigned char) /framework/source/services/frame.cxx:1699:12
>     #20 0x2b6946e89cbf in SfxFrame::DoClose() /sfx2/source/view/frame.cxx:125:29
>     #21 0x2b6946ff8dd0 in SfxViewFrame::Notify(SfxBroadcaster&, SfxHint const&) /sfx2/source/view/viewfrm.cxx:1489:28
>     #22 0x2b6917305ce0 in SfxBroadcaster::Broadcast(SfxHint const&) /svl/source/notify/SfxBroadcaster.cxx:49:24
>     #23 0x2b69466ae53d in SfxModelListener_Impl::notifyClosing(com::sun::star::lang::EventObject const&) /sfx2/source/doc/objxtor.cxx:170:12
>     #24 0x2b69467cda4f in SfxBaseModel::close(unsigned char) /sfx2/source/doc/sfxbasemodel.cxx:1391:76
>     #25 0x2b695a360fe3 in SwXTextDocument::close(unsigned char) /sw/source/uibase/uno/unotxdoc.cxx:623:19
>     #26 0x2b694aff5dd6 in UnoApiTest::closeDocument(com::sun::star::uno::Reference<com::sun::star::lang::XComponent> const&) /test/source/unoapi_test.cxx:40:17
>     #27 0x2b69244f60b6 in DesktopLOKTest::closeDoc() /desktop/qa/desktop_lib/test_desktop_lib.cxx:276:9
>     #28 0x2b69246c628d in DesktopLOKTest::tearDown() /desktop/qa/desktop_lib/test_desktop_lib.cxx:84:9
>     #29 0x2b69246d17b7 in CppUnit::TestCaller<DesktopLOKTest>::tearDown() /workdir/UnpackedTarball/cppunit/include/cppunit/TestCaller.h:185:15
>     #30 0x2b68e323561a in CppUnit::TestCaseMethodFunctor::operator()() const /workdir/UnpackedTarball/cppunit/src/cppunit/TestCase.cpp:32:5
>     #31 0x2b68fd72c8f7 in (anonymous namespace)::Protector::protect(CppUnit::Functor const&, CppUnit::ProtectorContext const&) /test/source/vclbootstrapprotector.cxx:49:14
>     #32 0x2b68e3206b47 in CppUnit::ProtectorChain::ProtectFunctor::operator()() const /workdir/UnpackedTarball/cppunit/src/cppunit/ProtectorChain.cpp:20:25
>     #33 0x2b68f23388b7 in (anonymous namespace)::Prot::protect(CppUnit::Functor const&, CppUnit::ProtectorContext const&) /unotest/source/cpp/unobootstrapprotector/unobootstrapprotector.cxx:89:12
>     #34 0x2b68e3206b47 in CppUnit::ProtectorChain::ProtectFunctor::operator()() const /workdir/UnpackedTarball/cppunit/src/cppunit/ProtectorChain.cpp:20:25
>     #35 0x2b68ef030448 in (anonymous namespace)::Prot::protect(CppUnit::Functor const&, CppUnit::ProtectorContext const&) /unotest/source/cpp/unoexceptionprotector/unoexceptionprotector.cxx:63:16
>     #36 0x2b68e3206b47 in CppUnit::ProtectorChain::ProtectFunctor::operator()() const /workdir/UnpackedTarball/cppunit/src/cppunit/ProtectorChain.cpp:20:25
>     #37 0x2b68e319de34 in CppUnit::DefaultProtector::protect(CppUnit::Functor const&, CppUnit::ProtectorContext const&) /workdir/UnpackedTarball/cppunit/src/cppunit/DefaultProtector.cpp:15:12
>     #38 0x2b68e3206b47 in CppUnit::ProtectorChain::ProtectFunctor::operator()() const /workdir/UnpackedTarball/cppunit/src/cppunit/ProtectorChain.cpp:20:25
>     #39 0x2b68e320054d in CppUnit::ProtectorChain::protect(CppUnit::Functor const&, CppUnit::ProtectorContext const&) /workdir/UnpackedTarball/cppunit/src/cppunit/ProtectorChain.cpp:86:18
>     #40 0x2b68e3296dc9 in CppUnit::TestResult::protect(CppUnit::Functor const&, CppUnit::Test*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /workdir/UnpackedTarball/cppunit/src/cppunit/TestResult.cpp:182:28
>     #41 0x2b68e323404a in CppUnit::TestCase::run(CppUnit::TestResult*) /workdir/UnpackedTarball/cppunit/src/cppunit/TestCase.cpp:95:11
>     #42 0x2b68e3237ab2 in CppUnit::TestComposite::doRunChildTests(CppUnit::TestResult*) /workdir/UnpackedTarball/cppunit/src/cppunit/TestComposite.cpp:64:30
>     #43 0x2b68e3236caa in CppUnit::TestComposite::run(CppUnit::TestResult*) /workdir/UnpackedTarball/cppunit/src/cppunit/TestComposite.cpp:23:3
>     #44 0x2b68e3237ab2 in CppUnit::TestComposite::doRunChildTests(CppUnit::TestResult*) /workdir/UnpackedTarball/cppunit/src/cppunit/TestComposite.cpp:64:30
>     #45 0x2b68e3236caa in CppUnit::TestComposite::run(CppUnit::TestResult*) /workdir/UnpackedTarball/cppunit/src/cppunit/TestComposite.cpp:23:3
>     #46 0x2b68e32c4abe in CppUnit::TestRunner::WrappingSuite::run(CppUnit::TestResult*) /workdir/UnpackedTarball/cppunit/src/cppunit/TestRunner.cpp:47:27
>     #47 0x2b68e329582e in CppUnit::TestResult::runTest(CppUnit::Test*) /workdir/UnpackedTarball/cppunit/src/cppunit/TestResult.cpp:149:9
>     #48 0x2b68e32c5a1b in CppUnit::TestRunner::run(CppUnit::TestResult&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /workdir/UnpackedTarball/cppunit/src/cppunit/TestRunner.cpp:96:14
>     #49 0x4fd145 in (anonymous namespace)::ProtectedFixtureFunctor::run() const /sal/cppunittester/cppunittester.cxx:316:20
>     #50 0x4f9ba5 in sal_main() /sal/cppunittester/cppunittester.cxx:466:20
>     #51 0x4f8bde in main /sal/cppunittester/cppunittester.cxx:373:1
>     #52 0x2b68e4dda3d4 in __libc_start_main (/lib64/libc.so.6+0x223d4)
>     #53 0x425d44 in _start (/workdir/LinkTarget/Executable/cppunittester+0x425d44)
> 
> SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /desktop/source/lib/init.cxx:978:15 in 
> 
> Error: a unit test failed, please do one of:
> 
> make CppunitTest_desktop_lib CPPUNITTRACE="gdb --args"
>     # for interactive debugging on Linux
> make CppunitTest_desktop_lib VALGRIND=memcheck
>     # for memory checking
> make CppunitTest_desktop_lib DEBUGCPPUNIT=TRUE
>     # for exception catching

Patch-set: 4