The test_lzma_import test no longer works on macOS
...after 347f0ca8e6f1b4fe61410552c6fa49a3e9a11b35 "remove python lzma for
macOS", causing

> ======================================================================
> ERROR: test_lzma_import (testimports.ImportsTest.test_lzma_import)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File ".../pyuno/qa/pytests/testimports.py", line 65, in test_lzma_import
>     import lzma
>   File ".../instdir/CollaboraOffice.app/Contents/Frameworks/LibreOfficePython.framework/Versions/3.12/lib/python3.12/lzma.py", line 27, in <module>
>     from _lzma import *
> ModuleNotFoundError: No module named '_lzma'
>
> ----------------------------------------------------------------------

Change-Id: Ie1ae5842177ff74f30839c8f150afb562186f2d2
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/202143
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Andras Timar <andras.timar@collabora.com>