Upgrade libatomic_ops to latest libatomic_ops-7.6.8.tar.gz
...from <https://github.com/ivmai/libatomic_ops/wiki/Download>.  (The md5sum
given there is 99128f05e3e3f4e0cd39aa23f23bbe0c.)

The old version of external/libatomic_ops failed to build at least when building
a Flatpak for aarch64, see
<https://flathub.org/builds/#/builders/39/builds/702/steps/5/logs/stdio>:

[...]
> Making all in src
> Making all in atomic_ops
> Making all in sysdeps
> In file included from atomic_ops_stack.h:32,
>                  from atomic_ops_malloc.c:20:
> atomic_ops.h:343:4: error: #error Cannot implement AO_compare_and_swap_full on this architecture.
>  #  error Cannot implement AO_compare_and_swap_full on this architecture.
>     ^~~~~
> atomic_ops.c:97:1: error: unknown type name ‘AO_TS_t’; did you mean ‘AO_TS_T’?
>  AO_TS_t AO_locks[AO_HASH_SIZE] = {
>  ^~~~~~~
>  AO_TS_T
[...]

(cf. <https://github.com/flathub/org.libreoffice.LibreOffice/pull/67/commits/
48b22dbabc06f1822df74f755096cf0ea5ba2499> "Upgrade libatomic_ops to latest
libatomic_ops-7.6.8.tar.gz")

Change-Id: Icc040cc47f45f71577995a2ff9c63df97150bdea
Reviewed-on: https://gerrit.libreoffice.org/66983
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit 6584a5d9d1bb3e9b00e529358c989e8485071e36)
Reviewed-on: https://gerrit.libreoffice.org/67006
Reviewed-by: Michael Stahl <Michael.Stahl@cib.de>