Update patch set 4
Patch Set 4:

> Patch Set 3: Verified+1 Code-Review+2
> 
> Jenkins approved - just a formatting change.

And also an "ignore" string at the start of the file:

 /home/vmiklos/git/libreoffice/master-clang/sw/source/core/text/porlay.cxx:1:1: error: unknown type name 'ignore'

Please fix that, it breaks the build. Thanks!

Patch-set: 4
CC: Gerrit User 1000013 <1000013@6622c302-437a-49ad-a91d-55ba7dcf1615>