Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/21729/ : FAILURE

Visual studio complained about error C3490: "mh50Bmp" cannot be modified because it is being accessed through a const object in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/vcl/win/gdi/gdiimpl.cxx(866) ( https://ci.libreoffice.org/job/gerrit_windows/24826/ )

Patch-set: 1
Label: Verified=-1