try to please ubsan
tinderbox Jenkins_Linux_Ubsan fails with:
> /home/tdf/lode/jenkins/workspace/lo_ubsan/svx/source/svdraw
> /svdedxv.cxx:462:48: 
> error: default initialization of an object of const type 
> ´const std::vector<basegfx::B2DRange>´ 
> without a user-provided default constructor
>  const std::vector< basegfx::B2DRange > aEmptySelection;
>                                         ^
>                                                        {}

we have to use value initialization instead of default initialization

Change-Id: I1e5e1266ac76e27afcbe57bc1414fd6ac774c9be