kde4: Add missing include to fix build
Fixes this build failure as reported e.g. by tinderbox [1]:

    In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                     from /usr/include/c++/7/locale:43,
                     from /usr/include/c++/7/iomanip:43,
                     from include/com/sun/star/uno/Any.hxx:27,
                     from workdir/UnoApiHeadersTarget/udkapi/normal/com/sun/star/uno/XInterface.hpp:9,
                     from workdir/UnoApiHeadersTarget/udkapi/normal/com/sun/star/uno/Exception.hpp:8,
                     from workdir/UnoApiHeadersTarget/udkapi/normal/com/sun/star/uno/RuntimeException.hpp:8,
                     from workdir/UnoApiHeadersTarget/udkapi/normal/com/sun/star/lang/XTypeProvider.hpp:8,
                     from include/cppuhelper/compbase.hxx:25,
                     from vcl/unx/kde4/KDE4FilePicker.hxx:22,
                     from vcl/unx/kde4/KDESalInstance.cxx:20:
    /usr/include/c++/7/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = SalVirtualDevice]’:
    /usr/include/c++/7/bits/unique_ptr.h:268:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = SalVirtualDevice; _Dp = std::default_delete<SalVirtualDevice>]’
    .../vcl/unx/kde4/KDESalInstance.cxx:70:107:   required from here
    /usr/include/c++/7/bits/unique_ptr.h:76:22: error: invalid application of ‘sizeof’ to incomplete type ‘SalVirtualDevice’
     static_assert(sizeof(_Tp)>0,

[1] https://tinderbox.libreoffice.org/cgi-bin/gunzip.cgi?tree=libreoffice-6-2&brief-log=1562787602.2042

Change-Id: I1da444b80447ec8896ff9898684ee14fd3933b18
Reviewed-on: https://gerrit.libreoffice.org/75381
Reviewed-by: Michael Stahl <Michael.Stahl@cib.de>
Tested-by: Michael Stahl <Michael.Stahl@cib.de>
(cherry picked from commit e84b9d0d5ac55a2f7a4936ca83a5eea5562f98a8)