When building with clang-cl, nevertheless use MSVC's CXXFLAGS_CXX11 for CLR
...which is built with MSVC after all.  0a99b5a1b7325454fe3d1174d44354888aa22012
"When building with clang-cl on Windows, build CLR code with MSVC" had happened
to get away with passing a bogus -Xclang -std=... (which cl then ignores)
instead of /std:c++17, but nowadays the build fails with things like

> [build CLR] cli_ure/source/climaker/climaker_app.cxx
[...]
> cl : Command line warning D9002 : ignoring unknown option '-Xclang'
> cl : Command line warning D9002 : ignoring unknown option '-std=gnu++2a'
> string_view is only available with C++17 or later.
> include\rtl/stringconcat.hxx(232): error C2429: attribute 'nodiscard' requires compiler flag '/std:c++17'
[...]

This is a bit of a hack, using hardcoded values for now.  Ideally we would
capture MSVC's CXXFLAGS_CXX11 in an additional variable in configure.ac, and do
a subst from CXXFLAGS_CXX11 to MSVC's CXXFLAGS_CXX11 here.

Change-Id: Ifde367c7d1c3db57e75a6ccadc82d534bcb13d0a