Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/38819/ : FAILURE

error: no need to explicitly init an instance of "std::unique_ptr<weld::TreeIter>" with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/cui/source/options/treeopt.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/41844/ )

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "std::unique_ptr<weld::TreeIter>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/41844/ )

Patch-set: 4
Label: Verified=-1