Update patch set 2
Patch Set 2:

The unit test uses a file that defines a *value* of the control to be 00:00:35 (form:value="PT35S" form:current-value="PT35S"), but text to be 12:12. When opens, the shown data is already 00:00:35AM, but text reported is still 12:12. Possibly that's a bug. This can be seen using this Basic code:

    Sub Main
      dp = ThisComponent.DrawPage
      sp = dp.getByIndex(0)
      MsgBox sp.Control.Text
    End Sub

After manual edit of the control, the code starts to show updated text. Saving and reloading the file allows to have the correct text right after the loading; however, the test still fails with a failed assertion like

warn:test:36428:14660:test/source/bootstrapfixture.cxx:220: C:\cygwin64\tmp\lu364285yo6t0.tmp/content.xml[2,5325]:  Error: attribute "form:value" has a bad value: "PT35S" does not satisfy the "time" type
99999999S" form:input-required="false"><form:properties><form:property form:pro
                                 ----^
C:\cygwin64\tmp\lu364285yo6t0.tmp:  Info: Generator: LibreOfficeDev/7.0.0.0.alpha0$Windows_X86_64 LibreOffice_project/66dc976b6f592ae64b8d63dc197e7404ca68b39b

tdf130515.odt:
C:/lo/src/core/test/source/bootstrapfixture.cxx:221:testTdf130515::Import_Export_Import
forced failure
- C:\cygwin64\tmp\lu364285yo6t0.tmp/content.xml[2,5325]:  Error: attribute "form:value" has a bad value: "PT35S" does not satisfy the "time" type
99999999S" form:input-required="false"><form:properties><form:property form:pro
                                 ----^
C:\cygwin64\tmp\lu364285yo6t0.tmp:  Info: Generator: LibreOfficeDev/7.0.0.0.alpha0$Windows_X86_64 LibreOffice_project/66dc976b6f592ae64b8d63dc197e7404ca68b39b


testTdf130515::Import_Export_Import finished in: 2551ms
C:/lo/src/core/test/source/bootstrapfixture.cxx(221) : error : Assertion
Test name: testTdf130515::Import_Export_Import
forced failure
- C:\cygwin64\tmp\lu364285yo6t0.tmp/content.xml[2,5325]:  Error: attribute "form:value" has a bad value: "PT35S" does not satisfy the "time" type
99999999S" form:input-required="false"><form:properties><form:property form:pro
                                 ----^
C:\cygwin64\tmp\lu364285yo6t0.tmp:  Info: Generator: LibreOfficeDev/7.0.0.0.alpha0$Windows_X86_64 LibreOffice_project/66dc976b6f592ae64b8d63dc197e7404ca68b39b






Also trying to open the control's properties interactively (Form->Design Mode; right-click the control -> Control Properties...) gives:

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Error!

Program: C:\lo\src\build\instdir\program\soffice.bin

abort() has been called

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------





(This, of course, needs a debug, or maybe dbgutil build)

tested with Version: 7.0.0.0.alpha0+ (x64)
Build ID: 66dc976b6f592ae64b8d63dc197e7404ca68b39b
CPU threads: 12; OS: Windows 10.0 Build 18363; UI render: Skia/Raster; VCL: win; 
Locale: ru-RU (ru_RU); UI-Language: en-US
Calc: CL

Patch-set: 2
CC: Gerrit User 1000994 <1000994@6622c302-437a-49ad-a91d-55ba7dcf1615>