fix getrandom check in expat's configure
https://github.com/libexpat/libexpat/issues/52

fixes /usr/include/sys/random.h:37:22: error: expected ')'
misdetection of random.h feature, already fixed upstream:
https://github.com/libexpat/libexpat/commit/602e6c78ca750c082b72f8cdf4a38839b312959f

(cherry picked from commit f78ed1ec528604f6db9bdd2a07462c5e99e0ab99)

Change-Id: I65e4aebaa838d2931a60cb34806d87b88861c4d8