Update patch set 2
Patch Set 2:

FTR:

I see a strange new certificate re-appearing at my local Personal cert store: "Issued to: 5008b16217855fa4". This cert is invalid, and makes CppunitTest_xmlsecurity_signing fail.

  ...
  [_RUN_____] testXAdES::TestBody
  warn:vcl:9464:16388:vcl/win/window/salframe.cxx:1086: WinSalFrame::SetIcon(): Could not load large icon !
  warn:vcl:9464:16388:vcl/win/window/salframe.cxx:1087: WinSalFrame::SetIcon(): Could not load small icon !
  warn:xmlsecurity.comp:9464:16388:xmlsecurity/source/helper/xmlsignaturehelper.cxx:601: X509Data do not form a chain: certificate has no issuer but already have
  start of chain: CN=5008b16217855fa4
  Assertion failed: signatureInfo.GetSigningCertificate(), file C:/lo/src/core/xmlsecurity/source/helper/xsecctl.cxx, line 761
  abort() has been calledwarn:legacy.osl:9464:16388:sw/source/core/layout/newfrm.cxx:313: Who didn't deregister?
  warn:legacy.osl:9464:16388:sw/source/core/layout/newfrm.cxx:313: Who didn't deregister?
  warn:legacy.osl:9464:16388:sw/source/core/layout/newfrm.cxx:313: Who didn't deregister?
  warn:svl.items:9464:16388:svl/source/items/style.cxx:50: SfxStyleSheetBase left 1; SfxStyleSheetBasePool left 1
  warn:unotools.config:9464:16388:unotools/source/config/configmgr.cxx:140: ConfigManager not empty
  
  Error: a unit test failed, please do one of:
  make CppunitTest_xmlsecurity_signing CPPUNITTRACE=TRUE # which is a shortcut for the following line
  ...

After manual removal of the cert, the test passes.

The certificate re-appears some time later, and I can't find out what re-creates it; when I run 'make check', it seems to not re-appear (at least when I watch :-)). I even can't be sure its creation is related to LO.

Patch-set: 2
CC: Gerrit User 1000994 <1000994@6622c302-437a-49ad-a91d-55ba7dcf1615>