Silence -Werror,-Wdeprecated-declarations for now
...as seen with qt5 5.13.2-1.fc31

/home/noel/libo2/vcl/qt5/Qt5System.cxx:18:83: error: 'screenCount' is
deprecated: Use QGuiApplication::screens()
[-Werror,-Wdeprecated-declarations]
                                ^
/home/noel/libo2/vcl/qt5/Qt5System.cxx:22:44: error: 'screenGeometry' is
deprecated: Use QGuiApplication::screens()
[-Werror,-Wdeprecated-declarations]
    QRect qRect = QApplication::desktop()->screenGeometry(nScreen);
                                           ^

Change-Id: I73385b56f58284fedf5acbfb914177e06f3512d1
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/86736
Tested-by: Jenkins
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>
(cherry picked from commit ea10986a0939cacd34e8d3e026579c8ce3e6ac6c)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/183436
Tested-by: allotropia jenkins <jenkins@allotropia.de>
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>