Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/30861/ : FAILURE

error "this member function can be declared static [loplugin:staticmethods]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sd/source/ui/inc/BulletAndPositionDlg.hxx:135:15 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/32926/ )

clang plugin external did trigger. externally available entity "SdResId" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/32926/ )

error: externally available entity "SdResId" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sd/source/ui/dlg/BulletAndPositionDlg.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/32926/ )

Patch-set: 7
Label: Verified=-1