Exempt --enable-gui from --enable-fuzz-options
From its description, --disable-gui appears to be experimental, and it causes
failures like

> /usr/bin/ld: /lo/home/tdf/lode/jenkins/workspace/lo_tb_random_config_linux/workdir/CxxObject/vcl/headless/svpgdi.o: in function `dl_cairo_surface_set_device_scale(_cairo_surface*, double, double)':
> /lo/home/tdf/lode/jenkins/workspace/lo_tb_random_config_linux/vcl/headless/svpgdi.cxx:2181: undefined reference to `dlsym'
> /usr/bin/ld: /lo/home/tdf/lode/jenkins/workspace/lo_tb_random_config_linux/workdir/CxxObject/vcl/headless/svpgdi.o: in function `dl_cairo_surface_get_device_scale(_cairo_surface*, double*, double*)':
> /lo/home/tdf/lode/jenkins/workspace/lo_tb_random_config_linux/vcl/headless/svpgdi.cxx:2189: undefined reference to `dlsym'
> /usr/bin/ld: /lo/home/tdf/lode/jenkins/workspace/lo_tb_random_config_linux/workdir/CxxObject/vcl/unx/generic/glyphs/freetype_glyphcache.o: in function `(anonymous namespace)::dlFT_Done_MM_Var(FT_LibraryRec_*, FT_MM_Var_*)':
> /lo/home/tdf/lode/jenkins/workspace/lo_tb_random_config_linux/vcl/unx/generic/glyphs/freetype_glyphcache.cxx:191: undefined reference to `dlsym'
> collect2: error: ld returned 1 exit status

(<https://ci.libreoffice.org//job/lo_tb_random_config_linux/1912/>) that are
probably not worth fixing.

Change-Id: Ia36a8665967601e1c6ef5af3b67d17d25822e339