Fail early when external tarball can't be fetched
...so that the error output is

> fetching libabw-noexist-test.tar.xz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0   153    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (22) The requested URL returned error: 404

rather than a somewhat misleading

> fetching libabw-noexist-test.tar.xz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   153  100   153    0     0   2463      0 --:--:-- --:--:-- --:--:--  2467
> ERROR: expected checksum for libabw-noexist-test.tar.xz is e763a9dc21c3d2667402d66e202e3f8ef4db51b34b79ef41f56cacb86dcd6eed

(see the mailing list sub-thread starting at
<https://lists.freedesktop.org/archives/libreoffice/2024-April/091882.html> "Re:
Uploading external tarballs to <https://dev-www.libreoffice.org/src>?")

Change-Id: I91b7f37601eb69b950024ed3e1b6924ddd039379
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/166692
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>