Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/17139/ : FAILURE

Visual studio complained about error C2440: "const_cast": cannot convert from "const sal_uInt8 *" to "sal_Int8 *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/canvas/source/directx/dx_impltools.cxx(507) ( https://ci.libreoffice.org/job/gerrit_windows/18956/ )

Patch-set: 4
Label: Verified=-1