Update patch set 9
Patch Set 9: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/70260/ : FAILURE

error ""Clear" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sfx2/source/inc/templatesearchview.hxx:55:10 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72583/ )

error: "Clear" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sfx2/source/inc/templatesearchview.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/72583/ )

Patch-set: 9
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1