We need to call decode method considering this:
java.lang.NumberFormatException: For input string: "#FF9966"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:481)
	at java.lang.Integer.parseInt(Integer.java:527)
	at com.sun.star.wizards.form.StyleApplier.getStyleColor(StyleApplier.java:321)

When creating form with wizard

Partly reverts http://cgit.freedesktop.org/libreoffice/core/commit/?id=10e8e10605b9c52bd7fd8a0665dd4d358c733a66

Cherry-picked from c2d8fed349747f526a74cde3fcd36c494fc199b2

Change-Id: Ide85566244e0dce1d30f6369d1f5d8d30534a01a
Reviewed-on: https://gerrit.libreoffice.org/13352
Reviewed-by: Caolán McNamara <caolanm@redhat.com>
Tested-by: Caolán McNamara <caolanm@redhat.com>