Update patch set 2
Patch Set 2:

> Patch Set 1: Verified-1
> 
> Build Failed 
> 
> https://ci.libreoffice.org/job/gerrit_master/53190/ : FAILURE
> 

Building against libxml2/libxslt in the following directory: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib
running install
Checking .pth file support in install/
/Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/workdir/UnpackedTarball/python3/python-inst/@__________________________________________________OOO/LibreOfficePython.framework/Versions/3.7/bin/python3.7 -E -c pass
TEST FAILED: install/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    install/

and your PYTHONPATH environment variable currently contains:

    ''


=>
it looks like building lxml is going to fail if you don't have a system python available at all, hope https://gerrit.libreoffice.org/c/core/+/91748 will fix it

Patch-set: 2
Reviewer: Gerrit User 1000022 <1000022@6622c302-437a-49ad-a91d-55ba7dcf1615>