Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/76336/ : FAILURE

Visual studio complained about error C2440: "<function-style-cast>": cannot convert from "const char [35]" to "com::sun::star::lang::IllegalArgumentException" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/canvas/source/directx/dx_textlayout.cxx(90) ( https://ci.libreoffice.org/job/gerrit_windows/86403/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1