Update patch set 1
Patch Set 1: Code-Review-1

or wait, later on during the build it causes

> [HPX] de/helpcontent2/source/text/schart/04
> /usr/include/c++/8/debug/vector:433:
> Error: attempt to access an element in an empty container.
> 
> Objects involved in the operation:
>     sequence "this" @ 0x0x7ffc84d62a00 {
>       type = std::__debug::vector<rtl::OString, std::allocator<rtl::OString> >;
>     }
> /bin/sh: line 1: 31092 Aborted                 (core dumped) LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}"$I/program:$I/program" $W/LinkTarget/Executable/helpex -l de -mi ${HELPFILES} -m ${POFILES} -o $W/HelpTranslatePartTarget/de/helpcontent2/source/text/schart/04
> make[1]: *** [/home/sbergman/lo-gcc/core/solenv/gbuild/HelpTarget.mk:68: /home/sbergman/lo-gcc/core/workdir/HelpTranslatePartTarget/de/helpcontent2/source/text/schart/04/done] Error 134
> make[1]: *** Waiting for unfinished jobs....

when calling m_sReferences.front() at l10ntools/source/po.cxx:206

Patch-set: 1
Label: Code-Review=-1