Update patch set 22
Patch Set 22:

[CXX] cui/source/dialogs/QrCodeGenDialog.cxx
S=/home/rene/LibreOffice/git/master && I=$S/instdir && W=$S/workdir &&  mkdir -p $W/CxxObject/cui/source/dialogs/ $W/Dep/CxxObject/cui/source/dialogs/ && cd /home/rene/LibreOffice/git/master &&   	  x86_64-linux-gnu-g++ -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_SYSTEM_NO_DEPRECATED -DCPPU_ENV=gcc3 -DLINUX -DNDEBUG -DOSL_DEBUG_LEVEL=0 -DUNIX -DUNX -DX86_64 -D_FORTIFY_SOURCE=2 -D_PTHREADS -D_REENTRANT -Wdate-time  -DCUI_DLLIMPLEMENTATION  -DSYSTEM_LIBXML   -fvisibility=hidden  -Wno-stringop-overflow   -Wall -Wno-missing-braces -Wnon-virtual-dtor -Wendif-labels -Wextra -Wundef -Wunreachable-code -Wunused-macros  -finput-charset=UTF-8 -fmessage-length=0 -fno-common -pipe -fdiagnostics-color=always  -Wdeprecated-copy-dtor -Wduplicated-cond -Wlogical-op -Wshift-overflow=2 -Wunused-const-variable=1 -Wno-cast-function-type -fvisibility-inlines-hidden -fPIC -Wshadow -Woverloaded-virtual -std=c++17 -pthread  -g -O2 -ffile-prefix-map=/home/rene/LibreOffice/git/master=. -fstack-protector-strong -Wformat -Werror=format-security  -DEXCEPTIONS_ON -fexceptions -fno-enforce-eh-specs    -DLIBO_INTERNAL_ONLY  -c $S/cui/source/dialogs/QrCodeGenDialog.cxx -o $W/CxxObject/cui/source/dialogs/QrCodeGenDialog.o -MMD -MT $W/CxxObject/cui/source/dialogs/QrCodeGenDialog.o -MP -MF $W/Dep/CxxObject/cui/source/dialogs/QrCodeGenDialog.d_ -DSYSTEM_ZXING -I$S/external/clew/source/include -I$S/include  -I/usr/lib/jvm/default-java/include -I/usr/lib/jvm/default-java/include/linux -I$S/config_host  -I$S/cui/inc -I$S/cui/source/inc  -I$W/CustomTarget/officecfg/registry -I$W/UnoApiHeadersTarget/udkapi/normal -I$W/UnoApiHeadersTarget/offapi/normal -I/usr/include    -isystem /usr/include/libxml2   -isystem /usr/include/liborcus-0.16      && mv $W/Dep/CxxObject/cui/source/dialogs/QrCodeGenDialog.d_ $W/Dep/CxxObject/cui/source/dialogs/QrCodeGenDialog.d 
/home/rene/LibreOffice/git/master/cui/source/dialogs/QrCodeGenDialog.cxx: In static member function 'static std::string QrCodeGenDialog::ConvertToSVGFormat(ZXing::BitMatrix)':
/home/rene/LibreOffice/git/master/cui/source/dialogs/QrCodeGenDialog.cxx:276:38: error: no match for 'operator=' (operand types are 'ZXing::BitArray' and 'void')
  276 |         row = bitmatrix.getRow(i, row);
      |                                      ^
In file included from /home/rene/LibreOffice/git/master/cui/source/dialogs/QrCodeGenDialog.cxx:29:
/usr/include/ZXing/BitArray.h:137:12: note: candidate: 'ZXing::BitArray& ZXing::BitArray::operator=(ZXing::BitArray&&)'
  137 |  BitArray& operator=(BitArray&& other) noexcept {
      |            ^~~~~~~~
/usr/include/ZXing/BitArray.h:137:33: note:   no known conversion for argument 1 from 'void' to 'ZXing::BitArray&&'
  137 |  BitArray& operator=(BitArray&& other) noexcept {
      |                      ~~~~~~~~~~~^~~~~
/home/rene/LibreOffice/git/master/cui/source/dialogs/QrCodeGenDialog.cxx:281:33: error: invalid operands of types 'const char*' and 'const char [2]' to binary 'operator+'
  281 |                 sbPath << " M"+j+","+i+"h1v1h-1z";
      |                           ~~~~~~^~~~
      |                               |  |
      |                               |  const char [2]
      |                               const char*
/home/rene/LibreOffice/git/master/cui/source/dialogs/QrCodeGenDialog.cxx: In static member function 'static rtl::OUString QrCodeGenDialog::GenerateQRCode(rtl::OUString, tools::Long, int)':
/home/rene/LibreOffice/git/master/cui/source/dialogs/QrCodeGenDialog.cxx:332:57: error: 'ZXing::BitMatrix::BitMatrix(const ZXing::BitMatrix&)' is private within this context
  332 |     std::string SvgString = ConvertToSVGFormat(bitmatrix);
      |                                                         ^
In file included from /home/rene/LibreOffice/git/master/cui/source/inc/QrCodeGenDialog.hxx:13,
                 from /home/rene/LibreOffice/git/master/cui/source/dialogs/QrCodeGenDialog.cxx:10:
/usr/include/ZXing/BitMatrix.h:64:2: note: declared private here
   64 |  BitMatrix(const BitMatrix&) = default;
      |  ^~~~~~~~~
/home/rene/LibreOffice/git/master/cui/source/dialogs/QrCodeGenDialog.cxx:268:66: note:   initializing argument 1 of 'static std::string QrCodeGenDialog::ConvertToSVGFormat(ZXing::BitMatrix)'
  268 | std::string QrCodeGenDialog::ConvertToSVGFormat(ZXing::BitMatrix bitmatrix)
      |                                                 ~~~~~~~~~~~~~~~~~^~~~~~~~~
make[1]: *** [/home/rene/LibreOffice/git/master/solenv/gbuild/LinkTarget.mk:301: /home/rene/LibreOffice/git/master/workdir/CxxObject/cui/source/dialogs/QrCodeGenDialog.o] Error 1
make[1]: Leaving directory '/home/rene/LibreOffice/git/master/cui'
make: *** [Makefile:111: cui] Error 2

Patch-set: 22
Reviewer: Gerrit User 1000130 <1000130@6622c302-437a-49ad-a91d-55ba7dcf1615>