Fix compilerplugins
...after ca7cadeeaecb422611d6a139a510be733927b87d "compilerplugins: make
pathnames absolute before matching them".

For one, adapt to
<https://github.com/llvm/llvm-project/commit/f122484b998d8dbfdaf2e6b9c222438c71e90d86>
"[llvm][support] Move make_absolute from sys::fs to sys::path (#161459)" in
Clang 22.

For another, the original code would cause at least my Clang 24 trunk to fail
with

> fatal error: error in backend: IO sandbox violation

from within loplugin::makePathnameAbsolute when no -working-directory option is
passed in.

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I484a6d5c9438b16d25f651131684e4c2e23d6732
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/8263
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>