native-code.py: stoc implementation is now converted to constructors.
Fixes error: undefined reference to 'stocservices_component_getFactory'

Change-Id: I799fc4d3d0adf201639ed04d3d5457b74cca887b