Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/121155/ : FAILURE

error: use "bool" instead of "gboolean" (aka "int") as return type [loplugin:fakebool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/unx/gtk3/gtkframe.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/121180/ )

clang plugin fakebool did trigger. use "bool" instead of "gboolean" (aka "int") as return type ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/121180/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1, 6fd9eac8ad9a76c91b3eefe1cc28a6284309da2d