upload libodfgen 0.1.3
(cherry picked from commit 9fbc8c06a3cb0df6d1208b8916e0e9f31ca8d025)

error C1083: Cannot open include file: 'config.h': No such file or directory

(cherry picked from commit fcf152ea70164f303861c7edcd83ab0766ad600a)

define all needed macros for libodfgen build on windows

(cherry picked from commit d2d941ceec8c02f2c062558bd573d49d988a0fcc)

Library_odfgen: missing quotes

(cherry picked from commit e4c2340c4e0c048af4c77d17380cccf7f2985b5d)

Change-Id: I4137a362b0f163b82d1212d3833f8037ed4a773f