Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/78568/ : FAILURE

Visual studio complained about error C2440: "static_cast": cannot convert from "Color" to "int" in file C:/cygwin/home/tdf/jenkins/workspace/gerrit_windows/vcl/skia/salbmp.cxx(1234) ( https://ci.libreoffice.org/job/gerrit_windows/88822/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1