Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/74069/ : FAILURE

error "‘SL::a0Table’ defined but not used [-Werror=unused-variable]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sw/source/filter/ww8/ww8scan.hxx:46:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/78235/ )

compiler warning unused-variable treated as error: ‘SL::a0Table’ defined but not used in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sw/source/filter/ww8/ww8scan.hxx:46:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/78235/ )

error: ‘SL::a0Table’ defined but not used [-Werror=unused-variable] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sw/source/filter/ww8/ww8scan.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/78235/ )

Patch-set: 6
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1