Fix UBSan build's RTTI needs
...after 0ed1cb5457a2106316f9d7fda10685360db4bc30 "make more symbols private in
writer" had caused CppunitTest_sw_core_text to fail with

> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_sw_core_text.so
> workdir/LinkTarget/CppunitTest/libtest_sw_core_text.so: undefined symbol: _ZTI12SwLineLayout"

Change-Id: I3f1fb7d6bca2ec726851c39919dddeeabb618542
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/164520
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>