Fix mac build with --with-package-format=dmg
Regression from 7a9f6df7fb83ec23d09cb5744c2c865fa22e7143

ERROR: The following errors occurred in packaging process:

ERROR: Source for LICENSE.html not found!
ERROR: Could not copy  to
 /Users/gerrit/lode/bibisect/core63/workdir/installation/LibreOfficeDev/dmg/
install/en-US_inprogress/LibreOfficeDev_6.3.0.0.alpha0_MacOS_x86-64/LICENSEs/LICENSE.html No such file or directory

Change-Id: I6c51a853238b1ecea64f900c0c60e7a9bb370dc9
Reviewed-on: https://gerrit.libreoffice.org/71417
Tested-by: Jenkins
Reviewed-by: Andras Timar <andras.timar@collabora.com>