Update patch set 8
Patch Set 8: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/116268/ : FAILURE

Visual studio complained about error C2398: Element "1": conversion from "unsigned long" to "tools::Long" requires a narrowing conversion in file C:\cygwin\home\tdf\jenkins\workspace\gerrit_windows\vcl\inc\salgeom.hxx(50) ( https://ci.libreoffice.org/job/gerrit_windows/128547/ )

Patch-set: 8
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1