Update patch set 3
Patch Set 3:

Can I get some help with this compile error?  Is it only complaining because I am defining a struct here instead of in a .hxx?  I only need it in one function, so I thought it best to just localize it.

Jenkins error: /home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Linux/writerfilter/source/dmapper/DomainMapper_Impl.cxx:2456:12: error: ‘*((void*)& aChainStruct +12)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     struct TextFramesForChaining {

Patch-set: 3
Label: Verified=0