Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/53660/ : FAILURE

error ""createPreferredContainer" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/drawinglayer/primitive2d/fillgraphicprimitive2d.hxx:81:47 ( https://ci.libreoffice.org/job/gerrit_mac/58097/ )

error: "createPreferredContainer" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/drawinglayer/primitive2d/fillgraphicprimitive2d.hxx ( https://ci.libreoffice.org/job/gerrit_mac/58097/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1