Update patch set 8
Patch Set 8: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/47566/ : FAILURE

error: externally available entity "lcl_ceil_TwipToMM100" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/writerfilter/source/dmapper/DomainMapperTableManager.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/50957/ )

clang plugin external did trigger. externally available entity "lcl_ceil_TwipToMM100" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/50957/ )

Patch-set: 8
Label: Verified=-1