Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/54975/ : FAILURE

clang plugin unusedvariablecheck did trigger. unused variable "aNativeData" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/58140/ )

error: unused variable "aNativeData" [loplugin:unusedvariablecheck] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/filter/html/htmlreqifreader.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/58140/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1