Fix builds against --enable-dbgutil engine
...which after 8328ce3e297147571d1d85a8a974d5796a3ae34a "Build POCO as a
third-party static lib in the engine" started to fail with

>   CXXLD    coolconvert
> /usr/bin/ld.bfd: tools/Tool.o: in function `Poco::Util::Application::init(int, char**)':
> .../engine/workdir/UnpackedTarball/poco/include/Poco/Util/Application.h:148:(.text._ZN4Poco4Util11Application4initEiPPc[_ZN4Poco4Util11Application4initEiPPc]+0x18f): undefined reference to `Poco::Util::Application::init(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)

etc.

This includes a revert of the earlier, alternate fix
efbd551d499c84327a033a4d053e2d4d9d8c0023 "engine: build the POCO static
libraries without the debug STL ABI", which no longer worked at least for
ASan/UBSan builds after 736fff527b18b830e61983c68626512f7262fd53 "Take Cppunit
from the engine, like POCO, OpenSSL, libpng and zstd", making them fail with something like

> ==1245493==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7bd2ace79890 at pc 0x7fd2af8e00e4 bp 0x7ffc8ea99790 sp 0x7ffc8ea98f60
> WRITE of size 104 at 0x7bd2ace79890 thread T0
>  #0 in __asan_memset at ~/github.com/llvm/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:69:3
>  #1 in CppUnit::TestResult::TestResult(CppUnit::SynchronizedObject::SynchronizationObject*) at engine/workdir/UnpackedTarball/cppunit/src/cppunit/TestResult.cpp:18:7
>  #2 in runClientTests(char const*, bool, bool) at test/test.cpp:214:28
>  #3 in main at test/test.cpp:144:12
[...]
> make[2]: *** [Makefile:7077: all-local] Error 1
> make[2]: Leaving directory 'test'

And this includes a revert of all the gbuild TODOs introduced with
99ad2e6a6f2b389e9dabe25dc21454abc5d79bb1 "From Automake to gbuild: switch the
coolconfig executable" et al:  "When engine is configured with --enable-dbgutil,
Automake runs into a libstdc++ _GLIBCXX_DEBUG mismatch for Poco that had been
addressed with efbd551d499c84327a033a4d053e2d4d9d8c0023 'engine: build the POCO
static libraries without the debug STL ABI' for now.  Keep to that by adding the
corresponding -U_GLIBCXX_DEBUG here too, marked with a 'TODO' to eventually
revert efbd551d499c84327a033a4d053e2d4d9d8c0023 and undo those TODOs, once there
is no remaining uses of Poco in Automake."

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I460a4a299ac249acba99f523875eb91a58bdffdf
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/4098
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>