Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/110663/ : FAILURE

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "tools::SvRef<RTFSprms>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/110217/ )

error: no need to explicitly init an instance of "tools::SvRef<RTFSprms>" with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/writerfilter/source/rtftok/rtfvalue.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/110217/ )

compiler couldn"t find the file »boost/property_tree/ptree_fwd.hpp« referenced from /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/svl/poolitem.hxx:34:10 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/110217/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000880 \u003c1000880@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}