-Werror,-Wuninitialized (apparently new in Clang 12 trunk)
> cppuhelper/source/typemanager.cxx:1571:47: error: field 'entity_' is uninitialized when used here [-Werror,-Wuninitialized]
>         ServiceBasedSingletonDescription_Base(entity_->isPublished()),
>                                               ^

The code was like that ever since it was introduced in
fa559f1c416884015d1d83d0a7ac8803e745d9df "WIP: Experimental new binary type.rdb
format".  Odd that that never caused an issue, but the code appears to at least
never be executed during `make check`.

Change-Id: I19fe78162c7c4a9211c380648595df9aa54bf4d7
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/100554
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit 986bd8b93b35ad7f2760dfe0576860532daa0e42)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/183383
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
Tested-by: allotropia jenkins <jenkins@allotropia.de>