Update patch set 2
Patch Set 2:

why did you push this despite the failures

windows failed because of 
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/windows_msc_dbgutil_32/sal/osl/w32/profile.cxx(357) : error C2220: warning treated as error - no 'object' file generated
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/windows_msc_dbgutil_32/sal/osl/w32/profile.cxx(357) : warning C4002: too many actual parameters for macro 'SAL_INFO'

and mac hung for 10 hours. before being cancelled

the reason of the hung was  malloc after fork before exec
it took 8 days to track that one down... and since you pushed it anyway.. now I'm getting ton of hung build on mac because of it
and plenty of gerrit build are failing for plenty of people on genuinely unrelated cause... which in turn makes people ignore ci even more...

Patch-set: 2
Reviewer: Gerrit User 1000003 <1000003@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0