Update patch set 1
Patch Set 1: Fails; This need some tweaks before it is merged

(1 inline comment)

Fails on make writerfilter.check with:

/home/andy/lo/wd-systemicu/writerfilter/qa/cppunittests/doctok/testdoctok.cxx:24:10: fatal error: 'ucb/ucb.hxx' file not found
#include <ucb/ucb.hxx>

(Also see inline comment for where you seem to have accidentally used a tab whereas the rest of the file uses spaces for indentation.)

Patch-set: 1
Label: Verified=-1
Label: Code-Review=-1