Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/57889/ : FAILURE

error "replace "<<" between string literals with juxtaposition [loplugin:stringconcatliterals]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sd/qa/unit/sdmodeltestbase.hxx:497:13 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/60913/ )

error: externally available entity "SearchContext" is not previously declared in an included file (if it is only used in this translation unit, put it in an unnamed namespace; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/graphic/VectorGraphicSearch.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/60913/ )

clang plugin external did trigger. externally available entity "SearchContext" is not previously declared in an included file (if it is only used in this translation unit, put it in an unnamed namespace; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/60913/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1