Fix some --without-system-jpeg builds
...like <https://ci.libreoffice.org/job/lo_daily_tb_linux_wasm/1026/>,

> wasm-ld: error: /home/tdf/lode/jenkins/workspace/lo_gerrit/tb/build_master/workdir/LinkTarget/StaticLibrary/liblibjpeg-turbo.a(jchuff.o): undefined symbol: jpeg_nbits_table

apparently broken with 451a7e9c435f2c76a718995faf52a59fd3a89127 "libjpeg-turbo:
upgrade to 3.0.4".  But just enabling the missing
workdir/UnpackedTarball/libjpeg-turbo/jpeg_nbits.cxx then caused

> workdir/UnpackedTarball/libjpeg-turbo/jpeg_nbits.c:29:27: error: expected ';' after top level declarator
>    29 | const unsigned char HIDDEN jpeg_nbits_table[65536] = {
>       |                           ^
>       |                           ;

so tweak external/libjpeg-turbo/jconfigint.h a bit more (cf.
workdir/UnpackedTarball/libjpeg-turbo/CMakeLists.txt and
workdir/UnpackedTarball/libjpeg-turbo/jconfigint.h.in).

Change-Id: I3ca1c78b467fb9f1d7584799591dbb8a797320ac
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/183653
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>