Update patch set 7
Patch Set 7:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/98559/ : FAILURE

error: unused class member [loplugin:unusedmember] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/filter/eps/eps.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/99139/ )

clang plugin unusedmember did trigger. unused class member ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/99139/ )

Patch-set: 7