Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/86403/ : FAILURE

the cppunit test CppunitTest_chart2_geometry failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/87750/ )

error: use of undeclared identifier "EE_CHAR_BKGCOLOR" in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sd/qa/unit/export-tests.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/87750/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/87750/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1