UITest_writer_tests7: wait until the child is available (blind fix)
it fails spuriously with

Traceback (most recent call last):
File "sw/qa/uitest/writer_tests7/tdf99711.py", line 43, in test_tdf99711
self.assertEqual(get_state_as_dict(xWriterEdit.getChild('selectwidth'))['Text'], '10.00 mm')
uno.com.sun.star.uno.RuntimeException: Could not find child with id: selectwidth

Change-Id: If80dac67880a1f4200331a7894ba2ecae4504bb2
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/97184
Tested-by: Jenkins
Tested-by: René Engelhard <rene@debian.org>
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
(cherry picked from commit b12d5d818672bcd4e4dfacccb80b23555af4d873)