-Werror,-Wimplicit-fallthrough in vcl
/home/julien/lo/libo_perf/vcl/unx/generic/dtrans/bmp.cxx:123:9: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
  123 |         default:
      |         ^
/home/julien/lo/libo_perf/vcl/unx/generic/dtrans/bmp.cxx:123:9: note: insert '[[fallthrough]];' to silence this warning
  123 |         default:
      |         ^
      |         [[fallthrough]];
/home/julien/lo/libo_perf/vcl/unx/generic/dtrans/bmp.cxx:123:9: note: insert 'break;' to avoid fall-through
  123 |         default:
      |         ^
      |         break;
1 error generated.

when with don't use enable-debug.
So we need #ifdef NDEBUG/#endif to not have "unreachable code" error.

Change-Id: I15b8b2af79d13de0140522d4537f85951b2c55d4
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/207195
Reviewed-by: Julien Nabet <serval2412@yahoo.fr>
Tested-by: Jenkins