Update patch set 6
Patch Set 6:

<https://ci.libreoffice.org//job/lo_tb_master_win/31622/consoleFull#-527421182cbd6b0d4-2729-45f4-a019-828721d0af3e>:

  C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win/package/source/zipapi/Deflater.cxx(72): error C2440: '=': cannot convert from 'const unsigned char *' to 'Bytef *'

Patch-set: 6
CC: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>