error: friend declaration specifying a default argument must be a definition
...(Clang trunk towards 3.4); this appears to be specific to C++11, which added at
the end of 8.3.6/4 [dcl.fct.default]:  "If a friend declaration specifies a default
argument expression, that declaration shall be a definition and shall be the only
declaration of the function or function template in the translation unit."

(cherry picked from commit 39f42b0b03489459540404dd218c38709853c021)

Change-Id: I750c60a2206d7af41322ebb31aa6deca2491067f