Update patch set 5
Patch Set 5:

All Jenkins lo_callgrind_linux builds since <https://ci.libreoffice.org/job/lo_callgrind_linux/4939/>, which introduced this commit, fail with

[...]
> Testing file:///home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/sc/qa/unit/data/functions/statistical/fods/t.dist.rt.fods:
> /home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/sc/qa/unit/functions_test.cxx:43:StatisticalFunctionsTest::testStatisticalFormulasFODS
> double equality assertion failed
> - Expected: 1
> - Actual  : 0
> - Delta   : 1e-14
> 
> StatisticalFunctionsTest::testStatisticalFormulasFODS finished in: 71527ms
> functions_test.cxx:43:Assertion
> Test name: StatisticalFunctionsTest::testStatisticalFormulasFODS
> double equality assertion failed
> - Expected: 1
> - Actual  : 0
> - Delta   : 1e-14
> 
> Failures !!!
> Run: 1   Failure total: 1   Failures: 1   Errors: 0
> 
> Error: a unit test failed, please do one of:
> 
> make CppunitTest_sc_statistical_functions_test CPPUNITTRACE="gdb --args"
>     # for interactive debugging on Linux
> make CppunitTest_sc_statistical_functions_test VALGRIND=memcheck
>     # for memory checking
> make CppunitTest_sc_statistical_functions_test DEBUGCPPUNIT=TRUE
>     # for exception catching

Patch-set: 5
Reviewer: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0