Fix MSVC build
 C:/BuildLO/core/svx/source/table/tablehtmlimporter.cxx(500): error C2220: the following warning is treated as an error
 C:\BuildLO\core\svx\source\table\tablehtmlimporter.cxx(446) : warning C6011: Dereferencing NULL pointer 'mpActDefault'. : Lines: 428, 429, 430, 440, 441, 443, 444, 445, 446

Change-Id: I2af1635a714cba3d27eb6b8b25db9b4c4aeaaade
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/168894
Tested-by: Jenkins
Reviewed-by: Aron Budea <aron.budea@collabora.com>
(cherry picked from commit d474b972ce63407d2a91b56808d6df37164b9cef)