Update patch set 18
Patch Set 18:

Jenkins is failing to build Android with some errors:

clang++: error: linker command failed 
libsfxlo.a(checkreadonlytask.o):checkreadonlytask.cxx:function CheckReadOnlyTask::doWork(): error: undefined reference to 'SfxMedium::CheckCanGetLockfile() const'

This function is defined in docfile.cxx, so I don't know why it's complaining.  I tried reproducing on a small example with both cl.exe and clang++ on Windows and couldn't reproduce.  I also Google'd and didn't find much.  Any idea how to fix this?

Patch-set: 18