fix build: SkiaHelper.cxx missed W on -Wunused-parameter
The error message was
vcl/skia/SkiaHelper.cxx:75:32: error: ‘-unused-parameter’
is not an option that controls warnings [-Werror=pragmas]
   75 | #pragma GCC diagnostic ignored "-unused-parameter"

This fixes commit f8c15850dbfaa46605e1e353ae1f49e69184e8a1
for gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

Change-Id: Iae927e6c794e09cdab2d0fbd30a84a631800c9a6
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/154247
Tested-by: Jenkins
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>