Update patch set 10
Patch Set 10: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/6857/ : FAILURE

Visual studio complained about error C2440: "<function-style-cast>": cannot convert from "initializer list" to "com::sun::star::lang::WrappedTargetRuntimeException" in file C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/windows_msc_dbgutil_32/extensions/source/ole/oleobjw.cxx(167) ( https://ci.libreoffice.org/job/gerrit_windows/6772/ )

Patch-set: 10
Label: Verified=-1