Update patch set 1
Patch Set 1: This need some tweaks before it is merged

sfx2/source/appl/sfxhelp.cxx:615:58: error: ‘class Dialog’ has no member named ‘hasBuilder’

Patch-set: 1
Label: Verified=0
Label: Code-Review=-1