Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/78452/ : FAILURE

error: cppu::OWeakObject subclass "(anonymous namespace)::TestResultListener" being managed via raw pointer, should be managed via rtl::Reference [loplugin:refcounting] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/extras/tiledrendering/tiledrendering.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/80357/ )

the cppunit test CppunitTest_xmlsecurity_pdfsigning failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/80357/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/80357/ )

clang plugin refcounting did trigger. cppu::OWeakObject subclass "(anonymous namespace)::TestResultListener" being managed via raw pointer, should be managed via rtl::Reference ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/80357/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1