engine cairo: fix internal freetype usage when host uses lib64
The Android 64bit build failed with:
	../src/cairo-ps-surface.c:106:14: error: static declaration of 'ctime_r' follows non-static declaration
	  106 | static char *ctime_r(const time_t *timep, char *buf)
	      |              ^
	/home/vmiklos/Android/Sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/time.h:291:17: note: previous declaration is here
	  291 | char* _Nullable ctime_r(const time_t* _Nonnull __t, char* _Nonnull __buf);
	      |                 ^
	1 error generated.

The cross-built freetype's .pc file is at
instdir/lib64/pkgconfig/freetype2.pc (note lib64), but
ExternalProject_cairo.mk only adds instdir/lib/pkgconfig to
PKG_CONFIG_PATH. Pkg-config can't find the cross-built freetype, falls
back to the host's /usr/lib64/libfreetype.so, which won't work, that one
is built for x86_64.

This means the meson link-tests fail, HAVE_CTIME_R stays undefined, and
cairo's fallback static ctime_r clashes with the NDK's real declaration.

Fix the problem by looking for lib64 next to lib when using internal
freetype for the cairo build.

Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: I20aa2eaa80c0a47ce95de775caba081affee8876
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/3390
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Andras Timar <andras.timar@collabora.com>