desktop: fix Android -Werror,-Wunreachable-code
error: code will never be executed [-Werror,-Wunreachable-code]

In the 'old' (JNI-based) Android app case. If clang doesn't like 'if
(false)', then invert the #if condition so we don't need it.

Change-Id: I79818a51cb284519313738ab4272d109171dfcd0