external/postgresql: Include configure fix for C23 stdbool.h
...by backporting upstream
<https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=bc5a4dfcf7390145dc3ba3c1c18c5ce561b778cd>
"Assume that <stdbool.h> conforms to the C standard." to our REL_14_15 version.
GCC 15 trunk defaults to C23 now, so started to fail with

> In file included from fls.c:49:
> ../../src/include/c.h:419:23: error: two or more data types in declaration specifiers
>   419 | typedef unsigned char bool;
>       |                       ^~~~
> ../../src/include/c.h:419:1: warning: useless type name in empty declaration
>   419 | typedef unsigned char bool;
>       | ^~~~~~~
> make: *** [<builtin>: fls.o] Error 1
> make: Leaving directory 'workdir/UnpackedTarball/postgresql/src/port'

(Removing HAVE__BOOL and HAVE_STDBOOL_H also from src/tools/msvc/Solution.pm is
necessary to avoid failures like

> "C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/workdir/UnpackedTarball/openssl\apps\openssl.exe" version 2>&1unused defines: HAVE_STDBOOL_H HAVE__BOOL at /home/tdf/jenkins/workspace/gerrit_windows/workdir/UnpackedTarball/postgresql/src/tools/msvc/Mkvcbuild.pm line 870.
> make[1]: *** [C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/external/postgresql/ExternalProject_postgresql.mk:27: C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/workdir/ExternalProject/postgresql/build] Error 1

in MSVC builds.)

Change-Id: I1f6bd0d613ae4d6ce70feaaf67aaf95496eeff87
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/177280
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>
Tested-by: Jenkins
(cherry picked from commit ea0b06415b35ff68959c8fb24355f2c15ad63e64)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191779
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>