Revert "re-enable PCH for skia"
This reverts commit 6fa110f141cd5f264366c36f6472f7f2ede68fcd.

Reason for revert: it's causing https://ci.libreoffice.org/job/lo_daily_tb_win_arm64
to fail with
In file included from E:/jenkins/workspace/build_master/workdir/UnpackedTarball/skia/src/core/SkBlendMode.cpp:1:
In file included from E:\jenkins\workspace\lo_daily_src\external\skia\inc\pch\precompiled_skia.cxx:10:
In file included from E:/jenkins/workspace/lo_daily_src/external/skia/inc/pch/precompiled_skia.hxx:284:
E:\jenkins\workspace\build_master\workdir\UnpackedTarball\skia\src\base\SkUtils.h(46,42): error: definition with same mangled name '??$sk_unaligned_load@U?$Vec@$03M@skvx@@T?$__vector@M$03@__clang@@@@YA?AU?$Vec@$03M@skvx@@PEBT?$__vector@M$03@__clang@@@Z' as another definition
   46 | static SK_ALWAYS_INLINE T SK_FP_SAFE_ABI sk_unaligned_load(const P* ptr) {
      |                                          ^
E:\jenkins\workspace\build_master\workdir\UnpackedTarball\skia\src\base\SkUtils.h(46,42): note: previous definition is here
E:\jenkins\workspace\build_master\workdir\UnpackedTarball\skia\src\base\SkUtils.h(68,44): error: definition with same mangled name '??$sk_bit_cast@U?$Vec@$03M@skvx@@T?$__vector@M$03@__clang@@@@YA?AU?$Vec@$03M@skvx@@AEBT?$__vector@M$03@__clang@@@Z' as another definition
   68 | static SK_ALWAYS_INLINE Dst SK_FP_SAFE_ABI sk_bit_cast(const Src& src) {
      |                                            ^
E:\jenkins\workspace\build_master\workdir\UnpackedTarball\skia\src\base\SkUtils.h(68,44): note: previous definition is here
2 errors generated.
[build CXX] workdir/UnpackedTarball/skia/src/core/SkBlitter_A8.cpp
make[1]: *** [E:/jenkins/workspace/lo_daily_src/solenv/gbuild/LinkTarget.mk:400: E:/jenkins/workspace/build_master/workdir/GenCxxObject/UnpackedTarball/skia/src/core/SkBlendMode.o] Error 1
make[1]: *** Waiting for unfinished jobs....

Change-Id: I051e05989bdcc9325cf8d5aa8b270c204b93d9e4
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/196330
Tested-by: Jenkins
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>