svx: work around GCC12 spurious -Werror=stringop-overflow
/usr/include/c++/12/bits/stl_algobase.h:431:30: error: ‘void*
__builtin_memcpy(void*, const void*, long unsigned int)’ writing 1 or
more bytes into a region of size 0 overflows the destination
[-Werror=stringop-overflow=]

Change-Id: Ib581b5788ff5d363b688000e700a42074c3b78eb
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/134740
Tested-by: Jenkins
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>
(cherry picked from commit d37486537e7d404b19acdfaec358cb0ad706940c)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/134633
Reviewed-by: Thorsten Behrens <thorsten.behrens@allotropia.de>