Update git submodules
* Update dictionaries from branch 'libreoffice-26-8'
  to 7d1789b019de8aaac67f62a5bd23ee9b1a6d7766
  - fix make translations / cfgex complaining about misplaced close tags
    
    in dictionaries/fr_FR/ui/addons.xcu:
    
    Error: "Misplaced close tag: </oor:component-data> in file /home/cl/vc/git/libo-core/dictionaries/fr_FR/ui/addons.xcu" in line 81, column 22: "</oor:component-data>"
    Error: Failed to execute /home/cl/rpmbuild/BUILD/l10ntools/workdir/LinkTarget/Executable/cfgex -i /home/cl/vc/git/libo-core/dictionaries/fr_FR/ui/addons.xcu -o /home/cl/rpmbuild/BUILD/l10ntools/workdir/pot/dictionaries/fr_FR/ui.pot
    
    cfgex doesn't like if the opening tag is split across multiple lines,
    at least when the opening tag isn't followed by an attribute or the
    closing tag. But even if it doesn't complain about misplaced closing
    tags, if the line is still split it would create duplicate entries in
    the resulting ui.pot file.
    
    Also remove the empty <value/> tag, while that one doesn't cause parse
    errors, it is superfluous.
    
    Change-Id: I3f36f834301b837a93421057b62e28b28691b28a
    Reviewed-on: https://gerrit.libreoffice.org/c/dictionaries/+/207881
    Tested-by: Xisco Fauli <xiscofauli@libreoffice.org>
    Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
    (cherry picked from commit 38d96a4d54ec3449cf7f28cddae1fce32e2b15a7)
    Reviewed-on: https://gerrit.libreoffice.org/c/dictionaries/+/207884