Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/57670/ : FAILURE

error ""GetFrame" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/uibase/inc/OutlineContentVisibilityWin.hxx:43:20 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/60708/ )

error: "GetFrame" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/uibase/inc/OutlineContentVisibilityWin.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/60708/ )

Patch-set: 5
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1