Fix the build
...after 756185b5795c95180d32d02abfbd65951779b40e "osl::Mutex->std::mutex in
PersistentPropertySet" caused

> ucb/source/core/ucbstore.cxx:1913:75: error: too few arguments to function call, expected 2, have 1
>             m_pPropertyChangeListeners->getContainer( rEvent.PropertyName );
>             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                      ^
> include/comphelper/multiinterfacecontainer4.hxx:71:50: note: 'getContainer' declared here
>     inline OInterfaceContainerHelper4<listener>* getContainer(std::unique_lock<std::mutex>& rGuard,
>                                                  ^
> ucb/source/core/ucbstore.cxx:1921:66: error: too few arguments to function call, expected 2, have 1
>             m_pPropertyChangeListeners->getContainer( OUString() );
>             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~             ^
> include/comphelper/multiinterfacecontainer4.hxx:71:50: note: 'getContainer' declared here
>     inline OInterfaceContainerHelper4<listener>* getContainer(std::unique_lock<std::mutex>& rGuard,
                                                 ^

Change-Id: Ie13c7bf17d066607ec7095b3e45ab7d6ecea1cb6
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/146940
Tested-by: Stephan Bergmann <sbergman@redhat.com>
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>