Update patch set 2
Patch Set 2:

> Patch Set 2: Verified-1
> 
> Build Failed 
> 
> https://ci.libreoffice.org/job/gerrit_master/88934/ : FAILURE
> 
> error: replace function parameter of type "const rtl::OUString &" with "std::u16string_view" [loplugin:stringviewparam] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/backendtest/GraphicsRenderTests.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/90169/ )
> 
> clang plugin stringviewparam did trigger. replace function parameter of type "const rtl::OUString &" with "std::u16string_view" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/90169/ )

I don't get this error, I've tried changing OUString to std::u16string_view but it gives me error as due to incompatibility of types. What should be causing it?

Patch-set: 2