Update patch set 2
Patch Set 2:

> Patch Set 2: Verified-1
> error: unknown type name "xmlDocUniquePtr" ...

This fails because you also need to #include <test/xmltesttools.hxx> in the tests file. However, on my side the inclusion of xmltesttools.hxx on 7.2 branch has failed with another buildtime error while there is no such error on master. That was why I did not include this testcase in my initial patch but inserted a comment in the commit message instead:
https://gerrit.libreoffice.org/c/core/+/120848

Patch-set: 2
Reviewer: Gerrit User 1000750 <1000750@6622c302-437a-49ad-a91d-55ba7dcf1615>