Update patch set 42
Patch Set 42:

It fails with:
C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/svl/qa/unit/test_URIHelper.cxx(282) : error : Assertion
Test name: `anonymous namespace'::Test::testNormalizedMakeRelative
assertion failed
- Expression: ok
- <file:///c:/windows/nonex1>, <file:///c:/nonex2>: </C:/nonex2> instead of <../nonex2>

I must recognize I don't know why and can't help here.

Patch-set: 42