Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/44670/ : FAILURE

clang plugin external did trigger. externally available entity "checkDisposed" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/48140/ )

error: externally available entity "checkDisposed" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/connectivity/source/drivers/firebird/Driver.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/48140/ )

Patch-set: 3
Label: Verified=-1