Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/75510/ : FAILURE

error "expression result unused [-Werror,-Wunused-value]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/svl/poolitem.hxx:156:9 ( https://ci.libreoffice.org/job/gerrit_mac/80993/ )

error: expression result unused [-Werror,-Wunused-value] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/svl/poolitem.hxx ( https://ci.libreoffice.org/job/gerrit_mac/80993/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1