Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/23771/ : FAILURE

clang plugin salbool did trigger. VarDecl, use "bool" instead of "sal_Bool" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/25264/ )

error: VarDecl, use "bool" instead of "sal_Bool" [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/filter/source/svg/svgexport.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/25264/ )

Patch-set: 1
Label: Verified=-1