external/nss: Fix -Wincompatible-pointer-types
...on macOS, where connectx(2) "appeared in Darwin 15.0.0" according to its man
page, and where recent Clang with
<https://github.com/llvm/llvm-project/commit/b24769855d97697de08e2296a548c033f193caf4>
"[Clang] [Sema] Make `-Wincompatible-pointer-types` an error by default
(#157364)" now started to fail with

> ../../../../pr/src/pthreads/ptio.c:2046:58: error: incompatible pointer types passing 'PRInt32 *' (aka 'int *') to parameter of type 'size_t *' (aka 'unsigned long *') [-Wincompatible-pointer-types]
>  2046 |                         CONNECT_DATA_IDEMPOTENT, iov, 1, &bytes, NULL);
>       |                                                          ^~~~~~
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk/usr/include/sys/socket.h:741:49: note: passing argument to parameter here
>   741 |     const struct iovec *, unsigned int, size_t *, sae_connid_t *);
>       |                                                 ^
> ../../../../pr/src/pthreads/ptio.c:2045:11: warning: unused variable 'rv' [-Wunused-variable]
>  2045 |   PRInt32 rv = connectx(fd->secret->md.osfd, &endpoints, SAE_ASSOCID_ANY,
>       |           ^~

Change-Id: I047a987e443ab0283f38d997d03062fe969a65c5
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191375
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>
(cherry picked from commit 1edb882cd03a632644f90003e07ca57f4268b053)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/200798
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>