Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/66907/ : FAILURE

clang plugin casttovoid did trigger. unused variable declaration ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/69404/ )

error: unused variable declaration [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/headless/svpinst.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/69404/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1