Update patch set 7
Patch Set 7:

This change causes (GCC 8)

> [CXX] libreofficekit/qa/gtktiledviewer/gtv-calc-header-bar.cxx
> libreofficekit/qa/gtktiledviewer/gtv-calc-header-bar.cxx: In function ‘gboolean gtv_calc_header_bar_draw(GtkWidget*, cairo_t*)’:
> libreofficekit/qa/gtktiledviewer/gtv-calc-header-bar.cxx:89:117: error: ‘aRectangle._cairo_rectangle_int::height’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>      cairo_move_to(pCairo, rRectangle.x + rRectangle.width / 2 - extents.width / 2, rRectangle.y + rRectangle.height / 2 + extents.height / 2);
>                                                                                                    ~~~~~~~~~~~~~~~~~~^~~
> libreofficekit/qa/gtktiledviewer/gtv-calc-header-bar.cxx:102:22: note: ‘aRectangle._cairo_rectangle_int::height’ was declared here
>          GdkRectangle aRectangle;
>                       ^~~~~~~~~~
> libreofficekit/qa/gtktiledviewer/gtv-calc-header-bar.cxx:89:59: error: ‘aRectangle._cairo_rectangle_int::width’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>      cairo_move_to(pCairo, rRectangle.x + rRectangle.width / 2 - extents.width / 2, rRectangle.y + rRectangle.height / 2 + extents.height / 2);
>                                           ~~~~~~~~~~~~~~~~~^~~
> libreofficekit/qa/gtktiledviewer/gtv-calc-header-bar.cxx:102:22: note: ‘aRectangle._cairo_rectangle_int::width’ was declared here
>          GdkRectangle aRectangle;
>                       ^~~~~~~~~~
> libreofficekit/qa/gtktiledviewer/gtv-calc-header-bar.cxx:89:97: error: ‘aRectangle._cairo_rectangle_int::y’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>      cairo_move_to(pCairo, rRectangle.x + rRectangle.width / 2 - extents.width / 2, rRectangle.y + rRectangle.height / 2 + extents.height / 2);
>                                                                                     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
> libreofficekit/qa/gtktiledviewer/gtv-calc-header-bar.cxx:102:22: note: ‘aRectangle._cairo_rectangle_int::y’ was declared here
>          GdkRectangle aRectangle;
>                       ^~~~~~~~~~
> libreofficekit/qa/gtktiledviewer/gtv-calc-header-bar.cxx:89:40: error: ‘aRectangle._cairo_rectangle_int::x’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>      cairo_move_to(pCairo, rRectangle.x + rRectangle.width / 2 - extents.width / 2, rRectangle.y + rRectangle.height / 2 + extents.height / 2);
>                            ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
> libreofficekit/qa/gtktiledviewer/gtv-calc-header-bar.cxx:102:22: note: ‘aRectangle._cairo_rectangle_int::x’ was declared here
>          GdkRectangle aRectangle;
>                       ^~~~~~~~~~
> cc1plus: all warnings being treated as errors
> make[1]: *** [solenv/gbuild/LinkTarget.mk:293: workdir/CxxObject/libreofficekit/qa/gtktiledviewer/gtv-calc-header-bar.o] Error 1

Patch-set: 7