Update patch set 5
Patch Set 5:

Just saw random failure <https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/2137/console>

> ERROR: test_gbuildtojson (gbuildtojson.CheckGbuildToJsonModules)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/solenv/qa/python/gbuildtojson.py", line 136, in test_gbuildtojson
>     ignore=shutil.ignore_patterns('.#*', '#*', '*~'))
>   File "/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/instdir/program/python-core-3.5.4/lib/shutil.py", line 359, in copytree
>     raise Error(errors)
> shutil.Error: [('/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/qa/uitest/autofilter/data/.~lock.tdf77479.ods#', '/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/tempdir/gbuildly6da34m/sc/qa/uitest/autofilter/data/.~lock.tdf77479.ods#', "[Errno 2] No such file or directory: '/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/qa/uitest/autofilter/data/.~lock.tdf77479.ods#'")]

which implies that these tests access test documents like sc/qa/uitest/autofilter/data/tdf77479.ods in the source tree in a way that causes lock files (.~lock.*#) to be put next to them.  Can that please be fixed (e.g., by copying the relevant test documents to some temporary, non-source-tree location, like somewhere in workdir, first; or by making sure the documents are opened in a way so that no such lock files are written).

Patch-set: 5
Reviewer: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0