Update patch set 4
Patch Set 4:

It seems it caused a TB fail with:
29640 NEXT    /home/tdf/lode/jenkins/workspace/lo_ubsan/svtools/qa/unit/svtools-dialogs-test.cxx:15:10: fatal error: ´uitest/uiobject.hxx´ file not found
29641         #include <uitest/uiobject.hxx>
29642                  ^~~~~~~~~~~~~~~~~~~~~
29643         [build CXX] reportdesign/source/ui/dlg/CondFormat.cxx
29644 NEXT    1 error generated.
29645 NEXT    /home/tdf/lode/jenkins/workspace/lo_ubsan/solenv/gbuild/LinkTarget.mk:303: recipe for target ´/home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/CxxObject/svtools/qa/unit/svtools-dialogs-test.o´ failed
29646 NEXT    make[1]: *** [/home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/CxxObject/svtools/qa/unit/svtools-dialogs-test.o] Error 1

Any idea?

Patch-set: 4
CC: Gerrit User 1000043 <1000043@6622c302-437a-49ad-a91d-55ba7dcf1615>