Revert "Replace list by vector in filtergrouping (sfx2)"
This reverts commit 62896fb7a5983eb13ee87b94ae803e6552626d8d.

The usage of iterators in CreateEmptyClassRememberPos
operator() is bogus and causes:

Error: attempt to dereference a singular iterator.