Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/14298/ : FAILURE

error: unused variable "rRows" [loplugin:unusedvariablecheck] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/connectivity/source/drivers/mysqlc/mysqlc_databasemetadata.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/14928/ )

clang plugin unusedvariablecheck did trigger. unused variable "rRows" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/14928/ )

Patch-set: 1
Label: Verified=-1