Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_feature/242/ : FAILURE

error ""getName" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/chart2/source/inc/ChartStyle.hxx:72:31 ( https://ci.libreoffice.org/job/gerrit_mac/39871/ )

error: "getName" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/chart2/source/inc/ChartStyle.hxx ( https://ci.libreoffice.org/job/gerrit_mac/39871/ )

Patch-set: 1
Label: Verified=-1