kit: Fix build of kit/Kit.cpp.
Error:

In function ‘ssize_t readlink(const char*, char*, size_t)’,
    inlined from ‘int {anonymous}::linkOrCopyFunction(const char*, const stat*, int, FTW*)’ at kit/Kit.cpp:579:49:
/usr/include/bits/unistd.h:119:10: error: argument 2 is null but the corresponding size argument 3 value is 18446744073709551615 [-Werror=nonnull]
  119 |   return __glibc_fortify (readlink, __len, sizeof (char),
      |          ^~~~~~~~~~~~~~~
/usr/include/bits/unistd.h: In function ‘int {anonymous}::linkOrCopyFunction(const char*, const stat*, int, FTW*)’:
/usr/include/bits/unistd.h:104:16: note: in a call to function ‘ssize_t __readlink_alias(const char*, char*, size_t)’ declared with attribute ‘access (write_only, 2, 3)’
  104 | extern ssize_t __REDIRECT_NTH (__readlink_alias,
      |                ^~~~~~~~~~~~~~

It was introduced by f0b848c4b73e3e6bb56b32a00030da5fbf94ccf0
Adaptation of a similar fix in common/FileUtil-unix.cpp

Signed-off-by: Hubert Figuière <hub@collabora.com>
Change-Id: Iac3360983063037d2b5f3e4f4bd27f5d23cf9f97
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/8585
Reviewed-by: Andras Timar <andras.timar@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>