silence -Werror=strict-overflow
error: assuming signed overflow does not occur when assuming that
(X + c) < X is always false [-Werror=strict-overflow]
     if ( rAddress.Row() < Row() )

Change-Id: Ia643491657680fffcaacae4a474af479b9a07e35
(cherry picked from commit 0e40e1e3243d57fdf67c54d7c5b69e77fe7d03ce)