Update patch set 2
Patch Set 2:

Stephan: Thanks for the feedback! :-)

> bridges/source/cpp_uno/gcc3_linux_aarch64/abi.cxx
> Line 42:
> (here and elsewhere:) such a cross-dir include looks fishy; why would it be necessary?

Without this, I'm getting:

/local/libreoffice/master-android-release-64bit/bridges/source/cpp_uno/gcc3_linux_aarch64/abi.cxx:118:40: error: no type named '__class_type_info' in namespace '__cxxabiv1'
                rtti = new __cxxabiv1::__class_type_info(strdup(rttiName));
                           ~~~~~~~~~~~~^
/local/libreoffice/master-android-release-64bit/bridges/source/cpp_uno/gcc3_linux_aarch64/abi.cxx:122:40: error: no type named '__si_class_type_info' in namespace '__cxxabiv1'
                rtti = new __cxxabiv1::__si_class_type_info(
                           ~~~~~~~~~~~~^

and similar.

I did not want to just copy the file over, I thought it would be better to share it.


> Line 266:
> (here and elsewhere:) SAL_FALLTHROUGH has been removed with ab9b67bbb001f380b3973941443bfbc59fe7141c "Remove obsolete SAL_FALLTHROUGH completely"
> bridges/source/cpp_uno/gcc3_linux_aarch64/cpp2uno.cxx

OK, will use [[fallthrough]] instead; but I guess would be good to go through a "git grep '// fall through' -- '*.c*'" and clean up the missing pieces there too (?)

> Line 317:
> why exactly is this necessary? which compiler version emits it (for the reads of indirectRet, functionIndex, vtableOffset, I assume)?

Without this, I'm getting:

/local/libreoffice/master-android-release-64bit/bridges/source/cpp_uno/gcc3_linux_aarch64/cpp2uno.cxx:349:9: warning: variable 'functionIndex' is uninitialized when used here [-Wuninitialized]
        functionIndex, vtableOffset, gpr,
        ^~~~~~~~~~~~~
/local/libreoffice/master-android-release-64bit/bridges/source/cpp_uno/gcc3_linux_aarch64/cpp2uno.cxx:325:46: note: initialize the variable 'functionIndex' to silence this warning
    register sal_Int32 volatile functionIndex asm ("x9");
                                             ^
                                              = 0
/local/libreoffice/master-android-release-64bit/bridges/source/cpp_uno/gcc3_linux_aarch64/cpp2uno.cxx:349:24: warning: variable 'vtableOffset' is uninitialized when used here [-Wuninitialized]
        functionIndex, vtableOffset, gpr,
                       ^~~~~~~~~~~~
/local/libreoffice/master-android-release-64bit/bridges/source/cpp_uno/gcc3_linux_aarch64/cpp2uno.cxx:326:45: note: initialize the variable 'vtableOffset' to silence this warning
    register sal_Int32 volatile vtableOffset asm ("x10");
                                            ^
                                             = 0
/local/libreoffice/master-android-release-64bit/bridges/source/cpp_uno/gcc3_linux_aarch64/cpp2uno.cxx:353:9: warning: variable 'indirectRet' is uninitialized when used here [-Wuninitialized]
        indirectRet);
        ^~~~~~~~~~~
/local/libreoffice/master-android-release-64bit/bridges/source/cpp_uno/gcc3_linux_aarch64/cpp2uno.cxx:324:41: note: initialize the variable 'indirectRet' to silence this warning
    register void * volatile indirectRet asm ("x8");
                                        ^
                                         = nullptr

The compiler is:

> /local/libreoffice/android/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --version
Android (5058415 based on r339409) clang version 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec746213857d083c0e8b0abb568790) (https://android.googlesource.com/toolchain/llvm 7a6618d69e7e8111e1d49dc9e7813767c5ca756a) (based on LLVM 8.0.2svn)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/libreoffice/android/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin

Patch-set: 2
Label: Verified=0