sc: Dereference after null check
C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/sc/source/core/data/column3.cxx(2821): error C2220: the following warning is treated as an error
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\sc\source\core\data\column3.cxx(2752) : warning C6011: Dereferencing NULL pointer 'pPattern'. : Lines: 2723, 2726, 2727, 2728, 2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740, 2742, 2744, 2745, 2747, 2751, 2752, 2753, 2754, 2756, 2762, 2763, 2766, 2791, 2809, 2811, 2814, 2819, 2740, 2742, 2744, 2745, 2747, 2751, 2752
make[1]: *** [C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/solenv/gbuild/LinkTarget.mk:339: C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/workdir/CxxObject/sc/source/core/data/column3.o] Error 2

After
commit 2c613da01d02d45a140b94b391a142aede46e8b8
Author: Noel Grandin <noel.grandin@collabora.co.uk>
Date:   Wed Dec 4 11:20:01 2024 +0200

    tdf#163010 inline and cache rDoc.GetCondFormat call

Change-Id: If9093d5b43ae63e059b3f0597c85b326599e9ed0
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/178621
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
(cherry picked from commit 85b7a25135eb96919d62a108fea18eab5531a4da)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/178644