Automake->gbuild prequel: Silence some loplugin:indentation
> engine/../common/ConfigUtil.hpp:162:9: error: statement mis-aligned compared to neighbours  [loplugin:indentation]
>   162 |         return isSslEnabled;
>       |         ^
> engine/../common/ConfigUtil.hpp:161:23: note: measured against this one [loplugin:indentation]
>   161 |         CONFIG_STATIC const bool isSslEnabled = getBool("ssl.enable", true);
>       |                       ^

etc.

(clang::Lexer::findPreviousToken was only introduced with
<https://github.com/llvm/llvm-project/commit/fbd86d05fe51d45f19df8d63aee41d979c268f8f>
"[clang-reorder-fields] Reorder leading comments (#123740)" in LLVM 20.)

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I2c2a0206dad24b724f7b9066e0529084dd05cb46
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/8345
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>