Remove stray defaulted argument
...that, for unclear reasons, had been added to this declaration in
436f3f8eb5b45620842351a1f29ba49571043515 "tdf#38742 - Start Center: introduce
push pins to favorite documents", but without also adding it to the definition
in unotools/source/config/historyoptions.cxx, causing

> unotools/source/config/historyoptions.cxx:307:13: error: call to 'Clear' is ambiguous
>   307 |             Clear(eHistory);
>       |             ^~~~~
> include/unotools/historyoptions.hxx:47:29: note: candidate function
>    47 |     UNOTOOLS_DLLPUBLIC void Clear(EHistoryType eHistory, bool bClearPinned = false);
>       |                             ^
> unotools/source/config/historyoptions.cxx:71:6: note: candidate function
>    71 | void Clear( EHistoryType eHistory )
>       |      ^

Change-Id: I7ad65d72be2c59da0ad6deaadefebf9662571433
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/152637
Tested-by: Stephan Bergmann <sbergman@redhat.com>
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>