Revert "flush CallbackFlushHandler queue via PostUserEvent..."
This reverts commit d78938768c6f8dbc0917184c8daa0c381400bff7.

on the theory that this is triggering:

Error: Timed out waiting for: http://localhost:9900
    at /home/collabora/jenkins/workspace/github_online_master_debug_vs_co-24.04_cypress_desktop/cypress_test/node_modules/wait-on/lib/wait-on.js:132:31
Change-Id: I39f0f36b08510805223da1105fa2a46977102bf2
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/167195
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>