Fix --disable-pch build: explicitly delete move constructor
Without this, the implicitly created constructor is exported by MSVC
for VCL_DLLPUBLIC class, and requires that VirtualDevice is defined,
resulting in this error in PCH-disabled builds:

  [build CXX] vcl/source/animate/Animation.cxx
  C:\lo\src\core\include\rtl/ref.hxx(129): error C2027: use of undefined type 'VirtualDevice'
  C:\lo\src\core\vcl\inc\impanmvw.hxx(29): note: see declaration of 'VirtualDevice'
  C:\lo\src\core\include\rtl/ref.hxx(127): note: while compiling class template member function 'rtl::Reference<reference_type>::~Reference(void)'
  with
  [
  reference_type=VirtualDevice
  ]
  C:\lo\src\core\include\vcl/vclptr.hxx(216): note: see reference to function template instantiation 'rtl::Reference<reference_type>::~Reference(void)' being comp
  iled
  with
  [
  reference_type=VirtualDevice
  ]
  C:\lo\src\core\include\vcl/vclptr.hxx(64): note: see reference to class template instantiation 'rtl::Reference<reference_type>' being compiled
  with
  [
  reference_type=VirtualDevice
  ]
  C:\lo\src\core\include\vcl/outdev.hxx(202): note: see reference to class template instantiation 'VclPtr<VirtualDevice>' being compiled
  make[1]: *** [C:/lo/src/core/solenv/gbuild/LinkTarget.mk:337: C:/lo/src/build/workdir/CxxObject/vcl/source/animate/Animation.o] Error 2

Change-Id: I78723ce7d00667595aff39bcab22169ff347098f