Update patch set 3
Patch Set 3: Verified; Looks good to me, approved

It looks good => pushed.

I only needed to revert the change for the equalsIgnoreAsciiCaseAsciiL call because the simplification is not yet supported there.

I have got the following build error with your original patch on Linux x86_64:
--- cut ---
[build CHK] loaded modules: basctl
/abuild/lo-git/libreoffice/core/basctl/source/basicide/scriptdocument.cxx: In member function 'bool basctl::ScriptDocument::Impl::isLibraryShared(const rtl::OUString&, basctl::LibraryContainerType)':
/abuild/lo-git/libreoffice/core/basctl/source/basicide/scriptdocument.cxx:950: error: no matching function for call to 'rtl::OUString::equalsIgnoreAsciiCaseAsciiL(const char [5])'
/abuild/lo-git/libreoffice/core/solver/unxlngx6.pro/inc/rtl/ustring.hxx:803: note: candidates are: sal_Bool rtl::OUString::equalsIgnoreAsciiCaseAsciiL(const sal_Char*, sal_Int32) const
/abuild/lo-git/libreoffice/core/basctl/source/basicide/scriptdocument.cxx:954: error: no matching function for call to 'rtl::OUString::equalsIgnoreAsciiCaseAsciiL(const char [17])'
/abuild/lo-git/libreoffice/core/solver/unxlngx6.pro/inc/rtl/ustring.hxx:803: note: candidates are: sal_Bool rtl::OUString::equalsIgnoreAsciiCaseAsciiL(const sal_Char*, sal_Int32) const
/abuild/lo-git/libreoffice/core/basctl/source/basicide/scriptdocument.cxx:957: error: no matching function for call to 'rtl::OUString::matchIgnoreAsciiCaseAsciiL(const char [21])'
/abuild/lo-git/libreoffice/core/solver/unxlngx6.pro/inc/rtl/ustring.hxx:870: note: candidates are: sal_Bool rtl::OUString::matchIgnoreAsciiCaseAsciiL(const sal_Char*, sal_Int32, sal_Int32) const
/abuild/lo-git/libreoffice/core/solver/unxlngx6.pro/inc/rtl/ustring.hxx:882: note:                 void rtl::OUString::matchIgnoreAsciiCaseAsciiL(const char*, sal_Int32, rtl_TextEncoding) const
--- cut ---

I am not sure when matchIgnoreAsciiCaseAscii will be supported. Lubos or Stefan might knew more.

Patch-set: 3
Reviewer: Gerrit User 1000053 <1000053@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=+1
Label: Code-Review=+2
Label: SUBM=+1