Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/121087/ : FAILURE

error: use "bool" instead of "gboolean" (aka "int") as return type [loplugin:fakebool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/unx/gtk3/gtkframe.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/121117/ )

clang plugin fakebool did trigger. use "bool" instead of "gboolean" (aka "int") as return type ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/121117/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1, 902f32d2fe082563166d1371e4b674b73e6599be
Attention: {"person_ident":"Gerrit User 1003664 \u003c1003664@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}