svl: fix build with --enable-debug
After

author	Armin Le Grand (allotropia) <armin.le.grand.extern@allotropia.de>	2023-12-20 19:42:28 +0100
committer	Armin Le Grand <Armin.Le.Grand@me.com>	2023-12-21 21:13:55 +0100
commit	789a737ac92c4f2b0eb9820b99c43cc8253c8b29 (patch)
tree	bc167ec04de29e63168844be973f59980fa36ac2
parent	3430a2c639a9f714259f9d319515464a653d21ab (diff)
Remove DeleteItemOnIdlex

it fails with

/home/xisco/libreoffice/include/svl/itemset.hxx: In member function ‘SfxItemPool& SfxPoolItemHolder::getPool() const’:
/home/xisco/libreoffice/include/svl/itemset.hxx:64:44: error: ‘isDeleted’ was not declared in this scope
   64 |     SfxItemPool& getPool() const { assert(!isDeleted() && "Destructed instance used (!)"); return *m_pPool; }
      |                                            ^~~~~~~~~
/home/xisco/libreoffice/include/svl/itemset.hxx: In member function ‘const SfxPoolItem* SfxPoolItemHolder::getItem() const’:
/home/xisco/libreoffice/include/svl/itemset.hxx:65:50: error: ‘isDeleted’ was not declared in this scope
   65 |     const SfxPoolItem* getItem() const { assert(!isDeleted() && "Destructed instance used (!)"); return m_pItem; }
      |                                                  ^~~~~~~~~
make[1]: *** [/home/xisco/libreoffice/solenv/gbuild/LinkTarget.mk:340: /home/xisco/libreoffice/workdir/CxxObject/svl/source/items/itemiter.o] Error 1
make[1]: *** Se espera a que terminen otras tareas....
In file included from /usr/include/c++/12/cassert:44,
                 from /home/xisco/libreoffice/include/svl/whichranges.hxx:16,
                 from /home/xisco/libreoffice/include/svl/itemset.hxx:30,
                 from /home/xisco/libreoffice/svl/source/items/sitem.cxx:23:
/home/xisco/libreoffice/include/svl/itemset.hxx: In member function ‘SfxItemPool& SfxPoolItemHolder::getPool() const’:
/home/xisco/libreoffice/include/svl/itemset.hxx:64:44: error: ‘isDeleted’ was not declared in this scope
   64 |     SfxItemPool& getPool() const { assert(!isDeleted() && "Destructed instance used (!)"); return *m_pPool; }
      |                                            ^~~~~~~~~
/home/xisco/libreoffice/include/svl/itemset.hxx: In member function ‘const SfxPoolItem* SfxPoolItemHolder::getItem() const’:
/home/xisco/libreoffice/include/svl/itemset.hxx:65:50: error: ‘isDeleted’ was not declared in this scope
   65 |     const SfxPoolItem* getItem() const { assert(!isDeleted() && "Destructed instance used (!)"); return m_pItem; }
      |                                                  ^~~~~~~~~
make[1]: *** [/home/xisco/libreoffice/solenv/gbuild/LinkTarget.mk:337: /home/xisco/libreoffice/workdir/CxxObject/svl/source/items/sitem.o] Error 1
In file included from /usr/include/c++/12/cassert:44,
                 from /home/xisco/libreoffice/include/svl/whichranges.hxx:16,
                 from /home/xisco/libreoffice/include/svl/itemset.hxx:30,
                 from /home/xisco/libreoffice/svl/source/items/itemset.cxx:30:
/home/xisco/libreoffice/include/svl/itemset.hxx: In member function ‘SfxItemPool& SfxPoolItemHolder::getPool() const’:
/home/xisco/libreoffice/include/svl/itemset.hxx:64:44: error: ‘isDeleted’ was not declared in this scope
   64 |     SfxItemPool& getPool() const { assert(!isDeleted() && "Destructed instance used (!)"); return *m_pPool; }
      |                                            ^~~~~~~~~
/home/xisco/libreoffice/include/svl/itemset.hxx: In member function ‘const SfxPoolItem* SfxPoolItemHolder::getItem() const’:
/home/xisco/libreoffice/include/svl/itemset.hxx:65:50: error: ‘isDeleted’ was not declared in this scope
   65 |     const SfxPoolItem* getItem() const { assert(!isDeleted() && "Destructed instance used (!)"); return m_pItem; }
      |                                                  ^~~~~~~~~
In file included from /usr/include/c++/12/cassert:44,
                 from /home/xisco/libreoffice/include/o3tl/sorted_vector.hxx:15,
                 from /home/xisco/libreoffice/include/svl/itempool.hxx:30,
                 from /home/xisco/libreoffice/svl/source/items/itemset.cxx:31:
/home/xisco/libreoffice/svl/source/items/itemset.cxx: In member function ‘const SfxPoolItemHolder& SfxPoolItemHolder::operator=(const SfxPoolItemHolder&)’:
/home/xisco/libreoffice/svl/source/items/itemset.cxx:120:13: error: ‘isDeleted’ was not declared in this scope
  120 |     assert(!isDeleted() && "Destructed instance used (!)");
      |             ^~~~~~~~~
/home/xisco/libreoffice/svl/source/items/itemset.cxx:121:21: error: ‘const class SfxPoolItemHolder’ has no member named ‘isDeleted’
  121 |     assert(!rHolder.isDeleted() && "Destructed instance used (!)");
      |                     ^~~~~~~~~
/home/xisco/libreoffice/svl/source/items/itemset.cxx: In member function ‘bool SfxPoolItemHolder::operator==(const SfxPoolItemHolder&) const’:
/home/xisco/libreoffice/svl/source/items/itemset.cxx:139:13: error: ‘isDeleted’ was not declared in this scope
  139 |     assert(!isDeleted() && "Destructed instance used (!)");
      |             ^~~~~~~~~
/home/xisco/libreoffice/svl/source/items/itemset.cxx:140:21: error: ‘const class SfxPoolItemHolder’ has no member named ‘isDeleted’
  140 |     assert(!rHolder.isDeleted() && "Destructed instance used (!)");
      |                     ^~~~~~~~~
make[1]: *** [/home/xisco/libreoffice/solenv/gbuild/LinkTarget.mk:337: /home/xisco/libreoffice/workdir/CxxObject/svl/source/items/itemset.o] Error 1
In file included from /usr/include/c++/12/cassert:44,
                 from /home/xisco/libreoffice/include/svl/itemset.hxx:23,
                 from /home/xisco/libreoffice/include/svl/setitem.hxx:25,
                 from /home/xisco/libreoffice/svl/source/items/itempool.cxx:21:
/home/xisco/libreoffice/include/svl/itemset.hxx: In member function ‘SfxItemPool& SfxPoolItemHolder::getPool() const’:
/home/xisco/libreoffice/include/svl/itemset.hxx:64:44: error: ‘isDeleted’ was not declared in this scope
   64 |     SfxItemPool& getPool() const { assert(!isDeleted() && "Destructed instance used (!)"); return *m_pPool; }
      |                                            ^~~~~~~~~
/home/xisco/libreoffice/include/svl/itemset.hxx: In member function ‘const SfxPoolItem* SfxPoolItemHolder::getItem() const’:
/home/xisco/libreoffice/include/svl/itemset.hxx:65:50: error: ‘isDeleted’ was not declared in this scope
   65 |     const SfxPoolItem* getItem() const { assert(!isDeleted() && "Destructed instance used (!)"); return m_pItem; }
      |                                                  ^~~~~~~~~
make[1]: *** [/home/xisco/libreoffice/solenv/gbuild/LinkTarget.mk:337: /home/xisco/libreoffice/workdir/CxxObject/svl/source/items/itempool.o] Error 1
In file included from /usr/include/c++/12/cassert:44,
                 from /home/xisco/libreoffice/include/svl/whichranges.hxx:16,
                 from /home/xisco/libreoffice/include/svl/itemset.hxx:30,
                 from /home/xisco/libreoffice/include/svl/itemprop.hxx:26,
                 from /home/xisco/libreoffice/svl/source/items/itemprop.cxx:23:
/home/xisco/libreoffice/include/svl/itemset.hxx: In member function ‘SfxItemPool& SfxPoolItemHolder::getPool() const’:
/home/xisco/libreoffice/include/svl/itemset.hxx:64:44: error: ‘isDeleted’ was not declared in this scope
   64 |     SfxItemPool& getPool() const { assert(!isDeleted() && "Destructed instance used (!)"); return *m_pPool; }
      |                                            ^~~~~~~~~
/home/xisco/libreoffice/include/svl/itemset.hxx: In member function ‘const SfxPoolItem* SfxPoolItemHolder::getItem() const’:
/home/xisco/libreoffice/include/svl/itemset.hxx:65:50: error: ‘isDeleted’ was not declared in this scope
   65 |     const SfxPoolItem* getItem() const { assert(!isDeleted() && "Destructed instance used (!)"); return m_pItem; }
      |                                                  ^~~~~~~~~
make[1]: *** [/home/xisco/libreoffice/solenv/gbuild/LinkTarget.mk:337: /home/xisco/libreoffice/workdir/CxxObject/svl/source/items/itemprop.o] Error 1
make: *** [Makefile:290: build] Error 2

Change-Id: I0f61738d4afbdfc06b372d6c5e5fff6f9f9f4e65
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/161142
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
(cherry picked from commit e9e3576ada06d53de12efed041fb309fe5388e01)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/161214