UBSan apparently needs ScScenariosObj etc. RTTI now
...presumably since 68f3831bed8907ad67df666e0a7b90dccc665253 "use more concrete
UNO classes", seeing e.g. CppunitTest_sc_filters_test fail with

> DynamicLibraryManagerException: "Failed to load dynamic library: /home/sberg/lo-asanubsan/core/workdir/LinkTarget/CppunitTest/libtest_sc_filters_test.so
> /home/sberg/lo-asanubsan/core/instdir/program/libscfiltlo.so: undefined symbol: _ZTI14ScScenariosObj"

etc.

Change-Id: Iaaf46935d349a8c5f4734602a964d546ebfa51a0
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/200095
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>