fdo#77979: sw: RTF export: write non-ASCII font names encoded
Currently font names like "微软雅黑" (Microsoft YaHei) are
written as "????" in the RTF export; to avoid that, set the \fcharset
of the font entry to something that at least is able to encode
the font name and alternate name.

This requires a new function since the existing
rtl_TextEncodingToWinCharset was changed in
b88fe998ce8c80d7629fe70118311096615d959d to return "default" 0x01
(for OOXML) which is quite unhelpful for RTF.

This is not entirely satisfactory, as of course that is no guarantee
that the encoding can represent all of the actual text that has the
font applied; hence there are some \'3f in the fall-back encoded text
of the heading of the bugdoc, which indicates that the detected
Shift-JIS is insufficient and GB-2132 would be required; but it's not
obvious how to do better here without iterating over all the text
twice, and that still leaves the possibility that all text that has a
particular font applied cannot be represented by a single non-Unicode
encoding.

But since we always write text as the \u Unicode + legacy fall-back,
this should not be a big problem since modern RTF readers will simply
read the Unicode.

(cherry picked from commit e47a02b1524061143d8e77a54eb95c77f2e6dae2)

fdo#77979: argh forgot to add the test document
(cherry picked from commit 90b2b378aecfa1914be0ce9aa7aa4e006e225e96)

(cherry picked from commit 276fb59ee66806709382d0eeef20f62a094a5995)

error C2361: initialization of 's_fallbacks' is skipped by 'default'
(cherry picked from commit f3695bbc17a547b547876dd1175c0b74e5b3e90e)

Conflicts:
	sw/source/filter/ww8/rtfattributeoutput.cxx

Change-Id: Ie6a42294c501d014dd9f0df82638519412ca19bb

Spell out UTF-8

Change-Id: Iea5f79fb12ac86d4348f46f8ad93a13aaf0f7eb6
(cherry picked from commit 809c8d4c990e77cd8ba52672be7c5e77aae4e90e)