Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/52860/ : FAILURE

error "value of type "SectionType" is not implicitly convertible to "int"" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sw/inc/section.hxx:49:34 ( https://ci.libreoffice.org/job/gerrit_mac/57247/ )

error: value of type "SectionType" is not implicitly convertible to "int" in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sw/inc/section.hxx ( https://ci.libreoffice.org/job/gerrit_mac/57247/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1