Update patch set 2
Patch Set 2:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/99800/ : FAILURE

error "‘SC_PIVOT_STYLE_PROG_TOP’ defined but not used [-Werror=unused-variable]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sc/inc/stylehelper.hxx:37:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/103448/ )

error: ‘SC_PIVOT_STYLE_PROG_TOP’ defined but not used [-Werror=unused-variable] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sc/inc/stylehelper.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/103448/ )

compiler warning unused-variable treated as error: ‘SC_PIVOT_STYLE_PROG_TOP’ defined but not used in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sc/inc/stylehelper.hxx:37:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/103448/ )

Patch-set: 2