Update patch set 14
Patch Set 14: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/63227/ : FAILURE

error: externally available entity "AlphabetsMathType" is not previously declared in an included file (if it is only used in this translation unit, make it static or put it in an unnamed namespace; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/starmath/source/mathtype.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/65968/ )

clang plugin external did trigger. externally available entity "AlphabetsMathType" is not previously declared in an included file (if it is only used in this translation unit, make it static or put it in an unnamed namespace; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/65968/ )

Patch-set: 14
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1