Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/92222/ : FAILURE

Visual studio complained about error C2676: binary "+": "rtl::OUString" does not define this operator or a conversion to a type acceptable to the predefined operator in file C:/cygwin64/home/tdf/lode/jenkins/workspace/gerrit_windows/jvmfwk/source/framework.cxx(214) ( https://ci.libreoffice.org/job/gerrit_windows/103045/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1