use C++ header <cstring> instead of string.h
This also fixes build error 'strlen' is not a member of 'std'
(unoidl/source/sourcetreeprovider.cxx:77)

Change-Id: I587ef2c38fd9377eef2073a49cd8497b2bd4bf9f