Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/115110/ : FAILURE

build likely got stuck and was aborted due to not producing any output to the log ( https://ci.libreoffice.org/job/gerrit_windows/127357/ )

Visual studio complained about error C2059: syntax error: "*" in file C:/cygwin/home/tdf/jenkins/workspace/gerrit_windows/comphelper/source/streaming/memorystream.cxx(92) ( https://ci.libreoffice.org/job/gerrit_windows/127357/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000083 \u003c1000083@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}