Update patch set 16
Patch Set 16:

(1 comment)

Error: Failed to execute /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/solenv/bin/uiex -i /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/svx/uiconfig/ui/sidebareffect.ui -o /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/workdir//pot/svx/messages.pot


→ so it is sidebareffect.ui that it stumbles upon (at least the first file that is affected, didn't check the other ones) - to check that locally, do "make l10ntools.all && make translations" (make translations runs the pot2po, and requires stuff from l10ntools to be built, but not the whole rest of LibreOffice, so should be relatively quick)

see comment for where it falls flat.

Patch-set: 16
CC: Gerrit User 1000027 <1000027@6622c302-437a-49ad-a91d-55ba7dcf1615>