Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/17580/ : FAILURE

error "struct "XWindow" was previously declared as a class [-Werror,-Wmismatched-tags]" triggered in included file ( https://ci.libreoffice.org/job/gerrit_mac/18281/ )

error: struct "XWindow" was previously declared as a class [-Werror,-Wmismatched-tags] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/dbaccess/source/ui/inc/UITools.hxx ( https://ci.libreoffice.org/job/gerrit_mac/18281/ )

Patch-set: 3
Label: Verified=-1