Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/39744/ : FAILURE

clang plugin unusedvariablecheck did trigger. unused variable "aRemainingSeries" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/42818/ )

error: unused variable "aRemainingSeries" [loplugin:unusedvariablecheck] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/xmloff/source/chart/SchXMLTableContext.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/42818/ )

Patch-set: 3
Label: Verified=-1