Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/35292/ : FAILURE

error: use "true" instead of "sal_True" [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/treelist/transfer.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/38023/ )

clang plugin salbool did trigger. use "true" instead of "sal_True" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/38023/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1