Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://cpci.cbg.collabora.co.uk:8080/job/Gerrit%20for%20co-2021/1306/ : FAILURE

Visual studio complained about error C2440: "reinterpret_cast": cannot convert from "long" to "tools::Long" in file C:/lo/jenkins/workspace/gerrit_windows_co-2021_32bit/sfx2/source/view/ipclient.cxx(96) ( https://cpci.cbg.collabora.co.uk:8080/job/gerrit_windows_co-2021_32bit/1191/ )

Patch-set: 3
Tag: autogenerated:jenkins-gerrit-trigger
Reviewer: Gerrit User 1002181 <1002181@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1