Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/91784/ : FAILURE

error "‘OUString’ was not declared in this scope" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/include/unotools/optionsdlg.hxx:31:33 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/95692/ )

error: ‘OUString’ was not declared in this scope in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/include/unotools/optionsdlg.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/95692/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/95692/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1