CppunitTest_sc_subsequent_export_test4: fix build
/home/vmiklos/git/libreoffice/co-26.04/sc/qa/unit/subsequent_export_test4.cxx: In member function ‘void testUserDefinedFunctions::TestBody()’:
/home/vmiklos/git/libreoffice/co-26.04/sc/qa/unit/subsequent_export_test4.cxx:2565:10: error: cannot convert ‘rtl::OUString’ to ‘TestFilter’
 2565 |     save(u"Calc Office Open XML"_ustr);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          |
      |          rtl::OUString

Similar for CppunitTest_sd_export_tests-ooxml4, too.

Went wrong in commit c2a46dc1ca02e9b682248099ef08e01e8f26dc92 (PPTX: Use
correct shape-id for connector shapes, 2026-03-21).

Change-Id: Ibfb084911fbd6d1266db32207b03861fb536c885
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/202323
Reviewed-by: Andras Timar <andras.timar@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>