Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/7027/ : FAILURE

Visual studio complained about error C2440: "return": cannot convert from "std::unique_ptr<SdrView,std::default_delete<_Ty>>" to "SdrView *" in file C:cygwinhometdflodejenkinsworkspacelo_gerritConfigwindows_msc_dbgutil_32swincunodraw.hxx(50) ( https://ci.libreoffice.org/job/gerrit_windows/6939/ )

Patch-set: 2
Label: Verified=-1