Update patch set 27
Patch Set 27:

> Patch Set 27:
> 
> > > Oh! Okay so, would version:1.0.8+ds2-2build1 corresponds to your version or do I have to install some previous version.
> > 
> > And also we use system library by giving the command --with-system-zxing right?
> 
> Yes and yes.
> It might be something wrong with my Ubuntu system; it segfaults on every dtor of objects from that library.
> 
> Just to double-check: could you please confirm that it works after you do
> 
>   make zxing.clean
> 
> and then
> 
>   make
> 
> ? If it works there, I suppose we are ready to merge, and I will consider my local crash as misconfigured system. Thanks!

FWIW, I have

test_insert_qr_code_gen (insertQrCodeGen.insertQrCode) ... OfficeConnection: connecting to: uno:pipe,name=pyteste0956f3a-8991-11eb-97a1-2016b9f1e514;urp;StarOffice.ComponentContext
NoConnectException: sleeping...
['OnNew']
OnCreate
['OnNew']
OnStorageChanged
['OnNew']
OnTitleChanged
['OnNew']
OnFocus
['OnNew']
OnViewCreated
['DialogExecute']
OnModeChanged
['DialogClosed']
OnModeChanged
['DialogExecute']
OnModeChanged
Execution time for insertQrCodeGen.insertQrCode.test_insert_qr_code_gen: 0.974
tearDown: calling terminate()...
...done
ok
test_insert_qr_code_gen2 (insertQrCodeGen.insertQrCode) ... OfficeConnection: connecting to: uno:pipe,name=pyteste1d0bca6-8991-11eb-97a1-2016b9f1e514;urp;StarOffice.ComponentContext
NoConnectException: sleeping...
['OnNew']
OnCreate
['OnNew']
OnStorageChanged
['OnNew']
OnTitleChanged
['OnNew']
OnFocus
['OnNew']
OnViewCreated
['DialogExecute']
OnModeChanged
Execution time for insertQrCodeGen.insertQrCode.test_insert_qr_code_gen2: 0.652
tearDown: calling terminate()...
...done
ok

so the test at least passes. Though with 1.1.1 from Debian unstable. Didn't try on a "real use with GUI" LO.

Patch-set: 27
Reviewer: Gerrit User 1000130 <1000130@6622c302-437a-49ad-a91d-55ba7dcf1615>