Fix build
...after 840b4eb2f3443ff883016e6a8a8ae49e9cbd9e4e "Recheck modules [a-c]* with
IWYU" causing

> In file included from workdir/UnpackedTarball/cppunit/include/cppunit/TestAssert.h:8,
>                  from workdir/UnpackedTarball/cppunit/include/cppunit/TestCase.h:6,
>                  from workdir/UnpackedTarball/cppunit/include/cppunit/TestCaller.h:5,
>                  from workdir/UnpackedTarball/cppunit/include/cppunit/extensions/HelperMacros.h:9,
>                  from cppu/qa/test_any.cxx:26:
> workdir/UnpackedTarball/cppunit/include/cppunit/tools/StringHelper.h: In instantiation of ‘typename std::enable_if<(! std::is_enum<_Tp>::value), std::__cxx11::basic_string<char> >::type CppUnit::StringHelper::toString(const T&) [with T = char16_t; typename std::enable_if<(! std::is_enum<_Tp>::value), std::__cxx11::basic_string<char> >::type = std::__cxx11::basic_string<char>]’:
> workdir/UnpackedTarball/cppunit/include/cppunit/TestAssert.h:74:50:   required from ‘static std::string CppUnit::assertion_traits<T>::toString(const T&) [with T = char16_t; std::string = std::__cxx11::basic_string<char>]’
> workdir/UnpackedTarball/cppunit/include/cppunit/TestAssert.h:168:58:   required from ‘void CppUnit::assertEquals(const T&, const T&, SourceLine, const std::string&) [with T = char16_t; std::string = std::__cxx11::basic_string<char>]’
> cppu/qa/test_any.cxx:282:9:   required from here
> workdir/UnpackedTarball/cppunit/include/cppunit/tools/StringHelper.h:25:9: error: use of deleted function ‘std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, char16_t) [with _Traits = char_traits<char>]’
>    25 |     ost << x;
>       |     ~~~~^~~~
> In file included from ~/gcc/trunk/inst/include/c++/12.0.0/istream:39,
>                  from ~/gcc/trunk/inst/include/c++/12.0.0/sstream:38,
>                  from workdir/UnpackedTarball/cppunit/include/cppunit/portability/Stream.h:283,
>                  from workdir/UnpackedTarball/cppunit/include/cppunit/TestAssert.h:7,
>                  from workdir/UnpackedTarball/cppunit/include/cppunit/TestCase.h:6,
>                  from workdir/UnpackedTarball/cppunit/include/cppunit/TestCaller.h:5,
>                  from workdir/UnpackedTarball/cppunit/include/cppunit/extensions/HelperMacros.h:9,
>                  from cppu/qa/test_any.cxx:26:
> ~/gcc/trunk/inst/include/c++/12.0.0/ostream:558:5: note: declared here
>   558 |     operator<<(basic_ostream<char, _Traits>&, char16_t) = delete;
>       |     ^~~~~~~~

etc.

Change-Id: I2e6d3591dec9eeb6647738d37296c7d2bfa6a186
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/128369
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>