Update patch set 8
Patch Set 8: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/74989/ : FAILURE

error: redundant functional cast from "bool" to "bool" [loplugin:redundantcast] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/qa/cppunit/BinaryDataContainerTest.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/77114/ )

clang plugin redundantcast did trigger. redundant functional cast from "bool" to "bool" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/77114/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/77114/ )

the cppunit test CppunitTest_dbaccess_firebird_regression failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/77114/ )

the test UITest_hideShowSheet failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/77114/ )

Patch-set: 8
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1