Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/42115/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "const char *" to "rtl::OUString" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sw/source/uibase/dochdl/swdtflvr.cxx(1455) ( https://ci.libreoffice.org/job/gerrit_windows/48707/ )

Patch-set: 2
Label: Verified=-1