Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/77661/ : FAILURE

error "static_assert failed due to requirement "std::is_signed_v<std::common_type_t<sal_Int64, unsigned long> >"" triggered in included file /home/tdf/lode/jenkins/workspace/android_x86_64/include/tools/UnitConversion.hxx:24:5 ( https://ci.libreoffice.org/job/gerrit_android_x86_64/2339/ )

error: static_assert failed due to requirement "std::is_signed_v<std::common_type_t<sal_Int64, unsigned long> >" in file /home/tdf/lode/jenkins/workspace/android_x86_64/include/tools/UnitConversion.hxx ( https://ci.libreoffice.org/job/gerrit_android_x86_64/2339/ )

Patch-set: 6
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1