Update patch set 2
Patch Set 2:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/17980/ : FAILURE

Visual studio complained about error C2819: type "GlyphItem" does not have an overloaded member "operator ->" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/vcl/win/gdi/salfont.cxx(1368) ( https://ci.libreoffice.org/job/gerrit_windows/20094/ )

Patch-set: 2