sc: uitest: fix sporadic test failures
Sometimes theses tests fail with

======================================================================
FAIL: test_tdf153972 (tdf153972.tdf153972)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64_branch/sc/qa/uitest/autofilter2/tdf153972.py", line 37, in test_tdf153972
    self.assertEqual('Lime', get_state_as_dict(xSubMenu.getChild('0'))['Text'])
AssertionError: 'Lime' != '#81D41A'
- Lime
+ #81D41A

======================================================================
FAIL: test_tdf95520 (tdf95520.tdf95520)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64_branch/sc/qa/uitest/autofilter2/tdf95520.py", line 36, in test_tdf95520
    self.assertEqual('Red', get_state_as_dict(xSubMenu.getChild('1'))['Text'])
AssertionError: 'Red' != '#FF0000'
- Red
+ #FF0000

See https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil_branch/10807/consoleFull#4610001379567f988-cbcf-4519-af05-6000b834f13f

and I believe the reason is the color palette fails to load in
sc/source/ui/view/gridwin.cxx:752 and then its not able to
translate #81D41A to Lime.
Adapt the test and document to use colors without a color name

Change-Id: Ie1119fe0ff31147b5395076969e41481706d8dfb
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/152897
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>