Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/87955/ : FAILURE

error: unused variable "aSeriesVector" [loplugin:unusedvariablecheck] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/source/tools/DiagramHelper.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/89236/ )

clang plugin unusedvariablecheck did trigger. unused variable "aSeriesVector" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/89236/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1