Update patch set 3
Patch Set 3:

/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Linux/sw/source/core/txtnode/ndtxt.cxx: In member function ‘virtual void SwTxtNode::Update(const SwIndex&, sal_Int32, bool, bool)’:
/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Linux/sw/source/core/txtnode/ndtxt.cxx:1063:28: error: unused variable ‘isOneUsed’ [-Werror=unused-variable]
                 bool const isOneUsed(&pRedl->GetBound(true) == pRedl->GetPoint());

FAILED it is not caused file patch.  Rebasing...

Patch-set: 3
Label: Verified=0