Update patch set 1
Patch Set 1:

this is based on a wrong revision of that other patch, which was also pushed to libreoffice-5-4 instead of my fixed one...

/home/tdf/lode/jenkins/workspace/lo_gerrit_54/linux_clang_dbgutil_64/sax/source/fastparser/fastparser.cxx:638:18: error: unknown log area 'sax.fastparser' (check or extend include/sal/log-areas.dox) [loplugin:sallogareas]
        SAL_INFO("sax.fastparser", "discarding exception, already have one");

Patch-set: 1