VclPtr requires its reference type to be defined
... at least with MSVC:

  [build CXX] oox/source/core/filterbase.cxx
  C:\lo\src\core\include\rtl/ref.hxx(129): error C2027: use of undefined type 'OutputDevice'
  C:\lo\src\core\include\oox/helper/graphichelper.hxx(50): note: see declaration of 'OutputDevice'
  C:\lo\src\core\include\rtl/ref.hxx(127): note: while compiling class template member function 'rtl::Reference<reference_type>::~Reference(void)'
  with
  [
  reference_type=OutputDevice
  ]
  C:\lo\src\core\include\vcl/vclptr.hxx(216): note: see reference to function template instantiation 'rtl::Reference<reference_type>::~Reference(void)' being comp
  iled
  with
  [
  reference_type=OutputDevice
  ]
  C:\lo\src\core\include\vcl/vclptr.hxx(64): note: see reference to class template instantiation 'rtl::Reference<reference_type>' being compiled
  with
  [
  reference_type=OutputDevice
  ]
  C:\lo\src\core\include\oox/helper/graphichelper.hxx(140): note: see reference to class template instantiation 'VclPtr<OutputDevice>' being compiled
  make[1]: *** [C:/lo/src/core/solenv/gbuild/LinkTarget.mk:301: C:/lo/src/build/workdir/CxxObject/oox/source/core/filterbase.o] Error 2

Change-Id: I50ee1bf97b7075224525525ef074c0ffcc168485