xmlsecurity: fix --without-system-nss build
signing2.cxx:71: error: undefined reference to 'NSS_OptionSet'

(regression from commit f0efcb917049547ad0496c004830ff0153602071)

Change-Id: Idad3f7d5d1a2cb642ac3485a750cdc7631fbf4df
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/179954
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>
Tested-by: Jenkins
(cherry picked from commit b57f1f7be140c5c69136e2b5c8b8826b1b27141a)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/179961
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>