Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/62550/ : FAILURE

error: no need to explicitly init an instance of "oox::drawingml::ShapePtr" (aka "shared_ptr<oox::drawingml::Shape>") with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/oox/source/ppt/pptshapecontext.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/65355/ )

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "oox::drawingml::ShapePtr" (aka "shared_ptr<oox::drawingml::Shape>") with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/65355/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1