Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/43581/ : FAILURE

error: no need to explicitly init an instance of "std::unique_ptr<connectivity::OSQLParseNode>" with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/connectivity/source/drivers/mork/MStatement.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/47044/ )

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "std::unique_ptr<connectivity::OSQLParseNode>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/47044/ )

Patch-set: 1
Label: Verified=-1