Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/63696/ : FAILURE

Visual studio complained about error C2819: type "`anonymous-namespace"::ScopedTrueTypeFont" does not have an overloaded member "operator ->" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/vcl/win/gdi/salfont.cxx(1751) ( https://ci.libreoffice.org/job/gerrit_windows/72738/ )

Patch-set: 5
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1