try wait_until_property_is_updated in test_tdf134390
======================================================================
FAIL: test_tdf134390 (navigator.navigator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/qa/uitest/calc_tests8/navigator.py", line 143, in test_tdf134390
    self.assertEqual(get_state_as_dict(xColumn)['Value'], '2')
AssertionError: '1' != '2'
- 1
+ 2

Change-Id: I7c781191facd10abbb25f895cb0d2bacb72d92ab
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/139933
Tested-by: Jenkins
Reviewed-by: Caolán McNamara <caolanm@redhat.com>
(cherry picked from commit 434f6a1b5a5089ff276918f9756501c91e146759)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/139974