tdf#162769 android nss/nspr: Drop '-D_PR_NO_LARGE_FILES=1'
The `-D_PR_NO_LARGE_FILES=1` configure option causes a

    --with-android-ndk=$HOME/Android/Sdk/ndk/26.1.10909125/
    --with-android-sdk=$HOME/Android/Sdk
    --with-distro=LibreOfficeAndroidX86_64

Android build (with NDK 26) to fail like this:

    [...]
    checking whether /usr/bin/ccache /home/michi/Android/Sdk/ndk/26.1.10909125//toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target x86_64-linux-android21 -no-canonical-prefixes -ffunction-sections -fdata-sections -Qunused-arguments -glldb -Xclang -debug-info-kind=constructor -D_PR_NO_LARGE_FILES=1 -DSQLITE_DISABLE_LFS=1 accepts -pthread... yes
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating config/Makefile
    config.status: creating config/autoconf.mk
    config.status: creating config/nsprincl.mk
    config.status: creating config/nsprincl.sh
    config.status: creating config/nspr-config
    config.status: creating config/nspr.pc
    config.status: creating lib/Makefile
    config.status: creating lib/ds/Makefile
    config.status: creating lib/libc/Makefile
    config.status: creating lib/libc/include/Makefile
    config.status: creating lib/libc/src/Makefile
    config.status: creating lib/tests/Makefile
    config.status: creating pkg/Makefile
    config.status: creating pr/Makefile
    config.status: creating pr/include/Makefile
    config.status: creating pr/include/md/Makefile
    config.status: creating pr/include/obsolete/Makefile
    config.status: creating pr/include/private/Makefile
    config.status: creating pr/src/Makefile
    config.status: creating pr/src/io/Makefile
    config.status: creating pr/src/linking/Makefile
    config.status: creating pr/src/malloc/Makefile
    config.status: creating pr/src/md/Makefile
    config.status: creating pr/src/md/unix/Makefile
    config.status: creating pr/src/memory/Makefile
    config.status: creating pr/src/misc/Makefile
    config.status: creating pr/src/threads/Makefile
    config.status: creating pr/tests/Makefile
    config.status: creating pr/tests/dll/Makefile
    config.status: creating pr/src/pthreads/Makefile
    config.status: executing default commands
    ../../../../../pr/src/md/unix/unix.c:2742:27: error: incompatible function pointer types assigning to '_MD_Fstat64' (aka 'int (*)(int, struct stat64 *)') from 'int (int, struct stat * _Nonnull)' [-Wincompatible-function-pointer-types]
        _md_iovector._fstat64 = fstat;
                              ^ ~~~~~
    ../../../../../pr/src/md/unix/unix.c:2743:26: error: incompatible function pointer types assigning to '_MD_Stat64' (aka 'int (*)(const char *, struct stat64 *)') from 'int (const char * _Nonnull, struct stat * _Nonnull)' [-Wincompatible-function-pointer-types]
        _md_iovector._stat64 = stat;
                             ^ ~~~~
    ../../../../../pr/src/md/unix/unix.c:3288:61: warning: passing 'int *' to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
        if (getsockopt(osfd, SOL_SOCKET, SO_ERROR, (char*)&err, &optlen) == -1) {
                                                                ^~~~~~~
    /home/michi/Android/Sdk/ndk/26.1.10909125//toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/sys/socket.h:304:92: note: passing argument to parameter '__value_length' here
    __socketcall int getsockopt(int __fd, int __level, int __option, void* __value, socklen_t* __value_length);
                                                                                               ^
    1 warning and 2 errors generated.

A similar build issue for Android API levels < 21
was fixed in NSPR commit [1] ("Bug 1784193 - Cast values when
setting _md_iovector._{f,}stat64 on Android API < 21.")

Patching nss/nspr to apply a similar change for the

    #elif defined(_PR_NO_LARGE_FILES)

code there would fix this issue, too (see initial description
in tdf#162769).

However, it seems that the `-D_PR_NO_LARGE_FILES=1` configure
flag for NSS/NSPR, originally added in

    commit 4082a18406c18af7b4fcef7bd501c3679c3be56b
    Date:   Wed Nov 22 23:08:06 2017 +0100

        android: use unified headers and llvm-c++ STL (x86) with NDK 16

is no longer necessary these days, so drop it.

(Potentially, more of the disabling of large file support
introduced in the above-mentioned commit is no longer
needed now or at least when bumping the minSdkVersion further.
Section [2] on the "32-bit ABI bugs" page has some more details
on large file support in different Android/NDK
versions and mentions "by API 24 you have everything including
<stdio.h>" - while our current `minSdkVersion` is 21.)

Building and running Android Viewer and opening files (including a
password-protected one, which is where NSS might be involved) worked
fine in a quick test with these build/device configurations:

* Android x86_64 AVD with API 35 (Android 15.0),
  NDK 26.1.10909125,
 `--with-distro=LibreOfficeAndroidX86_64`

* Samsung Galaxy S4 GT-I9505 (32 bit ARM) LineageOS 17.1
  (based on Android 10), NDK 25.2.9519653,
  `--with-distro=LibreOfficeAndroid`

Tests with a build with this change in place using the latest NDK 28.0.13004108
also worked fine on the above 2 devices (x86_64, 32-bit ARM)
and a Fairphone 3+ (aarch64, LineageOS 21, based on Android 14)
and an x86 AVD (API 24, i.e. Android 7.0).

[1] https://phabricator.services.mozilla.com/D154336
[2] https://android.googlesource.com/platform/bionic/+/refs/heads/main/docs/32-bit-abi.md#32_bit-and

Change-Id: I759c5213b5f5873fc097a6ca0e0f0f85962e421b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/181899
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins
Reviewed-by: Christian Lohmaier <lohmaier+LibreOffice@googlemail.com>
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/192021
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Skyler Grey <skyler.grey@collabora.com>