Avoid -Werror=dangling-pointer=
> vcl/source/bitmap/Octree.cxx: In constructor ‘Octree::Octree(const BitmapReadAccess&, sal_uLong)’:
> vcl/source/bitmap/Octree.cxx:69:17: error: storing the address of local variable ‘aColor’ in ‘*this.Octree::mpColor’ [-Werror=dangling-pointer=]
>    69 |         mpColor = &aColor;
>       |         ~~~~~~~~^~~~~~~~~
> vcl/source/bitmap/Octree.cxx:67:21: note: ‘aColor’ declared here
>    67 |         BitmapColor aColor;
>       |                     ^~~~~~
> vcl/source/bitmap/Octree.cxx:67:21: note: ‘<unknown>’ declared here

(new with GCC 12)

Change-Id: I5b1ffa15b92f2c41dbe51dfa843eb6bab3a4b449
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/128517
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit 5db574727f4564238a54159a1a0673eaa2884b69)