Update patch set 15
Patch Set 15:

Anyway, this change is causing the below -Werror with GCC 9, and it is totally unclear to me (witness my other questions posted here) how that should be fixed properly.  I'm pondering a revert for now if there is no further input forthcoming.

> [CXX] sw/source/core/doc/tblafmt.cxx
> /home/sbergman/lo2/core/sw/source/core/doc/tblafmt.cxx: In member function ‘void SwTableAutoFormat::SetBoxFormat(const SwBoxAutoFormat&, sal_uInt8)’:
> /home/sbergman/lo2/core/sw/source/core/doc/tblafmt.cxx:418:37: error: implicitly-declared ‘SwBoxAutoFormat& SwBoxAutoFormat::operator=(const SwBoxAutoFormat&)’ is deprecated [-Werror=deprecated-copy]
>   418 |         *m_aBoxAutoFormat[ nPos ] = rNew;
>       |                                     ^~~~
> /home/sbergman/lo2/core/sw/source/core/doc/tblafmt.cxx:256:1: note: because ‘SwBoxAutoFormat’ has user-provided ‘SwBoxAutoFormat::SwBoxAutoFormat(const SwBoxAutoFormat&)’
>   256 | SwBoxAutoFormat::SwBoxAutoFormat( const SwBoxAutoFormat& rNew )
>       | ^~~~~~~~~~~~~~~
> cc1plus: all warnings being treated as errors
> make[1]: *** [/home/sbergman/lo2/core/solenv/gbuild/LinkTarget.mk:292: /home/sbergman/lo2/core/workdir/CxxObject/sw/source/core/doc/tblafmt.o] Error 1

> [CXX] sw/source/core/unocore/unostyle.cxx
> /home/sbergman/lo2/core/sw/source/core/unocore/unostyle.cxx: In member function ‘virtual void sw::XStyleFamily::replaceByName(const rtl::OUString&, const com::sun::star::uno::Any&)’:
> /home/sbergman/lo2/core/sw/source/core/unocore/unostyle.cxx:990:66: error: implicitly-declared ‘SwBoxAutoFormat& SwBoxAutoFormat::operator=(const SwBoxAutoFormat&)’ is deprecated [-Werror=deprecated-copy]
>   990 |             *pBoxAutoFormat = *pStyleToReplaceWith->GetBoxFormat();
>       |                                                                  ^
> In file included from /home/sbergman/lo2/core/sw/inc/unostyle.hxx:25,
>                  from /home/sbergman/lo2/core/sw/source/core/unocore/unostyle.cxx:49:
> /home/sbergman/lo2/core/sw/inc/tblafmt.hxx:79:5: note: because ‘SwBoxAutoFormat’ has user-provided ‘SwBoxAutoFormat::SwBoxAutoFormat(const SwBoxAutoFormat&)’
>    79 |     SwBoxAutoFormat( const SwBoxAutoFormat& rNew );
>       |     ^~~~~~~~~~~~~~~
> /home/sbergman/lo2/core/sw/inc/tblafmt.hxx: In member function ‘SwBoxAutoFormat& SwBoxAutoFormat::operator=(const SwBoxAutoFormat&)’:
> /home/sbergman/lo2/core/sw/inc/tblafmt.hxx:64:7: error: implicitly-declared ‘AutoFormatBase& AutoFormatBase::operator=(const AutoFormatBase&)’ is deprecated [-Werror=deprecated-copy]
>    64 | class SwBoxAutoFormat : public AutoFormatBase
>       |       ^~~~~~~~~~~~~~~
> In file included from /home/sbergman/lo2/core/sw/inc/tblafmt.hxx:52,
>                  from /home/sbergman/lo2/core/sw/inc/unostyle.hxx:25,
>                  from /home/sbergman/lo2/core/sw/source/core/unocore/unostyle.cxx:49:
> /home/sbergman/lo2/core/include/svx/autoformathelper.hxx:138:5: note: because ‘AutoFormatBase’ has user-provided ‘AutoFormatBase::AutoFormatBase(const AutoFormatBase&)’
>   138 |     AutoFormatBase( const AutoFormatBase& rNew );
>       |     ^~~~~~~~~~~~~~
> /home/sbergman/lo2/core/sw/source/core/unocore/unostyle.cxx: In member function ‘virtual void sw::XStyleFamily::replaceByName(const rtl::OUString&, const com::sun::star::uno::Any&)’:
> /home/sbergman/lo2/core/sw/source/core/unocore/unostyle.cxx:990:66: note: synthesized method ‘SwBoxAutoFormat& SwBoxAutoFormat::operator=(const SwBoxAutoFormat&)’ first required here
>   990 |             *pBoxAutoFormat = *pStyleToReplaceWith->GetBoxFormat();
>       |                                                                  ^
> cc1plus: all warnings being treated as errors
> make[1]: *** [/home/sbergman/lo2/core/solenv/gbuild/LinkTarget.mk:292: /home/sbergman/lo2/core/workdir/CxxObject/sw/source/core/unocore/unostyle.o] Error 1

Patch-set: 15