Work around strange error seen at least with VS 2022 Preview 17.9.0 Preview 2.0
> vcl/source/pdf/XmpMetadata.cxx(39): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'rtl::OStringLiteral<55>'
> vcl/source/pdf/XmpMetadata.cxx(39): note: Invalid aggregate initialization
> vcl/source/pdf/XmpMetadata.cxx(39): note: too many initializers

(Smells like a bug in that compiler's u8"..." handling, where it maybe gets
tripped by the 3-byte UTF-8 encoding of \uFEFF?)

Change-Id: I1c6a856a67c8328ed5fcc2f2fa6bb26f16319f55
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/160681
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
(cherry picked from commit 297a6673175308168669870882c016b496652a76)