Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/87925/ : FAILURE

error: variable "sPath" of type "const rtl::OStringLiteral<148>" with automatic storage duration most likely needs to be static [loplugin:stringliteralvar] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/extras/ooxmlexport/ooxmlexport16.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/89208/ )

clang plugin stringliteralvar did trigger. variable "sPath" of type "const rtl::OStringLiteral<148>" with automatic storage duration most likely needs to be static ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/89208/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1