Update patch set 5
Patch Set 5: Code-Review-1

looks like you need to adapt the declaration of getIndexOf in some header file, for consistency:

C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/reportdesign/source/core/sdr/RptPage.cxx(58): error C2556: 'size_t rptui::OReportPage::getIndexOf(const com::sun::star::uno::Reference<com::sun::star::report::XReportComponent> &)': overloaded function differs only by return type from 'sal_uLong rptui::OReportPage::getIndexOf(const com::sun::star::uno::Reference<com::sun::star::report::XReportComponent> &)'

Patch-set: 5
Reviewer: Gerrit User 1000022 <1000022@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Code-Review=-1