android: Add missing make dependency
After

    commit f9b9e702465b4de29153b49e077c70a0ad78c89d
    Author: Michael Weghorn <m.weghorn@posteo.de>
    Date:   Wed Nov 15 13:26:38 2023 +0100

        android: Add button to open privacy URL

, Android Jenkins builds started to fail intermittently
(e.g. [1]) like this:

    > Task :stripStrippedUIEditingDebugDebugSymbols

    > Task :compileStrippedUIEditingDebugJavaWithJavac FAILED
    /home/tdf/lode/jenkins/workspace/android_x86/android/source/src/java/org/libreoffice/AboutDialogFragment.java:93: error: cannot find symbol
            final String privacyUrl = BuildConfig.PRIVACY_POLICY_URL;
                                                 ^
      symbol:   variable PRIVACY_POLICY_URL
      location: class BuildConfig
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    1 error

    FAILURE: Build failed with an exception.

This seems due to the pre-existing issue of a missing
dependency of the `liboSettings.gradle` target on
`android/Bootstrap/Makefile.shared`, so a change
to the latter would not have caused the former
to be regenerated and any old one still around
that didn't set the new build config variable
would get used, resulting in the above error.

Issue reproducible locally:

* do a local Android master build
* `git revert f9b9e702465b4de29153b49e077c70a0ad78c89d`
* `rm android/source/liboSettings.gradle`
* `make`
* `git cherry-pick f9b9e702465b4de29153b49e077c70a0ad78c89d`
* `make`

[1] https://ci.libreoffice.org/job/gerrit_android_x86/33773/console

Change-Id: I87275fc71d93f460dfad4d75fc197b8ed8cd9922
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/159497
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>