error: no matching function for call to 'assertEquals'
Change-Id: I0b87c2abeec30e9e4eab3ce488a5828b8a5b475d
(cherry picked from commit 4a3b0e544dbc45a3972006a2ead75492d6876f95)
Signed-off-by: Michael Stahl <mstahl@redhat.com>