Copy from rSource, not from *this
...which had been the case ever since 3a08fe4de389fae0add26bb64a4567b70d1bb91c
"INTEGRATION: CWS notes2 (1.1.2); FILE ADDED", but caused

> filter/source/msfilter/msdffimp.cxx: In constructor ‘SvxMSDffManager::SvxMSDffManager(SvStream&, rtl::OUString)’:
> filter/source/msfilter/msdffimp.cxx:5810:24: error: ‘<unknown>’ may be used uninitialized [-Werror=maybe-uninitialized]
>  5810 |      mbSkipImages(false)
>       |                        ^
> filter/source/msfilter/msdffimp.cxx:239:1: note: by argument 2 of type ‘const SvxMSDffManager&’ to ‘DffPropertyReader::DffPropertyReader(const SvxMSDffManager&)’ declared here
>   239 | DffPropertyReader::DffPropertyReader( const SvxMSDffManager& rMan )
>       | ^~~~~~~~~~~~~~~~~
> filter/source/msfilter/msdffimp.cxx: In constructor ‘SvxMSDffManager::SvxMSDffManager(SvStream&, rtl::OUString, sal_uInt32, SvStream*, SdrModel*, tools::Long, Color, SvStream*, bool)’:
> filter/source/msfilter/msdffimp.cxx:5769:31: error: ‘<unknown>’ may be used uninitialized [-Werror=maybe-uninitialized]
>  5769 |      mbSkipImages (bSkipImages)
>       |                               ^
> filter/source/msfilter/msdffimp.cxx:239:1: note: by argument 2 of type ‘const SvxMSDffManager&’ to ‘DffPropertyReader::DffPropertyReader(const SvxMSDffManager&)’ declared here
>   239 | DffPropertyReader::DffPropertyReader( const SvxMSDffManager& rMan )
>       | ^~~~~~~~~~~~~~~~~

at least with --disable-optimized against recent GCC 16 trunk

Change-Id: Ie908dba33d426f72f7819b3db0651a60cb3004c7
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/193060
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>
(cherry picked from commit d1d7660f39d2147e3fb5b132b8da782505186e1b)