solenv: remove no longer needed OptionalBox widget factory
Not needed since commit 2d0944ab7a94ea0d5cd5f66c4895a0c99d9a3593
(Resolves: tdf#130513 sfxlo-OptionalBox isn't in sfx, 2020-02-08).

Fixes this Android build error:

/tmp/native-code-7aaa80.o:native-code.cxx:custom_widgets: error: undefined reference to 'makeOptionalBox'

Change-Id: Ib03c9516963e6b14c57ecfca9c7f78132dea2059