Update patch set 6
Patch Set 6:

Looks like this breaks the DISABLE_DYNLOADING case, see

> Message-ID: <284112.039112614-sendEmail@libreoffice2>
> From: "lohmaier+libreoffice@googlemail.com" <lohmaier+libreoffice@googlemail.com>
> Subject: Tinderbox failure, Android-ARM@24-Bytemark-Hosting, MASTER, last success: 2019-08-28 05:20:07
> Date: Wed, 28 Aug 2019 07:18:40 +0000

> [build CXX] vcl/source/window/introwin.cxx
> /home/android/lo/master-android-arm/vcl/source/window/builder.cxx:2191:9: error: use of undeclared identifier 'ModuleMap'
>         ModuleMap::iterator aI = g_aModuleMap.find("libsfxlo.so");
>         ^
> /home/android/lo/master-android-arm/vcl/source/window/builder.cxx:2191:34: error: use of undeclared identifier 'g_aModuleMap'
>         ModuleMap::iterator aI = g_aModuleMap.find("libsfxlo.so");
>                                  ^
> 2 errors generated.

Patch-set: 6