Update patch set 31
Patch Set 31: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/96382/ : FAILURE

Visual studio complained about error C2440: "return": cannot convert from "vcl::font::PhysicalFontFamily *" to "vcl::PhysicalFontFamily *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/vcl/win/gdi/salfont.cxx(253) ( https://ci.libreoffice.org/job/gerrit_windows/107346/ )

Patch-set: 31
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000295 \u003c1000295@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}