Don't set _POSIX_C_SOURCE, _XOPEN_SOURCE in pyconfig.h on Linux
...which causes

> In file included from pyuno/source/module/pyuno_struct.cxx:28:
> In file included from pyuno/source/module/pyuno_impl.hxx:26:
> In file included from workdir/UnpackedTarball/python3/Include/Python.h:12:
> workdir/UnpackedTarball/python3/pyconfig.h:1874:9: error: '_POSIX_C_SOURCE' macro redefined [-Werror,-Wmacro-redefined]
>  1874 | #define _POSIX_C_SOURCE 200809L
>       |         ^
> /usr/include/features.h:319:10: note: previous definition is here
>   319 | # define _POSIX_C_SOURCE        202405L
>       |          ^
> In file included from pyuno/source/module/pyuno_struct.cxx:28:
> In file included from pyuno/source/module/pyuno_impl.hxx:26:
> In file included from workdir/UnpackedTarball/python3/Include/Python.h:12:
> workdir/UnpackedTarball/python3/pyconfig.h:1895:9: error: '_XOPEN_SOURCE' macro redefined [-Werror,-Wmacro-redefined]
>  1895 | #define _XOPEN_SOURCE 700
>       |         ^
> /usr/include/features.h:234:10: note: previous definition is here
>   234 | # define _XOPEN_SOURCE  800
>       |          ^

when building against glibc-devel-2.43-2.fc44.x86_64.  And it's not a good idea
anyway to have Python.h (which we typically don't include as the very first
file) override those macros when we are already deep into a translation unit.
So suppress those macro settings also at least for my
"Linux/6.19.6-300.fc44.x86_64/" case (and it probably doesn't hurt to
universally suppress it for all Linux flavors).

Change-Id: Ia055ae056d917ce91299f0d84bc2538e44861e23
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/201430
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
(cherry picked from commit a29151feee35f27e7bb53bf45aa4afc2d70fcf32)