Remove broken --enable-gpgmepp
...which was off by default due to on-by-default --enable-mpl-subset, and
started to fail to build after da24a950cef510f239afa88eb99ae532e4f6f15c
"loplugin:unusedmethods",

> engine/cui/source/options/optgenrl.cxx:305:42: error: no member named 'LinkStubChooseKeyButtonHdl' in 'SvxGeneralTabPage'
>   305 |     m_xSigningKeyButton->connect_clicked(LINK(this, SvxGeneralTabPage, ChooseKeyButtonHdl));
>       |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> engine/include/tools/link.hxx:73:57: note: expanded from macro 'LINK'
>    73 |     ::tools::detail::castTo<Class *>(Instance), &Class::LinkStub##Member, __FILE__ ":" SAL_STRINGIFY(__LINE__), SAL_STRINGIFY(Class::LinkStub##Member))
>       |                                                         ^~~~~~~~~~~~~~~~
> <scratch space>:140:1: note: expanded from here
>   140 | LinkStubChooseKeyButtonHdl
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~

This removes all of:

- The configure option --enable-gpgmepp (and matching --with-system-gpgmepp) and
  the corresponding engine/config_host/config_gpgme.h.in (HAVE_FEATURE_GPGME,
  HAVE_FEATURE_GPGVERIFY, and HAVE_GPGCONF_SOCKETDIR), and the matching
  ENABLE_GPGMEPP, SYSTEM_GPGMEPP, GPGMEPP_*, LIBASSUAN_*, and GPG_ERROR_* in
  engine/config_host.mk.in.

- The bundled engine/external/gpgmepp, engine/external/libassuan, and
  engine/external/libgpg-error.

- The xmlsecurity OpenPGP backend under engine/xmlsecurity/source/gpg/, the
  GPGSEInitializer service, and the gpg parts of the signing and verification
  code.

- The two file-picker check boxes for encrypting with an OpenPGP key and signing
  with the default key, including the published UNOIDL constants
  CHECKBOX_GPGENCRYPTION and CHECKBOX_GPGSIGN in
  css.ui.dialogs.ExtendedFilePickerElementIds, and the slot SID_GPGSIGN.

- The filter capability flag SfxFilterFlags::GPGENCRYPTION and its use in the
  ODF export filters.

- The OpenPGP package encryption path:
  OStorageHelper::CreateGpgPackageEncryptionData,
  DocPasswordHelper::decryptGpgSession,
  XEncryptionProtectedStorage::setGpgProperties,
  XDocumentDigitalSignatures::trustUntrustedCertificate (the "trust this
  untrusted OpenPGP key?" prompt), and the OpenPGP key information that was read
  from and written to the ODF manifest.

- The OpenPGP signing and encryption key fields on the "Tools - Options - User
  Data" page.

- The gpg unit-test helpers (setUpGpg, test_init_gpg and the Python bindings),
  the gpg key rings under test/signing-keys, the gpg signing test documents and
  their test cases, plus the create-dump-certs.sh dev script that generated
  OpenPGP test keys.

- recreate signatures on tdf42316_odt12.ott as X.509 so the
  testPreserveMacroTemplateSignature12_ODF continues to run

To note:

- CppunitTest_services is no longer skipped for the MPL subset build.  (It was
  skipped only because the gpg SEInitializer had no constructor there.)

- The OpenPGP data carried in the XML signature format is left in place on
  purpose (the ouGpgKeyID, ouGpgCertificate and ouGpgOwner fields in
  engine/include/svl/sigstruct.hxx with their reading and writing, and the
  PGP_RSA_OAEP_MGF1P key-derivation value):  That code is shared with the X.509
  path and is now inert, so it is kept to avoid disturbing the common signature
  machinery.

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I46568644ec6bf2816cc5a9d65dddcc1ae01f7d30
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/6304
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>