Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/109966/ : FAILURE

error: explicit cast from "sal_Int32" (aka "int") to "sal_uInt64" (aka "unsigned long") (of larger rank) in comparison against "sal_uInt64": if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast [loplugin:unsignedcompare] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sal/qa/rtl/oustring/rtl_OUString2.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/109573/ )

clang plugin unsignedcompare did trigger. explicit cast from "sal_Int32" (aka "int") to "sal_uInt64" (aka "unsigned long") (of larger rank) in comparison against "sal_uInt64": if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/109573/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000994 \u003c1000994@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}