Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/105891/ : FAILURE

error "unused virtual function parameter name [loplugin:casttovoid]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/inc/salinst.hxx:218:33 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/105874/ )

clang plugin casttovoid did trigger. unused virtual function parameter name ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/105874/ )

error: unused virtual function parameter name [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/inc/salinst.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/105874/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000562 \u003c1000562@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}