Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/87032/ : FAILURE

error: instead of an "rtl::OString" constructed from a "const char *", pass a "std::string_view" [loplugin:stringview] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/extras/txtexport/txtexport.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/88351/ )

clang plugin stringview did trigger. instead of an "rtl::OString" constructed from a "const char *", pass a "std::string_view" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/88351/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1