bnc#822341: PPTX export of embedded text documents
-Make embedded text documents exported by analogy with spreadsheet
embedded documents.
-Convert MS ole objects to LO sepcific objecst to allow
exporting those ole objects too.

Plus use gb_CppunitTest_use_rdb instead of wasting time on
finding out which missing components cause test failing.
Especcially when we have platform dependent components
(e.g. related to embedded object)

(cherry picked from commit 0c3d5fb0ad35ff7fc18917fc86fa58d9312fe3ae)

Conflicts:
	sd/qa/unit/export-tests.cxx


ERROR: Attribute 'spid' must appear on element 'p:oleObj'.

As pointed out by CppunitTest_sd_export_tests.

(cherry picked from commit 124c33dd1d6bf2040f0153de8c9ecaebe759c3bd)

ERROR: Invalid content was found starting with element 'p:pic'.

Again, as pointed out by CppunitTest_sd_export_tests. Sadly it seems that the
spec and PowerPoint is not in sync here, so just do what makes both happy. This
fixes the --with-export-validation build.

(cherry picked from commit cf15306ccf49da290b391517e2c5dd22a4f1be45)

Change-Id: Ic76d659b51274777a1669c215344a1169ebcba81
8ecbc3ef4ea9dc84ebf88506967d02de04ded852
c76d659b51274777a1669c215344a1169ebcba81