Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/82375/ : FAILURE

clang plugin cstylecast did trigger. C-style cast from "sal_Int32" (aka "int") to "sal_uInt32" (aka "unsigned int") (performs: static_cast) (NoOp) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/83907/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/83907/ )

the test UITest_impress_tests failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/83907/ )

error: C-style cast from "sal_Int32" (aka "int") to "sal_uInt32" (aka "unsigned int") (performs: static_cast) (NoOp) [loplugin:cstylecast] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/xmlscript/qa/cppunit/test.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/83907/ )

Patch-set: 6
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1