Update patch set 3
Patch Set 3: Code-Review-1

C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/vcl/win/gdi/salgdi.cxx(625) : error C2259: 'WinSalGraphicsImpl' : cannot instantiate abstract class
due to following members:
'void SalGraphicsImpl::SetXORMode(bool,bool)' : is abstract
c:cygwinhometdflodejenkinsworkspacelo_gerrit_mastergerritgerritplatformwindowsvclincsalgdiimpl.hxx(80) : see declaration of 'SalGraphicsImpl::SetXORMode'


you can't remove the parameter only in the Windows-specific derived class, if you want to remove it you have to remove it in SalGraphicsImpl and every class derived from that (there is at least one per platform).

the bug says that the Mac OS X backend may or may not actually use the parameter, so the first thing to be done here is to clarify the situation on Mac OS X - if it turns out that the 2nd parameter is still in use there, it cannot be removed.

Patch-set: 3
Reviewer: Gerrit User 1000022 <1000022@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Code-Review=-1