error C2361: initialization of 's_fallbacks' is skipped by 'default'
Change-Id: I63f7914b52af51b55a51d39953a1ee58636243a3
(cherry picked from commit f3695bbc17a547b547876dd1175c0b74e5b3e90e)