vcl a11y: Drop namespace "accessibility"
Drop the "accessibility" namespace in which the classes
moved to vcl from the earlier separate accessibility
module were, see

    commit 9283da858506fe3b4383e4cfe0506e470a4356f6
    Author: Michael Weghorn <m.weghorn@posteo.de>
    Date:   Tue Dec 17 12:04:04 2024 +0100

        a11y: Merge accessibility module into vcl

In an upcoming Gerrit change [1] that namespace was
now causing ambiguity in source files using

    using namespace css::uno;

because a simple `accessibility` namespace specifier
could now be for either the `accessibility` namespace
removed with this commit or `css::uno::accessibility`.

Sample from Windows CI failure [2]:

    C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/vcl/source/accessibility/vclxaccessiblecomponent.cxx(112): error C2872: 'accessibility': ambiguous symbol
    C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\vcl\inc\accessibility/accessibletablistbox.hxx(29): note: could be 'accessibility'
    C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\include\vcl/accessibility/vclxaccessiblecomponent.hxx(31): note: or       'com::sun::star::accessibility'
    C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/vcl/source/accessibility/vclxaccessiblecomponent.cxx(112): error C2039: 'XAccessibleContext': is not a member of 'accessibility'

Drop the namespace to avoid having to always specify
the whole namespace (`css::uno::accessibility` vs `::accessibility`).

(`git show --ignore-space-change` shows the "actual
changes" more clearly as some code was using an
extra indentation level due to the namespace
that has been removed along with the namespace.)

[1] https://gerrit.libreoffice.org/c/core/+/180848
[2] https://ci.libreoffice.org/job/gerrit_windows/192770/consoleFull#1759204403cbd6b0d4-2729-45f4-a019-828721d0af3e

Change-Id: I6ca85c2660c001f9bc45700f2f13bd0b6707f8ea
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/180870
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins