Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/73408/ : FAILURE

clang plugin getstr did trigger. directly use object of type "rtl::OString" in a call of "operator <<", instead of calling "getStr" first ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75584/ )

error: directly use object of type "rtl::OString" in a call of "operator <<", instead of calling "getStr" first [loplugin:getstr] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/basic/qa/cppunit/basictest.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75584/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1