Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/22312/ : FAILURE

error "‘SwFEShell’ has not been declared" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sw/source/core/inc/flyfrm.hxx:271:30 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/23150/ )

error: ‘SwFEShell’ has not been declared in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sw/source/core/inc/flyfrm.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/23150/ )

Patch-set: 2
Label: Verified=-1