replace tabs with spaces, and unclog clang buildbot
since
    commit 02c9e05551d69980e0757b1b0a624692ea21a96b
    Date:   Thu Mar 12 17:34:12 2020 +0100
    tdf#131291: Add UItest

Seems that only some buildbots are being strict about this and
generating an error like:
IndentationError: unindent does not match any outer indentation
level

Change-Id: Ifc8d01eefca0028cf134c8e71237fc0b59bc27d5