Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/67929/ : FAILURE

error "version control conflict marker in file" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/uibase/inc/instable.hxx:1:1 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70349/ )

error: version control conflict marker in file in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/uibase/inc/instable.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70349/ )

https://ci.libreoffice.org/job/gerrit_master_android/436/ : SUCCESS (skipped)

Patch-set: 5
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1