Update patch set 6
Patch Set 6:

> This error "include/vcl/test/GraphicsRenderTests.hxx:88:28: error: no member named 'test' in namespace 'vcl'" is caused as I couldn't include "test/outputdevice.hxx" file inside GraphicsRenderTests.hxx file.

Well, that's because vcl/inc/test/outputdevice.hxx is local to vcl module only, but mainly this is because there was no need to be used out of vcl, so what you have to do is create a new header file in include/vcl/test and move only this enum class to the file. Then you can include it here .. and also elsewhere it is needed.

Patch-set: 6
Reviewer: Gerrit User 1000154 <1000154@6622c302-437a-49ad-a91d-55ba7dcf1615>