Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/20123/ : FAILURE

error: unused parameter name [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/core/doc/DocumentTimerManager.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/20890/ )

clang plugin casttovoid did trigger. unused parameter name ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/20890/ )

Patch-set: 1
Label: Verified=-1