Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master_android/883/ : FAILURE

linking failed, likely because of sporadic OOM ( https://ci.libreoffice.org/job/gerrit_android_arm/199/ )

https://ci.libreoffice.org/job/gerrit_master/68341/ : FAILURE

error "this member function can be declared static [loplugin:staticmethods]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/svx/source/gallery2/galbrws1.hxx:75:40 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70757/ )

error: this member function can be declared static [loplugin:staticmethods] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/svx/source/gallery2/galbrws1.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70757/ )

clang plugin staticmethods did trigger. this member function can be declared static ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70757/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1