Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/33717/ : FAILURE

clang plugin salbool did trigger. ParmVarDecl, use "bool" instead of "sal_Bool" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/36332/ )

error: ParmVarDecl, use "bool" instead of "sal_Bool" [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/ucb/source/ucp/cmis/cmis_content.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/36332/ )

Patch-set: 1
Label: Verified=-1