Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/101079/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "const rtl::OUStringLiteral<40>" to "const char *const " in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/extensions/source/activex/so_activex.cxx(192) ( https://ci.libreoffice.org/job/gerrit_windows/112095/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1