Check up front that symbolic links can be created
On Windows some bundled tarballs (e.g. pixman) contain symlinks that tar
recreates while unpacking. Without the privilege to create symbolic
links the unpack aborts, and the build then fails much later with a
cryptic missing-header error:

    tar: .gitlab-ci.d/meson-cross/linux-386-gnu.meson: Cannot create
         symlink to 'native-gnu.meson': No such file or directory
    tar: Exiting with failure status due to previous errors
    make[1]: *** [...workdir/UnpackedTarget/pixman-0.46.4.tar.xz] Error 2
    ...\cairo\src\cairoint.h(66): fatal error C1083: Cannot open include
        file: 'pixman.h': No such file or directory

Detect this at configure time by actually creating a symbolic link and
erroring out with an actionable message if it fails. Testing the
operation itself, rather than a particular enabling mechanism, keeps the
check valid however the privilege is granted (Developer Mode today, or
any future arrangement).

Signed-off-by: Mike Kaganski <mike.kaganski@collabora.com>
Change-Id: I98e7675647a59b6cbf582ab2e62f4b4201c44843
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/6297
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>