libgpg-error: upgrade to 1.50
Add external/libgpg-error/undeclared-environ-macOS.patch
from https://github.com/gpg/libgpg-error/commit/a59e902b887fd92337c9728f668cf9c89da3957a
to fix

spawn-posix.c:345:5: error: use of undeclared identifier 'environ'
    environ = act->environ;
    ^
1 error generated.

on macOS.

Downloaded from https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.50.tar.bz2

Change-Id: Ica3a181626429da39651c29482326134ba25d556
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/169200
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
(cherry picked from commit 5a7283a0eb880c5273ea48b0d1a6f881c4297b1a)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/169299