Fix UBSan build's RTTI needs
...after 0ed1cb5457a2106316f9d7fda10685360db4bc30 "make more symbols private in
writer" had caused CppunitTest_sw_layoutwriter3 to fail with

> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_sw_layoutwriter3.so
> workdir/LinkTarget/CppunitTest/libtest_sw_layoutwriter3.so: undefined symbol: _ZTI9SwEditWin"

Change-Id: I97660648a78fe23bb9374ca28c7809490b715476
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/164513
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>