error: comparison between pointer and integer (Clang trunk towards 3.4)
...the check in itga.cxx was useless anyway, as new[] does not return null.

(cherry picked from commit b63524d269a792e20777a91e4ed7e8ceae7ff55f)

Change-Id: I4de5a46e14a83ab134d0a098a62748e909dc9c00