Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/92408/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "TranslateId" to "const char *" in file C:/cygwin/home/tdf/jenkins/workspace/gerrit_windows/fpicker/source/win32/resourceprovider.cxx(55) ( https://ci.libreoffice.org/job/gerrit_windows/103235/ )

Patch-set: 7
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1