Update patch set 9
Patch Set 9: Verified-1

> Build Failed
 > 
 > http://ci.libreoffice.org/job/lo_gerrit_master/4488/ : FAILURE

Can reproduce this weird error message on MSVC 12.0:

  C:/Users/david/projects/libo/sw/source/uibase/inc\wrtsh.hxx(299) :
  : error C3083: " ?? A0xd99cf0a4": Das Symbol links neben "::" muss ein Typ sein.

boost::none was refactored in recent boost releases. There is also this issue that references this bug: [1]. It claims that this is precompiled header related.

Applying the described workaround, a lá:

  $(eval $(call gb_Library_add_defs,sw,\
      -DBOOST_OPTIONAL_USE_OLD_DEFINITION_OF_NONE \
  ))

didn't fix it.

* [1] https://svn.boost.org/trac/boost/ticket/11203

Patch-set: 9
Label: Verified=-1