Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/97570/ : FAILURE

error: use of undeclared identifier "cout"; did you mean "std::cout"? in file DocumentLoader.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/98234/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/98234/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000043 \u003c1000043@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}