Update patch set 12
Patch Set 12: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/20437/ : FAILURE

error "ParmVarDecl, use "bool" instead of "sal_Bool" [loplugin:salbool]" triggered in included file ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/21252/ )

error: ParmVarDecl, use "bool" instead of "sal_Bool" [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sfx2/source/dialog/filedlgimpl.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/21252/ )

clang plugin salbool did trigger. ParmVarDecl, use "bool" instead of "sal_Bool" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/21252/ )

Patch-set: 12
Label: Verified=-1