Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/32693/ : FAILURE

error "private field "m_pRestartParent" is not used [-Werror,-Wunused-private-field]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/desktop/source/deployment/gui/dp_gui_dialog2.hxx:119:19 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/35055/ )

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "std::shared_ptr<ExtMgrDialog>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/35055/ )

error: unused variable "removedEntry" [-Werror,-Wunused-variable] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/desktop/source/deployment/gui/dp_gui_extlistbox.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/35055/ )

Patch-set: 3
Label: Verified=-1