Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/82966/ : FAILURE

error "missing "typename" prior to dependent type name "my_string_view::size_type"" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sal/rtl/strtmpl.hxx:398:5 ( https://ci.libreoffice.org/job/gerrit_mac/88450/ )

error: missing "typename" prior to dependent type name "my_string_view::size_type" in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sal/rtl/strtmpl.hxx ( https://ci.libreoffice.org/job/gerrit_mac/88450/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1