Update patch set 13
Patch Set 13: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/88486/ : FAILURE

error: variable is only used as rvalue, should be const [loplugin:conststringvar] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sdext/source/pdfimport/xpdfwrapper/wrapper_gpl.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/89744/ )

clang plugin conststringvar did trigger. variable is only used as rvalue, should be const ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/89744/ )

the cppunit test CppunitTest_vcl_filter_ipdf failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/89744/ )

Patch-set: 13
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1