Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/103303/ : FAILURE

error "implicit conversion (IntegralCast) from "bool" to "sal_Int32" (aka "int") [loplugin:implicitboolconversion]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sd/source/ui/inc/tools/GraphicSizeCheck.hxx:39:38 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/103513/ )

clang plugin external did trigger. externally available entity "ModelTraverseHandler" is not previously declared in an included file (if it is only used in this translation unit, put it in an unnamed namespace; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/103513/ )

error: externally available entity "ModelTraverseHandler" is not previously declared in an included file (if it is only used in this translation unit, put it in an unnamed namespace; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sd/source/ui/tools/GraphicSizeCheck.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/103513/ )

"file" vs <file> clang plugin ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/103513/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000154 \u003c1000154@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}