Update patch set 1
Patch Set 1:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/61658/ : FAILURE

clang plugin fakebool did trigger. VarDecl, use "bool" instead of "sal_Bool" (aka "unsigned char") ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/64507/ )

error: VarDecl, use "bool" instead of "sal_Bool" (aka "unsigned char") [loplugin:fakebool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/filter/ww8/docxexport.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/64507/ )

Patch-set: 1