external/mysql-connector-cpp uses std::auto_ptr, must not be compiled as C++17
But gb_CXX03FLAGS may contain -Werror=c++11-extensions and would thus fail with

> [CXX] workdir/UnpackedTarball/mysql-connector-cpp/driver/mysql_connection.cpp
> In file included from workdir/UnpackedTarball/mysql-connector-cpp/driver/mysql_connection.cpp:44:
> In file included from workdir/UnpackedTarball/mysql-connector-cpp/driver/mysql_util.h:30:
> In file included from workdir/UnpackedTarball/mysql-connector-cpp/driver/nativeapi/mysql_private_iface.h:63:
> workdir/UnpackedTarball/mariadb-connector-c/include/mysql.h:223:45: error: commas at the end of enumerator lists are a C++11 extension [-Werror,-Wc++11-extensions]
>                       MYSQL_STATUS_QUIT_SENT, /* object is "destroyed" at this stage */
>                                             ^

(And otherwise the code appears to build fine with gb_CXX03FLAGS, so just stick
with that instead of coming up with yet another way of compiling as >= C++11 and
< C++17.)

Change-Id: I924d906e34c073672f2038072743197d3f7fef5f