fix build error "error: NSPrintJobSavingURL was not declared in this scope"
see commits:
  c5c317ed20933c6508b35c34039df31669943f1c

Change-Id: I3a886bde11dc3620cffeb3e2e579c7b37285d9c5
Reviewed-on: https://gerrit.libreoffice.org/9759
Reviewed-by: Caolán McNamara <caolanm@redhat.com>
Tested-by: Caolán McNamara <caolanm@redhat.com>
(cherry picked from commit e509b9303bd0141143bc6e707f98a72b96d91311)