exernal/firebird: Ensure target directories are present
We noticed occasional build failures like
<https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/96392/>

> error: unable to open output file '/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/workdir/UnpackedTarball/firebird/temp/Debug/cloop/release/tests/test1/CTest.o': 'No such file or directory'
> 1 error generated.
> Makefile:72: recipe for target '/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/workdir/UnpackedTarball/firebird/temp/Debug/cloop/release/tests/test1/CTest.o' failed

and while target "all" depends on target "mkdirs" (which would create all those
directories) in workdir/UnpackedTarball/firebird/extern/cloop/Makefile, there is
no order among the dependencies of "all", so no guarantee that the directories
are already created when the compilation recipes are executed.

Change-Id: Iaa2b750a12e3df078b46e5bb4feeafc926e11165