Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/39019/ : FAILURE

error ""getValue" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/ui/vba/vbasheetobject.hxx:193:36 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/42049/ )

error: "getValue" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/ui/vba/vbasheetobject.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/42049/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1