Adapt a use of the TileLocation constructor
...that was apparently missed by d452eae27364587165e0a114ba2184396c464fd8
"desktop, wsd, kit, browser: name parts by the page identifier" and caused

> tools/Benchmark.cpp:31:39: error: conversion function from 'int' to 'std::string' (aka 'basic_string<char>') invokes a deleted function
>    31 |         TileLocation loc = { 0, 0, 0, 0, CanonicalViewId::None, 0 };
>       |                                       ^
> ~/gcc/inst/lib/gcc/x86_64-pc-linux-gnu/17.0.0/../../../../include/c++/17.0.0/bits/basic_string.h:889:7: note: 'basic_string' has been explicitly marked deleted here
>   889 |       basic_string(nullptr_t) = delete;
>       |       ^
> ~/co1/online/kit/Delta.hpp:50:59: note: passing argument to parameter 'part' here
>    50 |     TileLocation(int left, int top, int size, std::string part,
>       |                                                           ^

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I96e1d6173fc9efe8cee94fa75768782dfec34e37
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/11668
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>