Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/30547/ : FAILURE

clang plugin stringconstant did trigger. in call of "rtl::OUString::operator+=", replace "OUString" constructed from a "sal_Unicode" with an "OUStringLiteral1" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/32591/ )

error: in call of "rtl::OUString::operator+=", replace "OUString" constructed from a "sal_Unicode" with an "OUStringLiteral1" [loplugin:stringconstant] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/svx/qa/unit/customshapes.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/32591/ )

use default type instead of indirection ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/32591/ )

Patch-set: 2
Label: Verified=-1