Update patch set 1
Patch Set 1: This need some tweaks before it is merged

sfx2/source/doc/sfxbasemodel.cxx: In constructor ‘IMPL_SfxBaseModel_DataContainer::IMPL_SfxBaseModel_DataContainer(osl::Mutex&, SfxObjectShell*)’:
sfx2/source/doc/sfxbasemodel.cxx:217:21: error: ‘IMPL_SfxBaseModel_DataContainer::m_pGrabBagItem’ will be initialized after [-Werror=reorder]
sfx2/source/doc/sfxbasemodel.cxx:190:48: error:   ‘cppu::OMultiTypeInterfaceContainerHelper IMPL_SfxBaseModel_DataContainer::m_aInterfaceContainer’ [-Werror=reorder]
sfx2/source/doc/sfxbasemodel.cxx:219:5: error:   when initialized here [-Werror=reorder]

Patch-set: 1
Reviewer: Gerrit User 1000013 <1000013@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0
Label: Code-Review=-1