Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/5003/ : FAILURE

Visual studio complained about error C2440: "return": cannot convert from "std::vector<int,std::allocator<_Ty>>" to "std::vector<long,std::allocator<_Ty>>" in file C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/windows_msc_dbgutil_32/sc/source/ui/miscdlgs/shtabdlg.cxx(57) ( https://ci.libreoffice.org/job/gerrit_windows/4975/ )

Patch-set: 3
Label: Verified=-1