Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/21421/ : FAILURE

error ""SetDrawingArea" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/uibase/inc/optload.hxx:129:18 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/22398/ )

error: "SetDrawingArea" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/uibase/inc/optload.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/22398/ )

Patch-set: 1
Label: Verified=-1