WIP: zformat.cxx: migration to std::array from std::vector
this commit breaks build in my environment with:

zformat.cxx(140): error C2440: 'initializing': cannot convert from 'initializer list' to 'std::map<LanguageType,std::array<sal_uInt8,4>,std::less<LanguageType>,std::allocator<std::pair<const LanguageType,std::array<sal_uInt8,4>>>>'

Change-Id: I2041d0dc97331ee45f366c26839592f4d0356661