xmlsecurity: fix Windows XP build
xmlsecurity/source/xmlsec/mscrypt/x509certificate_mscryptimpl.cxx(511) :
error C2065: ´CERT_SHA256_HASH_PROP_ID´ : undeclared identifier

Change-Id: I644d6797d81a506ca9b91d83eead16503af93905
Reviewed-on: https://gerrit.libreoffice.org/23494
Tested-by: Jenkins <ci@libreoffice.org>
Reviewed-by: Christian Lohmaier <lohmaier+LibreOffice@googlemail.com>
(cherry picked from commit d78e644679be47d96bbb2e9d5909f2b559fa29c4)