external/boost: Avoid some -Wdeprecated-variadic-comma-omission
...new with GCC 15 trunk -std=c++26 since
<https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=cc67d95dc100706ea665e8cce581d59466aba62e>
"c++: Implement C++26 P3176R1 - The Oxford variadic comma",

> In file included from workdir/UnpackedTarball/boost/boost/rational.hpp:82,
>                  from source/external/boost/include/boost/rational.hpp:30,
>                  from source/tools/source/generic/fract.cxx:32:
> workdir/UnpackedTarball/boost/boost/integer/common_factor_rt.hpp:66:56: error: omission of ‘,’ before varargs ‘...’ is deprecated in C++26 [-Werror=deprecated-variadic-comma-omission]
>    66 |          inline constexpr void constexpr_swap(T&a, U& b...) BOOST_GCD_NOEXCEPT(T)
>       |                                                        ^~~
>       |                                                        ,

and

> In file included from workdir/UnpackedTarball/boost/boost/move/unique_ptr.hpp:24,
>                  from workdir/UnpackedTarball/boost/boost/spirit/home/classic/core/non_terminal/impl/grammar.ipp:18,
>                  from workdir/UnpackedTarball/boost/boost/spirit/home/classic/core/non_terminal/grammar.hpp:21,
>                  from workdir/UnpackedTarball/boost/boost/spirit/home/classic/core.hpp:42,
>                  from workdir/UnpackedTarball/boost/boost/spirit/home/classic.hpp:24,
>                  from workdir/UnpackedTarball/boost/boost/spirit/include/classic.hpp:11,
>                  from source/external/boost/include/boost/spirit/include/classic.hpp:30,
>                  from sdext/source/pdfimport/pdfparse/pdfparse.cxx:23:
> workdir/UnpackedTarball/boost/boost/move/detail/unique_ptr_meta_utils.hpp:500:39: error: omission of ‘,’ before varargs ‘...’ is deprecated in C++26 [-Werror=deprecated-variadic-comma-omission]
>   500 | struct is_unary_function_impl<R (*)(T0...)>
>       |                                       ^~~
>       |                                       ,

Change-Id: I56856e274a7c577c53d96343992bb79d4c3d602e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/177730
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
Tested-by: Jenkins