Enable Visual Studio "Minimal Rebuild" compiler switch
This is kind of a "ccache-lite" thing.

    https://msdn.microsoft.com/en-us/library/kfz8ad09.aspx

By itself, this generates

    error C2471: cannot update program database

on jenkins, so switch the debug info format to CodeView/C7:

    https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-6.0/aa260783(v=vs.60)

Note that C7 does not support "Edit and continue", so if that turns
out to be a problem, we will have to revert this.

Change-Id: I9a68780a0458f950e7c60d5acebb6bcd5dcf79de