Remove Library_avmediagtk that no longer builds
...after efe2cf5c896ed8343380f741302c9eb434f8c7a8 "cool#15913 remove cairo
canvas library",

> engine/avmedia/source/gtk/gtkplayer.cxx:411:28: error: no member named 'CreateFromCairoSurface' in namespace 'vcl::bitmap'
>   411 |             = vcl::bitmap::CreateFromCairoSurface(Size(m_aSize.Width, m_aSize.Height), surface);
>       |                            ^~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: If9c6771931b3615585e7a56626aafdcc5de515d3
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/6180
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>