Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/98316/ : FAILURE

error ""end" is deprecated: Has hidden COW cost; use begin + getLength or toNonConstRange if you need a modifiable range [-Werror,-Wdeprecated-declarations]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/comphelper/basicio.hxx:68:28 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/98913/ )

error: "end" is deprecated: Has hidden COW cost; use begin + getLength or toNonConstRange if you need a modifiable range [-Werror,-Wdeprecated-declarations] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sfx2/source/control/templatelocalview.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/98913/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1