Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/101007/ : FAILURE

Visual studio complained about error C2398: Element "2": conversion from "sal_Int32" to "const std::basic_string_view<char16_t,std::char_traits<char16_t>>::size_type" requires a narrowing conversion in file cl : Command line warning D9025 : cl : Command line warning D9025 : cl : Command line warning D9025 : C:\cygwin\home\tdf\lode\jenkins\workspace\gerrit_windows@2\include\rtl/ustring.hxx(164) ( https://ci.libreoffice.org/job/gerrit_windows/112028/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1