tdf#92404: Web Wizard - no result / crash
Fixes
Traceback (most recent call last):
  File "/home/laci/m/bibisect/lo-linux-dbgutil-daily/opt/program/wizards/web/WWD_Events.py", line 249, in addDocument
    oLoadDocs = self.LoadDocs(self.xMSF, self.xUnoDialog, files, self)
TypeError: __init__() missing 1 required positional argument: 'parent_'

and:
Traceback (most recent call last):
  File "/home/julien/compile-libreoffice/libreoffice/instdir/program/wizards/web/WWD_Events.py", line 252, in addDocument
    oLoadDocs.loadDocuments()
  File "/home/julien/compile-libreoffice/libreoffice/instdir/program/wizards/web/WWD_Events.py", line 934, in loadDocuments
    doc.cp_URL = FileAccess.connectURLs(files[0], self.files[i])
NameError: global name 'files' is not defined

Change-Id: I737117a6981e541f12453bb9d9b2680f5fb79142