Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/69508/ : FAILURE

error "call to function "operator<<" that is neither visible in the template definition nor found by argument-dependent lookup" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/workdir/UnpackedTarball/cppunit/include/cppunit/tools/StringHelper.h:25:9 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/71856/ )

error: ParmVarDecl, use "tools::Long" instead of "long" [loplugin:toolslong] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/writerperfect/inc/DirectoryStream.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/71856/ )

clang plugin toolslong did trigger. ParmVarDecl, use "tools::Long" instead of "long" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/71856/ )

Patch-set: 7
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1