Update patch set 6
Patch Set 6:

> <https://ci.libreoffice.org//job/lo_tb_master_win/31622/consoleFull#-527421182cbd6b0d4-2729-45f4-a019-828721d0af3e>:
> 
>   C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win/package/source/zipapi/Deflater.cxx(72): error C2440: '=': cannot convert from 'const unsigned char *' to 'Bytef *'

ah, you already suspect missing pch regeneration; let me run the clean job on tb72 and tb73 (the two boxes that built lo_tb_master_win since, and kept failing)

Patch-set: 6