Update patch set 3
Patch Set 3:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/31221/ : FAILURE

Visual studio complained about error C2440: "reinterpret_cast": cannot convert from "BitmapChecksum" to "size_t" in file C:\cygwin64\home\tdf\lode\jenkins\workspace\gerrit_windows\include\vcl/graph.hxx(245) ( https://ci.libreoffice.org/job/gerrit_windows/36154/ )

Patch-set: 3