stldebug assert in bad sort of postgresql schemas
/usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/debug/safe_iterator.h:305:
In function:
    __gnu_debug::_Safe_iterator::reference
    __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<rtl::OUString
    *, std::__cxx1998::vector<rtl::OUString>>, std::vector<rtl::OUString>,
    std::forward_iterator_tag>::operator*() const [_Iterator =
    __gnu_cxx::__normal_iterator<rtl::OUString *,
    std::__cxx1998::vector<rtl::OUString>>, _Sequence =
    std::vector<rtl::OUString>, _Category = std::forward_iterator_tag]

Error: attempt to dereference a past-the-end iterator.

Objects involved in the operation:
    iterator "this" @ 0x0x7fffffff75a8 {
      type = __gnu_cxx::__normal_iterator<rtl::OUString*, std::__cxx1998::vector<rtl::OUString, std::allocator<rtl::OUString> > > (mutable iterator);
      state = past-the-end;
      references sequence with type 'std::__debug::vector<rtl::OUString, std::allocator<rtl::OUString> >' @ 0x0x7fffffff7d10
    }

Thread 1 "soffice.bin" received signal SIGABRT, Aborted.

a problem since...

commit 5cbb6631e6d4c1000bff936712b4bd4aafbe04d5
Date:   Fri Mar 4 13:01:57 2016 +0100

    pgsql-sdbc: factorise common code

Change-Id: I7f7794e93224dfa946a7b5970c458fc3030fab73
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/125726
Tested-by: Jenkins
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>