Update patch set 3
Patch Set 3:

So this fails again, but almost never locally :-( It looks like the main problem type I get is missing "objects" after closing a dialog. That is actually understandable, because the click just means the dialog closes, but at that point nothing has been done for the layouted document yet. As a result, the instant lookup of the new object fails.

Literally all python failures I saw have this construct, like:

======================================================================
ERROR: test_insert_qr_code_gen2 (insertQrCodeGen.insertQrCode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/uitest/writer_tests3/insertQrCodeGen.py", line 74, in test_insert_qr_code_gen2
    self.assertEqual(document.DrawPage.getByIndex(0).QRCodeProperties.ErrorCorrection, 1)
AttributeError: 'NoneType' object has no attribute 'ErrorCorrection'

======================================================================
FAIL: test_go_to_page (goToPage.GoToPage_dialog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/uitest/writer_tests3/goToPage.py", line 24, in test_go_to_page
    self.assertEqual(get_state_as_dict(xWriterEdit)["CurrentPage"], "2")
AssertionError: '1' != '2'

======================================================================
ERROR: test_insert_signature_line2 (insertSignatureLine.insertSignatureLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jmg/Development/libreoffice/symbols/sw/qa/uitest/writer_tests3/insertSignatureLine.py", line 85, in test_insert_signature_line2
    element = document.DrawPage.getByIndex(0)
uno.com.sun.star.lang.IndexOutOfBoundsException: /home/jmg/Development/libreoffice/symbols/sw/source/core/doc/textboxhelper.cxx:284

And I have no good idea how to easily fix this with a correct solution.

Before this patch the SolarMutex was not released while the Scheduler was busy, so LO wouldn't process any commands from the PyUNO connection, until it was idle AKA for SW the idle layouter was finished.

In theory we "just" have to wait for an other OnLayoutFinished after modifications to the document. That is my understanding of one problem. But that would be a lot of work on all UItests.

A hacky solution might be:

diff --git a/vcl/source/uitest/uiobject.cxx b/vcl/source/uitest/uiobject.cxx
index 3c3d224024f4..f80a2bb8063f 100644
--- a/vcl/source/uitest/uiobject.cxx
+++ b/vcl/source/uitest/uiobject.cxx
@@ -16,6 +16,7 @@
 #include <vcl/event.hxx>
 #include <vcl/toolkit/floatwin.hxx>
 #include <vcl/menu.hxx>
+#include <vcl/scheduler.hxx>
 #include <vcl/tabpage.hxx>
 #include <vcl/tabctrl.hxx>
 #include <vcl/toolkit/lstbox.hxx>
@@ -622,6 +623,7 @@ void ButtonUIObject::execute(const OUString& rAction,
             return;
         }
         mxButton->Click();
+        Scheduler::ProcessEventsToIdle();
     }
     else
         WindowUIObject::execute(rAction, rParameters);

This is potentially dangerous for busy loops, where a Application::Reschedule(true) loop with some test would be better, but this can't be added to ButtonUIObject::execute, because I don't see a way to test for an expected result condition of a click, except LO being idle again.

I think just fixing the button "CLICK" should be enough. It would be better to expand the executeAction API, so the test writer could add a condition to the parameters, like
mkPropertyValues({"UITEST_CONDITION": "IDLE"}) or mkPropertyValues({"UITEST_CONDITION": "LAYOUT_FINISHED"}).
 
I'll upload a patch to see how far the dbgutil build can continue with this hack.

Any other ideas, comments?

Patch-set: 3
Reviewer: Gerrit User 1000179 <1000179@6622c302-437a-49ad-a91d-55ba7dcf1615>