vcl: improve ErrCode std::ostream pretty-printer
Let's say you specify a non-existing export filter during conversion.

Old output:

Error: Please verify input parameters... (SfxBaseModel::impl_store <file:///test.html> failed: 0x81a(Error Area:Io Class:Parameter Code:2074))

New output:

Error: Please verify input parameters... (SfxBaseModel::impl_store <file:///test.html> failed: 0x81a(Error Area:Io Class:Parameter Code:26))

The later (at least) allows going to include/vcl/errcode.hxx, searching
for Io.*Parameter.*26, and leads to ERRCODE_IO_INVALIDPARAMETER.

Change-Id: Iecfcfa4e805147131fde73cc0b89fa38f6ea61d4
Reviewed-on: https://gerrit.libreoffice.org/50421
Reviewed-by: Miklos Vajna <vmiklos@collabora.co.uk>
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>
Tested-by: Jenkins <ci@libreoffice.org>
(cherry picked from commit 905d9b81c933b46d0502f982aad1c2931fae0426)