Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/74001/ : FAILURE

error "‘vcl::pdf::constDictionaryKeyInteriorColor’ defined but not used [-Werror=unused-variable]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/include/vcl/filter/PDFiumLibrary.hxx:47:26 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/78167/ )

compiler warning unused-variable treated as error: ‘vcl::pdf::constDictionaryKeyInteriorColor’ defined but not used in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/include/vcl/filter/PDFiumLibrary.hxx:47:26 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/78167/ )

error: ‘vcl::pdf::constDictionaryKeyInteriorColor’ defined but not used [-Werror=unused-variable] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/include/vcl/filter/PDFiumLibrary.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/78167/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1