Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/71658/ : FAILURE

Visual studio complained about error C2440: "<function-style-cast>": cannot convert from "initializer list" to "std::u16string_view" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/sax/source/tools/converter.cxx(774) ( https://ci.libreoffice.org/job/gerrit_windows/81305/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1