Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/106881/ : FAILURE

clang plugin unusedvariablecheck did trigger. unused variable "aOldSeries" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/106761/ )

error: unused variable "aOldSeries" [loplugin:unusedvariablecheck] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/source/model/template/ChartType.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/106761/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1