Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/101064/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "const rtl::OUStringLiteral<40>" to "const char *const " in file C:/cygwin64/home/tdf/lode/jenkins/workspace/gerrit_windows/extensions/source/activex/so_activex.cxx(192) ( https://ci.libreoffice.org/job/gerrit_windows/112083/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000083 \u003c1000083@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}