Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/67081/ : FAILURE

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "std::unique_ptr<SdrDragMethod>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/69560/ )

error: no need to explicitly init an instance of "std::unique_ptr<SdrDragMethod>" with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/svx/source/svdraw/svddrgv.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/69560/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1