Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/46564/ : FAILURE

Visual studio complained about error C2440: "static_cast": cannot convert from "PROCESS_MEMORY_COUNTERS_EX *" to "PROCESS_MEMORY_COUNTERS *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/comphelper/source/misc/meminfo.cxx(90) ( https://ci.libreoffice.org/job/gerrit_windows/53815/ )

Patch-set: 5
Label: Verified=-1