fix nss build on macOS aarch64 - missing LITTLE_ENDIAN setting
the update to nss 3.128 put the -DHAVE_PLATFORM_GHASH define behind a
check for the variable LITTLE_ENDIAN, but the makefile based system only
had a check for that added to the coreconf/Linux.mk file instead of e.g.
the UNIX.mk one that would also be included in the macOS makefile
(Darwin.mk)
So as a workaround specify it on the commandline - our configure already
tests for it, so we don't need a dedicated compile check or patch to the
nss bits.

Not having the define results in having duplicate methods in both gcm.o
as well as ghash-aarch64.o and the macOS linker fails:

duplicate symbol '_gcm_HashInit_hw' in:
    /Users/cloph/build/workdir/UnpackedTarball/nss/nss/lib/freebl/out/Darwin_SINGLE_SHLIB/gcm.o
    /Users/cloph/build/workdir/UnpackedTarball/nss/nss/lib/freebl/out/Darwin_SINGLE_SHLIB/ghash-aarch64.o
duplicate symbol '_platform_ghash_support' in:
    /Users/cloph/build/workdir/UnpackedTarball/nss/nss/lib/freebl/out/Darwin_SINGLE_SHLIB/gcm.o
    /Users/cloph/build/workdir/UnpackedTarball/nss/nss/lib/freebl/out/Darwin_SINGLE_SHLIB/ghash-aarch64.o
duplicate symbol '_gcm_HashZeroX_hw' in:
    /Users/cloph/build/workdir/UnpackedTarball/nss/nss/lib/freebl/out/Darwin_SINGLE_SHLIB/gcm.o
    /Users/cloph/build/workdir/UnpackedTarball/nss/nss/lib/freebl/out/Darwin_SINGLE_SHLIB/ghash-aarch64.o
duplicate symbol '_gcm_HashWrite_hw' in:
    /Users/cloph/build/workdir/UnpackedTarball/nss/nss/lib/freebl/out/Darwin_SINGLE_SHLIB/gcm.o
    /Users/cloph/build/workdir/UnpackedTarball/nss/nss/lib/freebl/out/Darwin_SINGLE_SHLIB/ghash-aarch64.o
duplicate symbol '_gcm_HashMult_hw' in:
    /Users/cloph/build/workdir/UnpackedTarball/nss/nss/lib/freebl/out/Darwin_SINGLE_SHLIB/gcm.o
    /Users/cloph/build/workdir/UnpackedTarball/nss/nss/lib/freebl/out/Darwin_SINGLE_SHLIB/ghash-aarch64.o
ld: 5 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Change-Id: Ic662115581aef7c2083f73079b2cff99b941ecd5
(cherry picked from commit 4db2de9b54298fb763519733f93f224b9c30979b)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/210331
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Tested-by: Jenkins