Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/2917/ : FAILURE

clang plugin casttovoid did trigger. unused virtual function parameter name ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/2900/ )

error: unused virtual function parameter name [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/ui/docshell/arealink.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/2900/ )

Patch-set: 6
Label: Verified=-1