Update patch set 8
Patch Set 8: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/98238/ : FAILURE

error: rather than copy, pass with a view using subView() [loplugin:stringview] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/tools/qa/cppunit/test_json_writer.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/98853/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/98853/ )

clang plugin stringview did trigger. rather than copy, pass with a view using subView() ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/98853/ )

Patch-set: 8
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1