Use braces to workaround a strange GCC bug
Using gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04):

    [CXX] ucb/source/ucp/cmis/certvalidation_handler.cxx
    In file included from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/lexical_cast/detail/converter_lexical_streams.hpp:62,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/lexical_cast/detail/converter_lexical.hpp:54,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/lexical_cast/try_lexical_convert.hpp:44,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/lexical_cast.hpp:32,
                     from /home/valaki/projects/libreoffice/external/boost/include/boost/lexical_cast.hpp:30,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/date_time/format_date_parser.hpp:14,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/date_time/date_generator_parser.hpp:20,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/date_time/date_facet.hpp:25,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/date_time/gregorian/gregorian_io.hpp:16,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/date_time/gregorian/gregorian.hpp:31,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/date_time/posix_time/time_formatters.hpp:12,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/date_time/posix_time/posix_time.hpp:24,
                     from /home/valaki/projects/libreoffice/external/boost/include/boost/date_time/posix_time/posix_time.hpp:30,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/date_time/local_time/local_time.hpp:11,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/date_time.hpp:15,
                     from /home/valaki/projects/libreoffice/external/boost/include/boost/date_time.hpp:30,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/libcmis/inc/libcmis/object.hxx:40,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/libcmis/inc/libcmis/document.hxx:39,
                     from /home/valaki/projects/libreoffice/workdir/UnpackedTarball/libcmis/inc/libcmis/libcmis.hxx:34,
                     from /home/valaki/projects/libreoffice/ucb/source/ucp/cmis/certvalidation_handler.hxx:19,
                     from /home/valaki/projects/libreoffice/ucb/source/ucp/cmis/certvalidation_handler.cxx:23:
    /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/lexical_cast/detail/lcast_unsigned_converters.hpp: In member function ‘CharT* boost::detail::lcast_put_unsigned<Traits, T, CharT>::main_convert_loop()’:
    /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/lexical_cast/detail/lcast_unsigned_converters.hpp:149:17: error: this ‘while’ clause does not guard... [-Werror=misleading-indentation]
      149 |             inline CharT* main_convert_loop() BOOST_NOEXCEPT {
          |                 ^~~~~
    /home/valaki/projects/libreoffice/workdir/UnpackedTarball/boost/boost/lexical_cast/detail/lcast_unsigned_converters.hpp:150:17: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘while’
      150 |                 while (main_convert_iteration());
          |                 ^~~~~~

It surfaced after commit 00a76942e423589e3fdd4e059be753eab3393344,
apparently showing some version-specific compiler bug.

Change-Id: I92a989726cea5eafd762f724cfc0b3c1f986824c