Fix build [loplugin:unnecessaryparen]
After commit 0eb603db635aaa506ddd8050dc9b669be4c304e6
(remove SAL_CALL in codemaker).

 /home/collabora/jenkins/workspace/gerrit_linux_clang_dbgutil_main/engine/codemaker/source/cppumaker/cpputype.cxx:1129:12: error: unnecessary parentheses around single-token string literal [loplugin:unnecessaryparen]
  1129 |         << ("static inline ::cpo::uno::Type const & static_type(void * = 0);\n\n");
       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I1fd8cba74984cdbf9db26f8192f46405372c66fd
Signed-off-by: Mike Kaganski <mike.kaganski@collabora.com>
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/7300
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>