disable werror in external mythes
avoid useless optimized gcc build warning of:
error: 'void* __builtin_memcpy(void*, const void*, long unsigned int)' specified bound 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]

Change-Id: Iba277bedfa8061af6040891ae8d77c39454f983a
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/193157
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Tested-by: Jenkins
(cherry picked from commit 7a44dac223f057b67e59415cd484d7f222bca06c)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/193217
Reviewed-by: Adolfo Jayme Barrientos <fitojb@ubuntu.com>