fix win arm64 build
it was removed in

commit 71d738ed1434c908c94469ad27d778c00901db86
Author: Xisco Fauli <xiscofauli@libreoffice.org>
Date:   Mon Nov 3 14:20:12 2025 +0100

    some janitorial work

because we thought it was not necessary but now
lo_daily_tb_win_arm64 fails with

26>E:\jenkins\workspace\build_master\workdir_for_build\UnpackedTarball\sqlite3\sqlite3.c(1,1): error C1083: Cannot open source file: 'E:\jenkins\workspace\build_master\workdir_for_build\UnpackedTarball\sqlite3\sqlite3.c': No such file or directory [E:\jenkins\workspace\build_master\workdir_for_build\UnpackedTarball\python3\PCBuild\sqlite3.vcxproj]
         (compiling source file '../../sqlite3/sqlite3.c')

Change-Id: Iaf361e15f94da8d94d2de81fc4bf3763351282ca
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/193388
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>