Update patch set 3
Patch Set 3:

> Patch Set 2:
> 
> > Patch Set 2: Verified-1
> > 
> > Build Failed 
> > 
> > https://ci.libreoffice.org/job/gerrit_master/91710/ : FAILURE
> > 
> > error: static_cast from "MetaActionType" prvalue to "MetaActionType" prvalue is redundant [loplugin:redundantcast] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/filter/svm/SvmWriter.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/92723/ )
> > 
> > clang plugin redundantcast did trigger. static_cast from "MetaActionType" prvalue to "MetaActionType" prvalue is redundant ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/92723/ )
> 
> I do not understand what caused this error. Also why don't I see these in my local system?

You need to build LO with clang and have clang plugins enabled to see those errors..

Patch-set: 3
Reviewer: Gerrit User 1000154 <1000154@6622c302-437a-49ad-a91d-55ba7dcf1615>