gtk4: Include new header for Cairo format defines
... to adjust for

    commit 1aac139d504c9f7b60edeadba3c52a14524e5694
    Date:   Thu Apr 3 16:00:18 2025 +1030

        vcl: cairo: split cairo format defines into new header

to fix build failures for the --enable-gtk4 build:

    /home/michi/development/git/libreoffice/vcl/unx/gtk4/../gtk3/salnativewidgets-gtk.cxx:2201:24: error: use of undeclared identifier 'SVP_CAIRO_ALPHA'
     2201 |     sal_uInt8 a = data[SVP_CAIRO_ALPHA];
          |                        ^
    /home/michi/development/git/libreoffice/vcl/unx/gtk4/../gtk3/salnativewidgets-gtk.cxx:2202:47: error: use of undeclared identifier 'SVP_CAIRO_BLUE'
     2202 |     sal_uInt8 b = unpremultiply_table[a][data[SVP_CAIRO_BLUE]];
          |                                               ^
    /home/michi/development/git/libreoffice/vcl/unx/gtk4/../gtk3/salnativewidgets-gtk.cxx:2203:47: error: use of undeclared identifier 'SVP_CAIRO_GREEN'
     2203 |     sal_uInt8 g = unpremultiply_table[a][data[SVP_CAIRO_GREEN]];
          |                                               ^
    /home/michi/development/git/libreoffice/vcl/unx/gtk4/../gtk3/salnativewidgets-gtk.cxx:2204:47: error: use of undeclared identifier 'SVP_CAIRO_RED'
     2204 |     sal_uInt8 r = unpremultiply_table[a][data[SVP_CAIRO_RED]];
          |                                               ^
    4 errors generated.
    make[1]: *** [/home/michi/development/git/libreoffice/solenv/gbuild/LinkTarget.mk:339: /home/michi/development/git/libreoffice/workdir/CxxObject/vcl/unx/gtk4/salnativewidgets-gtk.o] Error 1
    make[1]: *** Waiting for unfinished jobs....
    make: *** [Makefile:301: build] Error 2

Change-Id: I54c329fe9caa59ca223c16c2c7737201e4427ff1
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/183691
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>