Update patch set 1
Patch Set 1: This need some tweaks before it is merged

I'm getting erros in one more case that is not inherited of XServiceInfo:

I tried to convert but, it gave me more errors, so I gave up of this conversion.

/home/marcos/gitroot/core/i18npool/source/transliteration/transliteration_commonclass.cxx: Na função membro ‘virtual sal_Bool com::sun::star::i18n::transliteration_commonclass::supportsService(const rtl::OUString&)’:
/home/marcos/gitroot/core/i18npool/source/transliteration/transliteration_commonclass.cxx:142:52: error: cannot convert ‘com::sun::star::i18n::transliteration_commonclass* const’ to ‘com::sun::star::lang::XServiceInfo*’ for argument ‘1’ to ‘bool cppu::supportsService(com::sun::star::lang::XServiceInfo*, const rtl::OUString&)’
/home/marcos/gitroot/core/i18npool/source/transliteration/transliteration_commonclass.cxx:143:1: warning: control reaches end of non-void function [-Wreturn-type]

Patch-set: 1
Reviewer: Gerrit User 1000186 <1000186@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0
Label: Code-Review=-1