Fix Windows build with warnings enabled
  C:\lo\core2\sw\source\core\layout\paintfrm.cxx(4660) : error C2220: the following warning is treated as an error
  C:\lo\core2\sw\source\core\layout\paintfrm.cxx(4660) : warning C4701: potentially uninitialized local variable 'nStyleNumber' used

after commit e5eec842b0c61c9c91a8f836661d6885c9c236a8 "enable spotlight
subset in kit mode", 2024-12-16. Not required in master, where the fix
was incorporated right in the ported original change, because master
buildbots luckily have warnings enabled.

Change-Id: I654d667d23665ba00d88fa7a11cd460b270b36a1
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/182268
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>