Update patch set 12
Patch Set 12: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/6150/ : FAILURE

error: use "false" instead of "sal_False" [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/core/layout/atrfrm.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/6081/ )

clang plugin salbool did trigger. use "false" instead of "sal_False" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/6081/ )

Patch-set: 12
Label: Verified=-1