NamedValue needs to be a complete type here now
...at least with VS 2022 Preview 17.6.0 Preview 3.0 and --with-latest-c++,

> C:\PROGRA~1\MICROS~3\2022\Preview\VC\Tools\MSVC\1436~1.323\Include\span(78): error C2036: 'const com::sun::star::beans::NamedValue *': unknown size
> C:\PROGRA~1\MICROS~3\2022\Preview\VC\Tools\MSVC\1436~1.323\Include\span(73): note: while compiling class template member function 'std::_Span_iterator<_Ty> &std::_Span_iterator<_Ty>::operator --(void) noexcept'
> with
> [
> _Ty=const com::sun::star::beans::NamedValue
> ]
> C:\PROGRA~1\MICROS~3\2022\Preview\VC\Tools\MSVC\1436~1.323\Include\xutility(1414): note: see the first reference to 'std::_Span_iterator<_Ty>::operator --' in 'std::iter_move'
> with
> [
> _Ty=const com::sun::star::beans::NamedValue
> ]
> C:\PROGRA~1\MICROS~3\2022\Preview\VC\Tools\MSVC\1436~1.323\Include\xutility(474): note: see the first reference to 'std::iter_move' in 'std::ranges::_Iter_move::_Cpo::operator ()'
> C:\PROGRA~1\MICROS~3\2022\Preview\VC\Tools\MSVC\1436~1.323\Include\__msvc_iter_core.hpp(392): note: see reference to class template instantiation 'std::_Span_iterator<_Ty>' being compiled
> with
> [
> _Ty=const com::sun::star::beans::NamedValue
> ]
> C:\PROGRA~1\MICROS~3\2022\Preview\VC\Tools\MSVC\1436~1.323\Include\xutility(602): note: see reference to variable template 'bool input_or_output_iterator<std::_Span_iterator<com::sun::star::beans::NamedValue const > >' being compiled
> C:\PROGRA~1\MICROS~3\2022\Preview\VC\Tools\MSVC\1436~1.323\Include\xutility(1778): note: see reference to variable template 'bool input_iterator<std::_Span_iterator<com::sun::star::beans::NamedValue const > >' being compiled
> filter\source\config\cache\filtercache.hxx(368): note: see reference to class template instantiation 'std::span<const com::sun::star::beans::NamedValue,18446744073709551615>' being compiled

Change-Id: Ibff530be810f56a1f33bf78f0d2e3b76c64b08cd
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/150385
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>