Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/73344/ : FAILURE

error "rather use make_shared than constructing from "std::unique_ptr<SvxScriptSelectorDialog, std::default_delete<SvxScriptSelectorDialog> >" [loplugin:makeshared]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/vcl/vclptr.hxx:129:61 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75520/ )

clang plugin makeshared did trigger. rather use make_shared than constructing from "std::unique_ptr<SvxScriptSelectorDialog, std::default_delete<SvxScriptSelectorDialog> >" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75520/ )

error: rather use make_shared than constructing from "std::unique_ptr<SvxScriptSelectorDialog, std::default_delete<SvxScriptSelectorDialog> >" [loplugin:makeshared] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/vcl/vclptr.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75520/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75520/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1