libassuan: upgrade to 3.0.1
Downloaded from https://gnupg.org/ftp/gcrypt/libassuan/libassuan-3.0.1.tar.bz2

Reviewed-on: https://gerrit.libreoffice.org/c/core/+/169198
Reviewed-by: Christian Lohmaier <lohmaier+LibreOffice@googlemail.com>
Tested-by: Jenkins

(cherry picked from commit 79d74f036f65dcf128fb9b967b345a9009028f53, as its
modifications to external/gpgmepp/find-libgpg-error-libassuan.patch happen to
fix a flatpak build against org.freedesktop.Sdk//24.08, which would otherwise
fail with

> libtool: link: LD_RUN_PATH="/usr/local/lib:" /usr/bin/ccache gcc -I/run/build/libreoffice/workdir/UnpackedTarball/libassuan/src -I/run/build/libreoffice/workdir/UnpackedTarball/libgpg-error/src -O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -O2 -Wall -Wcast-align -Wshadow -Wstrict-prototypes -Wno-format-y2k -Wno-missing-field-initializers -Wno-sign-compare -Wno-format-zero-length -Wno-format-truncation -Wno-sizeof-pointer-div -Wl,-z -Wl,origin -Wl,-rpath -Wl,\$ORIGIN -o .libs/gpgme-json gpgme-json.o cJSON.o  -lm ./.libs/libgpgme.so -L/run/build/libreoffice/workdir/UnpackedTarball/libgpg-error/src/.libs /run/build/libreoffice/workdir/UnpackedTarball/libgpg-error/src/.libs/libgpg-error.so
> /usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: warning: libassuan.so.0, needed by ./.libs/libgpgme.so, not found (try using -rpath or -rpath-link)
> /usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ./.libs/libgpgme.so: undefined reference to `assuan_socket_connect@LIBASSUAN_1.0'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ./.libs/libgpgme.so: undefined reference to `assuan_ctx_set_system_hooks@LIBASSUAN_1.0'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ./.libs/libgpgme.so: undefined reference to `assuan_get_active_fds@LIBASSUAN_1.0'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ./.libs/libgpgme.so: undefined reference to `assuan_sendfd@LIBASSUAN_1.0'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ./.libs/libgpgme.so: undefined reference to `assuan_transact@LIBASSUAN_1.0'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ./.libs/libgpgme.so: undefined reference to `assuan_write_line@LIBASSUAN_1.0'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ./.libs/libgpgme.so: undefined reference to `assuan_pending_line@LIBASSUAN_1.0'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ./.libs/libgpgme.so: undefined reference to `assuan_pipe_connect@LIBASSUAN_1.0'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ./.libs/libgpgme.so: undefined reference to `assuan_read_line@LIBASSUAN_1.0'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ./.libs/libgpgme.so: undefined reference to `assuan_new_ext@LIBASSUAN_1.0'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ./.libs/libgpgme.so: undefined reference to `assuan_release@LIBASSUAN_1.0'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ./.libs/libgpgme.so: undefined reference to `assuan_set_flag@LIBASSUAN_1.0'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ./.libs/libgpgme.so: undefined reference to `assuan_send_data@LIBASSUAN_1.0'
> collect2: error: ld returned 1 exit status
> make[4]: *** [Makefile:860: gpgme-json] Error 1
> make[3]: *** [Makefile:550: all-recursive] Error 1
> make[2]: *** [Makefile:482: all] Error 2
> make[1]: *** [/run/build/libreoffice/external/gpgmepp/ExternalProject_gpgmepp.mk:48: /run/build/libreoffice/workdir/ExternalProject/gpgmepp/build] Error 1

as linking the gpgme-json executable, due to the default
--no-allow-shlib-undefined, tries to resolve the linked-in libgpgme.so, which in
turn has a DT_NEEDED of libassuan.so.9 but a DT_RUNPATH of $ORIGIN, so doesn't
find any libassuan.so.9 if that doesn't happen to be available in the system,
but which it isn't for this flatpak build; I have no idea how that ever
happened to work)

Change-Id: Ie56dd4d88998c6b2a825a502aa34bae3436d2b25
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/174052
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
Tested-by: Stephan Bergmann <stephan.bergmann@allotropia.de>