Update patch set 2
Patch Set 2:

This broke the build: bridges/source/cpp_uno/msvc_win32_x86-64/except.cxx(884): error C2110: '+': cannot add two pointers

Patch-set: 2