Partial revert "make more classes private in mergedlibs"
This reverts bits of commit 01159643623de55f9e1de84d568032ca919dbd8f
because

./configure --enable-pch=yes --enable-debug --enable-split-debug
--enable-ld=gold --enable-mergelibs --disable-odk --without-help
--without-java --with-system-jpeg --with-system-icu --with-lang=lt

fails to build with:

[LNK] Library/libswlo.so
[LOC] top level modules: sw
/home/aurimas/projects/libreoffice-git/include/svx/shapepropertynotifier.hxx:49:
error: undefined reference to 'vtable for svx::IPropertyValueProvider'
/usr/bin/ld.gold: the vtable symbol may be undefined because the class
is missing its key function
/home/aurimas/projects/libreoffice-git/include/basegfx/color/bcolormodifier.hxx:67:
error: undefined reference to 'vtable for basegfx::BColorModifier'
/usr/bin/ld.gold: the vtable symbol may be undefined because the class
is missing its key function
collect2: error: ld returned 1 exit status

Signed-off-by: Aurimas Fišeras <aurimas@members.fsf.org>
Change-Id: I3b8750bed7408384638bde2965632eb2bd146884