Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/59056/ : FAILURE

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/62022/ )

the cppunit test CppunitTest_desktop_lib failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/62022/ )

error: too few arguments to function call, single argument "rJsonWriter" was not specified in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/extras/tiledrendering/tiledrendering.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/62022/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1