Update patch set 1
Patch Set 1:

You need to

  #include <array>

to fix

  C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\Include\utility(290): error C2079: 'std::pair<const LanguageType,std::array<sal_uInt8,4>>::second' uses undefined class 'std::array<sal_uInt8,4>'
  C:/lo/core/svl/source/numbers/zformat.cxx(143): note: see reference to class template instantiation 'std::pair<const LanguageType,std::array<sal_uInt8,4>>' being compiled
  C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\Include\type_traits(640): error C2139: 'std::array<sal_uInt8,4>': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_constructible'
  C:/lo/core/svl/source/numbers/zformat.cxx(140): note: see declaration of 'std::array<sal_uInt8,4>'
  C:/lo/core/svl/source/numbers/zformat.cxx(143): note: see reference to class template instantiation 'std::is_copy_constructible<std::array<sal_uInt8,4>>' being compiled
  C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\Include\type_traits(640): note: see reference to variable template 'const bool conjunction_v<std::is_copy_constructible<o3tl::strong_int<unsigned short,LanguageTypeTag> const >,std::is_copy_constructible<std::array<unsigned char,4> > >' being compiled

Patch-set: 1
CC: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>