Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/63767/ : FAILURE

error: unused variable "aFoldedOutlineNdsArray" [loplugin:unusedvariablecheck] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/uibase/utlui/content.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/66473/ )

clang plugin unusedvariablecheck did trigger. unused variable "aFoldedOutlineNdsArray" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/66473/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1