expat: fix WASM build
it fails with
/home/tdf/lode/jenkins/workspace/lo_gerrit/tb/build_master/workdir/UnpackedTarball/expat/lib/random_getrandom.c:78:14: error: call to undeclared function 'syscall'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   78 |         (int)syscall(SYS_getrandom, currentTarget, bytesToWrite,
      |              ^
/home/tdf/lode/jenkins/workspace/lo_gerrit/tb/build_master/workdir/UnpackedTarball/expat/lib/random_getrandom.c:78:22: error: use of undeclared identifier 'SYS_getrandom'
   78 |         (int)syscall(SYS_getrandom, currentTarget, bytesToWrite,
      |                      ^~~~~~~~~~~~~
2 errors generated.

Change-Id: I994f10533315c055e1da07fad982a6100e1856ef
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/204732
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
(cherry picked from commit 41d54fa5577ba5cf91af0ff3d49ffbef50a26bb2)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/204770
Reviewed-by: Adolfo Jayme Barrientos <fitojb@ubuntu.com>