KDE5FilePicker: Fix build on i386
This fixes the following build error on i386 as reported by
ricotz for LibreOffice 6.2.1.1 on #libreoffice-dev:

[build CXX] vcl/unx/kde5/KDE5SalGraphics.cxx
In file included from /<<PKGBUILDDIR>>/include/com/sun/star/uno/Any.h:29,
                 from /<<PKGBUILDDIR>>/workdir/UnoApiHeadersTarget/udkapi/normal/com/sun/star/uno/XInterface.hdl:6,
                 from /<<PKGBUILDDIR>>/workdir/UnoApiHeadersTarget/udkapi/normal/com/sun/star/lang/XTypeProvider.hdl:6,
                 from /<<PKGBUILDDIR>>/workdir/UnoApiHeadersTarget/udkapi/normal/com/sun/star/lang/XTypeProvider.hpp:6,
                 from /<<PKGBUILDDIR>>/include/cppuhelper/compbase.hxx:25,
                 from /<<PKGBUILDDIR>>/vcl/unx/kde5/KDE5FilePicker.hxx:22,
                 from /<<PKGBUILDDIR>>/vcl/unx/kde5/KDE5FilePicker2.cxx:20:
/<<PKGBUILDDIR>>/include/cppu/unotype.hxx: In instantiation of ‘static const com::sun::star::uno::Type& cppu::UnoType< <template-parameter-1-1> >::get() [with T = int]’:
/<<PKGBUILDDIR>>/include/cppu/unotype.hxx:321:37:   required from ‘const com::sun::star::uno::Type& cppu::getTypeFavourUnsigned(const T*) [with T = int]’
/<<PKGBUILDDIR>>/include/com/sun/star/uno/Any.hxx:268:55:   required from ‘void com::sun::star::uno::operator<<=(com::sun::star::uno::Any&, const C&) [with C = int]’
/<<PKGBUILDDIR>>/vcl/unx/kde5/KDE5FilePicker2.cxx:664:22:   required from here
/<<PKGBUILDDIR>>/include/cppu/unotype.hxx:296:38: error: no matching function for call to ‘cppu_detail_getUnoType(T1*)’
         return cppu_detail_getUnoType(static_cast< T1 * >(0));
                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I5b734160c4ce218a9a982ba4a595add13affa365