Correction to improve 'resize with cell'
Error: A vertical flipped shape lost flip on loading. The error slipped
in, when I have implemented the suggestions from Jan-Marek. The object
is vertical flipped, to have no flip for calculating the full sized
logical rectangle. Therefore the second call to method
lcl_NeedsMirrorYCorrection gives wrong result 'false'. I need to
remember the result of the first call.

Change-Id: Ia411fe7108be9fdcbbf748ee9de9f443e55d6ed0
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/105570
Tested-by: Jenkins
Reviewed-by: Regina Henschel <rb.henschel@t-online.de>