Fix Windows build
... after commit 235c892393f8c1459aa68447a0e3621e2b3cd10c
(editeng:qa: add single line unit test, 2023-02-15)

sal_Int32 is not int on that platform, resulting in

  C:/core/editeng/qa/unit/core-test.cxx(1771): error C2672: 'CppUnit::assertEquals': no matching overloaded function found
  C:/core/editeng/qa/unit/core-test.cxx(1771): error C2782: 'void CppUnit::assertEquals(const T &,const T &,CppUnit::SourceLine,const std::string &)': template parameter 'T' is ambiguous

Change-Id: Ie562ff301569bd85a185b6713e0896ecfa7c7eaa
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/150721
Reviewed-by: Andras Timar <andras.timar@collabora.com>
Tested-by: Mike Kaganski <mike.kaganski@collabora.com>