Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/57677/ : FAILURE

Visual studio complained about error C2398: Element "1": conversion from "unsigned long" to "long" requires a narrowing conversion in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sw/source/uibase/misc/swruler.cxx(53) ( https://ci.libreoffice.org/job/gerrit_windows/65812/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1