Further --with-java fixes
...following up on 863653205bfc391acdcd1dc44da28b028e77eca7 "fix --with-java
build", so that JunitTest_ridljar_typedesc no longer fails with

> 1) test(com.sun.star.lib.uno.typedesc.TypeDescription_Test)
> java.lang.AssertionError: TypeSignature.test(TypeClass); getTypeClass expected same:<com.sun.star.uno.TypeClass@4c3e4790> was not:<com.sun.star.uno.TypeClass@38cccef>
>         at org.junit.Assert.fail(Assert.java:89)
>         at org.junit.Assert.failNotSame(Assert.java:829)
>         at org.junit.Assert.assertSame(Assert.java:772)
>         at com.sun.star.lib.uno.typedesc.TypeDescription_Test$TypeSignature.test(TypeDescription_Test.java:228)
>         at com.sun.star.lib.uno.typedesc.TypeDescription_Test.test(TypeDescription_Test.java:108)

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I5db56a0eef63850ffe22739089442119f0814fdc
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/7259
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>