Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_feature/252/ : FAILURE

error ""getName" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/chart2/source/inc/ChartStyle.hxx:73:31 ( https://ci.libreoffice.org/job/gerrit_mac/40245/ )

error: "getName" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/chart2/source/inc/ChartStyle.hxx ( https://ci.libreoffice.org/job/gerrit_mac/40245/ )

Patch-set: 7
Label: Verified=-1