filter: XSLTFilter: unbreak XSLT2Transformer
Creating the service fails:

  java.lang.ClassCastException: class com.sun.star.beans.NamedValue cannot be cast to class [Ljava.lang.Object; (com.sun.star.beans.NamedValue is in unnamed module of loader com.sun.star.lib.unoloader.UnoClassLoader @6ff3c5b5; [Ljava.lang.Object; is in module java.base of loader 'bootstrap')
  at com.sun.star.comp.xsltfilter.XSLTransformer.initialize(XSLTransformer.java:143)
  at com.sun.star.comp.loader.FactoryHelper$Factory.createInstanceWithArgumentsAndContext(FactoryHelper.java:271)

because initialize gets a sequence<any> where the anys are NamedValues,
but it expects a sequence<any> where the any is sequence<any> where the
anys are NamedValues.

(regression from commit d22f3b8c787b93c38925adf92af542362dbda3e6)

Change-Id: I4fd13f3e04d79f7646e6bb31c8f0d35efd42ae69
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/197132
Tested-by: Jenkins
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
(cherry picked from commit d92905f099992c48fc7ec0a6d0be5675d123b833)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/197171
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>