Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/68146/ : FAILURE

clang plugin external did trigger. externally available entity "ImplGetScanline" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70563/ )

error: externally available entity "ImplGetScanline" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/gdi/bmpfast.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70563/ )

https://ci.libreoffice.org/job/gerrit_master_android/690/ : SUCCESS

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1