Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/76477/ : FAILURE

error "static_cast from "const SfxPoolItem *" to "const ScLineBreakCell *", which are not related by inheritance, is not allowed" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sc/inc/document.hxx:1719:16 ( https://ci.libreoffice.org/job/gerrit_mac/82046/ )

error: static_cast from "const ScLineBreakCell *" to "const SfxBoolItem *", which are not related by inheritance, is not allowed in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sc/source/ui/view/cliputil.cxx ( https://ci.libreoffice.org/job/gerrit_mac/82046/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1