Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> Hi Balazs,
> it fails here:
> 
> Traceback (most recent call last):
>   File "/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64_branch/sw/qa/uitest/writer_tests7/tdf143244.py", line 48, in test_tdf143244
>     self.assertEqual(sHexCustomText, "ffffff")
> AssertionError: 'bee3d3' != 'ffffff'
> 
> Does this patch depend on another patch wich is not backported to 7.2 branch ?

Hi Xisco!
I did not think of that. This patch is most certainly depended on my previous fix: https://gerrit.libreoffice.org/c/core/+/118336 which has not been backported. Could you backport this too please?

Patch-set: 5
Reviewer: Gerrit User 1002855 <1002855@6622c302-437a-49ad-a91d-55ba7dcf1615>