Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/92204/ : FAILURE

error: unused variable "tempVect" [loplugin:unusedvariablecheck] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/core/data/markdata.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/93176/ )

clang plugin unusedvariablecheck did trigger. unused variable "tempVect" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/93176/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1