Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/112294/ : FAILURE

build likely got stuck and was aborted due to not producing any output to the log ( https://ci.libreoffice.org/job/gerrit_windows/124504/ )

Visual studio complained about error C2504: "SalGraphicsAutoDelegateToImpl": base class undefined in file C:\cygwin\home\tdf\lode\jenkins\workspace\gerrit_windows\vcl\inc\win/salgdi.h(152) ( https://ci.libreoffice.org/job/gerrit_windows/124504/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1