Fix test on Windows
The assertion added in commit 58f2c1e6ab3052e0746dabb36e6061125779b034
(tdf#135413: sw: Add UItest, 2025-03-04) used page count 16, obviously
because that is what Writer shows opening the file. But the number is
caused by a wrong layout; the table in the document unexpectedly takes
two pages.

Testing the UI test on Windows, I see

AssertionError: '16' != '15'

and that's the same what Stephan reported on
https://gerrit.libreoffice.org/c/core/+/130940/comment/5a512c89_ff82b3a3.
So let the test assert on "no less than 15".

Reviewed-on: https://gerrit.libreoffice.org/c/core/+/201176
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>
Tested-by: Jenkins
Signed-off-by: Mike Kaganski <mike.kaganski@collabora.com>
Change-Id: I9331eff460b929503b41859833032e608c086aa4
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/1562
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>