Adapt test to LLVM 16 trunk libc++
...see
<https://github.com/llvm/llvm-project/commit/309aed306817e5b1a302d8f757231c734cf71370>
"[libc++] Implement P1423R3 (char8_t backward compatibility remediation)"
causing

> error: 'error' diagnostics seen but not expected:
>   compilerplugins/clang/test/getstr.cxx Line 43: overload resolution selected deleted operator '<<'

Change-Id: Ic2fb9409cf3033300aca6717a8db7889e9d03c6a
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/137786
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>