Silence upcoming GCC 8 -Werror=parentheses in external/boost
...reporting such delights as

> [CXX] sal/cppunittester/cppunittester.cxx
> In file included from workdir/UnpackedTarball/boost/boost/mpl/aux_/na_assert.hpp:23,
[...]
>                  from external/boost/include/boost/algorithm/string.hpp:25,
>                  from sal/cppunittester/cppunittester.cxx:60:
> workdir/UnpackedTarball/boost/boost/mpl/assert.hpp:188:21: error: unnecessary parentheses in declaration of ‘assert_arg’ [-Werror=parentheses]
>  failed ************ (Pred::************
>                      ^

where boost/mpl/assert.hpp contains

> template< typename Pred >
> failed ************ (Pred::************
>       assert_arg( void (*)(Pred), typename assert_arg_pred<Pred>::type )
>     );

Reviewed-on: https://gerrit.libreoffice.org/48386
Tested-by: Jenkins <ci@libreoffice.org>
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit b3b22ee3de5ddfc73e44a2d425450b1deeb3ed0d)

Change-Id: I6976b2cc23f1d309d27d3fde9098b10c9d877599