qt: QtFilePicker: Use modern connect syntax, port from deprecated signal
Use modern connect syntax and address the warning about
the use of a deprecated signal that this revealed:

`QCheckBox::checkStateChanged` was introduced in Qt 6.7 [1]
and `QCheckBox::stateChanged` was deprecated in Qt 6.9 [2].

    In file included from .../libreoffice/vcl/qt6/QtFilePicker.cxx:10:
    .../libreoffice/vcl/qt6/../qt5/QtFilePicker.cxx:693:44: error: 'stateChanged' is deprecated: Use checkStateChanged() instead [-Werror,-Wdeprecated-declarations]
      693 |             connect(pCheckbox, &QCheckBox::stateChanged, this,
          |                                            ^
    .../qt5/qtbase/src/widgets/widgets/qcheckbox.h:40:19: note: 'stateChanged' has been explicitly marked deprecated here
       40 |     QT_MOC_COMPAT QT_DEPRECATED_VERSION_X_6_9("Use checkStateChanged() instead")
          |                   ^
    .../qt5/qtbase/src/corelib/global/qtdeprecationmarkers.h:179:44: note: expanded from macro 'QT_DEPRECATED_VERSION_X_6_9'
      179 | # define QT_DEPRECATED_VERSION_X_6_9(text) QT_DEPRECATED_X(text)
          |                                            ^
    .../qt5/qtbase/src/corelib/global/qtdeprecationmarkers.h:29:33: note: expanded from macro 'QT_DEPRECATED_X'
       29 | #  define QT_DEPRECATED_X(text) Q_DECL_DEPRECATED_X(text)
          |                                 ^
    .../qt5/qtbase/src/corelib/global/qcompilerdetection.h:1004:36: note: expanded from macro 'Q_DECL_DEPRECATED_X'
     1004 | #  define Q_DECL_DEPRECATED_X(x) [[deprecated(x)]]

[1] https://doc.qt.io/qt-6/qcheckbox.html#checkStateChanged
[2] https://doc.qt.io/qt-6/qcheckbox-obsolete.html#stateChanged

Change-Id: I0787b378855009abea740a0f5c1aab537c41987e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/173348
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>