Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/80892/ : FAILURE

clang plugin stringview did trigger. instead of an "rtl::OUString", pass a "std::u16string_view" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/82540/ )

error: instead of an "rtl::OUString", pass a "std::u16string_view" [loplugin:stringview] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/qa/cppunit/png/PngFilterTest.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/82540/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1