-Werror=type-limits
> /home/tdf/lode/jenkins/workspace/lo_tb_master_linux_dbg/sc/source/core/data/bcaslot.cxx:647:25: error: comparison of unsigned expression >= 0 is always true [-Werror=type-limits]
>              assert(slot >= 0 && slot < mnBcaSlots);
>                     ~~~~~^~~~

(<https://ci.libreoffice.org//job/lo_tb_master_linux_dbg/36619/>), where slot is of
type SCSIZE, which is a typedef for size_t (sc/inc/address.hxx)

Change-Id: I52cfa8b746791d4bd43be9a9d16cda992319c694
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/129781
Reviewed-by: Julien Nabet <serval2412@yahoo.fr>
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
Tested-by: Jenkins