Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_feature/243/ : FAILURE

error ""getName" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/chart2/source/inc/ChartStyle.hxx:72:31 ( https://ci.libreoffice.org/job/gerrit_mac/39873/ )

error: "getName" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/chart2/source/inc/ChartStyle.hxx ( https://ci.libreoffice.org/job/gerrit_mac/39873/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1