Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/84754/ : FAILURE

error: explicit cast from "sal_Int32" (aka "int") to "sal_uInt64" (aka "unsigned long") (of larger rank) in comparison against "unsigned long": if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast [loplugin:unsignedcompare] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/app/help.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/86180/ )

clang plugin unsignedcompare did trigger. explicit cast from "sal_Int32" (aka "int") to "sal_uInt64" (aka "unsigned long") (of larger rank) in comparison against "unsigned long": if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/86180/ )

Patch-set: 5
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1