Missing include guard in new sal/rtl/strtmpl.hxx
...as causing trouble in ASan/UBSan builds,

> [CXX] jurt/source/pipe/staticsalhack.cxx
> In file included from jurt/source/pipe/staticsalhack.cxx:20:
> In file included from sal/rtl/ustring.cxx:51:
> sal/rtl/strtmpl.hxx:38:28: error: redefinition of 'IMPL_RTL_USTRCODE'
> template <typename C> auto IMPL_RTL_USTRCODE(C c) { return std::make_unsigned_t<C>(c); }
>                            ^
> sal/rtl/strtmpl.hxx:38:28: note: previous definition is here
> template <typename C> auto IMPL_RTL_USTRCODE(C c) { return std::make_unsigned_t<C>(c); }
>                            ^
[...]

Change-Id: Ied38a5f96bbb6d1c0d8ae956629ca6be64dc273f
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/109055
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>