Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/73772/ : FAILURE

clang plugin unsignedcompare did trigger. explicit cast from "SCROW" (aka "int") to "SCSIZE" (aka "unsigned long") (of larger rank) in comparison against "SCSIZE": if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75936/ )

error: explicit cast from "SCROW" (aka "int") to "SCSIZE" (aka "unsigned long") (of larger rank) in comparison against "SCSIZE": if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast [loplugin:unsignedcompare] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/ui/StatisticsDialogs/FourierAnalysisDialog.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75936/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1