Avoid loplugin:includeform with configure-generated file
...which in out-of-tree builds would cause

> engine/solenv/lockfile/lockfile.c:14:10: error: replace "..." include form with <...> for inclusion of a source file not next to the current source file, or a header, solenv/lockfile/autoconf.h [loplugin:includeform]
>    14 | #include "autoconf.h"
>       |          ^~~~~~~~~~~~

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: Ib6b9b85e5298138940672f2770be3de6620c9c95
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/3578
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>