Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/24371/ : FAILURE

clang plugin salbool did trigger. use "bool" instead of "sal_Bool" as return type ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/25946/ )

error: use "bool" instead of "sal_Bool" as return type [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/cppuhelper/source/tdmgr.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/25946/ )

Patch-set: 2
Label: Verified=-1