std::call_once() seems to require -lpthread at least on Linux
Without this, I get undefined reference to pthread_once, on openSUSE 15.0
with clang7+lld (and libstdc++).

Change-Id: I03571fd85ce0d16e8b47549fb2a158f2ff9a9c45