Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/5082/ : FAILURE

Visual studio complained about error C2440: "delete": cannot convert from "std::unique_ptr<sfx2::FileDialogHelper,std::default_delete<_Ty>>" to "void*" in file C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/windows_msc_dbgutil_32/sfx2/source/appl/shutdownicon.cxx(459) ( https://ci.libreoffice.org/job/gerrit_windows/5054/ )

Patch-set: 3
Label: Verified=-1