external/libwpd: Missing include for size_t
...as now reported when building with recent trunk GCC/libstdc++ on Linux:

> In file included from WPXContentListener.cpp:26:
> In file included from ./WPXContentListener.h:29:
> ./WPXTable.h:56:31: error: unknown type name 'size_t'; did you mean 'std::size_t'?
>         const WPXTableCell  *getCell(size_t i, size_t j)
>                                      ^~~~~~
>                                      std::size_t

Change-Id: Ic20240f01c7b0305cb87ababf53a3aaf66072d61
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/105324
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit 8d378abf1de0a47517427c086da26588f846592a)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/115000
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>
(cherry picked from commit 524cfb93d4033917ad20c718d538235078d068d5)