Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/20880/ : FAILURE

error: unused variable declaration [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/filter/excel/xichart.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/21784/ )

clang plugin casttovoid did trigger. unused variable declaration ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/21784/ )

Patch-set: 2
Label: Verified=-1