Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/55555/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "xmlDocUniquePtr" to "xmlDocPtr" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sd/qa/unit/export-tests.cxx(1284) ( https://ci.libreoffice.org/job/gerrit_windows/63661/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1