editeng: fix RTF export of colors
SfxItemPool may contain null pointers and return them from GetItem2(),
even if non-null pointers follow, so have to use GetItemCount2() here.

This later asserts when it can't find the items in aColorList.

(cherry picked from commit 30504139af039d524ca0fd7158fc21ed38db2d9f)

editeng: RTF export: another buggy GetItem2() loop, for fonts
(cherry picked from commit 8ce353279caa84944971f22ec536433030e5d9c7)

editeng: error: "remove_const_t" is not a member of "std"
Manual type inference was an interesting oxymoronic curiosity that
can probably only exist in C++, but it turns out our baseline
compilers don't even support it yet.
(cherry picked from commit 700e1e7fda6f0a415adbbd5bb190efa5c7435c4f)

Change-Id: I976c95387b4c45e5a4371254f130df6b24370eaa