Avoid some macOS loplugin warnings around SQLWChars
...like

> connectivity/source/drivers/odbc/OPreparedStatement.cxx:285:136: error: replace function parameter of type 'const OUString &' with 'std::u16string_view' [loplugin:stringviewparam]
>   285 | void OPreparedStatement::setParameter(const sal_Int32 parameterIndex, const sal_Int32 _nType, const sal_Int16 _nScale, const OUString &_sData)
>       |                                                                                                                        ~~~~~~~~~~~~~~~~^~~~~~

and

> connectivity/source/drivers/odbc/ODatabaseMetaDataResultSet.cxx:851:117: error: directly use a 'std::u16string_view' (aka 'basic_string_view<char16_t>') value instead of a _ustr user-defined string literal [loplugin:ostr]
>   851 |         SQLWChars aCOL = !uCOL.isEmpty() ? SQLWChars(uCOL.makeStringAndClear()) : SQLWChars(u"" SQL_ALL_TABLE_TYPES ""_ustr);
>       |                                                                                                                     ^~~~~~~

caused by SQLWCHAR being 32-bit wchar_t on macOS (rather than 16-bit unsigned
short, as on Linux), so SQLWChars is CHARS<sal_uInt32> (rather than
CHARS<sal_Unicode>) with a ctor taking a std::u16string_view argument (rather
than an OUString argument)

Change-Id: I194af5feda5ba6279ed87264bc467b5d574406cc
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/174263
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>