Fix some tautological std::type_info (in-)equality comparisons
...which could never succeed.

I became aware of this when Clang 15 trunk -std=c++2b, implementing
<http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1328r1.html> "Making
std::type_info::operator== constexpr", pointed at two of the broken comparisons
with

> sw/source/uibase/app/docsh2.cxx:478:25: error: code will never be executed [-Werror,-Wunreachable-code]
>                         pTmpFrame->GetFrame().Appear();
>                         ^~~~~~~~~
> sw/source/uibase/app/docsh2.cxx:475:33: error: code will never be executed [-Werror,-Wunreachable-code]
>                         bOnly = false;
>                                 ^~~~~

(It didn't emit warnings pointing at any of the other broken comparisons,
though.)

All of these broken comparisons were regressions introduced with
89d39bc100aabf5dccbe77c0b5c0c85736e85b39 "tdf#94559: 4th step to remove
rtti.hxx", replacing uses of the IS_TYPE macro (from include/tools/rtti.hxx,
meanwhile removed with d64e535fe9a00b671cf1be3eb5632c0d5f4b8bea "Remove unused
rtti.hxx").

I now added loplugin:typeidcomparison to also find the other broken comparisons
introduced by that commit.  (The remaining cases where that commit replaced uses
of TYPE_INFO with typeid comparisons were correct and/or have meanwhile been
replaced with code not using typeid, see
553ee72041d6f66e26156eb1ad0d9e3c13457f7a "simplify some use of typeid" and
d656da9bc4f2df0bb99c65a288847e3fdd43a37c "~SwModify: do not silently tolerate
clients registered past death".)

The original IS_TYPE macro made sure not to dereference null pointers,

> #define IS_TYPE(T,pObj) \
>         ( pObj && (pObj)->Type() == TYPE(T) )

I don't know if any of the pointers now dereferenced in those typeid expressions
can legitimately be null.  But to be on the safe side, I replicated that check
in the newly introduced isType (sw/inc/istype.hxx).

(It is interesting to note that none of the static analysis that we routinely
employ seems to have noticed these broken comparisons.)

Change-Id: I65baffdd27bac1abf744283ff98c2dc864fa63b4