Document that setting gb_CXX03FLAGS for clang-cl doesn't work
Setting it to

> gb_CXX03FLAGS := -Xclang -std=gnu++98 -Werror=c++11-extensions -Wno-c++11-long-long -Wno-deprecated-declarations

similar to the solenv/gbuild/platform/com_GCC_defs.mk setting would cause lots
of errors like

> In file included from <built-in>:1:
> In file included from C:\llvm\inst\lib\clang\13.0.0\include\Intrin.h:33:
> C:/PROGRA~2/MIB055~1/2019/COMMUN~1/VC/Tools/MSVC/1428~1.299/Include\setjmp.h(168,11): error: expected function body after function declarator
>         ) noexcept(false);
>           ^
> In file included from C:/lo-clang/core/odk/qa/checkapi/checkapi.cxx:22:
> In file included from C:/lo-clang/core/workdir/UnpackedTarball/cppunit/include\cppunit/plugin/TestPlugIn.h:8:
> In file included from C:/lo-clang/core/workdir/UnpackedTarball/cppunit/include\cppunit/plugin/PlugInParameters.h:8:
> In file included from C:/PROGRA~2/MIB055~1/2019/COMMUN~1/VC/Tools/MSVC/1428~1.299/Include\deque:11:
> In file included from C:/PROGRA~2/MIB055~1/2019/COMMUN~1/VC/Tools/MSVC/1428~1.299/Include\xmemory:11:
> C:/PROGRA~2/MIB055~1/2019/COMMUN~1/VC/Tools/MSVC/1428~1.299/Include\cstdint(55,11): error: expected identifier or '{'
> namespace _DEPRECATE_TR1_NAMESPACE tr1 {
>           ^
> C:/PROGRA~2/MIB055~1/2019/COMMUN~1/VC/Tools/MSVC/1428~1.299/Include\yvals_core.h(611,5): note: expanded from macro '_DEPRECATE_TR1_NAMESPACE'
>     [[deprecated(                                                                                                 \
>     ^

(where the first one comes from -FIIntrin.h that needs to be part of $(CXX) to
have the intrinsics available in all compilation units)

Change-Id: I1e8f135dd429dd18deb6df33dfa71e2fcbefa9f7