python3: silence distutils deprecated warning
Since a1295cb177295752f8cbfbb49e13d5bb69ed7dc7
"python: upgrade to 3.10.14 (master only)"
Some builds started to fail with

Traceback (most recent call last):
  File "/home/tdf/lode/jenkins/workspace/lo_callgrind_linux/workdir/UnpackedTarball/lxml/setup.py", line 15, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tdf/lode/jenkins/workspace/lo_callgrind_linux/workdir/UnpackedTarball/lxml/setup.py", line 17, in <module>
    from distutils.core import setup
  File "/home/tdf/lode/jenkins/workspace/lo_callgrind_linux/instdir/program/python-core-3.10.14/lib/distutils/__init__.py", line 19, in <module>
    warnings.warn(_DEPRECATION_MESSAGE,
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
make[1]: *** [/home/tdf/lode/jenkins/workspace/lo_callgrind_linux/external/lxml/ExternalProject_lxml.mk:26: /home/tdf/lode/jenkins/workspace/lo_callgrind_linux/workdir/ExternalProject/lxml/build] Error 1

The problem is that python 3.10 doesn't bundle setuptools so
it's not possible to replace it at the moment

Change-Id: I9a9d077b51f49e912dab4941efe8751c2fcc76e1
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/170068
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Tested-by: Jenkins