Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_feature/216/ : FAILURE

error ""setChartStyle" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/source/inc/OPropertySet.hxx:206:27 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/36636/ )

error: "setChartStyle" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/source/inc/OPropertySet.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/36636/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0