Remove the Base filter configurations
...that were left behind by 9139ee1ca3616e6b6884dee1b7dcc33bb7640794 "Remove the
Base application UI and its packaging" and caused JunitTest_framework_unoapi to
fail with

> StarOffice XML (Base)
> Exception while getting Environment The requested filter 'StarOffice XML (Base)' exists ... but it should not; because the corresponding LibreOffice module was not installed. at filter/source/config/cache/filtercache.cxx:397
> com.sun.star.container.NoSuchElementException: The requested filter 'StarOffice XML (Base)' exists ... but it should not; because the corresponding LibreOffice module was not installed. at filter/source/config/cache/filtercache.cxx:397
>         at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:156)
>         at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:120)
>         at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:312)
>         at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:278)
>         at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:82)
>         at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:617)
>         at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:145)
>         at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:129)
>         at jdk.proxy2/jdk.proxy2.$Proxy14.getByName(Unknown Source)
>         at mod._fwl.FilterFactory.createTestEnvironment(FilterFactory.java:98)
>         at lib.TestCase.getTestEnvironment(TestCase.java:120)
>         at base.java_fat.getTestEnvironment(java_fat.java:267)
>         at base.java_fat.executeTest(java_fat.java:140)
>         at org.openoffice.Runner.run(Runner.java:175)
>         at org.openoffice.test.UnoApiTest.test(UnoApiTest.java:41)

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I4d1ae3b2cc9715f5958afa685626516d2712ab18
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/4628
Reviewed-by: Andras Timar <andras.timar@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>