Fix shape rectangle calculation
At specific screen resolutions, caused failed CppunitTest_sc_shapetest:

  C:/lo/src/core/sc/qa/unit/scshapetest.cxx(169) : error : Assertion
  Test name: sc_apitest::ScShapeTest::testTdf137576_LogicRectInDefaultMeasureline
  assertion failed
  - Expression: std::abs(rExpected.Y() - rActual.Y()) <= nTolerance
  - after reload Y expected 9731 actual 10287 Tolerance 1

which manifested the actual wrong position of shape written into ODF.
Commit cd966aac6ecd8ce606ac3f2ccd602e467114ba3f
  Author Regina Henschel <rb.henschel@t-online.de>
  Date   Fri Dec 25 19:27:51 2020 +0100
    tdf#137033 improve save of cell anchored shapes

had corrected the calculation of anchor point, but the overlook was
that in some cases of non-transformed shapes, rMyCell.maCellAddress
may differ from pObjData->maStart. Since aSnapStartAddress could be
not set to pObjData->maStart for such shapes, the wrong cell range
could be calculated for resized-with-cell objects.

Fix this by using pObjData->maStart whenever there is pObjData. If
it turns out that in some cases, rMyCell.maCellAddress is needed in
calculations before the 'if (rShape.bResizeWithCell && pObjData)',
aSnapStartAddress should be assigned to pObjData->maStart after the
check.

Change-Id: I7e0dc834c2ffb147430fb5b2cb8bdb4dca201b3b