Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/55443/ : FAILURE

error ""INCLUDED_VCL_UITEST_FORMATTEDFIELDUIOBJECT_HXX" is used as a header guard here, followed by #define of a different macro [-Werror,-Wheader-guard]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/vcl/uitest/formattedfielduiobject.hxx:10:9 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/58587/ )

error: "INCLUDED_VCL_UITEST_FORMATTEDFIELDUIOBJECT_HXX" is used as a header guard here, followed by #define of a different macro [-Werror,-Wheader-guard] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/vcl/uitest/formattedfielduiobject.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/58587/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1