Update patch set 3
Patch Set 3:

Caolan: Hello!
I need some help with the code written by you for the linux_arm bridge in LO.

We are trying to set Clang as default compiler for Android building. 
With GCC things used to work fine, but when I tried to build with clang 
I faced this error: LibreOffice/bridges/source/cpp_uno/gcc3_linux_arm/except.cxx:290:44: error: no member named 'barrier_cache' in '_Unwind_Exception'
        return (void*)header->unwindHeader.barrier_cache.bitpattern[0];

With some digging, we found that you wrote that particular portion of code. The problem is here: https://github.com/LibreOffice/core/blob/master/bridges/source/cpp_uno/gcc3_linux_arm/except.cxx#L290

I know it has been a while(10 years) since you wrote that code and things must have been pretty rusty by now but it would be super helpful if you could give even slightest of hints for how can I approach to solve this. :)

We were also wondering how this piece of code behaves differently for GCC and Clang.  

Thanks!

Patch-set: 3
Reviewer: Gerrit User 1001521 <1001521@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0