Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/22585/ : FAILURE

clang plugin redundantinline did trigger. function has no external linkage but is explicitly declared "inline" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/23828/ )

error: function has no external linkage but is explicitly declared "inline" [loplugin:redundantinline] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/core/tool/math.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/23828/ )

Patch-set: 5
Label: Verified=-1