Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/100344/ : FAILURE

clang plugin stringview did trigger. instead of an "rtl::OString" constructed from a "const rtl::OStringLiteral<9>", pass a "std::string_view" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/100779/ )

error: instead of an "rtl::OString" constructed from a "const rtl::OStringLiteral<9>", pass a "std::string_view" [loplugin:stringview] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/l10ntools/source/xmlparse.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/100779/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1