Update patch set 5
Patch Set 5:

Hi Balazs,
it fails here:

Traceback (most recent call last):
  File "/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64_branch/sw/qa/uitest/writer_tests7/tdf143244.py", line 48, in test_tdf143244
    self.assertEqual(sHexCustomText, "ffffff")
AssertionError: 'bee3d3' != 'ffffff'

Does this patch depend on another patch wich is not backported to 7.2 branch ?

Patch-set: 5