-fsanitize=vptr needs DocumentBroker RTTI now
...since 97bd32ac0b062f400018179261965ddd3a309536 "Instrument document load and
startup for very simple diagnostics."

> ld.bfd: ../wsd/unittest-TileCache.o:(.data+0x16a8): undefined reference to `typeinfo for DocumentBroker'

So add stubs for the dtor (which causes RTTI to be emitted) and all the virtual
functions (which would otherwise cause linkage errors).

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: Ic0b4e92709772f98fd5b09c692224cadd523aaf3
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/2654
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>