CppunitTest_sc_vba_macro_test: Do not test specific file on Windows
tb39 fails now with

C:/cygwin64/home/tdf/lode/jenkins/workspace/gerrit_windows/sc/qa/extras/vba-macro-test.cxx(605) : error : Assertion
Test name: VBAMacroTest::testVba
equality assertion failed
- Expected: OK
- Actual  : Test Results
============

 Failed:  : Test change event for Range.Clear set:
 Failed:  : Test change event for Range.ClearContents set:
 Failed:  : Test change event for Range.Replace:
 Failed:  : Test change event for Range.FillRight:
Tests passed: 4
Tests failed: 4

- script reported failure in file Ranges-3.xls

Change-Id: If226dfc201f124712abeec422cf79a675d25b9fb
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/141365
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
(cherry picked from commit a42c8923031522284c3199bed397c9e9639a71b5)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/141413