Silence spurious -Werror=array-bounds=
seen at least with recent GCC 16 trunk,

> In member function ‘virtual void SbModule::SetParent(SbxObject*)’,
>     inlined from ‘virtual SbxVariable* SbModule::Find(const rtl::OUString&, SbxClassType)’ at basic/source/classes/sbxmod.cxx:653:36:
> basic/source/classes/sbxmod.cxx:671:13: error: array subscript ‘SbModule[0]’ is partly outside array bounds of ‘unsigned char [152]’ [-Werror=array-bounds=]
>   671 |     pParent = p;
>       |     ~~~~~~~~^~~
> basic/source/classes/sbxmod.cxx: In member function ‘virtual SbxVariable* SbModule::Find(const rtl::OUString&, SbxClassType)’:
> basic/source/classes/sbxmod.cxx:651:55: note: object of size 152 allocated by ‘operator new’
>   651 |                     pRes = new SbxVariable( SbxOBJECT );
>       |                                                       ^

Change-Id: I0823b28063b6e224f9cc28aee55fd21e2f21aa1a
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/197833
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>
(cherry picked from commit 56a43e096682b38780925e4ba8eb3e1bb056214a)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/200981
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Andras Timar <andras.timar@collabora.com>