Update patch set 1
Patch Set 1:

I had no success with '$ ./logerrit cherry-pick 45038' either. 

error: could not apply 881a9178ee5b... tdf#113512 Icons for 1.15, 2.5 and 3 line spacing
hint: after resolving the conflicts, mark the corrected paths

Patch-set: 1