Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/9498/ : FAILURE

Visual studio complained about error C2664: "rtl::OUString::OUString(const rtl::OUString &)": cannot convert argument 1 from "const char *" to "rtl_uString *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sc/source/ui/StatisticsDialogs/RegressionDialog.cxx(344) ( https://ci.libreoffice.org/job/gerrit_windows/10029/ )

Patch-set: 3
Label: Verified=-1