Update patch set 1
Patch Set 1:

> I had no success with '$ ./logerrit cherry-pick 45038' either.
 > 
 > error: could not apply 881a9178ee5b... tdf#113512 Icons for 1.15,
 > 2.5 and 3 line spacing
 > hint: after resolving the conflicts, mark the corrected paths

you likely need to update your git repo, but as mentioned previously, this patch awaits your patch to merge in first - https://gerrit.libreoffice.org/44318

Patch-set: 1