fix 32 bit build
/home/rene/LibreOffice/git/libreoffice-24-2/vcl/qa/cppunit/a11y/atspi2/atspi2.cxx: In static member function 'static void Atspi2TestTree::compareObjects(const com::sun::star::uno::Reference<com::sun::star::accessibility::XAccessible>&, const Atspi::Accessible&, sal_uInt16)':
/home/rene/LibreOffice/git/libreoffice-24-2/vcl/qa/cppunit/a11y/atspi2/atspi2.cxx:362:9: error: no matching function for call to 'assertEquals(const long int&, int, CppUnit::SourceLine, const char [1])'
  362 |         CPPUNIT_ASSERT_EQUAL(nLOTargetsCount, pAtspiRelation.getNTargets());
      |         ^
/usr/include/cppunit/TestAssert.h:161:6: note: candidate: 'template<class T> void CppUnit::assertEquals(const T&, const T&, SourceLine, const std::string&)'
  161 | void assertEquals( const T& expected,
      |      ^~~~~~~~~~~~
/usr/include/cppunit/TestAssert.h:161:6: note:   template argument deduction/substitution failed:
/home/rene/LibreOffice/git/libreoffice-24-2/vcl/qa/cppunit/a11y/atspi2/atspi2.cxx:362:9: note:   deduced conflicting types for parameter 'const T' ('long int' and 'int')
  362 |         CPPUNIT_ASSERT_EQUAL(nLOTargetsCount, pAtspiRelation.getNTargets());
      |         ^
make: *** [/home/rene/LibreOffice/git/libreoffice-24-2/solenv/gbuild/LinkTarget.mk:340: /home/rene/LibreOffice/git/libreoffice-24-2/workdir/CxxObject/vcl/qa/cppunit/a11y/atspi2/atspi2.o] Error 1

Change-Id: I7b7e3e756b135d1066af631e92738e7dfc1ede4a
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/160882
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
(cherry picked from commit ffa28c3565ca0474312c0fabca18689e8a80381b)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/160865
Tested-by: René Engelhard <rene@debian.org>