Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/21428/ : FAILURE

error ""SetDrawingArea" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sw/source/uibase/inc/optload.hxx:129:18 ( https://ci.libreoffice.org/job/gerrit_mac/22489/ )

error: "SetDrawingArea" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sw/source/uibase/inc/optload.hxx ( https://ci.libreoffice.org/job/gerrit_mac/22489/ )

Patch-set: 2
Label: Verified=-1