Fix build
 C:\lo\core\vcl\inc\jsdialog/jsdialogmessages.hxx(85): error C2039: 'mutex':
 is not a member of 'std'

Change-Id: I5d43e415cef5b16a4b71d3772e3f40e8135cdfab
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/178272
Tested-by: Jenkins
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>
(cherry picked from commit 40b6e282aacf5a641c0b0cbd6183aee43e28a463)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/182230
Tested-by: Mike Kaganski <mike.kaganski@collabora.com>