Update patch set 1
Patch Set 1:

> Visual studio complained about error C2065: "nNewLen": undeclared identifier in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sal/osl/w32/file_dirvol.cxx(1684) ( https://ci.libreoffice.org/job/gerrit_windows/56153/ )

And actually I don't understand what happened here... need to look into the related parent change maybe.

Patch-set: 1