Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/79367/ : FAILURE

Visual studio complained about error C2440: "reinterpret_cast": cannot convert from "LPCWSTR" to "char16_t *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/xmlsecurity/source/xmlsec/mscrypt/x509certificate_mscryptimpl.cxx(664) ( https://ci.libreoffice.org/job/gerrit_windows/89634/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1