-Werror=maybe-uninitialized
/home/noel/libo3/svx/source/toolbars/extrusionbar.cxx: In static member
function ‘static void svx::ExtrusionBar::getState(const SdrView*,
SfxItemSet&)’:
/home/noel/libo3/svx/source/toolbars/extrusionbar.cxx:938:25: error:
‘eMetalType’ may be used uninitialized in this function
[-Werror=maybe-uninitialized]
938 |                         if (eMetalType ==
EnhancedCustomShapeMetalType::MetalMSCompatible)
      |                         ^~
/home/noel/libo3/svx/source/toolbars/extrusionbar.cxx:933:31: note:
‘eMetalType’ was declared here
  933 |                     sal_Int16 eMetalType;
      |                               ^~~~~~~~~~

Change-Id: Ie98bb04900d271299cb930bf6d12af46d45ae8c9