Update patch set 38
Patch Set 38: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/83531/ : FAILURE

error: bad static variable causes crash on shutdown [loplugin:badstatics] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sfx2/source/doc/docfile.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/85023/ )

clang plugin badstatics did trigger. bad static variable causes crash on shutdown ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/85023/ )

Patch-set: 38
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1