Fix Windows build after 19f8ea668833a4dc90244792cbf91881b0ca9a07
c:\lo\src\core\connectivity\source\drivers\mysqlc\mysqlc_databasemetadata.cxx(1058) : error C2220: warning treated as error - no 'object' file generated
c:\lo\src\core\connectivity\source\drivers\mysqlc\mysqlc_databasemetadata.cxx(1058) : warning C4702: unreachable code

Make code match commit acafd1ac87cb23a447353b8f0419a25fbe1c4430 in master

Change-Id: I1da66e8cf97eb5820023c5bfa6342eb31cf89b74
Reviewed-on: https://gerrit.libreoffice.org/78984
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>
Tested-by: Mike Kaganski <mike.kaganski@collabora.com>