Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_61/1257/ : FAILURE

Visual studio complained about error C2440: "=": cannot convert from "const vcl::Window *" to "vcl::Window *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/vcl/source/window/dialog.cxx(136) ( https://ci.libreoffice.org/job/gerrit_windows/21552/ )

Patch-set: 1
Label: Verified=-1