comphelper: Fix GCC 11.3/12.1 build ('-Werror=class-memaccess')
After

    commit 826b536fddfebf9e19efae9dbf3dbd86861c6d74
    Date:   Fri May 20 12:52:13 2022 +0200

        don't waste time on memset when we're just going to overwrite it

, my build with GCC 11.3.0 or 12.1.0 on Debian testing started to fail
like this:

> .../comphelper/source/streaming/memorystream.cxx: In member function ‘virtual void comphelper::{anonymous}::UNOMemoryStream::writeBytes(const com::sun::star::uno::Sequence<signed char>&)’:
> .../comphelper/source/streaming/memorystream.cxx:221:11: error: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘struct comphelper::{anonymous}::UNOMemoryStream::NoInitInt8’ from an array of ‘const signed char’ [-Werror=class-memaccess]
>   221 |     memcpy( pCursor, aData.getConstArray(), nBytesToWrite );
>       |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> .../comphelper/source/streaming/memorystream.cxx:86:12: note: ‘struct comphelper::{anonymous}::UNOMemoryStream::NoInitInt8’ declared here
>    86 |     struct NoInitInt8
>       |            ^~~~~~~~~~
> cc1plus: all warnings being treated as errors

Cast to `void*` to avoid that.

Change-Id: Iadabb727abf6c60668c40e0729f5f434e609dde7