Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/52852/ : FAILURE

error "value of type "sfx2::SvBaseLinkObjectType" is not implicitly convertible to "int"" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sw/inc/section.hxx:49:34 ( https://ci.libreoffice.org/job/gerrit_mac/57236/ )

error: value of type "sfx2::SvBaseLinkObjectType" is not implicitly convertible to "int" in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sw/inc/section.hxx ( https://ci.libreoffice.org/job/gerrit_mac/57236/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1