Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/21898/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "std::unique_ptr<connectivity::OSQLParseNode,std::default_delete<_Ty>>" to "connectivity::OSQLParseNode *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/connectivity/source/drivers/ado/APreparedStatement.cxx(64) ( https://ci.libreoffice.org/job/gerrit_windows/25059/ )

Patch-set: 3
Label: Verified=-1