Update patch set 3
Patch Set 3:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/92813/ : FAILURE

error: externally available entity "Int2Str" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/hwpfilter/source/hcode.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/93760/ )

clang plugin external did trigger. externally available entity "Int2Str" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/93760/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>