Update patch set 7
Patch Set 7:

> Patch Set 7: Verified-1
> 
> Build Failed 
> 
> https://ci.libreoffice.org/job/gerrit_master/78217/ : FAILURE
> 
> error: member reference type "SmColorTokenTableEntry" is not a pointer; did you mean to use "."? in file /home/tdf/lode/jenkins/workspace/android_x86_64/starmath/source/visitors.cxx ( https://ci.libreoffice.org/job/gerrit_android_x86_64/2465/ )

Sorry, seems the rebase broke something.

Patch-set: 7