-Werror=maybe-uninitialized
> sw/source/core/text/guess.cxx: In member function ‘bool SwTextGuess::Guess(const SwTextPortion&, SwTextFormatInfo&, sal_uInt16)’:
> sw/source/core/text/guess.cxx:220:37: error: ‘bHyphenationNoLastWord’ may be used uninitialized [-Werror=maybe-uninitialized]
>   220 |         if ( bHyphenationNoLastWord && sal_Int32(m_nCutPos) > nLastWord )
>       |              ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> sw/source/core/text/guess.cxx:201:14: note: ‘bHyphenationNoLastWord’ was declared here
>   201 |         bool bHyphenationNoLastWord;
>       |              ^~~~~~~~~~~~~~~~~~~~~~

since 8c018910ae4d8701b1ce2a95727b9baed4016da3 "tdf#149248 sw offapi xmloff: add
option to not hyphenate last word"

Change-Id: Id3be25bf9f5d6769555bfe461a0f4e1e27e0e39e