Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/34662/ : FAILURE

error ""Flush" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/starmath/inc/edit.hxx:118:10 ( https://ci.libreoffice.org/job/gerrit_mac/37551/ )

error: "Flush" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/starmath/inc/edit.hxx ( https://ci.libreoffice.org/job/gerrit_mac/37551/ )

Patch-set: 1
Label: Verified=-1