Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://cpci.cbg.collabora.co.uk:8080/job/Gerrit%20for%20co-2021/1307/ : FAILURE

Visual studio complained about error C2440: "reinterpret_cast": cannot convert from "long" to "tools::Long" in file C:/jenkins/workspace/gerrit_windows_co-2021_64bit/sfx2/source/view/ipclient.cxx(96) ( https://cpci.cbg.collabora.co.uk:8080/job/gerrit_windows_co-2021_64bit/773/ )

Patch-set: 6
Tag: autogenerated:jenkins-gerrit-trigger
Reviewer: Gerrit User 1002181 <1002181@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1