Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/100765/ : FAILURE

error "‘RID_STR_ACC_ACTION_DECBLOCK’ defined but not used [-Werror=unused-variable]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/accessibility/inc/strings.hxx:18:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/104383/ )

compiler warning unused-variable treated as error: ‘RID_STR_ACC_ACTION_DECBLOCK’ defined but not used in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/accessibility/inc/strings.hxx:18:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/104383/ )

error: ‘RID_STR_ACC_ACTION_DECBLOCK’ defined but not used [-Werror=unused-variable] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/accessibility/inc/strings.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/104383/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1