Update patch set 2
Patch Set 2:

> : error C2039: '_tstring' : is not a member of 'std'
 > 
 > You should not define functions in the reserved std namespace.

no, the problem is that msiprop.hxx is included too early, it needs to be included after the #ifdef UNICODE #define _tstring ... block, and after #include <string>.

this whole _tstring nonsense is obsolete anyway, we should always have UNICODE defined on Win32, since DOS-based Windowses are no longer supported.  see also https://bugs.freedesktop.org/show_bug.cgi?id=72606

Patch-set: 2
Reviewer: Gerrit User 1000022 <1000022@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0