Revert "tdf#112689: Replace changed O(U)StringBuffer::append() with operator+"
Sorry, but this change breaks the build:
bridges/source/cpp_uno/msvc_win32_x86-64/except.cxx(884): error C2110: '+': cannot add two pointers

This reverts commit 867384792244667a33cad79a7348b34b6008822b.