Silence strange -Wclobbered with recent GCC 14
...seen at least with some (--enable-dbgutil --enable-otpimized etc.)
configuration and a recent GCC 14 trunk,

> vcl/source/filter/png/PngImageReader.cxx: In function ‘bool {anonymous}::reader(SvStream&, Graphic&, GraphicFilterImportFlags, BitmapScopedWriteAccess*, BitmapScopedWriteAccess*)’:
> vcl/source/filter/png/PngImageReader.cxx:361:16: error: variable ‘bSupportsBitmap32’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
>   361 |     const bool bSupportsBitmap32 = bFuzzing || ImplGetSVData()->mpDefInst->supportsBitmap32();
>       |                ^~~~~~~~~~~~~~~~~

Change-Id: Icc1932347a213877ecc9f561f98de779f8041c09
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/165823
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
(cherry picked from commit 2bcd9fe0fa10339294e6ab820498fa18334e02f3)