Do not convert the managed CLI Any to cpo::uno::Any
> [CLI] cli_uretypes
> error: .NET exception occurred: System.TypeLoadException: Access is denied: 'cpo.uno.Any'.
> [...]
> dying abnormally...

78580b29020a71bf87d59d61e7d2b71d6e59b1e8 ("cool#15927 convert css::uno::Any to
cpo::uno::Any", 2026-06-24) moved the native css::uno::Any to cpo::uno::Any, and
its blanket replacement also rewrote the C++/CLI references to the managed
cli_basetypes Any (uno::Any, used via ::typeid, ^ casts, cli::array, ::VOID) to
cpo::uno::Any. That managed type is the .NET binding in cli_basetypes (namespace
uno, i.e. uno.Any), which was not renamed, so climaker emitted references to the
native type's System::Type and aborted at CreateType.

Point those references back at the managed uno::Any.

Signed-off-by: Mike Kaganski <mike.kaganski@collabora.com>
Change-Id: I136215ba4508c072d1eef15b4459e5ac144e962e
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/5159
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>