Fix build
[CXX] svgio/qa/cppunit/SvgRead.cxx
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(103): error C2440: '<function-style-cast>': cannot convert from 'Color' to 'sal_Int32'
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(103): note: No user-defined-conversion operator available that can perform this conversion, or the operator
cannot be called
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(103): error C2672: 'CppUnit::assertEquals': no matching overloaded function found
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(103): error C2780: 'void CppUnit::assertEquals(const T &,const T &,CppUnit::SourceLine,const std::string
&)': expects 4 arguments - 3 provided
C:\lo\src\core2\workdir\UnpackedTarball\cppunit\include\cppunit/TestAssert.h(127): note: see declaration of 'CppUnit::assertEquals'
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(105): error C2440: '<function-style-cast>': cannot convert from 'Color' to 'sal_Int32'
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(105): note: No user-defined-conversion operator available that can perform this conversion, or the operator
cannot be called
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(105): error C2672: 'CppUnit::assertEquals': no matching overloaded function found
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(105): error C2780: 'void CppUnit::assertEquals(const T &,const T &,CppUnit::SourceLine,const std::string
&)': expects 4 arguments - 3 provided
C:\lo\src\core2\workdir\UnpackedTarball\cppunit\include\cppunit/TestAssert.h(127): note: see declaration of 'CppUnit::assertEquals'
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(134): error C2440: '<function-style-cast>': cannot convert from 'Color' to 'sal_Int32'
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(134): note: No user-defined-conversion operator available that can perform this conversion, or the operator
cannot be called
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(134): error C2672: 'CppUnit::assertEquals': no matching overloaded function found
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(134): error C2780: 'void CppUnit::assertEquals(const T &,const T &,CppUnit::SourceLine,const std::string
&)': expects 4 arguments - 3 provided
C:\lo\src\core2\workdir\UnpackedTarball\cppunit\include\cppunit/TestAssert.h(127): note: see declaration of 'CppUnit::assertEquals'
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(136): error C2440: '<function-style-cast>': cannot convert from 'Color' to 'sal_Int32'
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(136): note: No user-defined-conversion operator available that can perform this conversion, or the operator
cannot be called
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(136): error C2672: 'CppUnit::assertEquals': no matching overloaded function found
C:/lo/src/core2/svgio/qa/cppunit/SvgRead.cxx(136): error C2780: 'void CppUnit::assertEquals(const T &,const T &,CppUnit::SourceLine,const std::string
&)': expects 4 arguments - 3 provided
C:\lo\src\core2\workdir\UnpackedTarball\cppunit\include\cppunit/TestAssert.h(127): note: see declaration of 'CppUnit::assertEquals'
make[1]: *** [C:/lo/src/core2/solenv/gbuild/LinkTarget.mk:293: C:/lo/src/core2/workdir/CxxObject/svgio/qa/cppunit/SvgRead.o] Error 2
make: *** [Makefile:166: CppunitTest_svgio_read] Error 2

Change-Id: I4e1cf222a416772f1920194ccfcf459f40b577d6
Reviewed-on: https://gerrit.libreoffice.org/69064
Reviewed-by: Tomaž Vajngerl <quikee@gmail.com>
Tested-by: Tomaž Vajngerl <quikee@gmail.com>