Introduce --enable-quickjs and external/quickjs
...as a first step to "enable QuickJS-based JS UNO support".  (For simplicity,
--enable-quickjs is intended to control both building of external/quickjs now
and then building the upcoming UNO JS support on top of it.  Also, for now there
is no --with-system-quickjs, as it doesn't seem to be included in relevant
systems, anyway.)

The build system is using CMake (from within a Makefile), and even if we would
get that working from within gbuild, it wouldn't build a dynamic library (which
is what we are interested in here) by default.  And even if we would get a
-DBUILD_SHARED_LIBS=ON in, at least on Linux the resulting build would fail for
me with

> [  4%] Building C object CMakeFiles/cutils.dir/cutils.c.o
> [  9%] Linking C static library libcutils.a
> [  9%] Built target cutils
> [ 14%] Building C object CMakeFiles/qjs.dir/dtoa.c.o
> [ 19%] Building C object CMakeFiles/qjs.dir/libregexp.c.o
> [ 23%] Building C object CMakeFiles/qjs.dir/libunicode.c.o
> [ 28%] Building C object CMakeFiles/qjs.dir/quickjs.c.o
> [ 33%] Linking C shared library libqjs.so
> /usr/bin/ld: libcutils.a(cutils.c.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: failed to set dynamic section sizes: bad value
> collect2: error: ld returned 1 exit status

So just introduce an external/quickjs/Library_qjs.mk that builds that qjs
dynamic library from those five C source files manually (eliding the
intermediary cutils static library for simplicity).  (It appears that there's
also support for Meson; but yuck.)

(The external/quickjs/windows.patch is needed to avoid

> C:\PROGRA~2\WI3CF2~1\10\Include\10.0.26100.0\shared\ws2def.h(246): error C2011: 'sockaddr': 'struct' type redefinition
> C:\PROGRA~2\WI3CF2~1\10\Include\10.0.26100.0\um\winsock.h(482): note: see declaration of 'sockaddr'

when building workdir/UnpackedTarball/quickjs/cutils.c on Windows.)

The used quickjs-v0.12.0.tar.gz is from
<https://github.com/quickjs-ng/quickjs/archive/refs/tags/v0.12.0.tar.gz>.

Change-Id: I3e954e4e0b621d540e8b9cd9648fc4e9e2b54b9b
Reviewed-on: https://gerrit.collaboraoffice.com/c/core/+/189
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>