qt: Rename QtMenu::InsertMenuItem to avoid clash on win
Rename QtMenu::InsertMenuItem to QtMenu::InsertQtMenuItem
to avoid a name clash with Windows API on Windows, seen
when experimenting with WIP change [1]:

    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(78): error C2039: 'InsertMenuItemA': is not a member of 'QtMenu'
    C:\Users\mwegh\development\git\libreoffice\vcl\inc\qt6\../qt5/QtMenu.hxx(41): note: see declaration of 'QtMenu'
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(115): error C2355: 'this': can only be referenced inside non-static member functions or non-static data member initializers
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(117): error C2355: 'this': can only be referenced inside non-static member functions or non-static data member initializers
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(156): error C2355: 'this': can only be referenced inside non-static member functions or non-static data member initializers
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(158): error C2355: 'this': can only be referenced inside non-static member functions or non-static data member initializers
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(206): error C2355: 'this': can only be referenced inside non-static member functions or non-static data member initializers
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(208): error C2355: 'this': can only be referenced inside non-static member functions or non-static data member initializers
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(83): error C2065: 'mpVCLMenu': undeclared identifier
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(84): error C2065: 'mpVCLMenu': undeclared identifier
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(89): error C2065: 'mbMenuBar': undeclared identifier
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(92): error C3861: 'validateQMenuBar': identifier not found
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(95): error C3861: 'connectHelpSignalSlots': identifier not found
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(100): error C2065: 'mpQMenuBar': undeclared identifier
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(100): error C2672: 'o3tl::make_unsigned': no matching overloaded function found
    C:\Users\mwegh\development\git\libreoffice\include\o3tl/safeint.hxx(208): note: could be 'make_unsigned<_Ty>::type o3tl::make_unsigned(T)'
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(102): error C2065: 'mpQMenuBar': undeclared identifier
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(102): error C2065: 'mpQMenuBar': undeclared identifier
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(106): error C2065: 'mpQMenuBar': undeclared identifier
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(112): error C2248: 'QtMenu::mpQMenu': cannot access private member declared in class 'QtMenu'
    C:\Users\mwegh\development\git\libreoffice\vcl\inc\qt6\../qt5/QtMenu.hxx(54): note: see declaration of 'QtMenu::mpQMenu'
    C:\Users\mwegh\development\git\libreoffice\vcl\inc\qt6\../qt5/QtMenu.hxx(41): note: see declaration of 'QtMenu'
    [...]

An alternative solution could have been to undefine the
InsertMenuItem macro like this:

    diff --git a/vcl/qt5/QtMenu.cxx b/vcl/qt5/QtMenu.cxx
    index 69c88432f031..7b6484dacc9d 100644
    --- a/vcl/qt5/QtMenu.cxx
    +++ b/vcl/qt5/QtMenu.cxx
    @@ -44,6 +44,10 @@
     #include <vcl/toolkit/floatwin.hxx>
     #include <window.h>

    +#ifdef InsertMenuItem
    +#undef InsertMenuItem
    +#endif

[1] https://gerrit.libreoffice.org/c/core/+/199615

Change-Id: I65ee4d3f1596b188ce5d0b61073353504737afae
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/201547
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>