Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/118314/ : FAILURE

error: variable "sHyperLinkEvents" of type "const rtl::OUStringLiteral<16>" with automatic storage duration most likely needs to be static [loplugin:stringliteralvar] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/xmloff/source/text/txtparae.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/117132/ )

clang plugin stringliteralvar did trigger. variable "sHyperLinkEvents" of type "const rtl::OUStringLiteral<16>" with automatic storage duration most likely needs to be static ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/117132/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1, 6348890a9f7917595f56c1cc4f81797eb8d6137d
Attention: {"person_ident":"Gerrit User 1000994 \u003c1000994@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}