Fix gpgme build on Windows
Commit 97c67afac1ec9351d0a64011a7ddfb7dfa876484 (Update gpgme to 1.20.0,
2023-06-23) defined ssize_t in external/gpgmepp/w32-build-fixes.patch.1.
It was done to address the use of ssize_t in src/debug.h, appeared in
https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=patch;h=7d1159c1e99bb1bae0ab698c85105dcdcb95b7ea

This led to build errors like

  C:\cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win64_dbg\workdir\UnpackedTarball\gpgmepp\src\debug.h(26): error C2371: 'ssize_t': redefinition; different basic types
  C:\cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win64_dbg\workdir\UnpackedTarball\libassuan\src\assuan.h(47): note: see declaration of 'ssize_t'

To fix it locally, just revert the problematic patch, until fixed upstream.

Change-Id: Ib89496cc08b0ce6d24d5c9e9c7e615c6909d071b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/153671
Tested-by: Jenkins
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>