Update patch set 2
Patch Set 2:

> > bridges/source/cpp_uno/gcc3_linux_aarch64/abi.cxx
 > > Line 42:
 > > (here and elsewhere:) such a cross-dir include looks fishy; why
 > would it be necessary?
 > 
 > Without this, I'm getting:
 > 
 > /local/libreoffice/master-android-release-64bit/bridges/source/cpp_uno/gcc3_linux_aarch64/abi.cxx:118:40:
 > error: no type named '__class_type_info' in namespace '__cxxabiv1'
 > rtti = new __cxxabiv1::__class_type_info(strdup(rttiName));
 > ~~~~~~~~~~~~^
 > /local/libreoffice/master-android-release-64bit/bridges/source/cpp_uno/gcc3_linux_aarch64/abi.cxx:122:40:
 > error: no type named '__si_class_type_info' in namespace
 > '__cxxabiv1'
 > rtti = new __cxxabiv1::__si_class_type_info(
 > ~~~~~~~~~~~~^
 > 
 > and similar.
 > 
 > I did not want to just copy the file over, I thought it would be
 > better to share it.

So HAVE_CXXABI_H_CLASS_TYPE_INFO and HAVE_CXXABI_H_SI_CLASS_TYPE_INFO are apparently unset for your Android aarch64 build.  I would add any necessary definitions to bridges/source/cpp_uno/gcc3_linux_aarch64/abi.hxx.  gcc3_linux_arm/share.hxx includes stuff that is not relevant here, so I would avoid including it (esp. if you only test Android aarch64, but not other Linux aarch64 configurations which also use bridges/source/cpp_uno/gcc3_linux_aarch64/).  (Ultimately, we should clean the bridges/source/cpp_uno/gcc3_linux_*/ mess up, but that's a delicate task because it needs testing all those platforms to ensure nothing breaks.)

Patch-set: 2