Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/79053/ : FAILURE

error "virtual function "createPicker" has a different return type ("Qt5FilePicker *") than the function it overrides (which has return type "rtl::Reference<Qt5FilePicker>")" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/unx/kf5/KF5SalInstance.hxx:27:20 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/80908/ )

error: virtual function "createPicker" has a different return type ("Qt5FilePicker *") than the function it overrides (which has return type "rtl::Reference<Qt5FilePicker>") in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/unx/kf5/KF5SalInstance.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/80908/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1