Revert the removal of cast to build on old poppler
In file included from /usr/src/packages/BUILD/libreoffice-5.0.0.0.beta3/sdext/source/pdfimport/xpdfwrapper/wrapper_gpl.cxx:20:0:
/usr/src/packages/BUILD/libreoffice-5.0.0.0.beta3/sdext/source/pdfimport/xpdfwrapper/pdfioutdev_gpl.hxx:
In member function 'bool pdfi::FontAttributes::operator==(const pdfi::FontAttributes&) const':
/usr/src/packages/BUILD/libreoffice-5.0.0.0.beta3/sdext/source/pdfimport/xpdfwrapper/pdfioutdev_gpl.hxx:126:58:
error: passing 'const GooString' as 'this' argument of 'int GooString::cmp(GooString*)' discards qualifiers [-fpermissive]

Change-Id: Ie941c9028890fd0a51a4e86a9eedff04d60488bc