Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/33577/ : FAILURE

error ""visit" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/oox/source/drawingml/diagram/layoutatomvisitorbase.hxx:62:18 ( https://ci.libreoffice.org/job/gerrit_mac/36354/ )

error: "visit" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/oox/source/drawingml/diagram/layoutatomvisitorbase.hxx ( https://ci.libreoffice.org/job/gerrit_mac/36354/ )

Patch-set: 3
Label: Verified=-1