Missing test dependency
> [_RUN_____] CRMDBTest::testCRMDatabase
[...]
> java.lang.ClassNotFoundException: org.hsqldb.jdbcDriver
> 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:349)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:557)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
> unknown:0:CRMDBTest::testCRMDatabase
> An uncaught UNO exception
> - com.sun.star.sdbc.SQLException: {Message: "The driver class “org.hsqldb.jdbcDriver” could not be loaded.The additional driver class path is “vnd.sun.star.expand:$LO_JAVA_DIR/hsqldb.jar vnd.sun.star.expand:$LO_JAVA_DIR/sdbc_hsqldb.jar”. at /home/sberg/lo/core/connectivity/source/drivers/jdbc/JConnection.cxx:674", Context: @0x7b373fdfdb70, SQLState: "", ErrorCode: 1000, NextException: com.sun.star.sdbc.SQLException: {Message: "org.hsqldb.jdbcDriver at /home/sberg/lo/core/connectivity/source/drivers/jdbc/Object.cxx:185", Context: @0x7b373fd19b70, SQLState: "", ErrorCode: -1, NextException: void: void}}

Change-Id: I4aeadfcf2a5c82eea4bf1fd646bceba4e8da5f4a
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/182422
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
Tested-by: Jenkins