Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/69495/ : FAILURE

error "ParmVarDecl, use "tools::Long" instead of "long" [loplugin:toolslong]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/test/cppunitasserthelper.hxx:106:32 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/71843/ )

error: ParmVarDecl, use "tools::Long" instead of "long" [loplugin:toolslong] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/test/cppunitasserthelper.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/71843/ )

clang plugin toolslong did trigger. ParmVarDecl, use "tools::Long" instead of "long" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/71843/ )

Patch-set: 6
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1