qt5: Fix build
The utility constructor using 'StockImage::Yes' was only introduced
in master commit 0f104bf33530467380044b9eb4cd3f8bd9c283f1 and is
therefore not available in libreoffice-6-2 branch.

Build was therefore broken by commit
f10c1c648e698b48dfaa679a4909b3d9de6ed868 ("tdf#123549 Qt5 implement
Qt5Menu::ShowCloseButton"), which first went unnoticed since
qt5/kde5 wasn't enabled for CI builds on branch libreoffice-6-2.
(This will be changed by
 https://gerrit.libreoffice.org/#/c/72741/ .)

Also, add a missing include that lead to kde5-enabled CI builds
failing [1], which I couldn't reproduce locally
("shell/source/backends/kde5be/kde5backend.cxx:190:5: error:
‘unique_ptr’ is not a member of ‘std’").

And fix more issues showing up in [2].

[1] https://ci.libreoffice.org/job/gerrit_62/1535/
[2] https://ci.libreoffice.org/job/gerrit_62/1540/

Change-Id: I6a39a99114d15808b790242c96d0204916a0cc40