Update patch set 1
Patch Set 1:

This breaks the build:

 In file included from /master/sw/source/filter/ww8/docxattributeoutput.hxx:23:0,
                  from /master/sw/source/filter/ww8/docxexport.cxx:22:
 /master/sw/source/filter/ww8/attributeoutputbase.hxx:163:18: error: ‘virtual void AttributeOutputBase::EndParagraphProperties(const SwRedlineData*)’ was hidden [-Werror=overloaded-virtual]
      virtual void EndParagraphProperties( const SwRedlineData* pRedlineData ) = 0;
                   ^
 In file included from /master/sw/source/filter/ww8/docxexport.cxx:22:0:
 /master/sw/source/filter/ww8/docxattributeoutput.hxx:144:18: error:   by ‘virtual void DocxAttributeOutput::EndParagraphProperties(const SwRedlineData*, const SwRedlineData*)’ [-Werror=overloaded-virtual]
      virtual void EndParagraphProperties( const SwRedlineData* pRedlineData, const SwRedlineData* pRedlineParagraphMarkerDeleted );
                   ^
 /master/sw/source/filter/ww8/docxexport.cxx: In constructor ‘DocxExport::DocxExport(DocxExportFilter*, SwDoc*, SwPaM*, SwPaM*)’:
 /master/sw/source/filter/ww8/docxexport.cxx:1230:81: error: cannot allocate an object of abstract type ‘DocxAttributeOutput’
      m_pAttrOutput = new DocxAttributeOutput( *this, m_pDocumentFS, m_pDrawingML );
                                                                                  ^
 In file included from /master/sw/source/filter/ww8/docxexport.cxx:22:0:
 /master/sw/source/filter/ww8/docxattributeoutput.hxx:122:7: note:   because the following virtual functions are pure within ‘DocxAttributeOutput’:
  class DocxAttributeOutput : public AttributeOutputBase, public oox::vml::VMLTextExport, public oox::drawingml::DMLTextExport
        ^
 In file included from /master/sw/source/filter/ww8/docxattributeoutput.hxx:23:0,
                  from /master/sw/source/filter/ww8/docxexport.cxx:22:
 /master/sw/source/filter/ww8/attributeoutputbase.hxx:163:18: note:         virtual void AttributeOutputBase::EndParagraphProperties(const SwRedlineData*)
      virtual void EndParagraphProperties( const SwRedlineData* pRedlineData ) = 0;

I'll try to see if squashing this change with the other two of yours fixes the problem.

Patch-set: 1
Reviewer: Gerrit User 1000013 <1000013@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0
Label: Code-Review=0