Make abs return int, not double.
Without this change the output of abs is double, and % does not accept
double as an input. This causes a build failure:

sax/source/tools/converter.cxx:1270:47: error: invalid operands of types ‘__gnu_cxx::__enable_if<true, double>::__type {aka double}’ and ‘int’ to binary ‘operator%’
const sal_Int32 nMinutes(abs(nOffset) % 60);
                         ~~~~~~~~~~~~~^~~~

Change-Id: I811af07b90e2931487fe0f2d58d9b2d42bff43f9