Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/72162/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "std::vector<SvtDynMenuEntry,std::allocator<SvtDynMenuEntry>>" to "com::sun::star::uno::Sequence<com::sun::star::uno::Sequence<com::sun::star::beans::PropertyValue>>" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/sfx2/source/appl/shutdowniconw32.cxx(154) ( https://ci.libreoffice.org/job/gerrit_windows/81872/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1