Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/100679/ : FAILURE

error "definition of implicit copy constructor for "Theme" is deprecated because it has a user-declared destructor [-Werror,-Wdeprecated-copy-dtor]" triggered in included file /Volumes/Jenkins/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/oox/drawingml/theme.hxx:60:25 ( https://ci.libreoffice.org/job/gerrit_mac/105841/ )

error: definition of implicit copy constructor for "Theme" is deprecated because it has a user-declared destructor [-Werror,-Wdeprecated-copy-dtor] in file /Volumes/Jenkins/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/oox/drawingml/theme.hxx ( https://ci.libreoffice.org/job/gerrit_mac/105841/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000135 \u003c1000135@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}