Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/100227/ : FAILURE

clang plugin unusedcapturedefault did trigger. unused capture-default ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/100669/ )

error: unused capture-default [loplugin:unusedcapturedefault] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/desktop/source/deployment/misc/dp_platform.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/100669/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1