sd: fix missing include
/home/vmiklos/git/libreoffice/master/sd/source/ui/slidesorter/controller/SlsClipboard.cxx:758:13: error: ‘BOOST_ASSERT’ was not declared in this scope

Change-Id: I0fa4b70c931b14776e75be4f395798b9c038ae94