Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/107401/ : FAILURE

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "std::unique_ptr<SvxSearchItem>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/107201/ )

error: no need to explicitly init an instance of "std::unique_ptr<SvxSearchItem>" with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sd/source/ui/view/Outliner.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/107201/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1