Update patch set 1
Patch Set 1: Code-Review-1

As the Jenkins builds show this introduces duplicated indices
Error: Duplicated formatindex="6" in FormatElement.
Error: Duplicated formatindex="7" in FormatElement.

For semantics see the comments in https://gerrit.libreoffice.org/gitweb?p=core.git;a=blob_plain;f=i18npool/source/localedata/data/locale.dtd;hb=HEAD

I'll submit a corrected amended commit.

Patch-set: 1
Label: Code-Review=-1