move SAL_LOG code out of line
which is beneficial when we have a --enable-sal-log release build,
since most of the time the logging stuff will not be executed.

This is restricted to GCC because clang seems to have trouble
with the lambda binding in some places. (tested with clang 12.0.1)
I get errors like:
  cppuhelper/source/servicemanager.cxx:775:40:
  error: reference to local binding 'rImpls' declared in
  enclosing function 'cppuhelper::ServiceManager::addSingletonContextEntries'
  "Arbitrarily choosing " << rImpls[0]->name

Change-Id: I3fe6deb94996542b552af1e201f5a68f0136c680
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/192151
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
(cherry picked from commit f6b9b77d65c70ae77fa617c53e11d149a9fee1d1)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/192192
Tested-by: Jenkins