Create change
Uploaded patch set 1.

Patch-set: 1
Change-id: Iff1db722239c32822bbc23ddd13e2df105a993e3
Subject: Fix MSVC 2019 16.8.3 --with-latest-c++ error C2102: '&' requires l-value
Branch: refs/heads/master
Status: new
Topic: 
Commit: 3ad82207d8ce25b76489a0176464052075c5de0a
Tag: autogenerated:gerrit:newPatchSet
Groups: 3ad82207d8ce25b76489a0176464052075c5de0a
Private: false
Work-in-progress: false