Silence -Werror,-Wdeprecated-declarations for now
...as seen with qt5-qtbase-devel-5.13.2-1.fc31.x86_64:

> vcl/qt5/Qt5System.cxx:18:83: error: 'screenCount' is deprecated: Use QGuiApplication::screens() [-Werror,-Wdeprecated-declarations]
> unsigned int Qt5System::GetDisplayScreenCount() { return QApplication::desktop()->screenCount(); }
>                                                                                   ^
> /usr/include/qt5/QtWidgets/qdesktopwidget.h:72:5: note: 'screenCount' has been explicitly marked deprecated here
>     QT_DEPRECATED_X("Use QGuiApplication::screens()") int screenCount() const;
>     ^
[...]
> vcl/qt5/Qt5System.cxx:22:44: error: 'screenGeometry' is deprecated: Use QGuiApplication::screens() [-Werror,-Wdeprecated-declarations]
>     QRect qRect = QApplication::desktop()->screenGeometry(nScreen);
>                                            ^
> /usr/include/qt5/QtWidgets/qdesktopwidget.h:79:5: note: 'screenGeometry' has been explicitly marked deprecated here
>     QT_DEPRECATED_X("Use QGuiApplication::screens()") const QRect screenGeometry(int screen = -1) const;
>     ^
[...]

(Same as 09597ab01d22820137ada0dc08b5a9bf481468a8 "Silence -Werror,-Wdeprecated
-declarations for now", but which had been found with only a partial rebuild, so
had happened to miss these.)

Change-Id: If51be8349b00021da340577bea442d07507e9cfd