Update patch set 1
Patch Set 1: -Code-Review Verified-1

something missing in 5.3?

/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sw/source/filter/ww8/ww8scan.cxx:7930:31: error: ‘nRemLen’ was not declared in this scope
             if (nIndex + 1 >= nRemLen)

Patch-set: 1
Reviewer: Gerrit User 1000022 <1000022@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1