solenv: gdb: BigPtrArrayPrinter, try both 0 and 0ul
Apparently commit ea858ca92488309789e83666681a358af1d9f6f6 broke it on
Fedora 38, where i now get:
  gdb.error: No type named std::_Head_base<0ul, BlockInfo**, false>.

So try both variants.

Change-Id: If344077df7a6b329286bc1296446562301305946
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/154525
Tested-by: Jenkins
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>