Update patch set 3
Abandoned

> (The GCC 4.8.5 used on the tinderboxes controlled by
> distro-configs/Jenkins/linux_clang_dbgutil_64 only supports -std=c++1y, not
> -std=c++14.)

...but even then doesn't know std::make_unique, see <https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/40385/console>:

[...]
> export COMPILER_PLUGINS_CXX=ccache g++ -std=c++1y
[...]
> [build CXX] compilerplugins/clang/cppunitassertequals.cxx
> /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/compilerplugins/clang/pluginhandler.cxx: In member function ‘virtual std::unique_ptr<clang::ASTConsumer> loplugin::LibreOfficeAction::CreateASTConsumer(clang::CompilerInstance&, llvm::StringRef)’:
> /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/compilerplugins/clang/pluginhandler.cxx:389:12: error: ‘make_unique’ is not a member of ‘std’
>      return std::make_unique<PluginHandler>( Compiler, _args );
>             ^
[...]

So lets keep the (ugly) status quo for now.

Patch-set: 3
Status: abandoned