Fix UBSan build's RTTI needs
...after 3ba92b5f1eaf7d4447a0943ea260db515ca799dc "hide more symbols" had caused
CppunitTest_sw_uiwriter to fail with

> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_sw_uiwriter.so
> workdir/LinkTarget/CppunitTest/libtest_sw_uiwriter.so: undefined symbol: _ZTIN2sw11UndoManagerE"

Change-Id: Ia17fd3c9d8f4e227cdd9ca3a5aa6f94f51c46168
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/164028
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>