loplugin:typedefparam: Work around different size_t typedefs on macOS
...which for me caused

> [CXX] registry/tools/options.cxx
> /Users/stephan/Software/lo/core/registry/tools/options.cxx:39:89: error: function param 3 at definition site does not match function param at declaration site, 'size_t' (aka 'unsigned long') vs 'size_t' (aka 'unsigned long') [loplugin:typedefparam]
> bool Options::checkArgument(std::vector< std::string> & rArgs, char const * arg, size_t len)
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
> /Users/stephan/Software/lo/core/registry/tools/options.hxx:41:93: note: declaration site here [loplugin:typedefparam]
>     static bool checkArgument (std::vector< std::string > & rArgs, char const * arg, size_t len);
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~

because one is

  TypedefType 0x115a4d700 'size_t' sugar
  |-Typedef 0x115a4d460 'size_t'
  `-BuiltinType 0x7fde8e0393c0 'unsigned long'

while the other is

  TypedefType 0x7fde8e94a3a0 'size_t' sugar
  |-Typedef 0x7fde8e94a138 'size_t'
  `-TypedefType 0x7fde8e94a100 '__darwin_size_t' sugar
    |-Typedef 0x7fde8e88cc28 '__darwin_size_t'
    `-BuiltinType 0x7fde8e0393c0 'unsigned long'

and

> [CXX] store/source/storcach.cxx
> /Users/stephan/Software/lo/core/store/source/storcach.cxx:218:43: error: function param 1 at definition site does not match function param at declaration site, 'std::size_t' (aka 'unsigned long') vs 'std::size_t' (aka 'unsigned long') [loplugin:typedefparam]
> void PageCache::rescale_Impl (std::size_t new_size)
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
> /Users/stephan/Software/lo/core/store/source/storcach.hxx:67:36: note: declaration site here [loplugin:typedefparam]
>     void rescale_Impl (std::size_t new_size);
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~

because one is

  ElaboratedType 0x116f5cba0 'std::size_t' sugar
  `-TypedefType 0x7fd58673e090 'size_t' sugar
    |-Typedef 0x7fd58673dde8 'size_t'
    `-BuiltinType 0x7fd58603cfc0 'unsigned long'

while the other is

  ElaboratedType 0x7fd586742200 'std::size_t' sugar
  `-TypedefType 0x7fd58621cdc0 'size_t' sugar
    |-Typedef 0x7fd5861ce4a0 'size_t'
    `-TypedefType 0x7fd5861cdc70 '__darwin_size_t' sugar
      |-Typedef 0x7fd586889ec8 '__darwin_size_t'
      `-BuiltinType 0x7fd58603cfc0 'unsigned long'

Change-Id: I3622716376198cc046b0489db59c5cbf613ea1f4
Reviewed-on: https://gerrit.libreoffice.org/73585
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>