Update patch set 2
Patch Set 2:

the newly introduced (presumably contrieved) sd/qa/unit/data/cgm/pass/ofz36348-ubsan-1.cgm causes <https://ci.libreoffice.org//job/lo_ubsan/2086/> to fail,

  Testing load file:///home/tdf/lode/jenkins/workspace/lo_ubsan//sd/qa/unit/data/cgm/pass/ofz36348-ubsan-1.cgm:
  /filter/source/graphicfilter/icgm/actimpr.cxx:458:55: runtime error: 1.30319e+233 is outside the range of representable values of type 'long'
      #0 0x2adeec7cd6e3 in CGMImpressOutAct::DrawRectangle(FloatRect const&) /filter/source/graphicfilter/icgm/actimpr.cxx:458:55
      #1 0x2adeec8c5bbd in CGM::ImplDoClass4() /filter/source/graphicfilter/icgm/class4.cxx:351:27
      #2 0x2adeec876ae4 in CGM::ImplDoClass() /filter/source/graphicfilter/icgm/cgm.cxx:574:13
      #3 0x2adeec87807d in CGM::ImplDefaultReplacement() /filter/source/graphicfilter/icgm/cgm.cxx:634:17
      #4 0x2adeec8937d7 in CGM::ImplDoClass0() /filter/source/graphicfilter/icgm/class0.cxx:57:17
      #5 0x2adeec876aac in CGM::ImplDoClass() /filter/source/graphicfilter/icgm/cgm.cxx:568:18
      #6 0x2adeec87956d in CGM::Write(SvStream&) /filter/source/graphicfilter/icgm/cgm.cxx:679:5
      #7 0x2adeec87a5d3 in ImportCGM /filter/source/graphicfilter/icgm/cgm.cxx:721:31
      #8 0x2ade9388e7af in SdCGMFilter::Import() /sd/source/filter/cgm/sdcgmfilter.cxx:91:27
      #9 0x2ade940f5de1 in sd::DrawDocShell::ConvertFrom(SfxMedium&) /sd/source/ui/docshell/docshel4.cxx:482:46
      #10 0x2ade9cea135f in SfxObjectShell::DoLoad(SfxMedium*) /sfx2/source/doc/objstor.cxx:755:23
      #11 0x2ade8391c5b0 in SdFiltersTest::load(rtl::OUString const&, rtl::OUString const&, rtl::OUString const&, SfxFilterFlags, SotClipboardFormatId, unsigned int) /sd/qa/unit/filters-test.cxx:63:31
      #12 0x2adeb43d8344 in test::FiltersTest::recursiveScan(test::filterStatus, rtl::OUString const&, rtl::OUString const&, rtl::OUString const&, SfxFilterFlags, SotClipboardFormatId, unsigned int, bool) /unotest/source/cpp/filters-test.cxx:131:20
      #13 0x2adeb43dc1a6 in test::FiltersTest::testDir(rtl::OUString const&, std::basic_string_view<char16_t, std::char_traits<char16_t> >, rtl::OUString const&, SfxFilterFlags, SotClipboardFormatId, unsigned int, bool) /unotest/source/cpp/filters-test.cxx:156:5
      #14 0x2ade8391e55b in SdFiltersTest::testCVEs() /sd/qa/unit/filters-test.cxx:87:5
      #15 0x2ade83944054 in void std::__invoke_impl<void, void (SdFiltersTest::*&)(), SdFiltersTest*&>(std::__invoke_memfun_deref, void (SdFiltersTest::*&)(), SdFiltersTest*&) /home/tdf/lode/opt_private/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/invoke.h:73:14
      #16 0x2ade83943c2e in std::__invoke_result<void (SdFiltersTest::*&)(), SdFiltersTest*&>::type std::__invoke<void (SdFiltersTest::*&)(), SdFiltersTest*&>(void (SdFiltersTest::*&)(), SdFiltersTest*&) /home/tdf/lode/opt_private/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/invoke.h:95:14
      #17 0x2ade83943a72 in void std::_Bind<void (SdFiltersTest::* (SdFiltersTest*))()>::__call<void, 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) /home/tdf/lode/opt_private/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/functional:467:11
      #18 0x2ade83943652 in void std::_Bind<void (SdFiltersTest::* (SdFiltersTest*))()>::operator()<void>() /home/tdf/lode/opt_private/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/functional:549:17
      #19 0x2ade839424a1 in std::_Function_handler<void (), std::_Bind<void (SdFiltersTest::* (SdFiltersTest*))()> >::_M_invoke(std::_Any_data const&) /home/tdf/lode/opt_private/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/std_function.h:316:2
      #20 0x2ade839446b1 in std::function<void ()>::operator()() const /home/tdf/lode/opt_private/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/std_function.h:706:14
      #21 0x2ade83941754 in CppUnit::TestCaller<SdFiltersTest>::runTest() /workdir/UnpackedTarball/cppunit/include/cppunit/TestCaller.h:175:7
      #22 0x2ade37d915ba in CppUnit::TestCaseMethodFunctor::operator()() const /workdir/UnpackedTarball/cppunit/src/cppunit/TestCase.cpp:32:5
      #23 0x2ade52c2b937 in (anonymous namespace)::Protector::protect(CppUnit::Functor const&, CppUnit::ProtectorContext const&) /test/source/vclbootstrapprotector.cxx:46:14
      #24 0x2ade37d62c47 in CppUnit::ProtectorChain::ProtectFunctor::operator()() const /workdir/UnpackedTarball/cppunit/src/cppunit/ProtectorChain.cpp:20:25
      #25 0x2ade47225fd7 in (anonymous namespace)::Prot::protect(CppUnit::Functor const&, CppUnit::ProtectorContext const&) /unotest/source/cpp/unobootstrapprotector/unobootstrapprotector.cxx:78:12
      #26 0x2ade37d62c47 in CppUnit::ProtectorChain::ProtectFunctor::operator()() const /workdir/UnpackedTarball/cppunit/src/cppunit/ProtectorChain.cpp:20:25
      #27 0x2ade43d47962 in (anonymous namespace)::Prot::protect(CppUnit::Functor const&, CppUnit::ProtectorContext const&) /unotest/source/cpp/unoexceptionprotector/unoexceptionprotector.cxx:62:16
      #28 0x2ade37d62c47 in CppUnit::ProtectorChain::ProtectFunctor::operator()() const /workdir/UnpackedTarball/cppunit/src/cppunit/ProtectorChain.cpp:20:25
      #29 0x2ade37cf9f84 in CppUnit::DefaultProtector::protect(CppUnit::Functor const&, CppUnit::ProtectorContext const&) /workdir/UnpackedTarball/cppunit/src/cppunit/DefaultProtector.cpp:15:12
      #30 0x2ade37d62c47 in CppUnit::ProtectorChain::ProtectFunctor::operator()() const /workdir/UnpackedTarball/cppunit/src/cppunit/ProtectorChain.cpp:20:25
      #31 0x2ade37d5c697 in CppUnit::ProtectorChain::protect(CppUnit::Functor const&, CppUnit::ProtectorContext const&) /workdir/UnpackedTarball/cppunit/src/cppunit/ProtectorChain.cpp:86:18
      #32 0x2ade37dfba79 in CppUnit::TestResult::protect(CppUnit::Functor const&, CppUnit::Test*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /workdir/UnpackedTarball/cppunit/src/cppunit/TestResult.cpp:182:28
      #33 0x2ade37d8fc21 in CppUnit::TestCase::run(CppUnit::TestResult*) /workdir/UnpackedTarball/cppunit/src/cppunit/TestCase.cpp:91:13
      #34 0x2ade37d93a52 in CppUnit::TestComposite::doRunChildTests(CppUnit::TestResult*) /workdir/UnpackedTarball/cppunit/src/cppunit/TestComposite.cpp:64:30
      #35 0x2ade37d92c4a in CppUnit::TestComposite::run(CppUnit::TestResult*) /workdir/UnpackedTarball/cppunit/src/cppunit/TestComposite.cpp:23:3
      #36 0x2ade37d93a52 in CppUnit::TestComposite::doRunChildTests(CppUnit::TestResult*) /workdir/UnpackedTarball/cppunit/src/cppunit/TestComposite.cpp:64:30
      #37 0x2ade37d92c4a in CppUnit::TestComposite::run(CppUnit::TestResult*) /workdir/UnpackedTarball/cppunit/src/cppunit/TestComposite.cpp:23:3
      #38 0x2ade37e2960e in CppUnit::TestRunner::WrappingSuite::run(CppUnit::TestResult*) /workdir/UnpackedTarball/cppunit/src/cppunit/TestRunner.cpp:47:27
      #39 0x2ade37dfa4de in CppUnit::TestResult::runTest(CppUnit::Test*) /workdir/UnpackedTarball/cppunit/src/cppunit/TestResult.cpp:149:9
      #40 0x2ade37e2a56b in CppUnit::TestRunner::run(CppUnit::TestResult&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /workdir/UnpackedTarball/cppunit/src/cppunit/TestRunner.cpp:96:14
      #41 0x4ff42e in (anonymous namespace)::ProtectedFixtureFunctor::run() const /sal/cppunittester/cppunittester.cxx:324:20
      #42 0x4fb90c in sal_main() /sal/cppunittester/cppunittester.cxx:474:20
      #43 0x4fa40e in main /sal/cppunittester/cppunittester.cxx:381:1
      #44 0x2ade39ad4554 in __libc_start_main (/lib64/libc.so.6+0x22554)
      #45 0x425e04 in _start (/workdir/LinkTarget/Executable/cppunittester+0x425e04)
  
  SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /filter/source/graphicfilter/icgm/actimpr.cxx:458:55 in 
  
  Error: a unit test failed, please do one of:
  
  make CppunitTest_sd_filters_test CPPUNITTRACE="gdb --args"
      # for interactive debugging on Linux
  make CppunitTest_sd_filters_test VALGRIND=memcheck
      # for memory checking
  make CppunitTest_sd_filters_test DEBUGCPPUNIT=TRUE
      # for exception catching
  
  You can limit the execution to just one particular test by:
  
  make CPPUNIT_TEST_NAME="testXYZ" ...above mentioned params...
  
  /home/tdf/lode/jenkins/workspace/lo_ubsan/solenv/gbuild/CppunitTest.mk:123: recipe for target '/home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/CppunitTest/sd_filters_test.test' failed
  make[1]: *** [/home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/CppunitTest/sd_filters_test.test] Error 1

Patch-set: 2
CC: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>