Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/68066/ : FAILURE

clang plugin unsignedcompare did trigger. explicit cast from "sal_Int32" (aka "int") to "sal_uInt32" (aka "unsigned int") (of equal rank) in comparison against "sal_uInt32": if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70483/ )

error: comparison of integers of different signs: "sal_Int32" (aka "int") and "std::__cxx1998::vector::size_type" (aka "unsigned long") [-Werror,-Wsign-compare] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/svl/source/items/IndexedStyleSheets.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70483/ )

https://ci.libreoffice.org/job/gerrit_master_android/606/ : FAILURE

error: comparison of integers of different signs: "sal_Int32" (aka "int") and "std::__ndk1::vector<rtl::Reference<SfxStyleSheetBase>, std::__ndk1::allocator<rtl::Reference<SfxStyleSheetBase> > >::size_type" (aka "unsigned long") [-Werror,-Wsign-compare] in file /home/tdf/lode/jenkins/workspace/android_aarch64/svl/source/items/IndexedStyleSheets.cxx ( https://ci.libreoffice.org/job/gerrit_android_aarch64/123/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1