Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/4408/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "std::unique_ptr<ImplDeviceFontList,std::default_delete<_Ty>>" to "ImplDeviceFontList *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/windows_msc_dbgutil_32/vcl/win/gdi/salfont.cxx(317) ( https://ci.libreoffice.org/job/gerrit_windows/4409/ )

Patch-set: 2
Label: Verified=-1