Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/67838/ : FAILURE

the build failed because of an issue with the bot itself, not with the code.
The Bot failed to checkout the source ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70262/ )

https://ci.libreoffice.org/job/gerrit_master_android/355/ : FAILURE

error: out-of-line definition of "dispose" does not match any declaration in "TabPage" in file /home/tdf/lode/jenkins/workspace/android_arm/vcl/source/window/tabpage.cxx ( https://ci.libreoffice.org/job/gerrit_android_arm/77/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1