Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/92228/ : FAILURE

error: no matching function for call to "assertEquals" in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/qa/unit/ucalc_pivottable.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/93197/ )

the junit test JunitTest_sc_unoapi_1 failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/93197/ )

the test PythonTest_pyuno_pytests_testcollections failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/93197/ )

the cppunit test CppunitTest_vcl_fontfeature failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/93197/ )

the test UITest_solver failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/93197/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/93197/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1