Fix UBSan build's RTTI needs
...after 3ba92b5f1eaf7d4447a0943ea260db515ca799dc "hide more symbols" had caused
CppunitTest_ucb_webdav_core to fail with

> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_ucb_webdav_core.so
> workdir/LinkTarget/CppunitTest/libtest_ucb_webdav_core.so: undefined symbol: _ZTIN9ucbhelper16PropertyValueSetE"

etc.

Change-Id: I54832b1c7a9850e536bfcab076f15465b170a065
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/163690
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>