Update patch set 3
Patch Set 3:

>...
> Fix commit ticket:
> https://gerrit.libreoffice.org/c/core/+/105081

I cherry-picked this patch and after "make sysui.clean" then "make sysui", I got:
Conflicts: libreoffice7.1-debian-menus libreoffice7.1-mandriva-menus libreoffice7.1-redhat-menus libreoffice7.1-suse-menus
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/julien/lo/libo_perf/workdir/CustomTarget/sysui/rpm/libreoffice/freedesktop
error: Installed (but unpackaged) file(s) found:
   /usr/share/icons/gnome/128x128/mimetypes/libreoffice7.1-oasis-database.svg
   /usr/share/icons/gnome/128x128/mimetypes/libreoffice7.1-oasis-drawing-template.svg
   /usr/share/icons/gnome/128x128/mimetypes/libreoffice7.1-oasis-drawing.svg
   /usr/share/icons/gnome/128x128/mimetypes/libreoffice7.1-oasis-empty.svg
etc.

Did you try to build locally before submitting the patch?

Patch-set: 3
CC: Gerrit User 1000043 <1000043@6622c302-437a-49ad-a91d-55ba7dcf1615>