Fix shutil.copytree() error in PythonTest_solenv_python
During the test run of PythonTest_solenv_python the execution of
shutil.copytree() raises an error (traceback is include at the end).
This is happening because shutil.copytree() can't handle
special files (sockets, devices, ...).

The files which are causing the errors are 'S.gpg-agent.extra',
'S.gpg-agent.ssh', 'S.gpg-agent.browser', and 'S.gpg-agent' in the
directory 'xmlsecurity/qa/unit/signing/data' and all are sockets.

The fix is to add the parameter 'ignore' to the call of
shutil.copytree() with shutil.ignore_patterns() and the value
'S.gpg-agent*'.

The error happens with Python 3.6.3.

ERROR: test_gbuildtojson (gbuildtojson.CheckGbuildToJsonModules)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../core/solenv/qa/python/gbuildtojson.py", line 135, in test_gbuildtojson
    shutil.copytree(os.path.join(os.environ['SRCDIR'], module), os.path.join(self.tempsrc, module))
  File "/usr/lib/python3.6/shutil.py", line 359, in copytree
    raise Error(errors)
shutil.Error: [
    ('.../core/xmlsecurity/qa/unit/signing/data/S.gpg-agent.extra',
     '/tmp/gbuildi4h3ucas/xmlsecurity/qa/unit/signing/data/S.gpg-agent.extra',
     "[Errno 6] No such device or address: '.../core/xmlsecurity/qa/unit/signing/data/S.gpg-agent.extra'"),
    ('.../core/xmlsecurity/qa/unit/signing/data/S.gpg-agent.ssh',
     '/tmp/gbuildi4h3ucas/xmlsecurity/qa/unit/signing/data/S.gpg-agent.ssh',
     "[Errno 6] No such device or address: '.../core/xmlsecurity/qa/unit/signing/data/S.gpg-agent.ssh'"),
    ('.../core/xmlsecurity/qa/unit/signing/data/S.gpg-agent.browser',
     '/tmp/gbuildi4h3ucas/xmlsecurity/qa/unit/signing/data/S.gpg-agent.browser',
     "[Errno 6] No such device or address: '.../core/xmlsecurity/qa/unit/signing/data/S.gpg-agent.browser'"),
    ('.../core/xmlsecurity/qa/unit/signing/data/S.gpg-agent',
     '/tmp/gbuildi4h3ucas/xmlsecurity/qa/unit/signing/data/S.gpg-agent',
     "[Errno 6] No such device or address: '.../core/xmlsecurity/qa/unit/signing/data/S.gpg-agent'")]

Change-Id: Ifd9c4d491546326b96c49230869c4ad68694580e