oox,svgio,xmloff: missing stdint
workdir/UnpackedTarball/frozen/include/frozen/bits/pmh.h:59:3: error: ‘uint64_t’ does not name a type [-Wtemplate-body]

Change-Id: I3896d378ce8ea7ee933dbd3f55979bd0f8fd1814