Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/39035/ : FAILURE

Visual studio complained about error C2859: C:\cygwin\home\tdf\lode\jenkins\workspace\gerrit_windows\workdir\LinkTarget\Library\saxlo.dll.objects.pdb is not the pdb file that was used when this precompiled header was created, recreate the precompiled header. in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sax/source/tools/converter.cxx ( https://ci.libreoffice.org/job/gerrit_windows/45435/ )

Patch-set: 1
Label: Verified=-1