Work around odd -Werror=strict-overflow
"sc/source/filter/oox/pivotcachebuffer.cxx:401:45: error: assuming signed
overflow does not occur when assuming that (X + c) < X is always false" at least
with "g++ (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)" and --disable-debug

Change-Id: I1d267b2947f04b84f73da2b1458d316397e2374e