sfx2: fix mysterious -Werror=shadow
GCC 14 now mysteriously finds a -Wshadow here but not in the many other
SfxChildWindow subclass member functions that have a parameter named
"pParent":

  sw/source/uibase/sidebar/QuickFindPanel.cxx: In constructor ‘sw::sidebar::QuickFindPanelWrapper::QuickFindPanelWrapper(vcl::Window*, sal_uInt16, SfxBindings*, SfxChildWinInfo*)’:
  sw/source/uibase/sidebar/QuickFindPanel.cxx:115:59: error: declaration of ‘pParent’ shadows a member of ‘sw::sidebar::QuickFindPanelWrapper’ [-Werror=shadow]
  115 | QuickFindPanelWrapper::QuickFindPanelWrapper(vcl::Window* pParent, sal_uInt16 nId,
      |                                              ~~~~~~~~~~~~~^~~~~~~
  In file included from include/sfx2/quickfind.hxx:13,
                 from sw/source/uibase/inc/QuickFindPanel.hxx:13,
                 from sw/source/uibase/sidebar/QuickFindPanel.cxx:11:
  include/sfx2/childwin.hxx:102:32: note: shadowed declaration is here
  102 |     VclPtr<vcl::Window>        pParent;         // parent window ( Topwindow )
      |                                ^~~~~~~

Change-Id: I98228f312308ee69a17af34bb31a5d4109b06ad9
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/189017
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
(cherry picked from commit a8c445bb1ecf5a68c3925e3ab19d08f0b44644c9)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/193750
Tested-by: Jenkins
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>