Avoid a dynamic cross cast on macOS
...now causing

> In file included from vcl/osx/a11ytextattributeswrapper.mm:23:
> vcl/inc/quartz/salgdi.h:283:22: error: suspicious dynamic cross cast from 'AquaGraphicsBackendBase *' to 'SalGraphicsImpl *' [loplugin:crosscast]
>             mpImpl = dynamic_cast<SalGraphicsImpl*>(this);
>                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I0c9a4af0690c195c693f986e02284a48fe753a07
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/143505
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>