crashtesting: crash in ScInterpreter::ScCountIfs
seen on importing forum-mso-en4-253817.xls and others

Error: attempt to advance a dereferenceable (start-of-sequence) iterator
which falls outside its valid range.

presumably since:

commit 7674399aac661eb503d7badc53b9a4d68bd9839d
Date:   Fri May 27 19:51:40 2022 +0200

    try to range-reduce even COUNTIFS if not matching empty cells

bodge this to fill in 0 for missing ranges

Change-Id: If77d8ab887859f11b240975bb837a27785f500a1
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/146604
Tested-by: Jenkins
Tested-by: Caolán McNamara <caolanm@redhat.com>
Reviewed-by: Caolán McNamara <caolanm@redhat.com>
(cherry picked from commit e7897ce47e415e46eb36687f911a9a4b09ca6b8a)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/153376
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>