Update patch set 1
Patch Set 1: Fails

1. Compiler rejects it with (at least)

svtools/source/control/calendar.cxx:1292:65: error: call of overloaded 'valueOf(int)' is ambiguous

Does it build without errors for you? 

2. Are you sure that you don't pass sal_uInt8 and sal_uInt16 to OUString::valueOf ? Because actually sal_uInt8 is the same as sal_Bool and sal_uInt16 is the same as sal_Unicode.

Patch-set: 1
Label: Verified=-1
Label: Code-Review=0