Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/33710/ : FAILURE

error "class "SdrObjCreatorParams" was previously declared as a struct [-Werror,-Wmismatched-tags]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sw/inc/dobjfac.hxx:25:1 ( https://ci.libreoffice.org/job/gerrit_mac/36514/ )

error: class "SdrObjCreatorParams" was previously declared as a struct [-Werror,-Wmismatched-tags] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sw/inc/dobjfac.hxx ( https://ci.libreoffice.org/job/gerrit_mac/36514/ )

Patch-set: 1
Label: Verified=-1