Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/63204/ : FAILURE

Visual studio complained about error C2440: "return": cannot convert from "initializer list" to "com::sun::star::uno::Sequence<rtl::OUString>" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/sc/source/ui/unoobj/styleuno.cxx(1930) ( https://ci.libreoffice.org/job/gerrit_windows/72187/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1