vcl: GTK: fix libstdc++ "irreflexive" assert
/usr/include/c++/6.1.1/bits/stl_algo.h:4737:
Error: comparison doesn't meet irreflexive requirements, assert(!(a < a)).

GdkRectangleCoincident is clearly not a less-than operator as required
for std::sort.

Change-Id: If2e65d420dc8cdf0707081361a40d4eaea28424e
(cherry picked from commit e2b267b1906817cc45f0e4896bed58cff5b6b0f9)
Reviewed-on: https://gerrit.libreoffice.org/26762
Tested-by: Jenkins <ci@libreoffice.org>
Reviewed-by: Caolán McNamara <caolanm@redhat.com>
Tested-by: Caolán McNamara <caolanm@redhat.com>