Update patch set 12
Patch Set 12: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/27410/ : FAILURE

error "this member function can be declared static [loplugin:staticmethods]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/cui/source/inc/infodlg.hxx:36:15 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/29244/ )

error: externally available entity "file_exists" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/cui/source/dialogs/infodlg.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/29244/ )

clang plugin external did trigger. externally available entity "file_exists" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/29244/ )

Patch-set: 12
Label: Verified=-1