Update patch set 2
Patch Set 2: Verified-1

your changes look good but apparently a little incomplete, since the MSVC build fails:

C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/windows_msc_dbgutil_32/tools/source/inet/inetmsg.cxx(234) : error C2664: 'void INetMIMEMessage::SetHeaderField_Impl(const rtl::OString &,const rtl::OUString &,size_t &)' : cannot convert argument 3 from 'unsigned long' to 'size_t &'
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/windows_msc_dbgutil_32/tools/source/inet/inetmsg.cxx(241) : error C2664: 'void INetMIMEMessage::SetHeaderField_Impl(const rtl::OString &,const rtl::OUString &,size_t &)' : cannot convert argument 3 from 'unsigned long' to 'size_t &'
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/windows_msc_dbgutil_32/tools/source/inet/inetmsg.cxx(248) : error C2664: 'void INetMIMEMessage::SetHeaderField_Impl(const rtl::OString &,const rtl::OUString &,size_t &)' : cannot convert argument 3 from 'unsigned long' to 'size_t &'
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/windows_msc_dbgutil_32/tools/source/inet/inetmsg.cxx(256) : error C2664: 'void INetMIMEMessage::SetHeaderField_Impl(const rtl::OString &,const rtl::OUString &,size_t &)' : cannot convert argument 3 from 'unsigned long' to 'size_t &'


these reference parameters must match with what the caller passes in, so you need to adapt the type of "m_nMIMEIndex" member as well...

note that you probably won't get this build failure on a 64-bit platform, perhaps only 32-bit MSVC is affected, but such is life with C++.

Patch-set: 2
Reviewer: Gerrit User 1000022 <1000022@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1