vcl: WhitespaceToSpace() spurious -Werror=maybe-uninitialized
vcl/source/helper/strhelper.cxx:366:9: error: ‘pBuffer[-1]’ may be used uninitialized [-Werror=maybe-uninitialized]

Change-Id: I37250b0790bd9c33eb01c552c8267251bc0026f0
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/134738
Tested-by: Jenkins
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>
(cherry picked from commit cd4976646dc2e5b28c3328a7fa96361e147b23b9)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/134631
Reviewed-by: Thorsten Behrens <thorsten.behrens@allotropia.de>