Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/111692/ : FAILURE

clang plugin unsignedcompare did trigger. explicit cast from "int" to "sal_uInt8" (aka "unsigned char") (of smaller rank) in comparison against "unsigned char": if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/111179/ )

error: explicit cast from "int" to "sal_uInt8" (aka "unsigned char") (of smaller rank) in comparison against "unsigned char": if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast [loplugin:unsignedcompare] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/tools/qa/cppunit/test_guid.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/111179/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000154 \u003c1000154@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}