Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_feature/409/ : FAILURE

error: explicit cast from "int" to "sal_uInt16" (aka "unsigned short") (of smaller rank) in comparison against "sal_uInt16": if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast [loplugin:unsignedcompare] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/framework/source/uielement/toolbarmanager.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/87259/ )

clang plugin unsignedcompare did trigger. explicit cast from "int" to "sal_uInt16" (aka "unsigned short") (of smaller rank) in comparison against "sal_uInt16": if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/87259/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1