Update patch set 2
Patch Set 2:

see f7d01f3ea5b472878255345ac6ddc113b0de9e2e "Revert 'Do not include non-standardized xlocale.h, include locale.h instead': This reverts commit 274b2aee3bf65f139292d08a46d86f90d5ac8acb, which breaks in external/icu on macOS, <https://ci.libreoffice.org/job/lo_tb_master_mac/20605/>:

> digitlst.cpp:497:8: error: unknown type name 'locale_t'
> static locale_t gCLocale = (locale_t)0;
>        ^
"

Patch-set: 2
Reviewer: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0