Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/24174/ : FAILURE

clang plugin salbool did trigger. use "true" instead of "sal_True" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/25734/ )

error: use "true" instead of "sal_True" [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/image/ImplImageTree.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/25734/ )

Patch-set: 3
Label: Verified=-1