Update patch set 2
Patch Set 2:

It looks like Jenkins' lo_tb_master_win consistently fails in CppunitTest_vcl_pdfexport with

> C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win/vcl/qa/cppunit/pdfexport/pdfexport.cxx(814) : error : Assertion
> Test name: `anonymous namespace'::PdfExportTest::testTdf108963
> double equality assertion failed
> - Expected: 793.7
> - Actual  : 793
> - Delta   : 0.01

since this commit, see <https://ci.libreoffice.org//job/lo_tb_master_win/19701/>.  (It sporadically failed CppunitTest_vcl_pdfexport for different reasons before, and keeps sporadically failing it also for different reasons since, but appears to consistently fail it for that one 793.7 != 793 check in testTdf108963 now.)

Patch-set: 2