Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/32790/ : FAILURE

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "std::shared_ptr<ExtMgrDialog>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/35218/ )

error: no need to explicitly init an instance of "std::shared_ptr<ExtMgrDialog>" with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/desktop/source/deployment/gui/dp_gui_theextmgr.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/35218/ )

Patch-set: 1
Label: Verified=-1