Fix --enable-werror build
... producing this error in MSVC2017:

C:/lo/src/core2/desktop/source/lib/init.cxx(3486): error C2220: warning treated as error - no 'object' file generated
C:/lo/src/core2/desktop/source/lib/init.cxx(3486): warning C4190: 'getSidebarWindow' has C-linkage specified, but returns UDT 'VclPtr<vcl::Window>' which is incompatible with C
C:\lo\src\core2\include\vcl/cursor.hxx(49): note: see declaration of 'VclPtr<vcl::Window>'

... because getSidebarWindow was inside 'extern "C"' block.

Change-Id: If7364555d09f0955ac90ce127b19ce4bbdb5cc3c
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/86518
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>