Update patch set 2
Patch Set 2:

Noel: I updated the patch following your advice.

Also, because of this bt:
Error: attempt to access an element in an empty container.

Objects involved in the operation:
    sequence "this" @ 0x0x55555883a3d8 {
      type = std::__debug::vector<sd::TemplateEntry*, std::allocator<sd::TemplateEntry*> >;
    }

#4  0x00007f884cc207dc in sd::TemplateScanner::GetLastAddedEntry() const (this=0x55555883a3c0) at /home/julien/lo/libreoffice/sd/source/ui/inc/TemplateScanner.hxx:96
#5  0x00007f884cc20499 in sd::sidebar::MasterPageContainerFiller::ScanTemplate() (this=0x5555588890f0)
    at /home/julien/lo/libreoffice/sd/source/ui/sidebar/MasterPageContainerFiller.cxx:121
#6  0x00007f884cc2033d in sd::sidebar::MasterPageContainerFiller::RunNextStep() (this=0x5555588890f0)
    at /home/julien/lo/libreoffice/sd/source/ui/sidebar/MasterPageContainerFiller.cxx:68

I had to change this:
const TemplateEntry* GetLastAddedEntry() const { return mpTemplateEntries.back();}

into this:
const TemplateEntry* GetLastAddedEntry() const { return mpTemplateEntries.empty()?nullptr:mpTemplateEntries.back();}

Patch-set: 2
Reviewer: Gerrit User 1000043 <1000043@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0