Fix windows build
... after commit e1a599aa5082a528b36ba2d4711111c4cd39eb7a (cool#15535 sw
markdown import: handle pasting into an existing paragraph, 2026-04-17).

 C:\lo\core\include\rtl/ref.hxx(122): error C2027: use of undefined type 'SwXTextRange'
 C:\lo\core\sw\inc\shellio.hxx(51): note: see declaration of 'SwXTextRange'
 C:\lo\core\include\rtl/ref.hxx(122): note: the template instantiation context (the oldest one first) is
 C:\lo\core\sw\inc\shellio.hxx(216): note: see reference to class template instantiation 'rtl::Reference<SwXTextRange>' being compiled
 C:\lo\core\include\rtl/ref.hxx(119): note: while compiling class template member function 'rtl::Reference<SwXTextRange>::~Reference(void)'
 C:\lo\core\sw\inc\shellio.hxx(221): note: see the first reference to 'rtl::Reference<SwXTextRange>::~Reference' in 'SwPasteInfo::~SwPasteInfo'

Change-Id: I15c09b9bb01325330669e154a1d4aa38e1be9e61
Reviewed-on: https://gerrit.collaboraoffice.com/c/core/+/1130
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/1170
Tested-by: Andras Timar <andras.timar@collabora.com>
Reviewed-by: Andras Timar <andras.timar@collabora.com>