Blind fix for Android Tinderbox build
... which failed as follows, which looks related to
commit 6d9a31a58c2b55c0caef10c8bbb3d75147c2476f
("android: Use the best speed compression as on iOS"),
s. [1] for full log:

    12883         [build CXX] vcl/source/pdf/XmpMetadata.cxx
    12884         In file included from /home/android/lo/master-android-arm/vcl/source/filter/graphicfilter.cxx:24:
    12885         In file included from /home/android/lo/master-android-arm/include/comphelper/processfactory.hxx:23:
    12886         In file included from /home/android/lo/master-android-arm/include/com/sun/star/uno/Reference.hxx:28:
    12887         In file included from /home/android/lo/master-android-arm/workdir/UnoApiHeadersTarget/udkapi/comprehensive/com/sun/star/uno/RuntimeException.hpp:8:
    12888         In file included from /home/android/lo/master-android-arm/workdir/UnoApiHeadersTarget/udkapi/comprehensive/com/sun/star/uno/Exception.hpp:8:
    12889         In file included from /home/android/lo/master-android-arm/workdir/UnoApiHeadersTarget/udkapi/comprehensive/com/sun/star/uno/XInterface.hpp:6:
    12890         In file included from /home/android/lo/master-android-arm/workdir/UnoApiHeadersTarget/udkapi/comprehensive/com/sun/star/uno/XInterface.hdl:6:
    12891         In file included from /home/android/lo/master-android-arm/include/com/sun/star/uno/Any.h:29:
    12892 NEXT    /home/android/lo/master-android-arm/include/cppu/unotype.hxx:296:16: error: no matching function for call to ´cppu_detail_getUnoType´
    12893                 return cppu_detail_getUnoType(static_cast< T1 * >(0));
    12894                        ^~~~~~~~~~~~~~~~~~~~~~
    12895         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:321:34: note: in instantiation of member function ´cppu::UnoType<int>::get´ requested here
    12896             return ::cppu::UnoType< T >::get();
    12897                                          ^
    12898         /home/android/lo/master-android-arm/include/com/sun/star/uno/Any.hxx:276:34: note: in instantiation of function template specialization ´cppu::getTypeFavourUnsigned<int>´ requested here
    12899             const Type & rType = ::cppu::getTypeFavourUnsigned(&value);
    12900                                          ^
    12901         /home/android/lo/master-android-arm/vcl/source/filter/graphicfilter.cxx:2216:60: note: in instantiation of function template specialization ´com::sun::star::uno::operator<<=<int>´ requested here
    12902                     aFilterData[aFilterData.getLength() - 1].Value <<= 1;
    12903                                                                    ^
    12904         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:120:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const ::cppu::UnoVoidType *´ for 1st argument
    12905         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER ::cppu::UnoVoidType const *) {
    12906         ^
    12907         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:125:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const bool *´ for 1st argument
    12908         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER bool const *) {
    12909         ^
    12910         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:130:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const sal_Bool *´ (aka ´const unsigned char *´) for 1st argument
    12911         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER sal_Bool const *) {
    12912         ^
    12913         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:135:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const ::sal_Int8 *´ (aka ´const signed char *´) for 1st argument
    12914         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER ::sal_Int8 const *) {
    12915         ^
    12916         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:140:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const ::sal_Int16 *´ (aka ´const short *´) for 1st argument
    12917         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER ::sal_Int16 const *) {
    12918         ^
    12919         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:145:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const ::cppu::UnoUnsignedShortType *´ for 1st argument
    12920         cppu_detail_getUnoType(
    12921         ^
    12922         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:155:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const sal_uInt16 *´ (aka ´const unsigned short *´) for 1st argument
    12923         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER sal_uInt16 const *) {
    12924         ^
    12925         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:161:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const ::sal_Int32 *´ (aka ´const long *´) for 1st argument
    12926         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER ::sal_Int32 const *) {
    12927         ^
    12928         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:166:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const ::sal_uInt32 *´ (aka ´const unsigned long *´) for 1st argument
    12929         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER ::sal_uInt32 const *) {
    12930         ^
    12931         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:172:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const ::sal_Int64 *´ (aka ´const long long *´) for 1st argument
    12932         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER ::sal_Int64 const *) {
    12933         ^
    12934         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:177:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const ::sal_uInt64 *´ (aka ´const unsigned long long *´) for 1st argument
    12935         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER ::sal_uInt64 const *) {
    12936         ^
    12937         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:183:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const float *´ for 1st argument
    12938         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER float const *) {
    12939         ^
    12940         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:188:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const double *´ for 1st argument
    12941         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER double const *) {
    12942         ^
    12943         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:193:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const ::cppu::UnoCharType *´ for 1st argument
    12944         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER ::cppu::UnoCharType const *) {
    12945         ^
    12946         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:200:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const sal_Unicode *´ (aka ´const char16_t *´) for 1st argument
    12947         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER sal_Unicode const *) {
    12948         ^
    12949         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:206:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const ::rtl::OUString *´ for 1st argument
    12950         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER ::rtl::OUString const *) {
    12951         ^
    12952         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:211:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const css::uno::Type *´ for 1st argument
    12953         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER css::uno::Type const *)
    12954         ^
    12955         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:217:1: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const css::uno::Any *´ for 1st argument
    12956         cppu_detail_getUnoType(SAL_UNUSED_PARAMETER css::uno::Any const *)
    12957         ^
    12958 NEXT    /home/android/lo/master-android-arm/include/cppu/unotype.hxx:243:31: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const css::uno::Exception *´ for 1st argument
    12959         inline css::uno::Type const & cppu_detail_getUnoType(
    12960                                       ^
    12961         /home/android/lo/master-android-arm/include/cppu/unotype.hxx:249:31: note: candidate function not viable: no known conversion from ´T1 *´ (aka ´int *´) to ´const css::uno::XInterface *´ for 1st argument
    12962         inline css::uno::Type const & cppu_detail_getUnoType(
    12963                                       ^
    12964 NEXT    /home/android/lo/master-android-arm/include/cppu/unotype.hxx:223:1: note: candidate template ignored: could not match ´UnoSequenceType<type-parameter-0-0>´ against ´int´
    12965         cppu_detail_getUnoType(
    12966         ^
    12967 NEXT    /home/android/lo/master-android-arm/include/cppu/unotype.hxx:236:1: note: candidate template ignored: could not match ´Sequence<type-parameter-0-0>´ against ´int´
    12968         cppu_detail_getUnoType(
    12969         ^
    12970 NEXT    /home/android/lo/master-android-arm/include/cppu/unotype.hxx:256:1: note: candidate template ignored: could not match ´Reference<type-parameter-0-0>´ against ´int´
    12971         cppu_detail_getUnoType(
    12972         ^
    12973 NEXT    1 error generated.
    12974         [build CXX] vcl/source/uitest/logger.cxx

[1] https://tinderbox.libreoffice.org/cgi-bin/gunzip.cgi?tree=MASTER&full-log=1583961601.24939

Change-Id: I098c21bc492f734115ae0e91f095ef542851c2ea
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/90352
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>