Update patch set 2
Patch Set 2:

The patch still breaks --enable-werror builds:

/master/filter/source/msfilter/svdfppt.cxx:7373:15: error: enumeration value ‘LineStyle_MAKE_FIXED_SIZE’ not handled in switch [-Werror=switch]

Patch-set: 2
Label: Verified=0