Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/114352/ : FAILURE

error ""extractDiagramDataState" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/oox/source/drawingml/diagram/diagramhelper.hxx:81:63 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/113582/ )

error: "extractDiagramDataState" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/oox/source/drawingml/diagram/diagramhelper.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/113582/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1