Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/114636/ : FAILURE

error: variable "aText" of type "rtl::OUStringLiteral<11>" with automatic storage duration most likely needs to be static [loplugin:stringliteralvar] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/core/txtnode/justify.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/113818/ )

clang plugin stringliteralvar did trigger. variable "aText" of type "rtl::OUStringLiteral<11>" with automatic storage duration most likely needs to be static ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/113818/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1