Fix Python codecs.open deprecation warning
...seen at least with --with-system-python against
python3-3.14.0~rc3-1.fc43.x86_64, causing e.g.

> [FIF] fcfg_database_filters.xcu
> Traceback (most recent call last):
>   File "/home/sberg/lo-plain/core/filter/source/config/tools/merge/pyAltFCFGMerge", line 571, in getFragments
>     aFragmentFile = codecs.open(sFragPath, "r", "utf-8")
>   File "<frozen codecs>", line 916, in open
> DeprecationWarning: codecs.open() is deprecated. Use open() instead.
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>   File "/home/sberg/lo-plain/core/filter/source/config/tools/merge/pyAltFCFGMerge", line 588, in <module>
>     run(sys.argv)
>     ~~~^^^^^^^^^^
>   File "/home/sberg/lo-plain/core/filter/source/config/tools/merge/pyAltFCFGMerge", line 290, in run
>     aMerger.merge()
>     ~~~~~~~~~~~~~^^
>   File "/home/sberg/lo-plain/core/filter/source/config/tools/merge/pyAltFCFGMerge", line 529, in merge
>     sBuffer = sBuffer + self.getFragments(\
>                         ~~~~~~~~~~~~~~~~~^^
>         os.path.join(self.m_aFragmentsDir, sSubDir), \
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         sSetName, lFragments, 1)
>         ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sberg/lo-plain/core/filter/source/config/tools/merge/pyAltFCFGMerge", line 574, in getFragments
>     raise Exception("fragment \"" + sFragPath + "\" does not exists.")
> Exception: fragment "/home/sberg/lo-plain/core/filter/source/config/fragments/filters/../filters/StarOffice_XML__Base_.xcu" does not exists.
> make: *** [/home/sberg/lo-plain/core/filter/Configuration_filter.mk:81: /home/sberg/lo-plain/core/workdir/XcuFilterFiltersTarget/fcfg_database_filters.xcu] Error 1

to fail

Change-Id: I7de0459ff509009e3bc8afd803003a24b8fdaf41
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191349
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>
(cherry picked from commit d4ecccbddc1383b44f9c3447410e92c658e4dda3)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191355
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>