Update patch set 14
Patch Set 14: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/106658/ : FAILURE

clang plugin external did trigger. externally available entity "UserData" is not previously declared in an included file (if it is only used in this translation unit, put it in an unnamed namespace; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/106574/ )

error: externally available entity "UserData" is not previously declared in an included file (if it is only used in this translation unit, put it in an unnamed namespace; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/basic/source/runtime/stdobj1.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/106574/ )

Patch-set: 14
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1003497 \u003c1003497@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}