Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/62730/ : FAILURE

error "‘SgaObjKind’ has not been declared" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/include/svx/galleryfilestorage.hxx:69:47 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/66485/ )

error: ‘SgaObjKind’ has not been declared in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/include/svx/galleryfilestorage.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/66485/ )

compiler warning overloaded-virtual treated as error: ‘virtual INetURLObject GalleryFileStorage::implCreateUniqueURL(int, const INetURLObject&, ConvertDataFormat)’ was hidden in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/include/svx/galleryfilestorage.hxx:69:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/66485/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1