browsebox a11y: Call AccessibleBrowseBox* ctors directly
No longer use the AccessibleFactory for creating the
accessible objects.

In the past, this was necessary to break a dependency
cycle, but that's no longer the case, see

    commit 9283da858506fe3b4383e4cfe0506e470a4356f6
    Author: Michael Weghorn <m.weghorn@posteo.de>
    Date:   Tue Dec 17 12:04:04 2024 +0100

        a11y: Merge accessibility module into vcl

Mark copy ctors and operator= as deleted.
Otherwise, the Windows build fails like this [1]:

    [build CXX] vcl/source/accessibility/AccessibleBrowseBoxTableCell.cxx
    C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\include\cppuhelper/implbase.hxx(152): error C2280: 'AccessibleBrowseBoxCell::AccessibleBrowseBoxCell(const AccessibleBrowseBoxCell &)': attempting to reference a deleted function
    C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\include\vcl/accessibility/AccessibleBrowseBoxCell.hxx(61): note: see declaration of 'AccessibleBrowseBoxCell::AccessibleBrowseBoxCell'
    C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\include\vcl/accessibility/AccessibleBrowseBoxCell.hxx(61): note: 'AccessibleBrowseBoxCell::AccessibleBrowseBoxCell(const AccessibleBrowseBoxCell &)': function was explicitly deleted
    C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\include\vcl/accessibility/AccessibleBrowseBoxTableCell.hxx(100): note: see reference to function template instantiation 'cppu::ImplInheritanceHelper<AccessibleBrowseBoxCell,com::sun::star::accessibility::XAccessibleText,com::sun::star::accessibility::XAccessible>::ImplInheritanceHelper<cppu::ImplInheritanceHelper<AccessibleBrowseBoxCell,com::sun::star::accessibility::XAccessibleText,com::sun::star::accessibility::XAccessible>>(cppu::ImplInheritanceHelper<AccessibleBrowseBoxCell,com::sun::star::accessibility::XAccessibleText,com::sun::star::accessibility::XAccessible> &&)' being compiled
    C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\include\vcl/accessibility/AccessibleBrowseBoxTableCell.hxx(100): note: see reference to function template instantiation 'cppu::ImplInheritanceHelper<AccessibleBrowseBoxCell,com::sun::star::accessibility::XAccessibleText,com::sun::star::accessibility::XAccessible>::ImplInheritanceHelper<cppu::ImplInheritanceHelper<AccessibleBrowseBoxCell,com::sun::star::accessibility::XAccessibleText,com::sun::star::accessibility::XAccessible>>(cppu::ImplInheritanceHelper<AccessibleBrowseBoxCell,com::sun::star::accessibility::XAccessibleText,com::sun::star::accessibility::XAccessible> &&)' being compiled
    C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\include\cppuhelper/implbase.hxx(151): error C2248: 'AccessibleBrowseBoxCell::AccessibleBrowseBoxCell': cannot access private member declared in class 'AccessibleBrowseBoxCell'
    C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\include\vcl/accessibility/AccessibleBrowseBoxCell.hxx(61): note: see declaration of 'AccessibleBrowseBoxCell::AccessibleBrowseBoxCell'
    C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\include\vcl/accessibility/AccessibleBrowseBoxCell.hxx(30): note: see declaration of 'AccessibleBrowseBoxCell'
    make[1]: *** [C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/solenv/gbuild/LinkTarget.mk:339: C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/workdir/CxxObject/vcl/source/accessibility/AccessibleBrowseBoxTableCell.o] Error 2
    make[1]: *** Waiting for unfinished jobs....

[1] https://ci.libreoffice.org/job/gerrit_windows/193155/console

Change-Id: Ib24fc6b7f85e4ca575cb2505c172243da2cfb8b8
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/181206
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>