external/firebird: Implicit int in configure check
...so that with Clang 15 trunk after
<https://github.com/llvm/llvm-project/commit/2cb2cd242ca08d0bbd2a51a41f1317442e5414fc>
"Change the behavior of implicit int diagnostics" the check now failed to
compile with

> configure:21471: checking alignment of long
[...]
> conftest.c:166:2: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]

with consequences the same as in f6be6cd82bd84f13d2a597ceb62181111ae0eb80
"external/firebird: Missing include in configure check" (so rename the existing
configure-include.patch, as it now covers various kinds of C99 violations)

Change-Id: I64e7c13945a3ede3900cc6a84da575e35bdce953