fix build for system libxml that includes icu case
workdir/UnpackedTarball/icu/source/common/unicode/localpointer.h:67:1: error: template with C linkage

Change-Id: I08b0766a7b7a345bbb8b09bc191ecd16212400ac
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191537
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>
Tested-by: Caolán McNamara <caolan.mcnamara@collabora.com>
(cherry picked from commit 56ae90c7f8c804a353f1de8508f2b0471fb44c1e)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/192334
Tested-by: Jenkins