Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/20564/ : FAILURE

error: function has no external linkage but is explicitly declared "inline" [loplugin:redundantinline] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/headless/svpgdi.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/21394/ )

clang plugin redundantinline did trigger. function has no external linkage but is explicitly declared "inline" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/21394/ )

Patch-set: 3
Label: Verified=-1