move nScanLineBufferComponents to where it is used [-Werror=clobbered]
gcc (GCC) 4.9.2 20141101 (Red Hat 4.9.2-1)

vcl/source/filter/jpeg/jpegc.cxx: In function ‘void ReadJPEG(JPEGReader*, void*, long int*, const Size&)’:
vcl/source/filter/jpeg/jpegc.cxx:72:10: error: variable ‘nScanLineBufferComponents’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
     long                            nScanLineBufferComponents = 0;
          ^

Change-Id: I90a0d02977c49d2471069788a02fb1c7d28c039a