Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/7901/ : FAILURE

error: unused virtual function parameter name [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/ui/unoobj/externaltransformationuno.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/7902/ )

clang plugin casttovoid did trigger. unused virtual function parameter name ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/7902/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1