Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/10243/ : FAILURE

error: in LIBO_INTERNAL_ONLY code, replace literal cast to "sal_Unicode" (aka "char16_t") with a u"..." char16_t character literal [loplugin:salunicodeliteral] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/control/imp_listbox.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/10550/ )

use default type instead of indirection ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/10550/ )

clang plugin salunicodeliteral did trigger. in LIBO_INTERNAL_ONLY code, replace literal cast to "sal_Unicode" (aka "char16_t") with a u"..." char16_t character literal ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/10550/ )

Patch-set: 6
Label: Verified=-1