fix(svl): guard SfxItemSet m_bDeleted with NDEBUG
The isDeleted() method and the getPool()/getItem() asserts that
call it are compiled whenever NDEBUG is undefined, but m_bDeleted
and its init/set were guarded by DBG_UTIL. A debug build without
DBG_UTIL then references a member that does not exist and fails to
compile. Track m_bDeleted under NDEBUG, the same as the sibling
SfxPoolItemHolder; m_nRegisteredSfxItemIter stays under DBG_UTIL.

Fix the compiler error:
include/svl/itemset.hxx:128:37: error: use of undeclared identifier 'm_bDeleted'; did you mean 'isDeleted'?
  128 |     bool isDeleted() const { return m_bDeleted; }
      |                                     ^~~~~~~~~~
      |                                     isDeleted

Signed-off-by: Mohit Marathe <mohit.marathe@collabora.com>
Change-Id: I02aa1f948bcccecb965ba08bc304485c9b1239ba
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/7089
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>