Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/50535/ : FAILURE

error "C++ requires a type specifier for all declarations" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/drawinglayer/primitive2d/glowprimitive2d.hxx:64:5 ( https://ci.libreoffice.org/job/gerrit_mac/54749/ )

error: C++ requires a type specifier for all declarations in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/drawinglayer/primitive2d/glowprimitive2d.hxx ( https://ci.libreoffice.org/job/gerrit_mac/54749/ )

Patch-set: 5
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1