sax: fix overflow in sax::Converter::convertMeasure()
The problem is that -2^31 is negative after negation in 2's
complement.

This causes ODF validation error now in CppunitTest_sd_export_tests
testFdo84043:

Error: attribute "svg:x" has a bad value: ...
svg:x="--2147483.-6-4-7cm"

The validation error only happens in 32-bit builds; 64-bit builds
show a different value svg:x="2139324.72cm", so there must be another
problem somewhere else that isn't fixed here.

Change-Id: If2040cb6ae914c69b7cc651d3ab2d5d232fc71fb