fix Windows build of sfx2: C2487 on containerHasBasicMacros
The Windows build broke after commit
d17fd31994d71c28f503bb3cc93471c307756627 (don't load the document
Basic to parse formula names during ODF import, 2026-09-27):

  include/sfx2/docmacromode.hxx(281): error C2487:
  'containerHasBasicMacros': member of dll interface class may not
  be declared with dll interface

DocumentMacroMode is itself SFX2_DLLPUBLIC unless mergelibs is
enabled, and MSVC refuses a dllexport member inside a dllexport
class. Export the member only in the mergelibs build.

Signed-off-by: Mike Kaganski <mike.kaganski@collabora.com>
Change-Id: I4fbaaf0e5b79d4fdcef9073a12a7bd82f906c8e5
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/13706
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>