UBSan CppunitTest_sw_writerfilter_misc needs the SwXTableRows now
...presumably since 883febd60593e8a3c0c85c9859006cc0a35b10c2 "use more concrete
UNO type in writerfilter",

> DynamicLibraryManagerException: "Failed to load dynamic library: /home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/LinkTarget/CppunitTest/libtest_sw_writerfilter_misc.so
> /home/tdf/lode/jenkins/workspace/lo_ubsan/instdir/program/libsw_writerfilterlo.so: undefined symbol: _ZTI12SwXTableRows"

(<https://ci.libreoffice.org//job/lo_ubsan/3273/>)

Change-Id: I856ff7e2d7f31c83ad75b301caf4f8084f3e19a5
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/171806
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>
Tested-by: Jenkins