Update patch set 1
Patch Set 1:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/97700/ : FAILURE

Visual studio complained about error C2440: "<function-style-cast>": cannot convert from "initializer list" to "ApplicationEvent" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sfx2/source/appl/appdde.cxx(285) ( https://ci.libreoffice.org/job/gerrit_windows/108749/ )

Patch-set: 1