boost: upgrade to 1_91_0
<https://dev-www.libreoffice.org/src/boost_1_91_0.tar.xz> has been generated (on
Debian 13) with

> $ wget https://archives.boost.io/release/1.91.0/source/boost_1_91_0.tar.bz2
> $ printf 'de5e6b0e4913395c6bdfa90537febd9028ea4c0735d2cdb0cd9b45d5f51264f5 boost_1_91_0.tar.bz2' | sha256sum -c # cf. <https://www.boost.org/users/history/version_1_91_0.html>
> boost_1_91_0.tar.bz2: OK
> $ external/boost/repack_tarball.sh boost_1_91_0.tar.bz2
> Unpacking boost_1_91_0.tar.bz2 ...
> Removing unnecessary files ...
> Creating boost_1_91_0.tar.xz ...
> Cleaning up ...
> 2f975c10da79511c2f218189fc8a12eef1a92e3bd18206e9841d406296d065eb  boost_1_91_0.tar.xz
> Done.

0001-Allow-fallthrough-of-Android-to-128-bit-float.patch.1 fixes
In file included from /home/tdf/jenkins/workspace/android_x86_64/workdir/UnpackedTarball/boost/boost/math/special_functions/fpclassify.hpp:21:
/home/tdf/jenkins/workspace/android_x86_64/workdir/UnpackedTarball/boost/boost/math/special_functions/detail/fp_traits.hpp:314:15: error: static assertion failed due to requirement '113 == 64': Oops, assumption that long double is an 80-bit quantity is incorrect!!
  314 | static_assert(LDBL_MANT_DIG == 64, "Oops, assumption that long double is an 80-bit quantity is incorrect!!");

on Android x86_64
and unreachable_code.patch.1 fixes
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\boost\boost\optional\detail\union_optional.hpp(600) : error C2220: the following warning is treated as an error
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\boost\boost\optional\detail\union_optional.hpp(600) : warning C4702: unreachable code
on Windows

Change-Id: Iac97991234cdb24c41bc2f0e0567fd2adb8f2f7c
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/204152
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Tested-by: Jenkins