Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/9431/ : FAILURE

error: unused parameter name [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/libreofficekit/qa/tilebench/tilebench.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/9677/ )

clang plugin casttovoid did trigger. unused parameter name ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/9677/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0