Update patch set 14
Patch Set 14: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/83676/ : FAILURE

Visual studio complained about error C2440: "<function-style-cast>": cannot convert from "o3tl::is_typed_flags<SfxFilterFlags,2009011583>::Wrap" to "sal_Int32" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/desktop/source/app/dispatchwatcher.cxx(103) ( https://ci.libreoffice.org/job/gerrit_windows/94214/ )

Patch-set: 14
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1