Update patch set 8
Patch Set 8: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/110789/ : FAILURE

clang plugin fakebool did trigger. use "true" instead of "sal_True" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/110335/ )

error: use "true" instead of "sal_True" [loplugin:fakebool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/svtools/source/misc/embedhlp.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/110335/ )

Patch-set: 8
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000779 \u003c1000779@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}