fdo#65168: Fix previous fix, Class-Path is built up in solenv/gbuild/Jar.mk
...and must not be hard-coded in the manifest input (else report.jar was missing
the link to commonwizards.jar, so at least --disable-report-builder builds
failed with java.lang.NoClassDefFoundError).

Change-Id: I81cdadb599c7bf9a4a4503924dab4fbf9d60b44f