-Werror,-Wmicrosoft-exception-spec (clang-cl)
No idea why that started to show up now, but
C:/Program Files (x86)/Windows Kits/10/Include/10.0.17763.0/um/combaseapi.h
contains

> #define STDMETHOD(method)        virtual COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE method

while
C:/Program Files (x86)/Windows Kits/10/Include/10.0.17763.0/um/winnt.h
contains

> #define STDMETHODIMP            HRESULT STDMETHODCALLTYPE

which caused failures like

> [build CXX] embedserv/source/inprocserv/dllentry.cxx
> embedserv/source/inprocserv/dllentry.cxx(261,40): error: 'QueryInterface' is missing exception specification '__attribute__((nothrow))' [-Werror,-Wmicrosoft-exception-spec]
> STDMETHODIMP InprocEmbedProvider_Impl::QueryInterface( REFIID riid, void ** ppv )
>                                        ^
> embedserv/source/inprocserv/dllentry.cxx(143,15): note: previous declaration is here
>     STDMETHOD(QueryInterface)(REFIID riid, void ** ppvObj) override;
>               ^

Change-Id: I0fe3554c2da4089bf0f883e1132d6f2ee95ae2c3
Reviewed-on: https://gerrit.libreoffice.org/79970
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>