Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/93543/ : FAILURE

error ""bad_optional_access" is unavailable: introduced in macOS 10.14" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/editeng/outlobj.hxx:198:28 ( https://ci.libreoffice.org/job/gerrit_mac/98946/ )

error: "bad_optional_access" is unavailable: introduced in macOS 10.14 in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/editeng/outlobj.hxx ( https://ci.libreoffice.org/job/gerrit_mac/98946/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1