Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/43657/ : FAILURE

error "class "PropertyValue" was previously declared as a struct [-Werror,-Wmismatched-tags]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/vcl/commandinfoprovider.hxx:28:23 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/47129/ )

error: class "PropertyValue" was previously declared as a struct [-Werror,-Wmismatched-tags] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/vcl/commandinfoprovider.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/47129/ )

Patch-set: 1
Label: Verified=-1