Blind fix for kde
/home/tinderbox/master/vcl/unx/kde/salnativewidgets-kde.cxx:1987:88: error: implicit instantiation of undefined template ´boost::optional<Color>´
aStyleSettings.SetMenuBarTextColor( aStyleSettings.GetPersonaMenuBarTextColor().get_value_or( aMenuFore ) );

/home/tinderbox/master/include/vcl/settings.hxx:38:32: note: template is declared here
template<typename T> class optional;

Change-Id: Ic681d36f376f7433dae56fc1da5f8a2dd0f597ea
(cherry picked from commit 238575424341dedaef9713fcdb988ed39ccbf82c)