loplugin:redundantstatic in gtkinst
vcl/unx/gtk3/gtkinst.cxx:23657:1: error: redundant 'static' keyword in unnamed namespace [loplugin:redundantstatic]

after
  commit d5e894dec11f5fbc8c1e42625c01d3d3c2c250c2
  Author: Shardul Vikram Singh <shardul.singh@collabora.com>
  Date:   Mon May 4 16:27:22 2026 +0530
  vcl: add VclCustomWidget for client-rendered widgets

Change-Id: I602909932966014734a27c9963880fb66b32d32d
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/2906
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>
Tested-by: Noel Grandin <noel.grandin@collabora.com>