fix build of openssl with VS120
In openssl-1.0.2o the -WX switch was introduced (treat warnings as errors).
This caused a problem with Visual Studio 2013:
    ./crypto/des/set_key.c(70) : error C2220: warning treated as error - no 'object' file generated
    ./crypto/des/set_key.c(70) : warning C4172: returning address of local variable or temporary
The code in question has been unchanged for long, so supressing this warning looked like a plausible
solution.

Change-Id: Ie771f0f1fea6d4a7edc2e2ecb3a6d8dcf4c30368