Kit: skip the unstable textbox snap to grid test
testSnapTextBoxToGrid in CppunitTest_sw_snap_to_grid failed in a CODA-W
build with

 C:/lo/online/engine/sw/qa/extras/snaptogrid/snaptogrid.cxx(200) : error : Assertion
 Test name: `anonymous namespace'::testSnapTextBoxToGrid::TestBody
 equality assertion failed
 - Expected: 2032
 - Actual  : 3048

and with 4064 before I9bce49be53969414995049c0d9e3aa8c7135413c ("sw: drag
after text edit used a stale start point"): the value varies because the
first resize presses a corner before any click has selected the textbox,
so PickHandle finds nothing there, and the path that selects and arms a
drag decides where the textbox lands.

Signed-off-by: Mike Kaganski <mike.kaganski@collabora.com>
Change-Id: Ia2d46799dfd69f678a2409164d2c60a2e6bef2a0
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/8489
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>