Fix climaker build on Windows
Commit 14bf02c09226591481735d02b9276f3968d4bcbd ("cool#15927 move
css::uno::Sequence to cpo::uno namespace", 2026-07-06) moved the
template out of com::sun::star::uno but missed cli_ure/climaker, which
only builds with --enable-cli. Its two remaining css::uno::Sequence
declarations then no longer resolved:

    climaker_share.h(130): error C2039: 'Sequence': is not a member of
        'com::sun::star::uno'
    climaker_emit.cxx(1892): error C2511:
        '...get_exception_attribute(const cpo::uno::Sequence<...> &)':
        overloaded member function not found in 'climaker::TypeEmitter'

Signed-off-by: Mike Kaganski <mike.kaganski@collabora.com>
Change-Id: I1f07bbf1fe5a416343c3236fc6ec54b5e9fbe9e7
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/6300
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>