Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/103161/ : FAILURE

clang plugin cppunitassertequals did trigger. rather call CPPUNIT_ASSERT_EQUAL_MESSAGE when comparing "const ScProtectionAttr" and "const ScProtectionAttr" (or rewrite as an explicit operator == call when the operator itself is the topic) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/103378/ )

error: rather call CPPUNIT_ASSERT_EQUAL_MESSAGE when comparing "const ScProtectionAttr" and "const ScProtectionAttr" (or rewrite as an explicit operator == call when the operator itself is the topic) [loplugin:cppunitassertequals] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/qa/unit/subsequent_filters_test.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/103378/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/103378/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1