Update patch set 17
Patch Set 17: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/61785/ : FAILURE

Visual studio complained about error C7555: use of designated initializers requires at least "/std:c++latest" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/slideshow/source/engine/box2dtools.cxx(246) ( https://ci.libreoffice.org/job/gerrit_windows/70583/ )

Patch-set: 17
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1