Update patch set 15
Patch Set 15: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/73991/ : FAILURE

clang plugin stringview did trigger. instead of an "rtl::OUString", pass a "std::u16string_view" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/76150/ )

error: instead of an "rtl::OUString", pass a "std::u16string_view" [loplugin:stringview] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/extras/layout/layout2.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/76150/ )

Patch-set: 15
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1