Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/102657/ : FAILURE

Visual studio complained about error C2065: "FB_LOGFILENAME": undeclared identifier in file C:\cygwin\home\tdf\lode\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\firebird\src\yvalve\../common/file_params.h(74) ( https://ci.libreoffice.org/job/gerrit_windows/113804/ )

likely caused by leftovers that linger around from an aborted build ( https://ci.libreoffice.org/job/gerrit_windows/113804/ )

compiler couldn"t find the file »openssl/opensslconf.h« referenced from C:\cygwin\home\tdf\lode\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\openssl\include\openssl/asn1.h(15) ( https://ci.libreoffice.org/job/gerrit_windows/113804/ )

linker cannot find  ( https://ci.libreoffice.org/job/gerrit_windows/113804/ )

build likely got stuck and was aborted due to not producing any output to the log ( https://ci.libreoffice.org/job/gerrit_windows/113804/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000092 \u003c1000092@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}