Update patch set 1
Patch Set 1: Code-Review-1

Patch is good but missed a bit

make first line in the commit something like:
cid#1234 remove unused code

also be aware of side effects:
/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Linux/starmath/source/edit.cxx:1018:19: error: unused variable ‘nEndIndex’ [-Werror=unused-variable]
         sal_Int32 nEndIndex = 0;
                   ^
cc1plus: all warnings being treated as errors

Patch-set: 1
Label: Code-Review=-1