This shall likely produce "true" instead of "1"
...in code introduced in 503f526d1de72f5fe60378c82d5c071e650ddee7 "Impress:
initialize preview size according to it's page size", found with

> engine/../kit/KitHelper.hpp:207:63: error: implicit conversion (IntegralCast) from 'bool' to 'int' [loplugin:implicitboolconversion]
>   207 |             resultInfo["currentpageresized"] = std::to_string(true);
>       |                                                               ^~~~

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: Ifacec6d2fa8e2ce066b7506f97bbbce02a36880d
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/8056
Reviewed-by: Mohit Marathe <mohit.marathe@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>