remove assert
because it makes gcc10 unhappy:
canvas/source/vcl/outdevholder.hxx: In constructor
vclcanvas::OutDevHolder::OutDevHolder(OutputDevice&):
/home/michi/development/git/libreoffice/canvas/source/vcl/outdevholder.hxx:38:16:
error: the compiler can assume that the address of rOutDev will never be
NULL [-Werror=address]

Change-Id: I82e5aba9b08419176e4cbd9a6abf1e84d78f5585