Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/3210/ : FAILURE

clang plugin badstatics did trigger. bad static variable causes crash on shutdown ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/3190/ )

error: bad static variable causes crash on shutdown [loplugin:badstatics] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/inc/graphic/Manager.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/3190/ )

Patch-set: 5
Label: Verified=-1