Resolves: tdf#127982 SMALL()/LARGE() rank array can be larger than data array
 This is a combination of 4 commits.

Resolves: tdf#127982 SMALL()/LARGE() rank array can be larger than data array

Only set error for the positions where the requested rank is out
of bounds. This also includes zero or negative rank values,
instead of setting a global error.

Regression from

    commit e22ab5e6f6b0ea49231ca454a567133996306116
    CommitDate: Thu Nov 15 22:12:01 2018 +0100

        Resolves: i#32345 Make LARGE()/SMALL() return an array

Where previously due to the iteration in the array case single
values were returned and assembled.

Reviewed-on: https://gerrit.libreoffice.org/81279
Reviewed-by: Eike Rathke <erack@redhat.com>
Tested-by: Jenkins
(cherry picked from commit 475165e431b5392e426db0de4cea50efc2513875)

Related: tdf#127982 In JumpMatrix do not propagate individual errors as global

Which for
https://bugs.documentfoundation.org/attachment.cgi?id=154776
was the case in sheet1 МультиВПР.E6:E20 even in the to-be-fixed
SMALL() implementation.

The error is propagated as usual individual matrix element coded
double error.

Reviewed-on: https://gerrit.libreoffice.org/81252
Reviewed-by: Eike Rathke <erack@redhat.com>
Tested-by: Jenkins
(cherry picked from commit 12b54e485103aad4e7dd26423c355b96403b88ba)

-Wimplicit-int-float-conversion

with clang trunk

implicit conversion from 'unsigned long' to 'double' changes value from
18446744073709551615 to 18446744073709551616
[-Werror,-Wimplicit-int-float-conversion]
                if (f < 1.0 || f > std::numeric_limits<SCSIZE>::max())
                                 ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Reviewed-on: https://gerrit.libreoffice.org/81319
Tested-by: Jenkins
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>
(cherry picked from commit 1b0cba8c2cd672b0d5a59a215961c5136a6e656b)

-Werror,-Wimplicit-int-float-conversion

> sc/source/core/tool/interpr3.cxx:3659:36: error: implicit conversion from 'unsigned long' to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Werror,-Wimplicit-int-float-conversion]
>                 if (f < 1.0 || f > std::numeric_limits<SCSIZE>::max())
>                                  ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

since 475165e431b5392e426db0de4cea50efc2513875 "Resolves: tdf#127982
SMALL()/LARGE() rank array can be larger than data array"

(This supersedes 1b0cba8c2cd672b0d5a59a215961c5136a6e656b
"-Wimplicit-int-float-conversion", which would have incurred UB if f is larger
than std::numeric_limits<SCSIZE>::max().)

Reviewed-on: https://gerrit.libreoffice.org/81309
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit f26178b17691ccc9d3da9c25cec9ef08a633b3a7)

Backported:
As there is no o3tl/float_int_conversion.hxx in 6.3 unfold the
check to

-                if (f < 1.0 || !o3tl::convertsToAtMost(f, std::numeric_limits<SCSIZE>::max()))
+                if (f < 1.0 || !(f < double(std::numeric_limits<SCSIZE>::max()) + 1.0))

5fc6fa3454b354a4017a51a640b96ec80f74f4a4
ef0eb55ed1ade9fb88f5749774790aebbb27e085
1eeb75d73169ac89ec4bf9562edcf99d9925f607

Change-Id: Ic992c56cb79e80269cc7200fac5b15cb8aca3566