Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/18061/ : FAILURE

error: unused variable declaration [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/desktop/qa/desktop_lib/test_desktop_lib.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/18712/ )

clang plugin casttovoid did trigger. unused variable declaration ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/18712/ )

Patch-set: 4
Label: Verified=-1