engine configmgr: fix invalidated iterator access in Components::initGlobalBroadcaster()
'make -C engine/sw -sr UITest_sw_sidebar' fails sometimes under load
with a _GLIBCXX_DEBUG "singular iterator" abort in
Components::initGlobalBroadcaster(), coming from .uno:Sidebar at the
end of tdf133189:
        /usr/include/c++/15/debug/safe_iterator.h:392:
        In function:
            constexpr gnu_debug::_Safe_iterator<_Iterator, _Sequence, _Category>&
            gnu_debug::_Safe_iterator<_Iterator, _Sequence, _Category>::operator++()
            [with _Iterator = gnu_cxx::normal_iterator<configmgr::RootAccess*
            const*, std::vector<configmgr::RootAccess*,
            std::allocator<configmgr::RootAccess*> > >; _Sequence = std::
            debug::vector<configmgr::RootAccess*,
            std::allocator<configmgr::RootAccess*> >; _Category =
            std::forward_iterator_tag]
        Error: attempt to increment a singular iterator.
        Objects involved in the operation:
            iterator "this" @ 0x7fa671809950 {
              type = gnu_cxx::normal_iterator<configmgr::RootAccess* const*, std::vector<configmgr::RootAccess*, std::allocator<configmgr::RootAccess*> > > (constant iterator);
              state = singular;
              references sequence with type 'std::debug::vector<configmgr::RootAccess*, std::allocator<configmgr::RootAccess*> >' @ 0x7fa68282d908
            }
        Fatal exception: Signal 6
        Stack:
        #0 sal::backtrace_get(unsigned int) at engine/sal/osl/unx/backtraceapi.cxx:42 (discriminator 1)
        #1 (anonymous namespace)::printStack(int) at engine/sal/osl/unx/signal.cxx:276
        #2 (anonymous namespace)::callSystemHandler(int, siginfo_t*, void*) at engine/sal/osl/unx/signal.cxx:317
        #3 (anonymous namespace)::signalHandlerFunction(int, siginfo_t*, void*) at engine/sal/osl/unx/signal.cxx:406
        #4 __restore_rt in /lib64/libc.so.6
        #5 __pthread_kill_implementation in /lib64/libc.so.6
        #6 __GI_raise in /lib64/libc.so.6
        #7 __GI_abort in /lib64/libc.so.6
        #8 std::__throw_bad_exception() in /lib64/libstdc++.so.6
        #9 __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<configmgr::RootAccess* const*, std::__cxx1998::vector<configmgr::RootAccess*, std::allocator<configmgr::RootAccess*> > >, std::__debug::vector<configmgr::RootAccess*, std::allocator<configmgr::RootAccess*> >, std::forward_iterator_tag>::operator++() at /usr/include/c++/15/debug/safe_iterator.h:395
        #10 __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<configmgr::RootAccess* const*, std::__cxx1998::vector<configmgr::RootAccess*, std::allocator<configmgr::RootAccess*> > >, std::__debug::vector<configmgr::RootAccess*, std::allocator<configmgr::RootAccess*> >, std::bidirectional_iterator_tag>::operator++() at /usr/include/c++/15/debug/safe_iterator.h:680
        #11 __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<configmgr::RootAccess* const*, std::__cxx1998::vector<configmgr::RootAccess*, std::allocator<configmgr::RootAccess*> > >, std::__debug::vector<configmgr::RootAccess*, std::allocator<configmgr::RootAccess*> >, std::random_access_iterator_tag>::operator++() at /usr/include/c++/15/debug/safe_iterator.h:850
        #12 configmgr::Components::initGlobalBroadcaster(configmgr::Modifications const&, rtl::Reference<configmgr::RootAccess> const&, configmgr::Broadcaster*) at /home/vmiklos/git/collaboraonline/online/engine/configmgr/source/components.cxx:263 (discriminator 3)
        #13 configmgr::RootAccess::commitChanges() at engine/configmgr/source/rootaccess.cxx:167 (discriminator 5)
        #14 (anonymous namespace)::ConfigurationAccess_WindowState::replaceByName(rtl::OUString const&, cpo::uno::Any const&) at engine/framework/source/uiconfiguration/windowstateconfiguration.cxx:471

What happens is that we iterate roots_ in
Components::initGlobalBroadcaster(), and during iterating, some called
code modifies the container, which invalidates our iterator.

Fix the problem by iterating a copy and ignoring elements which are no
longer in roots_.

Unfortunately we only have a backtrace for the invalidated iterator
access, so it's not clear which location modifies the container. But
code reading suggests it's most likely that it's a deletion from a
RootAccess dtor (and not an insertion, for which the current fix would
hide a problem).

Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: I819717f11e82ea0bf65adce7ddf6cec8c058a7de
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/13048
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>