Fix build [-Werror=reorder]
  In file included from /home/mike/libreoffice/svx/source/items/hlnkitem.cxx:22:
  /home/mike/libreoffice/include/svx/hlnkitem.hxx: In constructor ‘SvxHyperlinkItem::SvxHyperlinkItem(sal_uInt16, const rtl::OUString&, const rtl::OUString&, const rtl::OUString&, const rtl::OUString&, SvxLinkInsertMode, HyperDialogEvent, const SvxMacroTableDtor*, const rtl::OUString&)’:
  /home/mike/libreoffice/include/svx/hlnkitem.hxx:60:22: error: ‘SvxHyperlinkItem::nMacroEvents’ will be initialized after [-Werror=reorder]
     60 |     HyperDialogEvent nMacroEvents;
        |                      ^~~~~~~~~~~~
  /home/mike/libreoffice/include/svx/hlnkitem.hxx:55:14: error:   ‘rtl::OUString SvxHyperlinkItem::sReplacementText’ [-Werror=reorder]
     55 |     OUString sReplacementText;
        |              ^~~~~~~~~~~~~~~~
  /home/mike/libreoffice/svx/source/items/hlnkitem.cxx:43:1: error:   when initialized here [-Werror=reorder]
     43 | SvxHyperlinkItem::SvxHyperlinkItem( sal_uInt16 _nWhich, const OUString& rName, const OUString& rURL,
        | ^~~~~~~~~~~~~~~~

after commit fb3597932ad9322feb58115528ca1dae070edfa5
  Author rash419 <rashesh.padia@collabora.com>
  Date   Thu Sep 15 18:02:06 2022 +0530
    svx: extended SvxHyperlinkItem to have a new property sReplacementText

Change-Id: Ia8be467919ac6f617a19f310535c6fff9b5e178e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/140686
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>