don't let msbuild reuse its worker processes between builds
A worker kept alive from an earlier build still holds that build's node
ids, so the external projects fail with the likes of:

 MSBUILD : error MSB4166: Child node "27" exited prematurely. Shutting
 down. Diagnostic information may be found in files in
 ".../gerrit_windows_app_main\tmp\MSBuildTempd083e9ee959f45a6826eadc2e3b03605\"
 and will be named MSBuild_*.failure.txt.

and the MSBuild_*.failure.txt dump it points at has:

 Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: Invalid node id specified: 6.

Signed-off-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Change-Id: I97f4ddb48c75307037143e2121346a2570497c28
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/10272
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>