qt6 avmedia: Adjust code to PngImageReader changes
Adjust the code after

    commit 70162a33fde729998e4d9c7558f3634352738772
    Date:   Tue Apr 15 14:17:21 2025 +0900

        vcl: Introduce ImportOutput to return BitmapEx or Animation

to address the following build failure for the --enable-qt6 build:

    /home/michi/development/git/libreoffice/avmedia/source/qt6/QtFrameGrabber.cxx:36:13: error: no matching member function for call to 'read'
       36 |     aReader.read(aGraphic);
          |     ~~~~~~~~^~~~
    /home/michi/development/git/libreoffice/include/vcl/filter/PngImageReader.hxx:58:10: note: candidate function not viable: no known conversion from 'Graphic' to 'BitmapEx &' for 1st argument
       58 |     bool read(BitmapEx& rBitmap);
          |          ^    ~~~~~~~~~~~~~~~~~
    /home/michi/development/git/libreoffice/include/vcl/filter/PngImageReader.hxx:59:10: note: candidate function not viable: no known conversion from 'Graphic' to 'ImportOutput &' for 1st argument
       59 |     bool read(ImportOutput& rImportOutput);
          |          ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/michi/development/git/libreoffice/include/vcl/filter/PngImageReader.hxx:61:14: note: candidate function not viable: requires 0 arguments, but 1 was provided
       61 |     BitmapEx read();
          |              ^
    1 error generated.

Change-Id: I7d322f66a09f76851e9045e8e90684ac35bb48f6
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/184424
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>