Update patch set 4
Patch Set 4: This need some tweaks before it is merged

Hm, and it also breaks the build:

 In file included from /master/sw/source/filter/ww8/docxattributeoutput.cxx:20:0:
 /master/sw/source/filter/ww8/docxattributeoutput.hxx: In constructor ‘DocxAttributeOutput::DocxAttributeOutput(DocxExport&, sax_fastparser::FSHelperPtr, oox::drawingml::DrawingML*)’:
 /master/sw/source/filter/ww8/docxattributeoutput.hxx:783:35: error: ‘DocxAttributeOutput::m_bParaAfterAutoSpacing’ will be initialized after [-Werror=reorder]
 /master/sw/source/filter/ww8/docxattributeoutput.hxx:781:45: error:   ‘boost::shared_ptr<DocxTableStyleExport> DocxAttributeOutput::m_pTableStyleExport’ [-Werror=reorder]
 /master/sw/source/filter/ww8/docxattributeoutput.cxx:6213:1: error:   when initialized here [-Werror=reorder]

Patch-set: 4
Label: Code-Review=-1