Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/110180/ : FAILURE

error: explicit cast from "tools::Long" (aka "long") to "size_t" (aka "unsigned long") (of equal rank) in comparison against "size_t": if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast [loplugin:unsignedcompare] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/uibase/utlui/content.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/109757/ )

clang plugin unsignedcompare did trigger. explicit cast from "tools::Long" (aka "long") to "size_t" (aka "unsigned long") (of equal rank) in comparison against "size_t": if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/109757/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1