Avoid LIBO_USE_SOURCE_LOCATION feature on user-facing LockFileException
(see 1d0bc2139759f087d50432f8a2116060676f34e1 "use
std::experimental::source_location in uno::Exception"), causing the unopkg
executable to print something like

> ERROR: unopkg cannot be started. The lock file indicates it is already running. If this does not apply, delete the lock file at:
> ~/.config/libreoffice/4/.lock desktop/source/pkgchk/unopkg/unopkg_shared.h:44

mentioning an unhelpful source location

Change-Id: Ie9ed716c9edc6c73c173a034ce8bd9bfaf05c0c9