Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/88994/ : FAILURE

error "‘CHEVRON’ defined but not used [-Werror=unused-variable]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/vcl/inc/bitmaps.hlst:225:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/92935/ )

error: ‘OOO_HELP_INDEX’ defined but not used [-Werror=unused-variable] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/include/vcl/help.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/92935/ )

compiler warning unused-variable treated as error: ‘CHEVRON’ defined but not used in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/vcl/inc/bitmaps.hlst:225:27 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/92935/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1