coda-m: Register the error and debug bridges also for the Backstage
On many installs (probably all the Sequoia ones, but not 100% sure),
File -> New (or just an app start) opened a near-blank Backstage
(only the close "x" showed), and the Safari console reported:

  TypeError: undefined is not an object
  (evaluating 'window.webkit.messageHandlers.error.postMessage')

The Backstage web view registered only the "lok" handler, so the first
console.error or uncaught error during startup hit the missing "error"
handler, threw & aborted.  No idea why it went through on the development
machine (with Tahoe - if that was the differentiator).

Register the "error" and "debug" handlers on the Backstage web view,
via sharing the code with the document webview, which was already doing
this.

Signed-off-by: Jan Holesovsky <kendy@collabora.com>
Change-Id: I0a40027e681b44f672e5554f10f0549b30aa0045
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/4089
Reviewed-by: Sarper Akdemir <sarper.akdemir@collabora.com>
Tested-by: Andras Timar <andras.timar@collabora.com>