Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/98322/ : FAILURE

error ""begin" is deprecated: has hidden COW cost; use getArray or asNonConstRange if you need a modifiable range [-Werror,-Wdeprecated-declarations]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/com/sun/star/uno/Sequence.hxx:295:28 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/98919/ )

error: "begin" is deprecated: has hidden COW cost; use getArray or asNonConstRange if you need a modifiable range [-Werror,-Wdeprecated-declarations] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/com/sun/star/uno/Sequence.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/98919/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1