Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/64464/ : FAILURE

error "‘basegfx’ has not been declared" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/chart2/source/view/inc/VSeriesPlotter.hxx:245:33 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/68267/ )

error: ‘basegfx’ has not been declared in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/chart2/source/view/inc/VSeriesPlotter.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/68267/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1