Update patch set 4
Patch Set 4:

> Are you able to build C++ 'DocumentLoader' example?

No. I found that I was missing --enable-odk in my configure line.
But even after that, includes are not found:

odk/examples/cpp/DocumentLoader$ make
mkdir -p /home/samuel/libreoffice7.2_sdk/LINUXexample.out/obj/DocumentLoader
gcc -c -fpic -fvisibility=hidden -O -I. -I/home/samuel/libreoffice7.2_sdk/LINUXexample.out/inc -I/home/samuel/libreoffice7.2_sdk/LINUXexample.out/inc/examples -I../../../include -I/home/samuel/libreoffice7.2_sdk/LINUXexample.out/inc/DocumentLoader -DUNX -DGCC -DLINUX -DCPPU_ENV=gcc3 -o/home/samuel/libreoffice7.2_sdk/LINUXexample.out/obj/DocumentLoader/DocumentLoader.o DocumentLoader.cxx
DocumentLoader.cxx:40:10: fatal error: sal/main.h: Datei oder Verzeichnis nicht gefunden
   40 | #include <sal/main.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:65: /home/samuel/libreoffice7.2_sdk/LINUXexample.out/obj/DocumentLoader/DocumentLoader.o] Fehler 1


odk/examples/cpp/Draw$ make
mkdir -p /home/samuel/libreoffice7.2_sdk/LINUXexample.out/obj/Draw
gcc -c -fpic -fvisibility=hidden -O -I. -I/home/samuel/libreoffice7.2_sdk/LINUXexample.out/inc -I/home/samuel/libreoffice7.2_sdk/LINUXexample.out/inc/examples -I../../../include -I/home/samuel/libreoffice7.2_sdk/LINUXexample.out/inc/Draw -DUNX -DGCC -DLINUX -DCPPU_ENV=gcc3 -o/home/samuel/libreoffice7.2_sdk/LINUXexample.out/obj/Draw/Draw.o Draw.cxx
Draw.cxx:22:10: fatal error: cppuhelper/bootstrap.hxx: Datei oder Verzeichnis nicht gefunden
   22 | #include <cppuhelper/bootstrap.hxx>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:49: /home/samuel/libreoffice7.2_sdk/LINUXexample.out/obj/Draw/Draw.o] Fehler 1

Patch-set: 4