Silence -Werror,-Wdeprecated-declarations for now
...as seen with qt5-qtbase-devel-5.13.2-1.fc31.x86_64:

> vcl/qt5/Qt5Frame.cxx:481:73: error: 'screenGeometry' is deprecated: Use QGuiApplication::screens() [-Werror,-Wdeprecated-declarations]
>             toSize(pScreen ? pScreen->size() : QApplication::desktop()->screenGeometry(0).size()));
>                                                                         ^
> /usr/include/qt5/QtWidgets/qdesktopwidget.h:79:5: note: 'screenGeometry' has been explicitly marked deprecated here
>     QT_DEPRECATED_X("Use QGuiApplication::screens()") const QRect screenGeometry(int screen = -1) const;
>     ^
[...]
> vcl/qt5/Qt5Frame.cxx:490:56: error: 'screenNumber' is deprecated: Use QGuiApplication::screenAt() [-Werror,-Wdeprecated-declarations]
>             int nLeftScreen = QApplication::desktop()->screenNumber(QPoint(0, 0));
>                                                        ^
> /usr/include/qt5/QtWidgets/qdesktopwidget.h:75:5: note: 'screenNumber' has been explicitly marked deprecated here
>     QT_DEPRECATED_X("Use QGuiApplication::screenAt()") int screenNumber(const QPoint &) const;
>     ^
[...]

Change-Id: I7db00ee0e7cd7f652af4f7426f9ea0172206d485
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/86660
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit 09597ab01d22820137ada0dc08b5a9bf481468a8)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/183435
Tested-by: allotropia jenkins <jenkins@allotropia.de>
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>