xmlsec: fix ATTRIBUTE_UNUSED compile failure
Mohit reports that it fails to build with gcc14:

keysstore.c:133:56: error: expected ';', ',' or ')' before 'ATTRIBUTE_UNUSED'
  133 |                             xmlSecKeysMngrPtr keysMngr ATTRIBUTE_UNUSED) {
      |                                                        ^~~~~~~~~~~~~~~~

symkeys.c:132:96: error: expected ';', ',' or ')' before 'ATTRIBUTE_UNUSED'
  132 | xmlSecNssSymKeyDataGenerate(xmlSecKeyDataPtr data, xmlSecSize sizeBits, xmlSecKeyDataType type ATTRIBUTE_UNUSED) {
      |                                                                                                ^~~~~~~~~~~~~~~~

The problem appears to be that ATTRIBUTE_UNUSED is not defined - it is
defined in the file include/xmlsec/private.h but that is not included in
the symkeys.c nor keysstore.c in src/nss but the file
/usr/include/libxml2/libxml/xmlversion.h is included in those files (as
seen in .dep/libxmlsec1_nss_la-symkeys.Plo) and that one also defines
ATTRIBUTE_UNUSED - so my impression is that it only ever worked by
accident.

Backport relevant looking commit from xmlsec 1.3.6, removing
configure.ac changes and 2 hunks in .c files that used different calls:

1 out of 12 hunks FAILED -- saving rejects to file configure.ac.rej
1 out of 2 hunks FAILED -- saving rejects to file src/keysmngr.c.rej
1 out of 2 hunks FAILED -- saving rejects to file src/templates.c.rej

Change-Id: I6fcc817c6e05b4ead77cc70ea6a9ffa0fc000cd9
(cherry picked from commit 2235dbd07cc7373740573dda7f31f44256cda576)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/192876
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>
(cherry picked from commit 2ff0a3485d925df99b0372499fac56e3e524b27d)