Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/49137/ : FAILURE

error: use of undeclared identifier "isspace" in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/comphelper/source/misc/debuggerinfo.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/52486/ )

clang plugin external did trigger. externally available entity "WatchdogHelper" is not previously declared in an included file (if it is only used in this translation unit, put it in an unnamed namespace; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/52486/ )

Patch-set: 1
Label: Verified=-1