Fix loplugin:unusedvariablecheck
...on macOS, where it started to cause false positives like

> vcl/inc/osx/a11ywrapper.h:89:98: error: unused parameter 'anAccessibleContext' [loplugin:unusedvariablecheck]
> -(id)initWithAccessibleContext: (css::uno::Reference < css::accessibility::XAccessibleContext >) anAccessibleContext;
>                                                                                                  ^

after a214369f14d3f53d45b1889827057882c0ffd62e "loplugin:unusedvariablecheck
improve"

Change-Id: I450df3a6d768b4452d0975b5920ea0b3ce53ce13