Update patch set 8
Patch Set 8: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/39087/ : FAILURE

error "static_assert failed due to requirement "vcl::detail::isIncompleteOrDerivedFromVclReferenceBase<vcl::OWizardPage>(nullptr)" "template argument type must be derived from VclReferenceBase"" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/vcl/vclptr.hxx:59:5 ( https://ci.libreoffice.org/job/gerrit_mac/42330/ )

error: static_assert failed due to requirement "vcl::detail::isIncompleteOrDerivedFromVclReferenceBase<vcl::OWizardPage>(nullptr)" "template argument type must be derived from VclReferenceBase" in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/vcl/vclptr.hxx ( https://ci.libreoffice.org/job/gerrit_mac/42330/ )

Patch-set: 8
Label: Verified=-1