Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/84012/ : FAILURE

error: instead of an "rtl::OUString", pass a "std::u16string_view" [loplugin:stringview] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/extras/ooxmlexport/ooxmllinks.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/85469/ )

the test UITest_writer_tests7 failed ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/85469/ )

clang plugin stringview did trigger. instead of an "rtl::OUString", pass a "std::u16string_view" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/85469/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1