Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/117547/ : FAILURE

Visual studio complained about error C2220: the following warning is treated as an error in file C:\cygwin\home\tdf\jenkins\workspace\gerrit_windows@2\vcl\qa\cppunit\text.cxx(251)  ( https://ci.libreoffice.org/job/gerrit_windows/130064/ )

build likely got stuck and was aborted due to not producing any output to the log ( https://ci.libreoffice.org/job/gerrit_windows/130064/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1, 26407633e066360f219faf40de46f47a8976fa45