Update patch set 3
Patch Set 3:

> > > The gerrit clang compiler usually gives me warnings about that those constructors are unnecessary.
> > 
> > No, it does not (or else ~everybody would get compilation failures with the current version)?
> 
> This is the warning I got:
> /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/starmath/source/mathml/export.cxx:412:16: error: elide constructor call [loplugin:stringconstant]
>         return OUString(u"");
> 
> What did I misunderstand?

That warning only triggers for occurrences in return statements.  (The context for that warning is as follows:  When back in the day Lubos simplified literal OUString construction from

  OUString(RTL_CONSTASCII_STRINGPARAM("foo"))

to just

  "foo"

across the code base, uses in return statements needed to instead be spelled

  OUString("foo")

as otherwise old GCC would complain.  That finally changed with GCC 7, at which point I added that specific loplugin warning, cf. all the "Improved loplugin:stringconstant (now that GCC 7 supports it)" commits.)

> > What is your motivation for changing from plain "..." string literals to UTF-16 u"..." ones?  None of these changes are wrong, but I don't see much motivation for any of them, either.  (Especially not if done only in one random location.  If there were a compelling reason to always use u"..." literals in OUString construction, we should do that change globally.)
> 
> Since OUString uses utf16 beneath it just made sense.

For technical reasons, when passed into an OUString constructor, both "..." and u"..." literals need to be copied.  While copying of u"..." literals may be a bit faster, they occupy a bit more space in the binaries.  So which is better overall is unclear, so we generally stick to the existing practice of using of "...".

Patch-set: 3
Reviewer: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>