Update patch set 9
Patch Set 9: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/39096/ : FAILURE

error "static_assert failed due to requirement "vcl::detail::isIncompleteOrDerivedFromVclReferenceBase<SfxTabPage>(nullptr)" "template argument type must be derived from VclReferenceBase"" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/vcl/vclptr.hxx:59:5 ( https://ci.libreoffice.org/job/gerrit_mac/42339/ )

error: no matching member function for call to "AddTabPage" in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/filter/source/pdf/impdialog.cxx ( https://ci.libreoffice.org/job/gerrit_mac/42339/ )

Patch-set: 9
Label: Verified=-1