Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/44291/ : FAILURE

clang plugin casttovoid did trigger. unused parameter name ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/47775/ )

error: unused parameter name [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/basegfx/source/range/b2dpolyrange.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/47775/ )

Patch-set: 3
Label: Verified=-1