Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/38055/ : FAILURE

error: no need to explicitly init an instance of "std::unique_ptr<weld::Label>" with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/extensions/source/dbpilots/controlwizard.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/40992/ )

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "std::unique_ptr<weld::Label>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/40992/ )

Patch-set: 1
Label: Verified=-1