vim-ide-integration: clang does not always like gnu++1y that much
And gives the error:

include/c++/4.8/cstdio:120:11: error: no member named 'gets' in the global namespace

when it's build against libstdc++.

Commit 9e6221f114ba4422caa79f38ee0a20fb8a8931cd (clang does not like gnu++11
that much, use c++11 instead, 2014-09-06) added support for invoking clang for
IDE purposes even in a tree configured for gcc. Extend this in case configure
sets -std=gnu++1y for gcc as well.

Change-Id: Ib767ef8f30bd6eb9ac825a1521184041f1269d93
Reviewed-on: https://gerrit.libreoffice.org/23983
Reviewed-by: Miklos Vajna <vmiklos@collabora.co.uk>
Tested-by: Jenkins <ci@libreoffice.org>