Update patch set 30
Patch Set 30:

Oops, https://ci.libreoffice.org/job/gerrit_linux_gcc_release/74581/console shows a problem related to the patch:

> Traceback (most recent call last):
>   File "/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/solenv/bin/uiex", line 30, in <module>
>     keyid = entry.msgctxt + '|' + entry.msgid
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Looks like you missed "entry.msgctxt" required there...

Patch-set: 30
Reviewer: Gerrit User 1000994 <1000994@6622c302-437a-49ad-a91d-55ba7dcf1615>