Update patch set 4
Patch Set 4:

looks like this is causing issues for the Android tinderbox, <https://tinderbox.libreoffice.org/cgi-bin/gunzip.cgi?tree=MASTER&brief-log=1520988602.29479#19155>:

> 19155         [build CXX] extensions/source/propctrlr/defaulthelpprovider.cxx
> 19156 NEXT    /home/android/lo/master-android-arm/desktop/source/lib/lokandroid.cxx:385:33: error: cannot initialize a parameter of type ´jstring´ (aka ´_jstring *´) with an lvalue of type ´const char *´
> 19157             pEnv->ReleaseStringUTFChars(pData, data);
> 19158                                         ^~~~~
> 19159         /home/android/android-sdk-linux/ndk-bundle/sysroot/usr/include/jni.h:850:40: note: passing argument to parameter ´string´ here
> 19160             void ReleaseStringUTFChars(jstring string, const char* utf)
> 19161                                                ^
> 19162 NEXT    1 error generated.

Patch-set: 4
Reviewer: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0