Enable Clang -Wembedded-directive
...which might have helped avoid the confusion with patch set 6 of
<https://gerrit.libreoffice.org/c/core/+/84765/6> "python3: upgrade to release
3.7.6", in that it would have reported:

> pyuno/source/module/pyuno.cxx:340:2: error: embedding a directive within macro arguments has undefined behavior [-Werror,-Wembedded-directive]
> #if PY_VERSION_HEX >= 0x030200f0
>  ^
> pyuno/source/module/pyuno.cxx:342:2: error: embedding a directive within macro arguments has undefined behavior [-Werror,-Wembedded-directive]
> #else
>  ^

(-Wembedded-directive was introduced with <https://github.com/llvm/llvm-project/
commit/300237f00c7ddf9c74de96272f2bb571fda61202> "Add a warning flag for
ext_embedded_directive. gcc considers this undefined" in 2011, so should be
available in all versions of Clang relevant for us.)

Change-Id: I4d90212aac30ba8715496d8c99cc6de05c6dc99a
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/86394
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>