Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/29722/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "const char *" to "rtl::OUString" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/vcl/source/window/dialog.cxx(809) ( https://ci.libreoffice.org/job/gerrit_windows/34439/ )

Patch-set: 3
Label: Verified=-1