Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/120083/ : FAILURE

error "‘std::optional’ has not been declared" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sw/source/core/inc/pamtyp.hxx:91:36 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/123588/ )

error: ‘std::optional’ has not been declared in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sw/source/core/inc/pamtyp.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/123588/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1, 62b07d356f96e6fe3ffef1615eea765f89755043
Attention: {"person_ident":"Gerrit User 1000083 \u003c1000083@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}