Work around POSIX <langinfo.h> ERA macro clash
...that hit me now at least when building on macOS 26.6.1 against a local
LLVM 24 trunk,

> In file included from engine/svl/source/numbers/zforfind.cxx:32:
> In file included from engine/workdir/UnoApiHeadersTarget/offapi/normal/com/sun/star/i18n/CalendarFieldIndex.hpp:3:
> engine/workdir/UnoApiHeadersTarget/offapi/normal/com/sun/star/i18n/CalendarFieldIndex.hdl:16:26: error: expected unqualified-id
>    16 | static const ::sal_Int16 ERA = (sal_Int16)13;
>       |                          ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk/usr/include/_langinfo.h:92:14: note: expanded from macro 'ERA'
>    92 | #define ERA             45      /* era description segments */
>       |                         ^
> engine/svl/source/numbers/zforfind.cxx:2253:49: error: expected unqualified-id
>  2253 |             pCal->setValue( CalendarFieldIndex::ERA, mbEraCE ? 1 : 0);
>       |                                                 ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk/usr/include/_langinfo.h:92:14: note: expanded from macro 'ERA'
>    92 | #define ERA             45      /* era description segments */
>       |                         ^

etc.

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: Ie817cf08ceb26c60b56f817665233930cdbe3991
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/8972
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>