Update patch set 19
Patch Set 19:

I assume that it is this change's addition of

  #include <o3tl/runtimetooustring.hxx>

that causes CompilerTest_compilerplugins_clang to now fail for me with

  [CPT] compilerplugins/clang/test/writeonlyvars.cxx
  error: 'error' diagnostics seen but not expected: 
    File include/o3tl/runtimetooustring.hxx Line 34: read ok [loplugin:writeonlyvars]
    File include/o3tl/runtimetooustring.hxx Line 33: read s [loplugin:writeonlyvars]
    File include/o3tl/runtimetooustring.hxx Line 33: write s [loplugin:writeonlyvars]
  3 errors generated.
  make[1]: *** [solenv/gbuild/LinkTarget.mk:303: workdir/CxxObject/compilerplugins/clang/test/writeonlyvars.o] Error 1

at least when building with recent Clang 11 trunk,

Patch-set: 19
Reviewer: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>