Update patch set 1
Patch Set 1:

Here are remnants in wizards:
./wizards/com/sun/star/wizards/text/TextDocument.py:62: undefined name 'URL'
./wizards/com/sun/star/wizards/text/TextSectionHandler.py:93: undefined name 'ControlCharacter'
./wizards/com/sun/star/wizards/text/TextSectionHandler.py:98: undefined name 'insertTextSection'
./wizards/com/sun/star/wizards/text/TextSectionHandler.py:102: redefinition of unused 'insertTextSection' from line 88
./wizards/com/sun/star/wizards/text/TextSectionHandler.py:113: undefined name 'linkSectiontoTemplate'
./wizards/com/sun/star/wizards/common/Configuration.py:63: undefined name 'getNode'
./wizards/com/sun/star/wizards/common/Configuration.py:64: undefined name 'com'
./wizards/com/sun/star/wizards/common/Configuration.py:66: undefined name 'com'
./wizards/com/sun/star/wizards/agenda/AgendaDocument.py:453: undefined name 'getDateString'
./wizards/com/sun/star/wizards/agenda/AgendaDocument.py:468: undefined name 'xrange'

when using:
pyflakes3 ./wizards|grep -v 'imported but unused'|grep -v 'but never used'

("grep -v" ones are for easyhack)

a bit stuck for them.

I just wonder if these scripts are really used. Indeed, they should crash for some (those using pure Java).

Patch-set: 1
Reviewer: Gerrit User 1000179 <1000179@6622c302-437a-49ad-a91d-55ba7dcf1615>
Reviewer: Gerrit User 1000043 <1000043@6622c302-437a-49ad-a91d-55ba7dcf1615>