android: Port from deprecated ComponentActivity.onBackPressed (I)
Port LibreOfficeMainActivity from overriding the deprecated
androidx.ComponentActivity.onBackPressed method [1]
and register a androidx.activity.OnBackPressedCallback [2].

Overriding the deprecated API was already triggering warning

    /home/michi/development/git/libreoffice-WORKTREE-android/android/source/src/java/org/libreoffice/LibreOfficeMainActivity.java:511: warning: [deprecation] onBackPressed() in ComponentActivity has been deprecated
        public void onBackPressed() {
                    ^
and that was turned into a build/lint error in a WIP branch updating the
compileSdkVersion and targetSdkVersion to 36:

    /home/michi/development/git/libreoffice-WORKTREE-android/android/source/src/java/org/libreoffice/LibreOfficeMainActivity.java:511: Error: onBackPressed is no longer called for back gestures; migrate to AndroidX's backward compatible OnBackPressedDispatcher [GestureBackNavigation]
        public void onBackPressed() {
                    ~~~~~~~~~~~~~

Interaction when using the back button (or gesture)
remains as before in a quick test (with an additional
local revert of commit 9d1e76f7da12353afc3d9479d3b2ecddbb2a71e6
to prevent a deadlock when opening documents that is unrelated
to this change here).

[1] https://developer.android.com/reference/androidx/activity/ComponentActivity#onBackPressed()
[2] https://developer.android.com/reference/androidx/activity/OnBackPressedCallback

Change-Id: Id5bde62fede7e0550a86bd0ba9bd1535a84003dc
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/187572
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
(cherry picked from commit 9fa0ea06bc4f6be647ef4ac4d5bc1830bfc93ec4)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/187715
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>