Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/88152/ : FAILURE

error "struct "ImplSVEvent" was previously declared as a class [-Werror,-Wmismatched-tags]" triggered in included file /home/tdf/lode/jenkins/workspace/android_aarch64/include/vcl/svapp.hxx:67:1 ( https://ci.libreoffice.org/job/gerrit_android_aarch64/5711/ )

error: struct "ImplSVEvent" was previously declared as a class [-Werror,-Wmismatched-tags] in file /home/tdf/lode/jenkins/workspace/android_aarch64/include/vcl/svapp.hxx ( https://ci.libreoffice.org/job/gerrit_android_aarch64/5711/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1