fdo#50169: band-aid another crash in GraphiteLayout::expandOrCondense:
error: attempt to subscript container with out-of-bounds index 6,
but container only holds 6 elements.
(cherry picked from commit b8452a89ceaa9008558b83f3a8b6937d14b7c803)

Signed-off-by: Caolán McNamara <caolanm@redhat.com>