Fix build on Windows
... since a76116c867380836080adc86bc37c2248778825d:

    C:\lo\src\core\vcl\inc\salvtables.hxx(841): error C2872: 'MenuButton': ambiguous symbol
    C:\lo\src\core\include\vcl/menubtn.hxx(31): note: could be 'MenuButton'
    C:\lo\src\core\include\vcl/weld.hxx(1320): note: or       'weld::MenuButton'
    C:\lo\src\core\vcl\inc\salvtables.hxx(834): note: while compiling class template member function 'void SalInstanceComboBox<ComboBox>::set_item_menu(const rtl::O
String &,weld::Menu *)'
    C:\lo\src\core\vcl\inc\salvtables.hxx(932): note: see reference to class template instantiation 'SalInstanceComboBox<ComboBox>' being compiled
    ...
    make[1]: *** [C:/lo/src/core/solenv/gbuild/LinkTarget.mk:303: C:/lo/src/build/workdir/CxxObject/vcl/jsdialog/jsdialogbuilder.o] Error 2

Change-Id: Ic1fb4756c2acda629dcb885cd5c2b2687ec902d8