Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/2803/ : FAILURE

clang plugin casttovoid did trigger. unused virtual function parameter name ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/2786/ )

error: unused virtual function parameter name [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/ui/docshell/arealink.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/2786/ )

Patch-set: 4
Label: Verified=-1