external/coinmp: Work around -Werror,-Wformat-pedantic
Clang trunk since r231211 with -pedantic-errors now emits
"Cbc_C_Interface.cpp:379:55: error: format specifies type 'void *' but the
argument has type 'char *' [-Werror,-Wformat-pedantic]"

Change-Id: I5d410068f1cd82334f26148df30a45dbc9eabd0a