Update patch set 3
Patch Set 3:

this broke the build on some tinderbox:

D:\lode\dev\core\scripting\java\com\sun\star\script\framework\provider\beanshell\PlainSourceView.java:189: error: no suitable method found for start(String)
                            ta.replaceRange(null, startOffset + matcher.start("tab"), startOffset + matcher.end("tab"));
                                                                       ^
    method Matcher.start(int) is not applicable
      (actual argument String cannot be converted to int by method invocation conversion)
    method Matcher.start() is not applicable
      (actual and formal argument lists differ in length)
D:\lode\dev\core\scripting\java\com\sun\star\script\framework\provider\beanshell\PlainSourceView.java:189: error: no suitable method found for end(String)
                            ta.replaceRange(null, startOffset + matcher.start("tab"), startOffset + matcher.end("tab"));
                                                                                                           ^
    method Matcher.end(int) is not applicable
      (actual argument String cannot be converted to int by method invocation conversion)
    method Matcher.end() is not applicable
      (actual and formal argument lists differ in length)


the tinderbox log says:

checking the installed JDK... checked (JDK 1.7.0_75)

Patch-set: 3