Update patch set 1
Patch Set 1:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/7159/ : FAILURE

Visual studio complained about error C2440: "return": cannot convert from "std::unique_ptr<SdrView,std::default_delete<_Ty>>" to "SdrView *" in file C:cygwinhometdflodejenkinsworkspacelo_gerritConfigwindows_msc_dbgutil_32swincunodraw.hxx(50) ( https://ci.libreoffice.org/job/gerrit_windows/7066/ )

Patch-set: 1