Update patch set 2
Patch Set 2:

My (x86) Android build with master as of 4be2607af6c474ba2d879a3a84996de0bc1b73b7 currently fails with the following output, which looks like it might be related to this commit. Any chance you could take a look at this?

> Task :compileStrippedUIDebugJavaWithJavac FAILED
warning: [options] source value 6 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
/home/michi/development/git/libreoffice-WORKTREE-for-android-x86/android/source/src/java/org/libreoffice/overlay/CalcHeadersController.java:238: error: incompatible types: long cannot be converted to Float
                headerInfo.rowDimens.add(rowResult.getJSONObject(i).getLong("size"));
                                                                           ^
/home/michi/development/git/libreoffice-WORKTREE-for-android-x86/android/source/src/java/org/libreoffice/overlay/CalcHeadersController.java:243: error: incompatible types: long cannot be converted to Float
                headerInfo.columnDimens.add(columnResult.getJSONObject(i).getLong("size"));
                                                                                 ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
2 errors
2 warnings

FAILURE: Build failed with an exception.

Patch-set: 2