thumbnailview a11y: Drop ThumbnailViewItemAcc::m_aMutex
Use SolarMutexGuard in ThumbnailViewItemAcc::ThumbnailViewItemDestroyed
instead, like in other methods.

This also fixes this build failure I see on Win 11
(due to missing `#include <mutex>`):

    C:\Users\mwegh\development\git\libreoffice\sfx2\source\control\thumbnailviewitemacc.hxx(33): error C2039: 'mutex': is not a member of 'std'
    C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\14.42.34433\Include\sstream(19): note: see declaration of 'std'
    C:\Users\mwegh\development\git\libreoffice\sfx2\source\control\thumbnailviewitemacc.hxx(33): error C3646: 'maMutex': unknown override specifier
    C:\Users\mwegh\development\git\libreoffice\sfx2\source\control\thumbnailviewitemacc.hxx(33): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

Change-Id: I783c42759df6305038d0901d35d81146084bb3ae
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/182346
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins