Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/117770/ : FAILURE

error: externally available entity "ChildDescriptorLess" is not previously declared in an included file (if it is only used in this translation unit, put it in an unnamed namespace; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/svx/source/accessibility/ChildrenManagerImpl.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/116605/ )

clang plugin external did trigger. externally available entity "ChildDescriptorLess" is not previously declared in an included file (if it is only used in this translation unit, put it in an unnamed namespace; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/116605/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1, e583c5c8fb06ba209303a4706cfa50a4ba04ddde
Attention: {"person_ident":"Gerrit User 1000083 \u003c1000083@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}