canvas: error C2397: conversion from 'size_t' to 'BYTE' requires ...
a narrowing conversion (at least other people's MSVC says so, mine
doesn't complain)

(cherry picked from commit f2d039f67743c7588df5cfd725915627b6efb0ba)

Conflicts:
	canvas/source/directx/dx_canvasbitmap.cxx
	(unrelated en passant fix in 8fe0733b45c161a36fc92da488f9bf72ebfd3bbb)

Change-Id: Ic87da76567778884b81361067075fd9325e2d276