Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/108294/ : FAILURE

error "unused function "acquire" [-Werror,-Wunused-function]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sal/rtl/strimp.hxx:104:6 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/107998/ )

error: unused function "acquire" [-Werror,-Wunused-function] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sal/rtl/strimp.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/107998/ )

Patch-set: 6
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1