uitest: blind fix for UITest_writer_tests7 failed
Traceback (most recent call last):
  File "/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/uitest/writer_tests7/forms.py", line 76, in test_tdf140239
    self.assertEqual("true", get_state_as_dict(xURL)['Enabled'])
AssertionError: 'true' != 'false'
- true
+ false

Change-Id: I535f1dd5d755b5896faa55651f5a1ff6c58cec4b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/125814
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
(cherry picked from commit 89f64b9f0dcdc27fdc6827b5aca42af1b38ede25)