Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/17569/ : FAILURE

error "struct "XWindow" was previously declared as a class [-Werror,-Wmismatched-tags]" triggered in included file ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/18217/ )

error: struct "XWindow" was previously declared as a class [-Werror,-Wmismatched-tags] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/dbaccess/source/ui/inc/UITools.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/18217/ )

Patch-set: 1
Label: Verified=-1