Update patch set 6
Patch Set 6: Code-Review-1

* Empty document color crashes with 
Error: attempt to subscript container with out-of-bounds index 10, but 
container only holds 10 elements.

Objects involved in the operation:
    sequence "this" @ 0x0x42fdf10 {
      type = std::__debug::vector<std::unique_ptr<Palette, std::default_delete<Palette> >, std::allocator<std::unique_ptr<Palette, std::default_delete<Palette> > > >;
    }
* it crashes also when there are colors set, and shown properly in the sidebar's color picker
* the 'user.soc' palette isn't filled immediately (only after reopening the dialog)
* user colors are nice but way too small; and exceed the palette width at max shown count (at best make it square, also the colors from the palette)
* Proposed name only counts "Color*" (having "Color 1" and "Test 1" inserts "Color 2" -> shouldn't it be "Color 3"?)
* Button Pick is not similar to Modify; better have a disabled Modify there and Pick below the inputs where it is effective)
* Buttons are not similarly sized to other sections (gradients and hatchings are okay)
* Width of palette differs from gradient/hatching preset
* New color is taken as Origin after switching the section, though it isn't applied
* user colors are not adopted as recent colors in sidebar color picker (users will expect that; disable recent colors?)
* once the user palette is chosen in solide colors it is used in every color dropdown
* new preview has not the same size as active
* tools > options > color has today an option to modify and delete the chosen color which is missing in the new version

Screenshots: http://postimg.org/gallery/10kjhibyw/

Patch-set: 6
Label: Code-Review=-1