Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/69074/ : FAILURE

error: variable is only used as rvalue, should be const [loplugin:conststringvar] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/libreofficekit/source/gtk/lokdocview.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/71441/ )

clang plugin conststringvar did trigger. variable is only used as rvalue, should be const ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/71441/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1