Update patch set 9
Patch Set 9: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/41098/ : FAILURE

Visual studio complained about error C2440: "static_cast": cannot convert from "o3tl::is_typed_flags<SfxSlotMode,20891436>::Wrap" to "sal_Int32" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/framework/source/dispatch/dispatchinformationprovider.cxx(78) ( https://ci.libreoffice.org/job/gerrit_windows/47618/ )

Patch-set: 9
Label: Verified=-1