error: missing binary operator before token '('
(cherry picked from commit 3928a1514c9202a52d698570022c197ecc8703eb)

Change-Id: Ieafb13245a11347cbda8a33e49ad618bf85d8a89