external/zxing: Silence MSVC 2022 error C3781
> workdir\UnpackedTarball\zxing\core\src\Generator.h(20): error C3781: Generator<ZXing::DetectorResult>::promise_type: a coroutine's promise must declare either 'return_value' or 'return_void'

seen at least when building with --with-latest-c++ against VS 2022 17.5.0
Preview 1.0

Change-Id: Ie69100d87e6cb85526d772e8f0f5d11e1f9d6704
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/143853
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit e2d3baf0db4dec6b7b00192c41700611bd1d147c)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/143865
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>