Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/13023/ : FAILURE

Visual studio complained about error C2440: "=": cannot convert from "void *(__cdecl *)(sal_Size)" to "rtl_allocateStringFn" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sal/rtl/strimp.cxx(101) ( https://ci.libreoffice.org/job/gerrit_windows/14345/ )

Patch-set: 5
Label: Verified=-1