Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3:
> > 
> > > Patch Set 3:
> > >
> > > i meant to merge the changes together  , I did that amend yesterday and it made a new patch i could make it again if you want
> > 
> > It will not make a new patch, if you just follow what the wiki instructions tell you. Pay attention to the Change-Id: line in the commit message. When it matches what you have here in Gerrit, it will submit a new patchset into the same Gerrit patch.
> 
> I made it with the same change id and it said that error :
>   ! [remote rejected]           HEAD -> refs/for/master%topic=assert0 (same Change-Id in multiple changes.
> Squash the commits with the same Change-Id or ensure Change-Ids are unique for each commit)
> error: failed to push some refs to 'ssh://logerrit/core'

Ok, let's go through it one more time. Here's what I do:

git checkout master
git checkout -b asserts
git fetch "ssh://ilmari-lauhakangas@gerrit.libreoffice.org:29418/core" refs/changes/98/113898/3 && git cherry-pick FETCH_HEAD
I edit the file.
git add sc/qa/extras/macros-test.cxx
git commit --amend

Now, at this point, there is no need for you to manually touch the change-id in the message editor, just confirm that it is the same Ibabb1775ea86a6dd548ee718ed1dede6ffc60be9 as in this patch. Just save the commit message without changing anything.

To me, it sounds like you were creating an additional commit instead of amending the same one.

Patch-set: 3