Revert "tdf#158068: Replace with static constexpr O(U)String"
This reverts commit 817cb41005db87c9bdd63663e5d1d1357d6e5cbc, as it causes

> desktop/source/app/crashreport.cxx:197:26: error: view pointing into temporary i.e. dangling [loplugin:stringviewdangle]
>   197 |         aCommandSeperator=u","_ustr;
>       |         ~~~~~~~~~~~~~~~~~^~~~~~~~~~

Change-Id: I787e4997c536f8bb37973da33c9ca1d660f2698c
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/182993
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>