Update patch set 10
Patch Set 10: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/68582/ : FAILURE

error: ParmVarDecl, use "tools::Long" instead of "long" [loplugin:toolslong] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/qa/extras/scannotationsobj.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70974/ )

clang plugin toolslong did trigger. ParmVarDecl, use "tools::Long" instead of "long" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70974/ )

Patch-set: 10
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1