Update patch set 3
Patch Set 3: Verified-1

so if i interpret the following concise and clear error correctly, this patch runs into the problem that MSVC's std::bind creates a function object that cannot be invoked if it is "const".

the reason is quite obvious from the error so i won't waste space with explaining it and leave that as an exercise for the reader.

i've run into this before and used lambdas in such cases, which oddly enough seem to work even with MSVC.

the alternative is probably to patch boost::spirit to remove the "const" on the function object variables in question - should be rather trivial to do i hope.


C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/scanner/scanner.hpp(148) : error C3848: expression having type 'const std::_Bind<true,void,std::_Pmf_wrap<void (__thiscall PDFGrammar<const char *>::* )(iteratorT,iteratorT),void,PDFGrammar<iteratorT>,iteratorT,iteratorT>,PDFGrammar<iteratorT> *&,std::_Ph<1> &,std::_Ph<2> &>' would lose some const-volatile qualifiers in order to call 'void std::_Bind<true,void,std::_Pmf_wrap<void (__thiscall PDFGrammar<const char *>::* )(iteratorT,iteratorT),void,PDFGrammar<iteratorT>,iteratorT,iteratorT>,PDFGrammar<iteratorT> *&,std::_Ph<1> &,std::_Ph<2> &>::operator ()<const IteratorT&,const IteratorT&>(const IteratorT &,const IteratorT &)'
with
[
iteratorT=const char *
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/scanner/scanner.hpp(163) : see reference to function template instantiation 'void boost::spirit::attributed_action_policy<boost::spirit::nil_t>::call<ActorT,IteratorT>(const ActorT &,boost::spirit::nil_t,const IteratorT &,const IteratorT &)' being compiled
with
[
ActorT=std::_Bind<true,void,std::_Pmf_wrap<void (__thiscall PDFGrammar<const char *>::* )(const char *,const char *),void,PDFGrammar<const char *>,const char *,const char *>,PDFGrammar<const char *> *&,std::_Ph<1> &,std::_Ph<2> &>
,            IteratorT=iterator_t
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/composite/actions.hpp(116) : see reference to function template instantiation 'void boost::spirit::action_policy::do_action<ActionT,boost::spirit::match<boost::spirit::nil_t>::return_t,iterator_t>(const ActorT &,AttrT &,const IteratorT &,const IteratorT &) const' being compiled
with
[
ActionT=std::_Bind<true,void,std::_Pmf_wrap<void (__thiscall PDFGrammar<const char *>::* )(const char *,const char *),void,PDFGrammar<const char *>,const char *,const char *>,PDFGrammar<const char *> *&,std::_Ph<1> &,std::_Ph<2> &>
,            ActorT=std::_Bind<true,void,std::_Pmf_wrap<void (__thiscall PDFGrammar<const char *>::* )(const char *,const char *),void,PDFGrammar<const char *>,const char *,const char *>,PDFGrammar<const char *> *&,std::_Ph<1> &,std::_Ph<2> &>
,            AttrT=boost::spirit::match<boost::spirit::nil_t>::return_t
,            IteratorT=iterator_t
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/non_terminal/impl/rule.ipp(240) : see reference to function template instantiation 'boost::spirit::match<boost::spirit::nil_t> boost::spirit::action<DerivedT,std::_Bind<true,void,std::_Pmf_wrap<void (__thiscall PDFGrammar<const char *>::* )(iteratorT,iteratorT),void,PDFGrammar<iteratorT>,iteratorT,iteratorT>,PDFGrammar<iteratorT> *&,std::_Ph<1> &,std::_Ph<2> &>>::parse<ScannerT>(const ScannerT &) const' being compiled
with
[
DerivedT=boost::spirit::alternative<boost::spirit::strlit<const char *>,boost::spirit::strlit<const char *>>
,            iteratorT=const char *
,            ScannerT=boost::spirit::scanner<const char *,boost::spirit::scanner_policies_t>
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/non_terminal/impl/rule.ipp(240) : see reference to function template instantiation 'boost::spirit::match<boost::spirit::nil_t> boost::spirit::action<DerivedT,std::_Bind<true,void,std::_Pmf_wrap<void (__thiscall PDFGrammar<const char *>::* )(iteratorT,iteratorT),void,PDFGrammar<iteratorT>,iteratorT,iteratorT>,PDFGrammar<iteratorT> *&,std::_Ph<1> &,std::_Ph<2> &>>::parse<ScannerT>(const ScannerT &) const' being compiled
with
[
DerivedT=boost::spirit::alternative<boost::spirit::strlit<const char *>,boost::spirit::strlit<const char *>>
,            iteratorT=const char *
,            ScannerT=boost::spirit::scanner<const char *,boost::spirit::scanner_policies_t>
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/non_terminal/impl/rule.ipp(239) : while compiling class template member function 'boost::spirit::match<boost::spirit::nil_t> boost::spirit::impl::concrete_parser<ParserT,boost::spirit::scanner<const char *,boost::spirit::scanner_policies_t>,boost::spirit::nil_t>::do_parse_virtual(const ScannerT &) const'
with
[
ParserT=boost::spirit::action<boost::spirit::alternative<boost::spirit::strlit<const char *>,boost::spirit::strlit<const char *>>,std::_Bind<true,void,std::_Pmf_wrap<void (__thiscall PDFGrammar<const char *>::* )(const char *,const char *),void,PDFGrammar<const char *>,const char *,const char *>,PDFGrammar<const char *> *&,std::_Ph<1> &,std::_Ph<2> &>>
,            ScannerT=boost::spirit::scanner<const char *,boost::spirit::scanner_policies_t>
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/non_terminal/rule.hpp(137) : see reference to class template instantiation 'boost::spirit::impl::concrete_parser<ParserT,boost::spirit::scanner<const char *,boost::spirit::scanner_policies_t>,boost::spirit::nil_t>' being compiled
with
[
ParserT=boost::spirit::action<boost::spirit::alternative<boost::spirit::strlit<const char *>,boost::spirit::strlit<const char *>>,std::_Bind<true,void,std::_Pmf_wrap<void (__thiscall PDFGrammar<const char *>::* )(const char *,const char *),void,PDFGrammar<const char *>,const char *,const char *>,PDFGrammar<const char *> *&,std::_Ph<1> &,std::_Ph<2> &>>
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/sdext/source/pdfimport/pdfparse/pdfparse.cxx(141) : see reference to function template instantiation 'boost::spirit::rule<ScannerT,boost::spirit::nil_t,boost::spirit::nil_t> &boost::spirit::rule<ScannerT,boost::spirit::nil_t,boost::spirit::nil_t>::operator =<boost::spirit::action<DerivedT,std::_Bind<true,void,std::_Pmf_wrap<void (__thiscall PDFGrammar<const char *>::* )(iteratorT,iteratorT),void,PDFGrammar<iteratorT>,iteratorT,iteratorT>,PDFGrammar<iteratorT> *&,std::_Ph<1> &,std::_Ph<2> &>>>(const ParserT &)' being compiled
with
[
ScannerT=scanner_t
,            DerivedT=boost::spirit::alternative<boost::spirit::strlit<const char *>,boost::spirit::strlit<const char *>>
,            iteratorT=const char *
,            ParserT=boost::spirit::action<boost::spirit::alternative<boost::spirit::strlit<const char *>,boost::spirit::strlit<const char *>>,std::_Bind<true,void,std::_Pmf_wrap<void (__thiscall PDFGrammar<const char *>::* )(const char *,const char *),void,PDFGrammar<const char *>,const char *,const char *>,PDFGrammar<const char *> *&,std::_Ph<1> &,std::_Ph<2> &>>
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/sdext/source/pdfimport/pdfparse/pdfparse.cxx(141) : see reference to function template instantiation 'boost::spirit::rule<ScannerT,boost::spirit::nil_t,boost::spirit::nil_t> &boost::spirit::rule<ScannerT,boost::spirit::nil_t,boost::spirit::nil_t>::operator =<boost::spirit::action<DerivedT,std::_Bind<true,void,std::_Pmf_wrap<void (__thiscall PDFGrammar<const char *>::* )(iteratorT,iteratorT),void,PDFGrammar<iteratorT>,iteratorT,iteratorT>,PDFGrammar<iteratorT> *&,std::_Ph<1> &,std::_Ph<2> &>>>(const ParserT &)' being compiled
with
[
ScannerT=scanner_t
,            DerivedT=boost::spirit::alternative<boost::spirit::strlit<const char *>,boost::spirit::strlit<const char *>>
,            iteratorT=const char *
,            ParserT=boost::spirit::action<boost::spirit::alternative<boost::spirit::strlit<const char *>,boost::spirit::strlit<const char *>>,std::_Bind<true,void,std::_Pmf_wrap<void (__thiscall PDFGrammar<const char *>::* )(const char *,const char *),void,PDFGrammar<const char *>,const char *,const char *>,PDFGrammar<const char *> *&,std::_Ph<1> &,std::_Ph<2> &>>
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/sdext/source/pdfimport/pdfparse/pdfparse.cxx(133) : while compiling class template member function 'PDFGrammar<const char *>::definition<ScannerT>::definition(const PDFGrammar<const char *> &)'
with
[
ScannerT=scanner_t
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/non_terminal/impl/grammar.ipp(165) : see reference to function template instantiation 'PDFGrammar<const char *>::definition<ScannerT>::definition(const PDFGrammar<const char *> &)' being compiled
with
[
ScannerT=scanner_t
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/non_terminal/impl/grammar.ipp(260) : see reference to class template instantiation 'PDFGrammar<const char *>::definition<ScannerT>' being compiled
with
[
ScannerT=scanner_t
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/non_terminal/impl/grammar.ipp(279) : see reference to function template instantiation 'void boost::spirit::impl::call_helper<0>::do_<result_t,definition_t,ScannerT>(RT &,DefinitionT &,const ScannerT &)' being compiled
with
[
ScannerT=scanner_t
,            RT=result_t
,            DefinitionT=definition_t
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/non_terminal/grammar.hpp(55) : see reference to function template instantiation 'boost::spirit::match<boost::spirit::nil_t> boost::spirit::impl::grammar_parser_parse<0,PDFGrammar<const char *>,boost::spirit::parser_context<boost::spirit::nil_t>,ScannerT>(const boost::spirit::grammar<PDFGrammar<const char *>,boost::spirit::parser_context<boost::spirit::nil_t>> *,const ScannerT &)' being compiled
with
[
ScannerT=scanner_t
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/non_terminal/grammar.hpp(65) : see reference to function template instantiation 'boost::spirit::match<boost::spirit::nil_t> boost::spirit::grammar<PDFGrammar<const char *>,boost::spirit::parser_context<boost::spirit::nil_t>>::parse_main<ScannerT>(const ScannerT &) const' being compiled
with
[
ScannerT=scanner_t
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/non_terminal/grammar.hpp(65) : see reference to function template instantiation 'boost::spirit::match<boost::spirit::nil_t> boost::spirit::grammar<PDFGrammar<const char *>,boost::spirit::parser_context<boost::spirit::nil_t>>::parse_main<ScannerT>(const ScannerT &) const' being compiled
with
[
ScannerT=scanner_t
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/scanner/impl/skipper.ipp(133) : see reference to function template instantiation 'boost::spirit::match<boost::spirit::nil_t> boost::spirit::grammar<PDFGrammar<const char *>,boost::spirit::parser_context<boost::spirit::nil_t>>::parse<scanner_t>(const ScannerT &) const' being compiled
with
[
ScannerT=scanner_t
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/scanner/impl/skipper.ipp(133) : see reference to function template instantiation 'boost::spirit::match<boost::spirit::nil_t> boost::spirit::grammar<PDFGrammar<const char *>,boost::spirit::parser_context<boost::spirit::nil_t>>::parse<scanner_t>(const ScannerT &) const' being compiled
with
[
ScannerT=scanner_t
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/workdir/UnpackedTarball/boostboost/spirit/home/classic/core/scanner/impl/skipper.ipp(155) : see reference to function template instantiation 'boost::spirit::parse_info<const char *> boost::spirit::impl::phrase_parser<boost::spirit::space_parser>::parse<IteratorT,DerivedT>(const IteratorT &,const IteratorT &,const ParserT &,const boost::spirit::space_parser &)' being compiled
with
[
IteratorT=const char *
,            DerivedT=PDFGrammar<const char *>
,            ParserT=PDFGrammar<const char *>
]
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit_master/Gerrit/Gerrit/Platform/Windows/sdext/source/pdfimport/pdfparse/pdfparse.cxx(556) : see reference to function template instantiation 'boost::spirit::parse_info<const char *> boost::spirit::parse<const char*,DerivedT,boost::spirit::space_parser>(const IteratorT &,const IteratorT &,const boost::spirit::parser<DerivedT> &,const boost::spirit::parser<boost::spirit::space_parser> &)' being compiled
with
[
DerivedT=PDFGrammar<const char *>
,            IteratorT=const char *
]

Patch-set: 3
Reviewer: Gerrit User 1000022 <1000022@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1