Fix build problem under traditional Chinese Windows.
Add bom to sw/inc/strings.hrc to get rid of
"error C2001: newline in constant" caused by '“', '”', '→'.

Change-Id: I25a5da88c0a8f6af6e1a365903d31d032c85813d