Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_feature/166/ : FAILURE

error: no need to explicitly init an instance of "std::unique_ptr<VclBuilder>" with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/window/printdlg.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/17517/ )

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "std::unique_ptr<VclBuilder>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/17517/ )

Patch-set: 2
Label: Verified=-1