Update patch set 10
Patch Set 10: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/110811/ : FAILURE

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "::std::unique_ptr<FileChangedChecker>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/110356/ )

error: no need to explicitly init an instance of "::std::unique_ptr<FileChangedChecker>" with nullptr, just use default constructor [loplugin:simplifyconstruct] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/embeddedobj/source/commonembedding/miscobj.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/110356/ )

Patch-set: 10
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1