Fix presumed | vs. & typos
...introduced in 25e08e4ea0df956f46bd7ef81493fcf5a5c1879c "Resolves: tdf#164920
add scrollbar width to desired size if enabled" and causing

> svx/source/tbxctrls/linectrl.cxx:435:15: error: bitwise or with non-zero value always evaluates to true [-Werror,-Wtautological-bitwise-compare]
>   435 |     if (nBits | WB_VSCROLL)
>       |         ~~~~~~^~~~~~~~~~~~
> svx/source/tbxctrls/linectrl.cxx:576:15: error: bitwise or with non-zero value always evaluates to true [-Werror,-Wtautological-bitwise-compare]
>   576 |     if (nBits | WB_VSCROLL)
>       |         ~~~~~~^~~~~~~~~~~~

Change-Id: I6f77cd30f3b98abb15afb665b336fba13d46ee01
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/192963
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>
(cherry picked from commit ad6e817e38545903f5fbbe11a2dcb033e5affead)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/192968
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
(cherry picked from commit 656a79ed1365851e7f8b0f3dacb29321c0264b6b)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/193021
Reviewed-by: Adolfo Jayme Barrientos <fitojb@ubuntu.com>
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Ilmari Lauhakangas <ilmari.lauhakangas@libreoffice.org>