Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/101055/ : FAILURE

clang plugin badstatics did trigger. bad static variable causes crash on shutdown ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/101449/ )

error: bad static variable causes crash on shutdown [loplugin:badstatics] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/source/window/split.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/101449/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1