curl: upgrade to release 7.86.0
Fixes CVE-2022-32221 which could affect libcmis, CVE-2022-42915,
and 2 more CVEs that probably don't affect LO.

* remove --without-ssl:
  On the one hand, on GNU/Linux this now results in:

    configure: error: --without-ssl has been set together with an explicit option to use an ssl library

  On the other hand, using the more obvious --without-openssl yields a link
  failure on Android on the nss check in configure:

  configure:28220: checking for SSL_VersionRangeSet in -lnss
  /home/cl/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: liblog.so, needed by /home/cl/rpmbuild/BUILD/lo-android2/workdir/UnpackedTarball/nss/dist/out/lib/libnss3.so, not found (try using -rpath or -rpath-link)
  /home/cl/rpmbuild/BUILD/lo-android2/workdir/UnpackedTarball/nss/dist/out/lib/libnspr4.so: undefined reference to `__android_log_write'
  /home/cl/rpmbuild/BUILD/lo-android2/workdir/UnpackedTarball/nss/dist/out/lib/libnspr4.so: undefined reference to `__android_log_assert'

  ... so add the -llog for android in curl-nss.patch.1

Reviewed-on: https://gerrit.libreoffice.org/c/core/+/141866
Tested-by: Jenkins
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>
(cherry picked from commit a76a88203d8508f38b10d9bbb94c3bba2485fcaf)

Change-Id: I3931a1eec2d681c2ce0e5695039492772e9fcc81

Conflicts:
	download.lst
	external/curl/curl-nss.patch.1