sd: fix -Werror=sign-compare
	sd/source/core/drawdoc2.cxx: In member function ‘bool SdDrawDocument::ValidateCanvasPage(const SdPage*) const’:
	sd/source/core/drawdoc2.cxx:1491:32: error: comparison of integer expressions of different signedness: ‘std::__cxx1998::unordered_set<SdrPage*, std::hash<SdrPage*>, std::equal_to<SdrPage*>, std::allocator<SdrPage*> >::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
	 1491 |     if (aPreviewPageSet.size() != GetSdPageCount(PageKind::Standard) - 1)
	      |         ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Seen with GCC 12.3.0.

Change-Id: I34a6e93faa68a503eeaab943ef08d7023ab81851
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/194410
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
(cherry picked from commit b72e4e938c81b71b4aeb47aa677d84c26709e1b2)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/197199
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>