Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://cpci.cbg.collabora.co.uk:8080/job/Gerrit%20for%20cp-6.2/2949/ : FAILURE

Visual studio complained about error C2953: "_CrtEnableIf<true,_Ty>": class template has already been defined in file C:\PROGRA~2\WINDOW~3\10\Include\10.0.19041.0\ucrt\corecrt.h(208) ( https://cpci.cbg.collabora.co.uk:8080/job/gerrit_windows_cp-6.2_32bit/2460/ )

Patch-set: 1
Tag: autogenerated:jenkins-gerrit-trigger
Reviewer: Gerrit User 1002181 <1002181@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1