Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/32083/ : FAILURE

error "static_assert failed due to requirement "__check_hash_requirements<const SdrPage *, CacheEntry>::value" "the specified hash does not meet the Hash requirements"" triggered in included file /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:868:5 ( https://ci.libreoffice.org/job/gerrit_mac/34496/ )

error: no template named "unordered_map" in namespace "std"; did you mean "unordered_set"? in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sd/source/ui/slidesorter/cache/SlsBitmapCache.cxx ( https://ci.libreoffice.org/job/gerrit_mac/34496/ )

Patch-set: 1
Label: Verified=-1