Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/109415/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "sal_uInt16" to "TypedWhichId<SvxFontItem>" in file C:/cygwin64/home/tdf/lode/jenkins/workspace/gerrit_windows/sw/source/filter/ww8/wrtw8nds.cxx(406) ( https://ci.libreoffice.org/job/gerrit_windows/121343/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000013 \u003c1000013@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}