no matching function for call to 'intrusive_ptr_add_ref'
...with clang-cl, in instantiation of member function
'boost::intrusive_ptr<const ScMatrix>::intrusive_ptr' requested at
sc/inc/token.hxx(291,20):
class SC_DLLPUBLIC ScMatrixCellResultToken : public formula::FormulaToken

since commit fd3fc84e590fc84f62ce3bace668fe40a25f54b5
    clang-tidy modernize-use-equals-default in sc/source/core/tool

Change-Id: I5b48cf7e9f830ec411202c5364d0caac76449095