Update patch set 3
Patch Set 3:

> > ah! that should make the test run, at the cost of making the test
 > > useless in predicting whether it works in the actual build.
 > 
 > And again I don't know what you mean. With fixed Icecream, it will
 > detect everything properly, just the compile won't be done
 > remotely.

i mean that if you build the CompilerTest always locally, then you don't know if the same warnings would be generated if you had built it remotely, as would likely happen in the case of an actual cxx file.

 > > > > * the already mentioned problem that this doesn't work:
 > > > > compiler.getSourceManager().getFileEntryForID(
 > > > > compiler.getSourceManager().getMainFileID())
 > > >
 > > > I don't understand, what is the problem?
 > >
 > > i forgot to paste the "->getName()" at the end...
 > >
 > > the whitelisting based on the return value of that call doesn't
 > > work, e.g.:
 > >
 > > opencl/source/openclwrapper.cxx:524:11: error: expression always
 > > evaluates to zero, lhs=0 rhs=unknown [loplugin:expressionalwayszero]
 > >
 > > presumably the return value is <stdin> though i havent checked
 > it.
 > 
 > And yet again I don't know what you mean. Isn't this patch supposed
 > to handle this kind of problems?

well i discovered that this problem exists only after i finished the first version of this patch, so it doesn't :)

the checks that use getMainFileID are relatively rarely used compared to the ones that are fixed in this patch; iirc the first one is hit about 10 min. into the build.

Patch-set: 3