[do not submit] test
Jenkins should fail with

self.assertEqual(get_state_as_dict(xWriterEdit)["CurrentPage"], "4")
AssertionError: '2' != '4'
- 2
+ 4

and not aborted silently

At least, I think this is what happened with
647958099600923d9ba3a57101891f62de326f4b, which was later
reverted in 5872f0c0d206466ad78e92be3d7d551b7ff4dbf1

Change-Id: Icc9a6f46a792c20798f09dbcf00dc2d71719434c