Update patch set 5
Patch Set 5: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/99328/ : FAILURE

Visual studio complained about error C2398: Element "2": conversion from "const sal_Int32" to "o3tl::span<const tools::Long>::size_type" requires a narrowing conversion in file C:/cygwin/home/tdf/jenkins/workspace/gerrit_windows/canvas/source/directx/dx_textlayout_drawhelper.cxx(216) ( https://ci.libreoffice.org/job/gerrit_windows/110361/ )

Patch-set: 5
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1