Update patch set 1
Patch Set 1:

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/36631/ : FAILURE

error: externally available entity "decimalStringToNumber" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/comphelper/source/misc/string.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/39412/ )

clang plugin external did trigger. externally available entity "decimalStringToNumber" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/39412/ )

Patch-set: 1