Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/39046/ : FAILURE

error "virtual function "createPage" has a different return type ("VclPtr<TabPage>") than the function it overrides (which has return type "std::unique_ptr<BuilderPage>")" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/svtools/source/uno/wizard/wizardshell.hxx:56:33 ( https://ci.libreoffice.org/job/gerrit_mac/42294/ )

error: virtual function "createPage" has a different return type ("VclPtr<TabPage>") than the function it overrides (which has return type "std::unique_ptr<BuilderPage>") in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/svtools/source/uno/wizard/wizardshell.hxx ( https://ci.libreoffice.org/job/gerrit_mac/42294/ )

Patch-set: 7
Label: Verified=-1