Update patch set 2
Change has been successfully cherry-picked as 2ea32dcffd41c985cb33f107fda16d2eafcece14 by Stephan Bergmann

Patch-set: 2
Subject: Fix MSVC 2019 16.8.3 --with-latest-c++ error C2102: '&' requires l-value
Status: merged
Commit: 2ea32dcffd41c985cb33f107fda16d2eafcece14
Tag: autogenerated:gerrit:merged
Groups: 3ad82207d8ce25b76489a0176464052075c5de0a
Label: Verified=+1 Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Code-Review=+2
Label: SUBM=+1
Submission-id: 108837
Submitted-with: OK
Submitted-with: OK: Code-Review: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>
Submitted-with: OK: Verified: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>