Update patch set 12
Patch Set 12: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/92733/ : FAILURE

error: explicit cast from "sal_Int32" (aka "int") to "size_t" (aka "unsigned long") (of larger rank) in comparison against "sal_uInt32" (aka "unsigned int"): if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast [loplugin:unsignedcompare] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/basic/source/classes/image.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/93685/ )

clang plugin unsignedcompare did trigger. explicit cast from "sal_Int32" (aka "int") to "size_t" (aka "unsigned long") (of larger rank) in comparison against "sal_uInt32" (aka "unsigned int"): if the cast value is known to be non-negative, use o3tl::make_unsigned instead of the cast ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/93685/ )

Patch-set: 12
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1