Update patch set 2
Patch Set 2:

Unfortunately this broke an --enable-werror build that uses a recent tool-chain:

sw/qa/extras/ooxmlimport/ooxmlimport.cxx:1858:38: error: 'userSpaceScaleFactor' is deprecated: first deprecated in OS X 10.7 - Use -convertRectToBacking: or -backingScaleFactor instead [-Werror,-Wdeprecated-declarations]

Patch-set: 2
Reviewer: Gerrit User 1000062 <1000062@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0