Fix UBSan build's RTTI needs
...after 3ba92b5f1eaf7d4447a0943ea260db515ca799dc "hide more symbols" had caused
CppunitTest_desktop_lib to fail with

> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_desktop_lib.so
> workdir/LinkTarget/CppunitTest/libtest_desktop_lib.so: undefined symbol: _ZTIN7desktop20CallbackFlushHandlerE"

Change-Id: I051e1a233757a6ccb7cf9ea564ab6b510d6df571
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/163742
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>