Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_70/1813/ : FAILURE

likely caused by leftovers that linger around from an aborted build ( https://ci.libreoffice.org/job/gerrit_windows/90951/ )

Visual studio complained about error C2855: command-line option "/Zc:referenceBinding" inconsistent with precompiled header in file C:/cygwin64/home/tdf/lode/jenkins/workspace/gerrit_windows/sal/osl/all/signalshared.cxx ( https://ci.libreoffice.org/job/gerrit_windows/90951/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1