Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/17905/ : FAILURE

error: in LIBO_INTERNAL_ONLY code, replace literal cast to "sal_Unicode" (aka "char16_t") with a u"..." char16_t character literal [loplugin:salunicodeliteral] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/cui/source/options/optjava.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/18554/ )

use default type instead of indirection ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/18554/ )

clang plugin salunicodeliteral did trigger. in LIBO_INTERNAL_ONLY code, replace literal cast to "sal_Unicode" (aka "char16_t") with a u"..." char16_t character literal ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/18554/ )

Patch-set: 2
Label: Verified=-1