Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/108686/ : FAILURE

error "static_assert failed due to requirement "integral_constant<bool, false>::value" "the specified hash does not meet the Hash requirements"" triggered in included file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/__hash_table:872:5 ( https://ci.libreoffice.org/job/gerrit_mac/113827/ )

error: no template named "unordered_map" in namespace "std"; did you mean "unordered_set"? in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/sfx2/source/dialog/StyleList.cxx ( https://ci.libreoffice.org/job/gerrit_mac/113827/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000446 \u003c1000446@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}