Update patch set 13
Patch Set 13: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_feature/105/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "const char *" to "rtl::OUString" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/vcl/source/window/printdlg.cxx(739) ( https://ci.libreoffice.org/job/gerrit_windows/11098/ )

Patch-set: 13
Label: Verified=-1