Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_feature/234/ : FAILURE

error ""setChartStyle" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/chart2/source/inc/OPropertySet.hxx:206:27 ( https://ci.libreoffice.org/job/gerrit_mac/39236/ )

error: "setChartStyle" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/chart2/source/inc/OPropertySet.hxx ( https://ci.libreoffice.org/job/gerrit_mac/39236/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1