Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master_android/494/ : FAILURE

the build failed because of an issue with the bot itself, not with the code.
The Bot failed to checkout the source ( https://ci.libreoffice.org/job/gerrit_android_aarch64/95/ )

https://ci.libreoffice.org/job/gerrit_master/67989/ : FAILURE

error "SAL_CALL unnecessary here [loplugin:salcall]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/include/xmloff/xmlimp.hxx:306:18 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70407/ )

clang plugin salcall did trigger. SAL_CALL unnecessary here ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70407/ )

error: SAL_CALL unnecessary here [loplugin:salcall] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/xmloff/source/core/xmlimp.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/70407/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1