New Clang 21 trunk -Werror,-Wunnecessary-virtual-specifier
...warning about non-overriding virtual dtors in final classes.  Every single
one of these might or might not be suspicious (e.g., in some cases it might be
better to have a virtual dtor in a derived-from class).  Also, for some of the
virtual dtors, making them non-virtual then caused

> error: unnecessary user-declared destructor [loplugin:unnecessaryoverride]

so those were removed completely.

Change-Id: If0ee71645a347d6096b65988c56f627c42fe54b2
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/185223
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
(cherry picked from commit 887804deb541a9a4d14cdafd7eff8f2df35a8cdc)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/187543
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>