Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/109897/ : FAILURE

Visual studio complained about error C2440: "<function-style-cast>": cannot convert from "initializer list" to "oox::xls::Color" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/sc/source/filter/oox/SparklineFragment.cxx(29) ( https://ci.libreoffice.org/job/gerrit_windows/121906/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1
Attention: {"person_ident":"Gerrit User 1000154 \u003c1000154@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}