Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/21812/ : FAILURE

error "lvalue required as left operand of assignment" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sw/source/filter/ww8/ww8scan.hxx:1149:22 ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/22547/ )

error: lvalue required as left operand of assignment in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sw/source/filter/ww8/ww8scan.hxx ( https://ci.libreoffice.org/job/gerrit_linux_gcc_release/22547/ )

Patch-set: 1
Label: Verified=-1