workaround for kCTForegroundColorFromContextAttributeName unavailability
fixes "error: ‘kCTForegroundColorFromContextAttributeName’ was not declared in this scope"

see commits:
  5bc5387669bca8a0b410e295b0992fd2424a1536

Change-Id: Ifdf69ab2f9a6437d18a6d3e3f5d756beeed3ba5c
Reviewed-on: https://gerrit.libreoffice.org/9758
Reviewed-by: Noel Grandin <noelgrandin@gmail.com>
Reviewed-by: Caolán McNamara <caolanm@redhat.com>
Tested-by: Caolán McNamara <caolanm@redhat.com>
(cherry picked from commit 4af1b789545bc3815f79fafed5b1806b3c08b69d)