Fix no-pch Windows build: missing include
> In file included from C:/lo/src/build/workdir/UnpackedTarball/skia/tools/sk_app/win/VulkanWindowContext_win.cpp:9:
> C:/lo/src/build/workdir/UnpackedTarball/skia\tools/sk_app/win/WindowContextFactory_win.h(23,1): error: unknown type name 'SK_API'
> SK_API std::unique_ptr<WindowContext> MakeVulkanForWin(HWND, const DisplayParams&);
> ...

Change-Id: I7f88cbb005310dd586e53b262ce31a71d49faedc
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/146121
Tested-by: Mike Kaganski <mike.kaganski@collabora.com>
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>