gtk3 a11y: Use sal_Int32 consistently to fix i386 build
... after

    commit 3b7db802731826b6cc3b55100470b0c61c1f2dfa
    Date:   Thu May 4 10:06:14 2023 +0200

        tdf#105404 [API CHANGE] add index to accessiblity change event

Reported to fail like this:

    /home/rene/LibreOffice/git/libreoffice-7-6/vcl/unx/gtk3/a11y/atklistener.cxx:164:6: error: no declaration matches 'void AtkListener::handleChildAdded(const com::sun::star::uno::Reference<com::sun::star::accessibility::XAccessibleContext>&, const com::sun::star::uno::Reference<com::sun::star::accessibility::XAccessible>&, sal_Int32)'
      164 | void AtkListener::handleChildAdded(
          |      ^~~~~~~~~~~
    In file included from /home/rene/LibreOffice/git/libreoffice-7-6/vcl/unx/gtk3/a11y/atklistener.cxx:29:
    /home/rene/LibreOffice/git/libreoffice-7-6/vcl/unx/gtk3/a11y/atklistener.hxx:54:10: note: candidate is: 'void AtkListener::handleChildAdded(const com::sun::star::uno::Reference<com::sun::star::accessibility::XAccessibleContext>&, const com::sun::star::uno::Reference<com::sun::star::accessibility::XAccessible>&, int)'
       54 |     void handleChildAdded(
          |          ^~~~~~~~~~~~~~~~

Change-Id: I03caa5480ef133091ccd5c9ae682629cec3a789b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/154190
Tested-by: René Engelhard <rene@debian.org>
Reviewed-by: René Engelhard <rene@debian.org>
Tested-by: Jenkins