Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/92080/ : FAILURE

Visual studio complained about error C2440: "=": cannot convert from "const unsigned char *" to "Bytef *" in file C:/cygwin/home/tdf/jenkins/workspace/gerrit_windows/package/source/zipapi/Deflater.cxx(74) ( https://ci.libreoffice.org/job/gerrit_windows/102921/ )

Patch-set: 3
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1