sfx2: fix gcc dbgutil -Werror=unused-variable
/home/vmiklos/git/libreoffice/master/sfx2/source/appl/workwin.cxx: In member function ‘void SfxWorkWindow::ToggleChildWindow_Impl(sal_uInt16, bool)’:
/home/vmiklos/git/libreoffice/master/sfx2/source/appl/workwin.cxx:1861:27: error: unused variable ‘pCW’ [-Werror=unused-variable]
 1861 |     if (SfxChildWin_Impl* pCW = Get_BySaveId(aChildWins, nId))
      |                           ^~~
/home/vmiklos/git/libreoffice/master/sfx2/source/appl/workwin.cxx: In member function ‘void SfxWorkWindow::ShowChildWindow_Impl(sal_uInt16, bool, bool)’:
/home/vmiklos/git/libreoffice/master/sfx2/source/appl/workwin.cxx:1990:27: error: unused variable ‘pCW’ [-Werror=unused-variable]
 1990 |     if (SfxChildWin_Impl* pCW = Get_BySaveId(aChildWins, nId))
      |                           ^~~

Change-Id: Iecc60032459ca8a6543f3836f17b76b25939cda9
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/157516
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>
Tested-by: Jenkins