fix build with system-libjxl
/usr/bin/x86_64-linux-gnu-ld.bfd: /home/rene/LibreOffice/git/master/workdir/CxxObject/vcl/source/filter/jxl/reader.o: in function `readJxl(SvStream&, Graphic&)':
/usr/include/jxl/resizable_parallel_runner_cxx.h:60:(.text+0x3f): undefined reference to `JxlResizableParallelRunnerCreate'
/usr/bin/x86_64-linux-gnu-ld.bfd: /home/rene/LibreOffice/git/master/workdir/CxxObject/vcl/source/filter/jxl/reader.o: in function `JxlResizableParallelRunnerDestroyStruct::operator()(void*)':
/usr/include/jxl/resizable_parallel_runner_cxx.h:34:(.text+0x87): undefined reference to `JxlResizableParallelRunnerDestroy'
/usr/bin/x86_64-linux-gnu-ld.bfd: /home/rene/LibreOffice/git/master/workdir/CxxObject/vcl/source/filter/jxl/reader.o: in function `readJxl(SvStream&, Graphic&)':
././vcl/source/filter/jxl/reader.cxx:56:(.text+0xe3): undefined reference to `JxlResizableParallelRunner'
/usr/bin/x86_64-linux-gnu-ld.bfd: /home/rene/LibreOffice/git/master/workdir/CxxObject/vcl/source/filter/jxl/reader.o: in function `JxlResizableParallelRunnerDestroyStruct::operator()(void*)':
/usr/include/jxl/resizable_parallel_runner_cxx.h:34:(.text+0x199): undefined reference to `JxlResizableParallelRunnerDestroy'
/usr/bin/x86_64-linux-gnu-ld.bfd: /home/rene/LibreOffice/git/master/workdir/CxxObject/vcl/source/filter/jxl/reader.o: in function `readJxl(SvStream&, Graphic&)':
././vcl/source/filter/jxl/reader.cxx:135:(.text+0x47f): undefined reference to `JxlResizableParallelRunnerSuggestThreads'
/usr/bin/x86_64-linux-gnu-ld.bfd: ././vcl/source/filter/jxl/reader.cxx:134:(.text+0x489): undefined reference to `JxlResizableParallelRunnerSetThreads'
/usr/bin/x86_64-linux-gnu-ld.bfd: /home/rene/LibreOffice/git/master/workdir/CxxObject/vcl/source/filter/jxl/reader.o: in function `JxlResizableParallelRunnerDestroyStruct::operator()(void*)':
/usr/include/jxl/resizable_parallel_runner_cxx.h:34:(.text+0x604): undefined reference to `JxlResizableParallelRunnerDestroy'
/usr/bin/x86_64-linux-gnu-ld.bfd: /usr/include/jxl/resizable_parallel_runner_cxx.h:34:(.text.unlikely+0x68): undefined reference to `JxlResizableParallelRunnerDestroy'

$ grep JxlResizableParallelRunner /usr/lib/x86_64-linux-gnu/*so*
[...]
grep: /usr/lib/x86_64-linux-gnu/libQt6WaylandEglCompositorHwIntegration.so: No such file or directory
grep: /usr/lib/x86_64-linux-gnu/libjxl_threads.so.0.11: binary file matches
grep: /usr/lib/x86_64-linux-gnu/libjxl_threads.so.0.11.2: binary file matches
[...]

so we need libjxl_threads, too

Change-Id: I43ed34093d583f72eb2b8710bcb2ddea8ef17e2d
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/210116
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>