Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/112504/ : FAILURE

clang plugin stringviewparam did trigger. replace function parameter of type "const rtl::OString &" with "std::string_view" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/111924/ )

error: replace function parameter of type "const rtl::OString &" with "std::string_view" [loplugin:stringviewparam] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/unodevtools/source/skeletonmaker/javacompskeleton.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/111924/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/111924/ )

Patch-set: 6
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1