Update patch set 2
Patch Set 2:

This breaks the build:

/home/master/src/libreoffice/workdirs/libreoffice-4-4/cui/source/options/optgdlg.cxx: In constructor ‘OfaViewTabPage::OfaViewTabPage(vcl::Window*, const SfxItemSet&)’:
/home/master/src/libreoffice/workdirs/libreoffice-4-4/cui/source/options/optgdlg.cxx:668:20: error: redeclaration of ‘Size aPrefSize’
     Size aPrefSize(m_pForceOpenGL->get_preferred_size());
                    ^
/home/master/src/libreoffice/workdirs/libreoffice-4-4/cui/source/options/optgdlg.cxx:646:10: note: ‘Size aPrefSize’ previously declared here
     Size aPrefSize(m_pSystemFont->get_preferred_size());
          ^
/home/master/src/libreoffice/workdirs/libreoffice-4-4/cui/source/options/optgdlg.cxx:669:16: error: redeclaration of ‘Size aSize’
     Size aSize(m_pForceOpenGL->CalcMinimumSize(40*approximate_char_width()));
                ^
/home/master/src/libreoffice/workdirs/libreoffice-4-4/cui/source/options/optgdlg.cxx:647:10: note: ‘Size aSize’ previously declared here
     Size aSize(pRef->get_preferred_size());
          ^

Patch-set: 2
Reviewer: Gerrit User 1000084 <1000084@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0