Update patch set 3
Patch Set 3: Fails

The build fails with

/home/kyoshida/libo/master/sc/source/core/tool/ddelink.cxx:49:21: error: conflicting declaration ‘sal_Bool ScDdeLink::bIsInUpdate’
/home/kyoshida/libo/master/sc/source/core/inc/ddelink.hxx:45:13: error: ‘ScDdeLink::bIsInUpdate’ has a previous declaration as ‘bool ScDdeLink::bIsInUpdate’
/home/kyoshida/libo/master/sc/source/core/tool/ddelink.cxx:49:21: error: declaration of ‘bool ScDdeLink::bIsInUpdate’ outside of class is not definition

You also need to change sal_Bool to bool in 

sal_Bool ScDdeLink::bIsInUpdate = false;

in ddelink.cxx#49, to get it to build.

Patch-set: 3
Label: Verified=-1