Update patch set 2
Patch Set 2:

Hi Eike, 

I was unable to reply on the thread of the inline comments so I preferred to write those things here:

If I don't make the changes in sc/source/filter/xml/XMLConverter.cxx, then on doing 'make' I get an error :

/home/elixir/libo/sc/source/filter/xml/XMLConverter.cxx: In static member function ‘static void ScXMLConverter::GetStringFromFunction(rtl::OUString&, ScSubTotalFunc, bool)’:
/home/elixir/libo/sc/source/filter/xml/XMLConverter.cxx:145:11: error: enumeration value ‘SUBTOTAL_FUNC_SELECTION_COUNT’ not handled in switch [-Werror=switch]
cc1plus: all warnings being treated as errors .

with --enable-werror [ I enabled this, since warnings are no good and mac crashes with warnings is what I've learnt through irc conversations ].

So handling ‘SUBTOTAL_FUNC_SELECTION_COUNT’ in switch became necessary.

The rest of xml file changes follow this change.

And definitely I shall take care of indentation. :)

I small doubt: Should the hidden rows be counted in 'Selection count', i.e. if the row was hidden, its value should be added or not?

Thanks
Prashant

Patch-set: 2