Fix MSVC 2019 16.8.3 --with-latest-c++ error C2102: '&' requires l-value
Change-Id: Iff1db722239c32822bbc23ddd13e2df105a993e3
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/108837
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>