Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/82995/ : FAILURE

clang plugin simplifyconstruct did trigger. no need to explicitly init an instance of "std::unique_ptr<Qt5SvpGraphics>" with nullptr, just use default constructor ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/84508/ )

error: replace function parameter of type "const rtl::OUString &" with "std::u16string_view" [loplugin:stringviewparam] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/qt5/Qt5Instance.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/84508/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1