SwTokenWindow::InsertAtSelection: fix STL assertion:
 error: attempt to copy-construct an iterator from a singular iterator.
(regression from 39b8a5f87f55abe53488c9c3c35b65fb0df84cde)

Change-Id: Iab29f4c356ea1cb5ca0f687bcfc5e54f185fbba3
(cherry picked from commit c47505a4525c342694ba4196544715467c2bdb8e)