Update patch set 21
Patch Set 21: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/94507/ : FAILURE

Visual studio complained about error C2672: "CppUnit::assertEquals": no matching overloaded function found in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/vcl/qa/cppunit/text.cxx(392) ( https://ci.libreoffice.org/job/gerrit_windows/105467/ )

likely caused by leftovers that linger around from an aborted build ( https://ci.libreoffice.org/job/gerrit_windows/105467/ )

Patch-set: 21
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1