set libtiff ac_cv_lib_jpeg_jpeg12_read_scanlines cache val to false
to avoid:

...
checking for jpeg12_read_scanlines in -ljpeg... yes
...
JPEG 8/12 bit dual mode:            yes (libjpeg turbo >= 2.2 dual mode)
...
tif_jpeg.c:143:25: error: unknown type name ‘J12SAMPARRAY’
  143 | #define TIFF_JSAMPARRAY J12SAMPARRAY

where the system jpeg is linked against during configure but the build
is against the internal jpeg and the system one happens to support
jpeg12_read_scanlines

Change-Id: I895d77c59a5bef1af0b1a85d44da1a54e502f8e4
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/155670
Tested-by: Jenkins
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>
(cherry picked from commit 72b118e4cb7f97cbd296fd829a463fe9fafb8486)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/157464
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>