external/libnumbertext: Silence -Werror,-Wdeprecated-declarations
...when building against emsdk 5.0.2,

> In file included from Numbertext.cxx:6:
> In file included from ~/emsdk/5.0.2/emsdk/emscripten/main/cache/sysroot/include/c++/v1/locale:203:
> ~/emsdk/5.0.2/emsdk/emscripten/main/cache/sysroot/include/c++/v1/__locale_dir/wstring_convert.h:179:1: error: 'wstring_convert<std::codecvt_utf8<wchar_t>>' is deprecated [-Werror,-Wdeprecated-declarations]
>   179 | wstring_convert<_Codecvt, _Elem, _WideAlloc, _ByteAlloc>::to_bytes(const _Elem* __frm, const _Elem* __frm_end) {
>       | ^
> ~/emsdk/5.0.2/emsdk/emscripten/main/cache/sysroot/include/c++/v1/__locale_dir/wstring_convert.h:83:12: note: in instantiation of member function 'std::wstring_convert<std::codecvt_utf8<wchar_t>>::to_bytes' requested here
>    83 |     return to_bytes(__wstr.data(), __wstr.data() + __wstr.size());
>       |            ^
> Numbertext.cxx:160:22: note: in instantiation of member function 'std::wstring_convert<std::codecvt_utf8<wchar_t>>::to_bytes' requested here
>   160 |     return converter.to_bytes( s );
>       |                      ^
> ~/emsdk/5.0.2/emsdk/emscripten/main/cache/sysroot/include/c++/v1/__locale_dir/wstring_convert.h:34:7: note: 'wstring_convert<std::codecvt_utf8<wchar_t>>' has been explicitly marked deprecated here
>    34 | class _LIBCPP_DEPRECATED_IN_CXX17 wstring_convert {
>       |       ^
> ~/emsdk/5.0.2/emsdk/emscripten/main/cache/sysroot/include/c++/v1/__config:740:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
>   740 | #    define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
>       |                                         ^
> ~/emsdk/5.0.2/emsdk/emscripten/main/cache/sysroot/include/c++/v1/__config:713:49: note: expanded from macro '_LIBCPP_DEPRECATED'
>   713 | #      define _LIBCPP_DEPRECATED __attribute__((__deprecated__))
>       |                                                 ^

So following up on ad6ba4a3a63a25c5b9043bb5d0b178411b3eb714
"external/libnumbertext: Silence -Werror,-Wdeprecated-declarations", move the
pragma even earlier.

Change-Id: I599c751e703fec4bbffde6b43385236e6f5808d6
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/200731
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>
(cherry picked from commit 921f41924f908c1bcbceb47c80be23c5c77d1cc0)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/200777
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Andras Timar <andras.timar@collabora.com>