Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/41686/ : FAILURE

Visual studio complained about error C2440: "return": cannot convert from "void" to "bool" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/sw/source/uibase/app/docsh2.cxx(1353) ( https://ci.libreoffice.org/job/gerrit_windows/48240/ )

Patch-set: 1
Label: Verified=-1