error: logical not is only applied to the left hand side of this comparison
[-Werror,-Wlogical-not-parentheses] from recent Clang trunk towards 3.4.  Code
was likethat "since the beginning," but I guess the way it needs a fix it is
rather obvious.

Change-Id: I8c962ae696de5482ac4e3fff5e08df71355de4a8