Update patch set 17
Patch Set 17: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/20729/ : FAILURE

error: use "true" instead of "sal_True" [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sfx2/source/dialog/filedlghelper.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/21577/ )

clang plugin salbool did trigger. use "true" instead of "sal_True" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/21577/ )

Patch-set: 17
Label: Verified=-1