vcl: fix SalGtkXWindow::getPosSize()
This function was introduced with commit
9869ca098765ed5ec0325492fa2cdce4a5bab795 and never existed on master?
Very mysterious...

vcl/unx/gtk3/gtk3gtkinst.cxx:13213:46: error: ‘y’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
13213 |         return css::awt::Rectangle(x, y, w, h);

Change-Id: I277253be7302ec04961b918c8588b441e6e87ba5