workaround error C2589: ´(´ : illegal token on right side of ´::´
Change-Id: I3654a4eb4caa3a987f6d797c9bcb577c6fd6b426
(cherry picked from commit 1fc30a25e2c69fe8b365300b0784f3a282183e80)