Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/77805/ : FAILURE

Visual studio complained about error C2440: "=": cannot convert from "std::unique_ptr<SdrObjGeoData,std::default_delete<SdrObjGeoData>>" to "SdrObjGeoData *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/sc/source/filter/xml/xmlexprt.cxx(3498) ( https://ci.libreoffice.org/job/gerrit_windows/88006/ )

Patch-set: 1
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1