Silence -Werror,-Wdeprecated-declarations for now
...that got introduced with e10e5981ca020af11d25d5756964c95d51dd1535 "tdf#152183
update settings when dark/light system mode toggled",

> vcl/osx/salframe.cxx:1269:19: error: 'setCurrentAppearance:' is deprecated: first deprecated in macOS 12.0 - Use -performAsCurrentDrawingAppearance: to temporarily set the drawing appearance, or +currentDrawingAppearance to access the currently drawing appearance. [-Werror,-Wdeprecated-declarations]
>     [NSAppearance setCurrentAppearance: mpNSView.effectiveAppearance];
>                   ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSAppearance.h:28:58: note: property 'currentAppearance' is declared deprecated here
> @property (class, null_resettable, strong) NSAppearance *currentAppearance API_DEPRECATED("Use -performAsCurrentDrawingAppearance: to temporarily set the drawing appearance, or +currentDrawingAppearance to access the currently drawing appearance.", macos(10.9, 12.0));
>                                                          ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSAppearance.h:28:58: note: 'setCurrentAppearance:' has been explicitly marked deprecated here

Change-Id: If4aa9a30fda2977fa3cc23f2cb0d056a8dcde311
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/143402
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>