Update patch set 1
Patch Set 1: Code-Review+1

You didn't get the point. But minused this. Nice, nice.

It's LO's code which needs to be changed.

Actual error is/was_with_patch:

unoidl/source/sourcetreeprovider.cxx:77:28: error: 'strlen' is not a member of 'std'
                 p->d_name, std::strlen(p->d_name), osl_getThreadTextEncoding());
                            ^
unoidl/source/sourcetreeprovider.cxx:77:28: note: suggested alternative:
In file included from include/osl/file.hxx:25:0,
                 from unoidl/source/sourcetreeprovider.cxx:16:
/usr/include/string.h:98:8: note:   'strlen'
 size_t  strlen(const char *);
        ^

Patch-set: 1