Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/73472/ : FAILURE

clang plugin redundantcast did trigger. redundant dynamic cast from "JSTreeView *" to "JSTreeView *" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75648/ )

error: redundant dynamic cast from "JSTreeView *" to "JSTreeView *" [loplugin:redundantcast] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/vcl/jsdialog/executor.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75648/ )

Killed by the kill-wrapper, typically due to no stdout/-err activity during a specified timeout interval. ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/75648/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1