Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/82701/ : FAILURE

clang plugin selfinit did trigger. referencing a variable during its own initialization is error-prone and thus suspicious ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/84224/ )

error: referencing a variable during its own initialization is error-prone and thus suspicious [loplugin:selfinit] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/animations/source/animcore/animcore.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/84224/ )

Patch-set: 4
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1