Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/93006/ : FAILURE

Visual studio complained about error C2664: "sal_Int64 oox::drawingml::convertHmmToEmu(sal_Int32)": cannot convert argument 1 from "Color" to "sal_Int32" in file C:/cygwin64/home/tdf/lode/jenkins/workspace/gerrit_windows/sd/qa/unit/export-tests-ooxml1.cxx(991) ( https://ci.libreoffice.org/job/gerrit_windows/103862/ )

build likely got stuck and was aborted due to not producing any output to the log ( https://ci.libreoffice.org/job/gerrit_windows/103862/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1