Fix testTdf134553 in Kit case
After commit 60d19b289bcdbb8957e30ab8bd5abd95d54e5865 ("sc: paste a copied
shape at the cell the paste was issued from", 2026-08-12), it started to fail
in CODA-W builds:

 C:/lo/online/engine/sc/qa/unit/jumbosheets-test.cxx(263) : error : Assertion
 Test name: ScJumboSheetsTest::testTdf134553
 equality assertion failed
 - Expected: 4574
 - Actual  : 1641

Earlier commit 1d5e313cb82cba7d644cd08c9acfba7375a49518 (Kit: expect a pasted
chart to keep its position, 2026-08-01) introduced a Kit-specific branch; it
was obsoleted by the commit above, but still coordinate is different with Kit.

Signed-off-by: Mike Kaganski <mike.kaganski@collabora.com>
Change-Id: I80171b20046c5b44f4da22916a200fe7493a76b5
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/9611
Reviewed-by: Dennis Francis <dennis.francis@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>