Fix build in vcl
/home/julien/lo/libreoffice/vcl/unx/gtk3/a11y/gtk3atkwrapper.cxx: In function ‘AtkObject* atk_object_wrapper_new(const com::sun::star::uno::Reference<com::sun::star::accessibility::XAccessible>&, AtkObject*, AtkObject*)’:
/home/julien/lo/libreoffice/vcl/unx/gtk3/a11y/gtk3atkwrapper.cxx:866:53: error: ‘XAccessibleContext2’ is not a member of ‘com::sun::star::accessibility’; did you mean ‘XAccessibleContext’?
  866 |             css::uno::Reference<css::accessibility::XAccessibleContext2> xContext2(xContext, css::uno::UNO_QUERY);
      |                                                     ^~~~~~~~~~~~~~~~~~~
      |                                                     XAccessibleContext
/home/julien/lo/libreoffice/vcl/unx/gtk3/a11y/gtk3atkwrapper.cxx:866:72: error: template argument 1 is invalid
  866 |             css::uno::Reference<css::accessibility::XAccessibleContext2> xContext2(xContext, css::uno::UNO_QUERY);
      |                                                                        ^
/home/julien/lo/libreoffice/vcl/unx/gtk3/a11y/gtk3atkwrapper.cxx:866:113: error: expression list treated as compound expression in initializer [-fpermissive]
  866 |             css::uno::Reference<css::accessibility::XAccessibleContext2> xContext2(xContext, css::uno::UNO_QUERY);
      |                                                                                                                 ^
/home/julien/lo/libreoffice/vcl/unx/gtk3/a11y/gtk3atkwrapper.cxx:866:84: error: left operand of comma operator has no effect [-Werror=unused-value]
  866 |             css::uno::Reference<css::accessibility::XAccessibleContext2> xContext2(xContext, css::uno::UNO_QUERY);
      |                                                                                    ^~~~~~~~
/home/julien/lo/libreoffice/vcl/unx/gtk3/a11y/gtk3atkwrapper.cxx:867:27: error: request for member ‘is’ in ‘xContext2’, which is of non-class type ‘int’
  867 |             if( xContext2.is() )
      |                           ^~
/home/julien/lo/libreoffice/vcl/unx/gtk3/a11y/gtk3atkwrapper.cxx:869:59: error: base operand of ‘->’ is not a pointer
  869 |                 OString aId = OUStringToOString( xContext2->getAccessibleId(), RTL_TEXTENCODING_UTF8);

Due to https://cgit.freedesktop.org/libreoffice/core/commit/?id=07359ea21cf27e29d3e642d6ff1851155888a875

Change-Id: I61967a41f43a31199369e5c25e008259ca3786dc