poppler: upgrade to 25.04.0
After 032d035220702523cf10d924fd436c9e6c83d24c
"Enforce error checking on stream::reset" the return from reset
has to be checked, otherwise it fails with
error: ignoring return value of ‘bool ImageStream::reset()’, declared with attribute ‘nodiscard’ [-Werror=unused-result]

Downloaded from https://poppler.freedesktop.org/poppler-25.04.0.tar.xz

Change-Id: I5c6022b11c307f4293e4b2ea566e811053e3ab6f
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/183632
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
(cherry picked from commit 4f13305178c1bf88dffceb42ec15d0944b808a5c)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/184642
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>