error C2782: template parameter '_Ty' is ambiguous
Change-Id: Ieb8f91a629b9e14480c0372e747fea326c549833
(cherry picked from commit 02e0bac73be8d11abf539130f3d3541fa72af93a)
Signed-off-by: Andras Timar <andras.timar@collabora.com>