Silence GCC 11 trunk -Werror=nonnull in external/boost
...like

> In file included from workdir/UnpackedTarball/boost/boost/concept/assert.hpp:35,
>                  from workdir/UnpackedTarball/boost/boost/concept_check.hpp:20,
>                  from workdir/UnpackedTarball/boost/boost/range/concepts.hpp:19,
>                  from workdir/UnpackedTarball/boost/boost/range/size_type.hpp:20,
>                  from workdir/UnpackedTarball/boost/boost/range/size.hpp:21,
>                  from workdir/UnpackedTarball/boost/boost/range/functions.hpp:20,
>                  from workdir/UnpackedTarball/boost/boost/range/iterator_range_core.hpp:38,
>                  from workdir/UnpackedTarball/boost/boost/range/iterator_range.hpp:13,
>                  from external/boost/include/boost/range/iterator_range.hpp:29,
>                  from workdir/UnpackedTarball/boost/boost/range/as_literal.hpp:22,
>                  from workdir/UnpackedTarball/boost/boost/algorithm/string/trim.hpp:19,
>                  from workdir/UnpackedTarball/boost/boost/algorithm/string.hpp:19,
>                  from external/boost/include/boost/algorithm/string.hpp:29,
>                  from sal/cppunittester/cppunittester.cxx:61:
> workdir/UnpackedTarball/boost/boost/concept/detail/general.hpp: In instantiation of ‘static void boost::concepts::constraint<Model>::failed() [with Model = boost::algorithm::FinderConcept<boost::algorithm::detail::token_finderF<boost::algorithm::detail::is_any_ofF<char> >, const char*>]’:
> workdir/UnpackedTarball/boost/boost/algorithm/string/iter_find.hpp:81:13:   required from ‘SequenceSequenceT& boost::algorithm::iter_split(SequenceSequenceT&, RangeT&&, FinderT) [with SequenceSequenceT = std::__debug::vector<std::__cxx11::basic_string<char> >; RangeT = const char*&; FinderT = boost::algorithm::detail::token_finderF<boost::algorithm::detail::is_any_ofF<char> >]’
> workdir/UnpackedTarball/boost/boost/algorithm/string/split.hpp:158:50:   required from ‘SequenceSequenceT& boost::algorithm::split(SequenceSequenceT&, RangeT&&, PredicateT, boost::algorithm::token_compress_mode_type) [with SequenceSequenceT = std::__debug::vector<std::__cxx11::basic_string<char> >; RangeT = const char*&; PredicateT = boost::algorithm::detail::is_any_ofF<char>]’
> sal/cppunittester/cppunittester.cxx:303:71:   required from here
> workdir/UnpackedTarball/boost/boost/concept/detail/general.hpp:47:52: error: ‘this’ pointer null [-Werror=nonnull]
>    47 |     static void failed() { ((Model*)0)->constraints(); }
>       |                            ~~~~~~~~~~~~~~~~~~~~~~~~^~

Change-Id: Ia22b5d510ba41bea138dfcc8d8e0b9eb1e9ad41c
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/99217
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit 7adb6398dcb081999003c61985ae8a203c65ce0d)