Refine .git-hooks/pre-commit check_prettier skip
...so that we don't run into the confusing scenario that an engine-only commit

> git commit -m foo -s

succeeds (by skipping check_prettier) but an immediately following

> git commit -m bar --amend

fails with

> ===============================================
>   ERROR: Code formatting check failed
> ===============================================
> Your code is not properly formatted.
> Please run 'gmake prettier-write' before committing.
> ===============================================

Change-Id: I9d6827b0ef2eeb955ab7e23f8355d77fe1a484eb
Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/4090
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>