dbaccess: fix testCloneMovesPlusDeletions test
JunitTest_dbaccess_complex spuriously fails 1% of the time with:

1) testCloneMovesPlusDeletions(complex.dbaccess.RowSet)
java.lang.AssertionError: moving to the next record after |deleteRow| and clone moves failed
    at complex.dbaccess.RowSet.testCloneMovesPlusDeletions(RowSet.java:756)

The problem is that line RowSet.java:750 deleteRow() manages to delete
the last row in the set, because the positionRandom() is tricked to
position itself on the last row (which it tries not to do), becuase the
RowSet is currently positioned past-the-end on a deleted row and the
ORowSetBase::impl_getRowCount() is a lying bastard that adds 1 to the
result in this special case.

Funnily both the ORowSetBase::impl_getRowCount() and the test using
positionRandom() were added in CWS rowsetdel.  Yay for randomized
tests!

Change-Id: Ic8c7bfa190f6a5269604cf5b3c338f2d0b64205e
(cherry picked from commit ae8bd4267ac2da58f9e476d24e1e894202e92dea)
Reviewed-on: https://gerrit.libreoffice.org/32991
Tested-by: Jenkins <ci@libreoffice.org>
Reviewed-by: Caolán McNamara <caolanm@redhat.com>
Tested-by: Caolán McNamara <caolanm@redhat.com>
(cherry picked from commit 8fde9af18698d85f13294ca0990478b707fc748a)