Copy from rSource, not from *this
...which had been the case ever since 5d431414afa79d392fe6a885940c559236c25aa2
"CWS-TOOLING: integrate CWS impressnotes01", but caused

> svx/source/annotation/TextAPI.cxx:187:32: error: ‘<unknown>’ may be used uninitialized [-Werror=maybe-uninitialized]
>   187 |     , mpHolder(rSource.mpHolder) // shallow copy; uses internal refcounting
>       |                                ^
> In file included from include/editeng/unotext.hxx:55,
>                  from include/svx/annotation/TextAPI.hxx:22,
>                  from svx/source/annotation/TextAPI.cxx:24:
> include/editeng/unoedsrc.hxx:59:5: note: by argument 2 of type ‘const SvxEditSource&’ to ‘constexpr SvxEditSource::SvxEditSource(const SvxEditSource&)’ declared here
>    59 |     SvxEditSource(SvxEditSource const &) = default;
>       |     ^~~~~~~~~~~~~

at least with --disable-optimized against recent GCC 16 trunk

Change-Id: I2815df15042444aa2826f25262253cb78ec0da68
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/193059
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>
(cherry picked from commit c0370b81ee8c900486df48030c9bf362fb7fd897)