Fix Windows build, where sal_Int32 is not int
 C:/lo/core/svx/qa/unit/svdraw.cxx(330): error C2672: 'CppUnit::assertEquals': no matching overloaded function found
 C:\lo\build\workdir\UnpackedTarball\cppunit\include\cppunit/TestAssert.h(161): note: could be 'void CppUnit::assertEquals(const T &,const T &,CppUnit::SourceLine,const std::string &)'
 C:/lo/core/svx/qa/unit/svdraw.cxx(330): note: 'void CppUnit::assertEquals(const T &,const T &,CppUnit::SourceLine,const std::string &)': template parameter 'T' is ambiguous
 C:/lo/core/svx/qa/unit/svdraw.cxx(330): note: could be 'sal_Int32'
 C:/lo/core/svx/qa/unit/svdraw.cxx(330): note: or       'int'
 C:/lo/core/svx/qa/unit/svdraw.cxx(330): note: 'void CppUnit::assertEquals(const T &,const T &,CppUnit::SourceLine,const std::string &)': could not deduce template argument for 'const T &' from 'sal_Int32'

To simplify things, this change makes methods of XmlElement and
XPathObject take and return int. The classes were added in commit
99354e5cb0abb025c0ee980676bf0e37822c8119 (introduce tools::XPath
to be able to reuse the result after call, 2025-12-22) for tests;
and in tests, we have an established convention of using int (see
e.g. SwModelTestBase::getParagraphs).

Change-Id: I2e5040e48a34b0c2f48be3561ac475e91a21ff03
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/201630
Reviewed-by: Michael Stahl <michael.stahl@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>