Update patch set 1
Patch Set 1:

I get build failure of Library_vclplug_gtk3 because -licuuc is missing. I use system ICU, but non-system harfbuzz.

This patch fixes the issue for me. Is it the right fix?

/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/.libs/libharfbuzz.a(libharfbuzz_la-hb-icu.o): In function `hb_icu_script_to_script':
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/hb-icu.cc:49: undefined reference to `uscript_getShortName_57'
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/.libs/libharfbuzz.a(libharfbuzz_la-hb-icu.o): In function `hb_icu_unicode_combining_class(hb_unicode_funcs_t*, unsigned int, void*)':
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/hb-icu.cc:72: undefined reference to `u_getCombiningClass_57'
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/.libs/libharfbuzz.a(libharfbuzz_la-hb-icu.o): In function `hb_icu_unicode_eastasian_width(hb_unicode_funcs_t*, unsigned int, void*)':
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/hb-icu.cc:80: undefined reference to `u_getIntPropertyValue_57'
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/.libs/libharfbuzz.a(libharfbuzz_la-hb-icu.o): In function `hb_icu_unicode_general_category(hb_unicode_funcs_t*, unsigned int, void*)':
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/hb-icu.cc:99: undefined reference to `u_getIntPropertyValue_57'
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/.libs/libharfbuzz.a(libharfbuzz_la-hb-icu.o): In function `hb_icu_unicode_mirroring(hb_unicode_funcs_t*, unsigned int, void*)':
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/hb-icu.cc:150: undefined reference to `u_charMirror_57'
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/.libs/libharfbuzz.a(libharfbuzz_la-hb-icu.o): In function `hb_icu_unicode_script(hb_unicode_funcs_t*, unsigned int, void*)':
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/hb-icu.cc:159: undefined reference to `uscript_getScript_57'
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/.libs/libharfbuzz.a(libharfbuzz_la-hb-icu.o): In function `hb_icu_unicode_compose(hb_unicode_funcs_t*, unsigned int, unsigned int, unsigned int*, void*)':
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/hb-icu.cc:180: undefined reference to `unorm2_composePair_57'
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/.libs/libharfbuzz.a(libharfbuzz_la-hb-icu.o): In function `hb_icu_unicode_decompose(hb_unicode_funcs_t*, unsigned int, unsigned int*, unsigned int*, void*)':
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/hb-icu.cc:229: undefined reference to `unorm2_getRawDecomposition_57'
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/hb-icu.cc:232: undefined reference to `u_countChar32_57'
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/.libs/libharfbuzz.a(libharfbuzz_la-hb-icu.o): In function `hb_icu_unicode_decompose_compatibility(hb_unicode_funcs_t*, unsigned int, unsigned int*, void*)':
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/hb-icu.cc:334: undefined reference to `unorm2_getNFKDInstance_57'
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/hb-icu.cc:334: undefined reference to `unorm2_normalize_57'
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/hb-icu.cc:340: undefined reference to `u_strToUTF32_57'
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/.libs/libharfbuzz.a(libharfbuzz_la-hb-icu.o): In function `hb_icu_get_unicode_funcs':
/path/to/libo-6-1-sources/workdir/UnpackedTarball/harfbuzz/src/hb-icu.cc:375: undefined reference to `unorm2_getNFCInstance_57'
collect2: error: ld returned 1 exit status
/path/to/libo-6-1-sources/vcl/Library_vclplug_gtk3.mk:20: recipe for target '/path/to/libo-6-1-sources/instdir/program/libvclplug_gtk3lo.so' failed
make: *** [/path/to/libo-6-1-sources/instdir/program/libvclplug_gtk3lo.so] Error 1

Patch-set: 1