Avoid C++20 operator overloading ambiguity
...which is reported now by Clang 10 trunk with -std=c++2a:

> cui/source/tabpages/tpline.cxx:481:80: error: use of overloaded operator '==' is ambiguous (with operand types 'const XLineEndItem' and 'XLineStartItem')
>             if( pItem && ( !pOld || !( *static_cast<const XLineEndItem*>(pOld) == *pItem ) ) )
>                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~
> include/svx/xlnstit.hxx:43:29: note: candidate function (with reversed parameter order)
>     virtual bool            operator==(const SfxPoolItem& rItem) const override;
>                             ^
> include/svx/xlnedit.hxx:43:29: note: candidate function
>     virtual bool            operator==(const SfxPoolItem& rItem) const override;
>                             ^

But the base SfxPoolItem::operator == is virtual anyway, so no need to cast
pOld to a derived type.

Change-Id: I3de9175b30d8645ed7a52f87cfac320144576cc8