Update patch set 2
Patch Set 2:

> Patch Set 1: Code-Review-1
> 
> > Patch Set 1: Verified-1
> > 
> > Build Failed 
> > 
> > https://ci.libreoffice.org/job/gerrit_master/77690/ : FAILURE
> > 
> > error: CPPUNIT_ASSERT_EQUALS parameters look switched, expected value should be first param [loplugin:cppunitassertequals] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/extras/ww8export/ww8export3.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/79640/ )
> > 
> > clang plugin cppunitassertequals did trigger. CPPUNIT_ASSERT_EQUALS parameters look switched, expected value should be first param ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/79640/ )
> 
> Well, the error message is pretty clear, right?

Opps! I think I might've ran the wrong test because the error was something else.

Patch-set: 2