fdo#48017 fix WIN32 long path name support of spelling dictionaries
+ try including windows.h for MultiByteToWideChar

(cherry picked from commit 187765b8a45761e14d18da58463dbc0f5bd825e9)

+ error C2059: syntax error : ´)´

(cherry picked from commit 445d62565d662a7119a0c49e8e8de68ee244dc74)

Change-Id: I1ccaae9dba4f82cd50531890e159519a765a0fff
Reviewed-on: https://gerrit.libreoffice.org/9182
Reviewed-by: Caolán McNamara <caolanm@redhat.com>
Tested-by: Caolán McNamara <caolanm@redhat.com>