Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/20997/ : FAILURE

clang plugin redundantinline did trigger. function has no external linkage but is explicitly declared "inline" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/21919/ )

error: function has no external linkage but is explicitly declared "inline" [loplugin:redundantinline] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/svx/source/sidebar/possize/PosSizePropertyPanel.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/21919/ )

Patch-set: 1
Label: Verified=-1