sw: fix warning C6011: Dereferencing NULL pointer 'pDocSh'
after
commit ab91358566ccf31f7a9ac57f1c32a9c62840f5d5
Author: Miklos Vajna <vmiklos@collabora.com>
Date:   Mon Mar 10 10:18:10 2025 +0100

    cool#11226 sw per-view redline on: support this-view <-> all-views transition

Catch by https://ci.libreoffice.org/job/lo_tb_master_win_analyze/
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/sw/source/core/edit/edredln.cxx(44): error C2220: the following warning is treated as an error
C:\cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win_analyze\sw\source\core\edit\edredln.cxx(36) : warning C6011: Dereferencing NULL pointer 'pDocSh'. : Lines: 35, 36
make[1]: *** [C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/solenv/gbuild/LinkTarget.mk:339: C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/workdir/CxxObject/sw/source/core/edit/edredln.o] Error 2

Change-Id: I0f191ee2bf583ba0fda5c9868679996baf480ca8
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/182767
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>