Update patch set 8
Patch Set 8:

> Patch Set 8: Verified-1
> 
> Build Failed 
> 
> https://ci.libreoffice.org/job/gerrit_master/70945/ : FAILURE
> 
> Uncategorized build failure. If it is generic enough, please add a suitable Cause for it. ( https://ci.libreoffice.org/job/gerrit_master/70945/ )

  C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/workdir/UnpackedTarball/firebird/temp/Debug/isql/show.cpp: fatal error C1041: cannot open program database 'C:\cygwin\home\tdf\lode\jenkins\workspace\gerrit_windows@2\workdir\UnpackedTarball\firebird\gen\vc140.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
  make[5]: *** [make.rules:93: C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/workdir/UnpackedTarball/firebird/temp/Debug/isql/show.o] Error 2
  make[5]: *** Waiting for unfinished jobs....
  make[4]: *** [Makefile:176: master_process] Error 2
  make[3]: *** [Makefile:73: Debug] Error 2
  make[2]: *** [Makefile:6: Debug] Error 2
  make[1]: *** [C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/external/firebird/ExternalProject_firebird.mk:30: C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows@2/workdir/ExternalProject/firebird/build] Error 1

(<https://ci.libreoffice.org/job/gerrit_windows/80526/console>) looks like it may be caused by this change

Patch-set: 8
Reviewer: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>