Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/46402/ : FAILURE

error: unused variable declaration [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/extras/ooxmlexport/ooxmlexport5.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/49832/ )

clang plugin casttovoid did trigger. unused variable declaration ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/49832/ )

Patch-set: 7
Label: Verified=-1