fix wasm build (int vs sal_Int32 mismatch)
error: non-const lvalue reference to type 'sal_Int32' (aka 'long')
cannot bind to a value of unrelated type 'int' in file
/home/tdf/jenkins/workspace/lo_gerrit/tb/src_wasm/vcl/qt5/QtAccessibleWidget.cxx

(since refactoring in 15a6e23c4fc160c50a316da3d18980a02fc10ce8 )

Change-Id: I2689701839ba18b5cffae13afcaa5b1a32b5e4b9
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/158305
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins