Fix build after commit 6d63cb8749811ff407c3b3f523a329bcaab05542
Failed on Windows with

  C:/lo/src/core2/svx/source/svdraw/svdmrkv.cxx(925): error C2079: 'aDragParameters' uses undefined class 'std::array<int,5>'
  C:/lo/src/core2/svx/source/svdraw/svdmrkv.cxx(927): error C3312: no callable 'begin' function found for type 'int'
  C:/lo/src/core2/svx/source/svdraw/svdmrkv.cxx(927): error C3312: no callable 'end' function found for type 'int'
  C:/lo/src/core2/svx/source/svdraw/svdmrkv.cxx(931): error C2065: 'rParam': undeclared identifier
  C:/lo/src/core2/svx/source/svdraw/svdmrkv.cxx(935): error C2109: subscript requires array or pointer type
  C:/lo/src/core2/svx/source/svdraw/svdmrkv.cxx(936): error C2109: subscript requires array or pointer type
  C:/lo/src/core2/svx/source/svdraw/svdmrkv.cxx(937): error C2109: subscript requires array or pointer type
  C:/lo/src/core2/svx/source/svdraw/svdmrkv.cxx(938): error C2109: subscript requires array or pointer type
  C:/lo/src/core2/svx/source/svdraw/svdmrkv.cxx(941): error C2109: subscript requires array or pointer type
  C:/lo/src/core2/svx/source/svdraw/svdmrkv.cxx(944): error C2109: subscript requires array or pointer type
  C:/lo/src/core2/svx/source/svdraw/svdmrkv.cxx(945): error C2109: subscript requires array or pointer type
  C:/lo/src/core2/svx/source/svdraw/svdmrkv.cxx(930): error C2043: illegal break
  make[1]: *** [C:/lo/src/core2/solenv/gbuild/LinkTarget.mk:293: C:/lo/src/core2/workdir/CxxObject/svx/source/svdraw/svdmrkv.o] Error 2

Change-Id: Iaf2762a43a7eefce582bb187dd6978d5b28564e5