Update patch set 2
Patch Set 2:

this broke `make screenshot`,

  [CXX] sd/qa/unit/dialogs-test.cxx
  /data/sbergman/lo-system/core/sd/qa/unit/dialogs-test.cxx: In member function ‘virtual VclPtr<VclAbstractDialog> SdDialogsTest::createDialogByID(sal_uInt32)’:
  /data/sbergman/lo-system/core/sd/qa/unit/dialogs-test.cxx:456:69: error: no matching function for call to ‘SfxStyleSheetBasePool::First()’
    456 |             SfxStyleSheetBase* pStyleSheet = pStyleSheetPool->First();
        |                                                                     ^
  In file included from /data/sbergman/lo-system/core/sd/inc/drawdoc.hxx:24,
                   from /data/sbergman/lo-system/core/sd/qa/unit/dialogs-test.cxx:25:
  /data/sbergman/lo-system/core/include/svl/style.hxx:274:25: note: candidate: ‘SfxStyleSheetBase* SfxStyleSheetBasePool::First(SfxStyleFamily, SfxStyleSearchBits)’
    274 |     SfxStyleSheetBase*  First(SfxStyleFamily eFamily, SfxStyleSearchBits eMask = SfxStyleSearchBits::All);
        |                         ^~~~~
  /data/sbergman/lo-system/core/include/svl/style.hxx:274:25: note:   candidate expects 2 arguments, 0 provided
  /data/sbergman/lo-system/core/sd/qa/unit/dialogs-test.cxx:485:69: error: no matching function for call to ‘SfxStyleSheetBasePool::First()’
    485 |             SfxStyleSheetBase* pStyleSheet = pStyleSheetPool->First();
        |                                                                     ^
  In file included from /data/sbergman/lo-system/core/sd/inc/drawdoc.hxx:24,
                   from /data/sbergman/lo-system/core/sd/qa/unit/dialogs-test.cxx:25:
  /data/sbergman/lo-system/core/include/svl/style.hxx:274:25: note: candidate: ‘SfxStyleSheetBase* SfxStyleSheetBasePool::First(SfxStyleFamily, SfxStyleSearchBits)’
    274 |     SfxStyleSheetBase*  First(SfxStyleFamily eFamily, SfxStyleSearchBits eMask = SfxStyleSearchBits::All);
        |                         ^~~~~
  /data/sbergman/lo-system/core/include/svl/style.hxx:274:25: note:   candidate expects 2 arguments, 0 provided
  make[1]: *** [/data/sbergman/lo-system/core/solenv/gbuild/LinkTarget.mk:306: /data/sbergman/lo-system/core/workdir/CxxObject/sd/qa/unit/dialogs-test.o] Error 1

Patch-set: 2
CC: Gerrit User 1000045 <1000045@6622c302-437a-49ad-a91d-55ba7dcf1615>