Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/5604/ : FAILURE

error: VarDecl, use "bool" instead of "sal_Bool" [loplugin:salbool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/reportdesign/source/filter/xml/xmlExport.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/5557/ )

clang plugin salbool did trigger. VarDecl, use "bool" instead of "sal_Bool" ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/5557/ )

Patch-set: 3
Label: Verified=-1