Update patch set 8
Patch Set 8: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_feature/212/ : FAILURE

clang plugin external did trigger. externally available entity "lcl_GetFillColor" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/27833/ )

error: externally available entity "lcl_GetFillColor" is not previously declared in an included file (if it is only used in this translation unit, make it static; otherwise, provide a declaration of it in an included file) [loplugin:external] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/core/crsr/DropDownFormFieldButton.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/27833/ )

Patch-set: 8
Label: Verified=-1