reduce export of some symbols from toolkit
undo (and a few more) the export of

commit bb182b47ca7362b05c03d583d3547643d9a99562
Date:   Thu Aug 7 21:18:56 2014 +0200

    toolkit: export some ListenerMultiplexer types

    These are used from svx and apparently some (buggy?) toolchains fail with
    fmgridif.cxx:: undefined reference to `non-virtual thunk
     to WindowListenerMultiplexer::acquire()'

now that the baseline has moved on

Change-Id: If17e96067b475b6b9ad16937572695ce63a33614