Update patch set 3
Patch Set 3:

Reported on IRC, and I can confirm locally:

> 09:12 < htietze> Build fails with BitmapShadowFilter.cxx:15:10: fatal error: bitmapwriteaccess.hxx: No such file or directory. Any advice?

Sounds like the Jenkins Verified+1 was old enough that a silent merge conflict went in.

Patch-set: 3
CC: Gerrit User 1000013 <1000013@6622c302-437a-49ad-a91d-55ba7dcf1615>