gdb pretty-printers: fix StringPrinterHelper for gdb 8.0
Latest gdb release "lazy_string" validates the array size:

  Traceback (most recent call last):
    File "/work/lo/master/solenv/gdb/libreoffice/util/string.py", line
29, in to_string
      return self.make_string(data, self.encoding, len)
    File "/work/lo/master/solenv/gdb/libreoffice/util/string.py", line
66, in make_string
      return data.lazy_string(encoding, length)
  gdb.error: Length is larger than array size.

rtl_uString has "sal_Unicode buffer[1];", which is a lie
as the real size is the same as "length".

Taking the address of "buffer" appears to avoid the exception.

Change-Id: I85710b1adfae584ba09c8d517e9b49b290e79d8a
(cherry picked from commit 205677c88cb01e2bbee278443867baed2c89e5fe)