Fix Windows 64-bit build using VS 2022
... after commit fce18155052821756466ea043c638f4ed72f41d6, failing like

  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): error C7692: 'bool Color::operator ==(const Color &) const': rewritten candidate function was excluded from overload resolution because a corresponding operator!= declared in the same scope
  C:\lo\src\core\include\vcl/vclenum.hxx(174): note: could be 'bool operator ==(const ItalicMatrix &,const ItalicMatrix &)'
  C:\lo\src\core\include\comphelper/errcode.hxx(249): note: or       'bool operator ==(ErrCode,const ErrCodeMsg &)'
  C:\lo\src\core\include\comphelper/errcode.hxx(247): note: or       'bool operator ==(const ErrCodeMsg &,ErrCode)'
  C:\lo\src\core\include\tools/gen.hxx(536): note: or       'bool operator ==(const Selection &,const Selection &)'
  C:\lo\src\core\include\tools/gen.hxx(473): note: or       'bool operator ==(const Range &,const Range &)'
  C:\lo\src\core\include\tools/gen.hxx(365): note: or       'bool operator ==(const AbsoluteScreenPixelSize &,const AbsoluteScreenPixelSize &)'
  C:\lo\src\core\include\tools/gen.hxx(361): note: or       'bool operator ==(const Size &,const Size &)'
  C:\lo\src\core\include\tools/gen.hxx(231): note: or       'bool operator ==(const AbsoluteScreenPixelPoint &,const AbsoluteScreenPixelPoint &)'
  C:\lo\src\core\include\tools/gen.hxx(227): note: or       'bool operator ==(const Point &,const Point &)'
  C:\lo\src\core\include\tools/color.hxx(256): note: or 'bool Color::operator ==(const Color &) const' [synthesized expression 'y == x']
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool Color::operator ==(const Color &) const': rewritten candidate function was excluded from overload resolution because a corresponding operator!= declared in the same scope
  C:\lo\src\core\include\tools/gen.hxx(227): note: or 'bool operator ==(const Point &,const Point &)' [synthesized expression 'y == x']
  C:\lo\src\core\include\tools/gen.hxx(231): note: or 'bool operator ==(const AbsoluteScreenPixelPoint &,const AbsoluteScreenPixelPoint &)' [synthesized expression 'y == x']
  C:\lo\src\core\include\tools/gen.hxx(361): note: or 'bool operator ==(const Size &,const Size &)' [synthesized expression 'y == x']
  C:\lo\src\core\include\tools/gen.hxx(365): note: or 'bool operator ==(const AbsoluteScreenPixelSize &,const AbsoluteScreenPixelSize &)' [synthesized expression 'y == x']
  C:\lo\src\core\include\tools/gen.hxx(473): note: or 'bool operator ==(const Range &,const Range &)' [synthesized expression 'y == x']
  C:\lo\src\core\include\tools/gen.hxx(536): note: or 'bool operator ==(const Selection &,const Selection &)' [synthesized expression 'y == x']
  C:\lo\src\core\include\comphelper/errcode.hxx(247): note: or 'bool operator ==(const ErrCodeMsg &,ErrCode)' [synthesized expression 'y == x']
  C:\lo\src\core\include\comphelper/errcode.hxx(249): note: or 'bool operator ==(ErrCode,const ErrCodeMsg &)' [synthesized expression 'y == x']
  C:\lo\src\core\include\vcl/vclenum.hxx(174): note: or 'bool operator ==(const ItalicMatrix &,const ItalicMatrix &)' [synthesized expression 'y == x']
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: or       'built-in C++ operator==(int, sal_uInt32)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: or       'built-in C++ operator==(int, sal_Int32)'
  C:\lo\src\core\include\svl/typedwhich.hxx(59): note: or       'bool operator ==(const TypedWhichId<T> &,sal_uInt16)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(const TypedWhichId<T> &,sal_uInt16)': could not deduce template argument for 'const TypedWhichId<T> &' from 'int'
  C:\lo\src\core\include\svl/typedwhich.hxx(51): note: or       'bool operator ==(sal_uInt16,const TypedWhichId<T> &)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(sal_uInt16,const TypedWhichId<T> &)': could not deduce template argument for 'const TypedWhichId<T> &' from 'Color'
  C:\lo\src\core\include\svl/typedwhich.hxx(43): note: or       'bool operator ==(const TypedWhichId<T> &,TypedWhichId<T>)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(const TypedWhichId<T> &,TypedWhichId<T>)': could not deduce template argument for 'const TypedWhichId<T> &' from 'int'
  C:\lo\src\core\include\vcl/vclptr.hxx(238): note: or       'bool operator ==(T *,const VclPtr<reference_type> &)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(T *,const VclPtr<reference_type> &)': could not deduce template argument for 'T *' from 'int'
  C:\lo\src\core\include\vcl/vclptr.hxx(233): note: or       'bool operator ==(const T *,const VclPtr<reference_type> &)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(const T *,const VclPtr<reference_type> &)': could not deduce template argument for 'const T *' from 'int'
  C:\lo\src\core\include\vcl/vclptr.hxx(229): note: or       'bool operator ==(const VclPtr<reference_type> &,T *)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(const VclPtr<reference_type> &,T *)': could not deduce template argument for 'const VclPtr<reference_type> &' from 'int'
  C:\lo\src\core\include\vcl/vclptr.hxx(224): note: or       'bool operator ==(const VclPtr<reference_type> &,const T *)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(const VclPtr<reference_type> &,const T *)': could not deduce template argument for 'const VclPtr<reference_type> &' from 'int'
  C:\lo\src\core\include\vcl/vclptr.hxx(220): note: or       'bool operator ==(const VclPtr<reference_type> &,const VclPtr<T2> &)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(const VclPtr<reference_type> &,const VclPtr<T2> &)': could not deduce template argument for 'const VclPtr<reference_type> &' from 'int'
  C:\lo\src\core\include\vcl/vclptr.hxx(220): note: or 'bool operator ==(const VclPtr<reference_type> &,const VclPtr<T2> &)' [synthesized expression 'y == x']
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(const VclPtr<reference_type> &,const VclPtr<T2> &)': could not deduce template argument for 'const VclPtr<reference_type> &' from 'Color'
  C:\lo\src\core\include\vcl/vclptr.hxx(224): note: or 'bool operator ==(const VclPtr<reference_type> &,const T *)' [synthesized expression 'y == x']
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(const VclPtr<reference_type> &,const T *)': could not deduce template argument for 'const VclPtr<reference_type> &' from 'Color'
  C:\lo\src\core\include\vcl/vclptr.hxx(229): note: or 'bool operator ==(const VclPtr<reference_type> &,T *)' [synthesized expression 'y == x']
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(const VclPtr<reference_type> &,T *)': could not deduce template argument for 'const VclPtr<reference_type> &' from 'Color'
  C:\lo\src\core\include\vcl/vclptr.hxx(233): note: or 'bool operator ==(const T *,const VclPtr<reference_type> &)' [synthesized expression 'y == x']
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(const T *,const VclPtr<reference_type> &)': could not deduce template argument for 'const T *' from 'Color'
  C:\lo\src\core\include\vcl/vclptr.hxx(238): note: or 'bool operator ==(T *,const VclPtr<reference_type> &)' [synthesized expression 'y == x']
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(T *,const VclPtr<reference_type> &)': could not deduce template argument for 'T *' from 'Color'
  C:\lo\src\core\include\svl/typedwhich.hxx(43): note: or 'bool operator ==(const TypedWhichId<T> &,TypedWhichId<T>)' [synthesized expression 'y == x']
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(const TypedWhichId<T> &,TypedWhichId<T>)': could not deduce template argument for 'const TypedWhichId<T> &' from 'Color'
  C:\lo\src\core\include\svl/typedwhich.hxx(51): note: or 'bool operator ==(sal_uInt16,const TypedWhichId<T> &)' [synthesized expression 'y == x']
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(sal_uInt16,const TypedWhichId<T> &)': could not deduce template argument for 'const TypedWhichId<T> &' from 'int'
  C:\lo\src\core\include\svl/typedwhich.hxx(59): note: or 'bool operator ==(const TypedWhichId<T> &,sal_uInt16)' [synthesized expression 'y == x']
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: 'bool operator ==(const TypedWhichId<T> &,sal_uInt16)': could not deduce template argument for 'const TypedWhichId<T> &' from 'Color'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1739): note: while trying to match the argument list '(int, Color)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1750): error C7692: 'bool Color::operator ==(const Color &) const': rewritten candidate function was excluded from overload resolution because a corresponding operator!= declared in the same scope
  C:\lo\src\core\include\vcl/vclenum.hxx(174): note: could be 'bool operator ==(const ItalicMatrix &,const ItalicMatrix &)'
  C:\lo\src\core\include\comphelper/errcode.hxx(249): note: or       'bool operator ==(ErrCode,const ErrCodeMsg &)'
  C:\lo\src\core\include\comphelper/errcode.hxx(247): note: or       'bool operator ==(const ErrCodeMsg &,ErrCode)'
  C:\lo\src\core\include\tools/gen.hxx(536): note: or       'bool operator ==(const Selection &,const Selection &)'
  C:\lo\src\core\include\tools/gen.hxx(473): note: or       'bool operator ==(const Range &,const Range &)'
  C:\lo\src\core\include\tools/gen.hxx(365): note: or       'bool operator ==(const AbsoluteScreenPixelSize &,const AbsoluteScreenPixelSize &)'
  C:\lo\src\core\include\tools/gen.hxx(361): note: or       'bool operator ==(const Size &,const Size &)'
  C:\lo\src\core\include\tools/gen.hxx(231): note: or       'bool operator ==(const AbsoluteScreenPixelPoint &,const AbsoluteScreenPixelPoint &)'
  C:\lo\src\core\include\tools/gen.hxx(227): note: or       'bool operator ==(const Point &,const Point &)'
  C:\lo\src\core\include\tools/color.hxx(256): note: or 'bool Color::operator ==(const Color &) const' [synthesized expression 'y == x']
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1750): note: 'bool Color::operator ==(const Color &) const': rewritten candidate function was excluded from overload resolution because a corresponding operator!= declared in the same scope
  C:\lo\src\core\include\tools/gen.hxx(227): note: or 'bool operator ==(const Point &,const Point &)' [synthesized expression 'y == x']
  C:\lo\src\core\include\tools/gen.hxx(231): note: or 'bool operator ==(const AbsoluteScreenPixelPoint &,const AbsoluteScreenPixelPoint &)' [synthesized expression 'y == x']
  C:\lo\src\core\include\tools/gen.hxx(361): note: or 'bool operator ==(const Size &,const Size &)' [synthesized expression 'y == x']
  C:\lo\src\core\include\tools/gen.hxx(365): note: or 'bool operator ==(const AbsoluteScreenPixelSize &,const AbsoluteScreenPixelSize &)' [synthesized expression 'y == x']
  C:\lo\src\core\include\tools/gen.hxx(473): note: or 'bool operator ==(const Range &,const Range &)' [synthesized expression 'y == x']
  C:\lo\src\core\include\tools/gen.hxx(536): note: or 'bool operator ==(const Selection &,const Selection &)' [synthesized expression 'y == x']
  C:\lo\src\core\include\comphelper/errcode.hxx(247): note: or 'bool operator ==(const ErrCodeMsg &,ErrCode)' [synthesized expression 'y == x']
  C:\lo\src\core\include\comphelper/errcode.hxx(249): note: or 'bool operator ==(ErrCode,const ErrCodeMsg &)' [synthesized expression 'y == x']
  C:\lo\src\core\include\vcl/vclenum.hxx(174): note: or 'bool operator ==(const ItalicMatrix &,const ItalicMatrix &)' [synthesized expression 'y == x']
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1750): note: or       'built-in C++ operator==(int, sal_uInt32)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1750): note: or       'built-in C++ operator==(int, sal_Int32)'
  C:\lo\src\core\include\svl/typedwhich.hxx(59): note: or       'bool operator ==(const TypedWhichId<T> &,sal_uInt16)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1750): note: 'bool operator ==(const TypedWhichId<T> &,sal_uInt16)': could not deduce template argument for 'const TypedWhichId<T> &' from 'int'
  C:\lo\src\core\include\svl/typedwhich.hxx(51): note: or       'bool operator ==(sal_uInt16,const TypedWhichId<T> &)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1750): note: 'bool operator ==(sal_uInt16,const TypedWhichId<T> &)': could not deduce template argument for 'const TypedWhichId<T> &' from 'Color'
  C:\lo\src\core\include\svl/typedwhich.hxx(43): note: or       'bool operator ==(const TypedWhichId<T> &,TypedWhichId<T>)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1750): note: 'bool operator ==(const TypedWhichId<T> &,TypedWhichId<T>)': could not deduce template argument for 'const TypedWhichId<T> &' from 'int'
  C:\lo\src\core\include\vcl/vclptr.hxx(238): note: or       'bool operator ==(T *,const VclPtr<reference_type> &)'
  C:/lo/src/core/sw/qa/extras/rtfimport/rtfimport.cxx(1750): note: 'bool operator ==(T *,const VclPtr<reference_type> &)': could not deduce template argument for 'T *' from 'int'
  ...

Change-Id: Id976fe515287a4aa12d7ff8ca0ca09c31c65309f
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/159316
Tested-by: Jenkins
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>