Explicitly build external/freetype --without-png
...instead of having its configure.ac determine whether to support png based on
it being installed on the system, but which then might cause a Linux
--without-system-freetype build to fail to link Library_pdfium with

> workdir/UnpackedTarball/freetype/src/sfnt/pngshim.c:199: error: undefined reference to 'png_get_error_ptr'

etc.

Change-Id: Idf47ba5252b8f4d7f2e295f7adf6b761dbee4d2f