editeng: error: "remove_const_t" is not a member of "std"
Manual type inference was an interesting oxymoronic curiosity that
can probably only exist in C++, but it turns out our baseline
compilers don't even support it yet.

Change-Id: I3e9ac14e69c2c1288fa58a4279ede3202952b2fa