Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/117367/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "xmlDocUniquePtr" to "xmlDocPtr" in file C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows@2/sw/qa/extras/ooxmlexport/ooxmlexport12.cxx(773) ( https://ci.libreoffice.org/job/gerrit_windows/129842/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1, 6e1f2c111a8b12152470d29c2c3d0e2e5578c43f
Attention: {"person_ident":"Gerrit User 1000804 \u003c1000804@6622c302-437a-49ad-a91d-55ba7dcf1615\u003e","operation":"ADD","reason":"A robot voted negatively on a label"}