Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/23201/ : FAILURE

clang plugin casttovoid did trigger. unused virtual function parameter name ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/24562/ )

error: unused virtual function parameter name [loplugin:casttovoid] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/source/ui/vba/vbaapplication.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/24562/ )

Patch-set: 1
Label: Verified=-1