Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/19039/ : FAILURE

error: bad static variable causes crash on shutdown [loplugin:badstatics] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/core/data/document.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/19655/ )

clang plugin badstatics did trigger. bad static variable causes crash on shutdown ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/19655/ )

Patch-set: 1
Label: Verified=-1