Update external/cairo/cairo/Wincompatible-pointer-types.patch.0
...to 2b515d095d7251db98241e6b69f9b110e64e9aea "upgrade pixman and cairo", where
it now caused an Emscripten build against emsdk 4.0.15 (cf.
4ad6309f5b7460a8e1c558d68a94c4515ec1b73f "external/cairo: Silence some
-Wincompatible-pointer-types") to fail with

> ../src/cairo-image-source.c:89:33: error: incompatible pointer types passing 'void **' to parameter of type 'cairo_atomic_intptr_t *' (aka '_Atomic(void *) *') [-Wincompatible-pointer-types]
>    89 |         if (_cairo_atomic_ptr_cmpxchg ((void **) &__pixman_transparent_image,
>       |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../src/cairo-atomic-private.h:121:34: note: expanded from macro '_cairo_atomic_ptr_cmpxchg'
>   121 |   _cairo_atomic_ptr_cmpxchg_impl(x, oldv, newv)
>       |                                  ^
> ../src/cairo-atomic-private.h:114:55: note: passing argument to parameter 'x' here
>   114 | _cairo_atomic_ptr_cmpxchg_impl(cairo_atomic_intptr_t *x, void *oldv, void *newv)
>       |                                                       ^
> ../src/cairo-image-source.c:121:33: error: incompatible pointer types passing 'void **' to parameter of type 'cairo_atomic_intptr_t *' (aka '_Atomic(void *) *') [-Wincompatible-pointer-types]
>   121 |         if (_cairo_atomic_ptr_cmpxchg ((void **) &__pixman_black_image,
>       |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../src/cairo-atomic-private.h:121:34: note: expanded from macro '_cairo_atomic_ptr_cmpxchg'
>   121 |   _cairo_atomic_ptr_cmpxchg_impl(x, oldv, newv)
>       |                                  ^
> ../src/cairo-atomic-private.h:114:55: note: passing argument to parameter 'x' here
>   114 | _cairo_atomic_ptr_cmpxchg_impl(cairo_atomic_intptr_t *x, void *oldv, void *newv)
>       |                                                       ^
> ../src/cairo-image-source.c:153:33: error: incompatible pointer types passing 'void **' to parameter of type 'cairo_atomic_intptr_t *' (aka '_Atomic(void *) *') [-Wincompatible-pointer-types]
>   153 |         if (_cairo_atomic_ptr_cmpxchg ((void **) &__pixman_white_image,
>       |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../src/cairo-atomic-private.h:121:34: note: expanded from macro '_cairo_atomic_ptr_cmpxchg'
>   121 |   _cairo_atomic_ptr_cmpxchg_impl(x, oldv, newv)
>       |                                  ^
> ../src/cairo-atomic-private.h:114:55: note: passing argument to parameter 'x' here
>   114 | _cairo_atomic_ptr_cmpxchg_impl(cairo_atomic_intptr_t *x, void *oldv, void *newv)
>       |                                                       ^

Change-Id: Icbda11b95e8e9dfae3af6e0c84c68f3b5842f193
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191700
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>