Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_feature/219/ : FAILURE

error ""setChartStyle" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override]" triggered in included file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/source/inc/OPropertySet.hxx:206:27 ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/37059/ )

error: "setChartStyle" overrides a member function but is not marked "override" [-Werror,-Winconsistent-missing-override] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/chart2/source/inc/OPropertySet.hxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/37059/ )

Patch-set: 3
Label: Verified=-1