Update patch set 4
Patch Set 4: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/32216/ : FAILURE

error "static_assert failed due to requirement "__check_hash_requirements<OUString, PropertyInfo>::value" "the " triggered in included file /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:868:5 ( https://ci.libreoffice.org/job/gerrit_mac/34649/ )

error: no template named "unordered_map" in namespace "std"; did you mean "unordered_set"? in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/reportdesign/source/core/sdr/UndoEnv.cxx ( https://ci.libreoffice.org/job/gerrit_mac/34649/ )

Patch-set: 4
Label: Verified=-1