Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/61938/ : FAILURE

clang plugin fakebool did trigger. ParmVarDecl, use "bool" instead of "sal_Bool" (aka "unsigned char") ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/64775/ )

error: ParmVarDecl, use "bool" instead of "sal_Bool" (aka "unsigned char") [loplugin:fakebool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sc/source/filter/excel/xepage.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/64775/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1