build(android): fix type error
When building Android, I've been getting this error:

  /home/collabora/jenkins/workspace/co-26.04-android/net/Socket.hpp:370:72: error: cannot initialize a parameter of type 'socklen_t * _Nonnull' (aka 'int *') with an rvalue of type 'unsigned int *'
    370 |         const int rc = ::getsockopt(_fd, SOL_SOCKET, SO_ERROR, &error, &len);
        |                                                                        ^~~~
  /nix/store/pslcrlvq3wp9zwkz9qajmy8cpygba8bn-androidsdk/libexec/android-sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/sys/socket.h:286:98: note: passing argument to parameter '__value_length' here
    286 | int getsockopt(int __fd, int __level, int __option, void* _Nullable __value, socklen_t* _Nonnull __value_length);
        |                                                                                                  ^

It seems like this is from I63c2883e76cc2699b307dc88193fe1436a0e69e5,
which converted ifdefs to contsexprs. That is fine, except it also moved
some statements which were not previously compiled on mobile into a
place where they would be compiled. Therefore, we need to use the mobile
safe type socklen_t here rather than `unsigned int`

Signed-off-by: Skyler Grey <skyler.grey@collabora.com>
Change-Id: Ic5600f31ee8e0c261d06169878f40cec6a6a6964
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/11527
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>