Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/46723/ : FAILURE

error: use "bool" instead of "sal_Bool" (aka "unsigned char") as return type [loplugin:fakebool] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/xmlsecurity/source/component/documentdigitalsignatures.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/50138/ )

clang plugin fakebool did trigger. use "bool" instead of "sal_Bool" (aka "unsigned char") as return type ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/50138/ )

Patch-set: 1
Label: Verified=-1