Fix Windows build
After commit 9e67072a21bdbdfa9dc8da826654bf6fb4ec6116
(tdf#153368: Support optical size for variable fonts, part 1,
2023-03-02).

 C:/lo/core/vcl/qa/cppunit/complextext.cxx(885): error C3861:
 'addFont': identifier not found

If the test is expected to run on Windows, the definition of
`addFont` must be made available there.

Change-Id: I184f0dc1cc6363faba4c2ca147a812ddd4a98c2b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/200872
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>
Tested-by: Jenkins
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/202538
Tested-by: Tomaž Vajngerl <quikee@gmail.com>
Reviewed-by: Tomaž Vajngerl <quikee@gmail.com>