Avoid loplugin:rangedforcopy on converted temporaries
...where e.g.

> wsd/ClientSession.cpp:2314:10: error: Loop variable passed by value, pass by reference instead, e.g. 'const const std::string_view&' [loplugin:rangedforcopy]
>  2314 |     for (const std::string_view docType : { "text", "spreadsheet", "presentation", "drawing" })
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

would, when turned into a reference, cause

> wsd/ClientSession.cpp:2314:35: error: loop variable 'docType' of type 'const std::string_view &' (aka 'const basic_string_view<char> &') binds to a temporary constructed from type 'const char *const &' [-Werror,-Wrange-loop-construct]
>  2314 |     for (const std::string_view & docType : { "text", "spreadsheet", "presentation", "drawing" })
>       |                                   ^
> wsd/ClientSession.cpp:2314:10: note: use non-reference type 'std::string_view' (aka 'basic_string_view<char>') to make construction explicit or type 'const char *const &' to prevent copying
>  2314 |     for (const std::string_view & docType : { "text", "spreadsheet", "presentation", "drawing" })
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(And the new check makes the existing special-case check for OUStringChar
redundant.)

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I7d16826780519c8d957a57865a6fcef82f90e180
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/13241
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>