Use Gdiplus::PrivateFontCollection to obtain family name from TTF
This avoids the path length limitation of CreateScalableFontResourceW,
which manifests e.g. in CI - see https://ci.libreoffice.org/job/gerrit_windows/203249/console:

  warn:vcl.fonts:3512:11352:vcl/win/gdi/salfont.cxx:962: CreateScalableFontResource failed for C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\tempdir\tesE8AE.tmp Manbow Solid0.ttf C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\CppunitTest\sw_uiwriter10.test.user\user\temp\embeddedfonts\fromdocs 0
  warn:vcl.fonts:3512:11352:vcl/win/gdi/salfont.cxx:994: error extracting font family from file:///C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/workdir/CppunitTest/sw_uiwriter10.test.user/user/temp/embeddedfonts/fromdocs/Manbow Solid0.ttf

The implementation is put into vcl/win/gdi/salgdi_gdiplus.cxx, because
the GDI+ headers create conflicts when put into vcl/win/gdi/salfont.cxx;
the file name of salgdi_gdiplus.cxx looked relevant (although I don't
see any actual GDI+-related code there).

By the way, this new implementation seems to also perform better: in a
test, it finished in ~3 ms in a dbgutil build, while the previous code
took about 8 ms in an optimized build.

Change-Id: I95b09847e2fcba13489050d3a61a56776d8c8e47
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/189186
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>
Tested-by: Jenkins
(cherry picked from commit e2e1c5cb10cc33878495fa767d0c2a21459f924d)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/189203
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>