Missing dependency
[build LNK] CppunitTest/test_sc_theme_import_export_test.dll
ThemeImportExportTest.o : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class editeng::SvxBorderLine const * __cdecl SvxBoxItem::GetT
op(void)const " (__imp_?GetTop@SvxBoxItem@@QEBAPEBVSvxBorderLine@editeng@@XZ) referenced in function "void __cdecl `anonymous namespace'::checkCellBorderThemeCo
lor(class ScDocument *)" (?checkCellBorderThemeColor@?A0x620fdfa5@@YAXPEAVScDocument@@@Z)
ThemeImportExportTest.o : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class editeng::SvxBorderLine const * __cdecl SvxBoxItem::GetB
ottom(void)const " (__imp_?GetBottom@SvxBoxItem@@QEBAPEBVSvxBorderLine@editeng@@XZ) referenced in function "void __cdecl `anonymous namespace'::checkCellBorderT
hemeColor(class ScDocument *)" (?checkCellBorderThemeColor@?A0x620fdfa5@@YAXPEAVScDocument@@@Z)
ThemeImportExportTest.o : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class editeng::SvxBorderLine const * __cdecl SvxBoxItem::GetL
eft(void)const " (__imp_?GetLeft@SvxBoxItem@@QEBAPEBVSvxBorderLine@editeng@@XZ) referenced in function "void __cdecl `anonymous namespace'::checkCellBorderTheme
Color(class ScDocument *)" (?checkCellBorderThemeColor@?A0x620fdfa5@@YAXPEAVScDocument@@@Z)
ThemeImportExportTest.o : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class editeng::SvxBorderLine const * __cdecl SvxBoxItem::GetR
ight(void)const " (__imp_?GetRight@SvxBoxItem@@QEBAPEBVSvxBorderLine@editeng@@XZ) referenced in function "void __cdecl `anonymous namespace'::checkCellBorderThe
meColor(class ScDocument *)" (?checkCellBorderThemeColor@?A0x620fdfa5@@YAXPEAVScDocument@@@Z)
ThemeImportExportTest.o : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class Color const & __cdecl SvxBrushItem::GetColor(void)const
 " (__imp_?GetColor@SvxBrushItem@@QEBAAEBVColor@@XZ) referenced in function "void __cdecl `anonymous namespace'::checkCellBackgroundThemeColor(class ScDocument
*)" (?checkCellBackgroundThemeColor@?A0x620fdfa5@@YAXPEAVScDocument@@@Z)
ThemeImportExportTest.o : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class model::ComplexColor __cdecl SvxBrushItem::getComplexCol
or(void)const " (__imp_?getComplexColor@SvxBrushItem@@QEBA?AVComplexColor@model@@XZ) referenced in function "void __cdecl `anonymous namespace'::checkCellBackgr
oundThemeColor(class ScDocument *)" (?checkCellBackgroundThemeColor@?A0x620fdfa5@@YAXPEAVScDocument@@@Z)
ThemeImportExportTest.o : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class Color const & __cdecl SvxColorItem::getColor(void)const
 " (__imp_?getColor@SvxColorItem@@QEBAAEBVColor@@XZ) referenced in function "void __cdecl `anonymous namespace'::checkCellTextThemeColor(class ScDocument *)" (?
checkCellTextThemeColor@?A0x620fdfa5@@YAXPEAVScDocument@@@Z)
ThemeImportExportTest.o : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class model::ComplexColor const & __cdecl SvxColorItem::getCo
mplexColor(void)const " (__imp_?getComplexColor@SvxColorItem@@QEBAAEBVComplexColor@model@@XZ) referenced in function "void __cdecl `anonymous namespace'::checkC
ellTextThemeColor(class ScDocument *)" (?checkCellTextThemeColor@?A0x620fdfa5@@YAXPEAVScDocument@@@Z)
ThemeImportExportTest.o : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class Color const & __cdecl editeng::SvxBorderLine::GetColor(
void)const " (__imp_?GetColor@SvxBorderLine@editeng@@QEBAAEBVColor@@XZ) referenced in function "void __cdecl `anonymous namespace'::checkCellBorderThemeColor(cl
ass ScDocument *)" (?checkCellBorderThemeColor@?A0x620fdfa5@@YAXPEAVScDocument@@@Z)
ThemeImportExportTest.o : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class model::ComplexColor const & __cdecl editeng::SvxBorderL
ine::getComplexColor(void)const " (__imp_?getComplexColor@SvxBorderLine@editeng@@QEBAAEBVComplexColor@model@@XZ) referenced in function "void __cdecl `anonymous
 namespace'::checkCellBorderThemeColor(class ScDocument *)" (?checkCellBorderThemeColor@?A0x620fdfa5@@YAXPEAVScDocument@@@Z)
C:\lo\src\core2\workdir\LinkTarget\CppunitTest\test_sc_theme_import_export_test.dll : fatal error LNK1120: 10 unresolved externals
make[1]: *** [C:/lo/src/core2/solenv/gbuild/LinkTarget.mk:841: C:/lo/src/core2/workdir/LinkTarget/CppunitTest/test_sc_theme_import_export_test.dll] Error 96

Change-Id: Id12484db3823e59b709f54515b18535d1511a4ec
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/158438
Reviewed-by: Michael Stahl <michael.stahl@allotropia.de>
Tested-by: Mike Kaganski <mike.kaganski@collabora.com>