Update patch set 7
Patch Set 7: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/61598/ : FAILURE

error "C++ requires a type specifier for all declarations" triggered in included file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/svx/galtheme.hxx:68:12 ( https://ci.libreoffice.org/job/gerrit_mac/66613/ )

error: C++ requires a type specifier for all declarations in file /Users/tdf/lode/jenkins/workspace/lo_gerrit/Config/macosx_clang_dbgutil/include/svx/galtheme.hxx ( https://ci.libreoffice.org/job/gerrit_mac/66613/ )

Patch-set: 7
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1