Update patch set 9
Patch Set 9: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/102899/ : FAILURE

Visual studio complained about error C2440: "initializing": cannot convert from "initializer list" to "const XMLPropertyMapEntry" in file C:/cygwin/home/tdf/lode/jenkins/workspace/gerrit_windows/xmloff/source/text/txtprmap.cxx(385) ( https://ci.libreoffice.org/job/gerrit_windows/114079/ )

Patch-set: 9
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1