cool#16219 engine sw, merged paste: limit paragraph properties
Merged paste keeps only a whitelist of the source's character
properties; paragraph's properties, though, were still pasted unchanged.

A source paragraph's properties reach the destination text node via
SwTextNode::SetAttr(), where filtering of paragraph properties can be
done, but were not done. Doing it in the document model and not in the
import filter has the advantage of not having to support merged paste in
each & every import filter.

Fix the problem by dropping most paragraph properties in
SwTextNode::SetAttr() when the merged paste mode is used, with one big
exception: list properties are still used from the source.

Also fix two related problems:
- When filtering for a few wanted paragraph properties, also allow all
  wanted character properties, since full-paragraph character properties
  go to the item set of the text not, they won't be in a hint's
  auto-style.
- On pasting multiple paragraphs, from Writer, to the start of a
  paragraph that has a page-break-before property set, putting the
  breaks back didn't work, so add a flag where non-filter code can still
  create any paragraph property when a merged paste is in progress.

Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: Ic285874371c5d07377ced15d25096e5af975203b
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/13311
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>