linux aarch64: use -fsigned-char
pretty much considering it a workaround, better fix would be to use
explicit signed/unsigned variants, but this is what macOS/iOS also use
already/what the code apparently expects.

There doesn't seem to be a major issue, at least none covered by a make
check, but there's at least one WaE issue in oox:
oox/source/vml/vmlinputstream.cxx:45:18: error: result of comparison of unsigned expression >= 0 is always true [-Werror,-Wtautological-unsigned-zero-compare]
    return cChar >= 0 && cChar <= 32;
           ~~~~~ ^  ~
1 error generated.

(hit by default with --enable-werror when using gcc (comparison is
always true due to limited range of data type [-Werror=type-limits]),
with clang you have to add -Wtautological-unsigned-zero-compare)

Change-Id: Ib143b446bc842032e98c3d51d973bc0cd3bfcf15
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/186271
Tested-by: Jenkins
Reviewed-by: Christian Lohmaier <lohmaier+LibreOffice@googlemail.com>
Tested-by: Christian Lohmaier <lohmaier+LibreOffice@googlemail.com>