Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/49084/ : FAILURE

error: in LIBO_INTERNAL_ONLY code, replace literal cast to "sal_Unicode" (aka "char16_t") with a u"..." char16_t character literal [loplugin:salunicodeliteral] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sw/qa/extras/ooxmlimport/ooxmlimport2.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/52431/ )

use default type instead of indirection ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/52431/ )

clang plugin salunicodeliteral did trigger. in LIBO_INTERNAL_ONLY code, replace literal cast to "sal_Unicode" (aka "char16_t") with a u"..." char16_t character literal ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/52431/ )

Patch-set: 1
Label: Verified=-1