Blind fix for Windows TB failing
1064  NEXT    C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win64_dbg/vcl/win/gdi/gdiimpl.cxx(1564): error C2511: ´void WinSalGraphicsImpl::DrawPixelImpl(tools::Long,tools::Long,COLORREF)´: overloaded member function not found in ´WinSalGraphicsImpl´
1065          C:\cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win64_dbg\vcl\win\gdi\gdiimpl.hxx(34): note: see declaration of ´WinSalGraphicsImpl´
1066  NEXT    C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win64_dbg/vcl/win/gdi/gdiimpl.cxx(1565): error C2789: ´hDC´: an object of const-qualified type must be initialized
1067          C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win64_dbg/vcl/win/gdi/gdiimpl.cxx(1565): note: see declaration of ´hDC´
1068  NEXT    C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win64_dbg/vcl/win/gdi/gdiimpl.cxx(1567): error C2597: illegal reference to non-static member ´WinSalGraphicsImpl::mbXORMode´
1069          C:\cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win64_dbg\vcl\win\gdi\gdiimpl.hxx(39): note: see declaration of ´WinSalGraphicsImpl::mbXORMode´

Regression from:
Date:   Tue Nov 10 10:14:12 2020 +0200

    convert more long -> tools::Long

    found by grepping and changed by hand.

Change-Id: I4b47f8fe854fba55e803685c8eaa97c14c88b8aa