Drop accidental deletion of previously declared ctor
Introduced in commit 67e8da990fbdba7719ea107c29f4e57b62d5b6db
(replace sal_Bool with bool, 2026-06-20).

Fails MSVC build with

 C:\lo\online\engine\connectivity\source\inc\ado\Aolevariant.hxx(43): error C2535:
  'connectivity::ado::OLEVariant::OLEVariant(bool)': member function already defined or declared

Change-Id: I698286fce456a3b97631cc90e08ebf5222d9236c
Signed-off-by: Mike Kaganski <mike.kaganski@collabora.com>
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/5129
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>