Update patch set 4
Patch Set 4:

> Do you have the failure output?  (I'm still on 16.8.3, will update later and see if I can reproduce it.)

  mikek@DESKTOP-8SHAE9Q /cygdrive/c/lo/src/build
  $ nice make Library_OGLTrans
  C:/cygwin64/opt/lo/bin/make -j 14 -rs -f C:/lo/src/core/Makefile.gbuild Library_OGLTrans
  [build DEP] RC:OGLTrans/default
  [build DEP] LNK:Library/OGLTranslo.dll
  [build PRL] CustomTarget/postprocess/images/sorted.lst
  [build PRL] CustomTarget/postprocess/images/commandimagelist.ilst
  [build RC ] OGLTrans/default
  [build PRL] CustomTarget/postprocess/images/images_colibre.zip
  [build PKG] postprocess_images
  [build CXX] slideshow/source/engine/opengl/TransitionerImpl.cxx
  [build CXX] slideshow/source/engine/opengl/TransitionImpl.cxx
  [build CXX] slideshow/source/engine/opengl/Operation.cxx
  C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1428~1.299\Include\memory(14): error C2220: the following warning is treated as an error
  C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1428~1.299\Include\memory(14): warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop)
  C:\lo\src\core\slideshow\source\engine\opengl\Operation.hxx(34): warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop)
  C:/lo/src/core/slideshow/source/engine/opengl/Operation.cxx(36): warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop)
  make[1]: *** [C:/lo/src/core/solenv/gbuild/LinkTarget.mk:301: C:/lo/src/build/workdir/CxxObject/slideshow/source/engine/opengl/Operation.o] Error 2
  make[1]: *** Waiting for unfinished jobs....
  make: *** [Makefile:166: Library_OGLTrans] Error 2

Patch-set: 4