Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/81891/ : FAILURE

clang plugin stringliteralvar did trigger. variable "aCmisProps" of type "const rtl::OUStringLiteral<15>" with automatic storage duration most likely needs to be static ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/83459/ )

error: variable "aCmisProps" of type "const rtl::OUStringLiteral<15>" with automatic storage duration most likely needs to be static [loplugin:stringliteralvar] in file /home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_clang_dbgutil_64/sfx2/source/doc/sfxbasemodel.cxx ( https://ci.libreoffice.org/job/gerrit_linux_clang_dbgutil/83459/ )

Patch-set: 2
Reviewer: Gerrit User 1000855 <1000855@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=-1