Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://ci.libreoffice.org/job/gerrit_master/4416/ : FAILURE

Visual studio complained about error C2440: "=": cannot convert from "std::unique_ptr<BitmapBuffer,std::default_delete<_Ty>>" to "BitmapBuffer *" in file C:/cygwin/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/windows_msc_dbgutil_32/vcl/win/gdi/salbmp.cxx(278) ( https://ci.libreoffice.org/job/gerrit_windows/4417/ )

Patch-set: 2
Label: Verified=-1